gohugoio/hugo

commands/benchmark.go, commands/check.go, commands/convert.go, commands/hugo.go, commands/import_jekyll.go, commands/list.go, commands/list_config.go, commands/server.go
Also add `--force` flag copied from `hugo new site`.
Fixes #1625
=> Add sanity checks for `hugo import jekyll`

commands/gendoc.go
And print a feedback if the directory does not exist and needs to be created.
=> Use MkdirAll instead of Mkdir in `hugo gen doc`

docs/content/templates/functions.md, tpl/template_funcs.go, tpl/template_funcs_test.go
=> tpl: Modify tpl.humanize to add ordinals to integer input.

parser/frontmatter.go
=> Add description do "DetectFrontMatter" function

hugolib/datafiles_test.go, hugolib/handler_test.go, hugolib/menu_test.go, hugolib/site_test.go, hugolib/site_url_test.go
=> hugolib: Use named keys in composite literals

docs/content/overview/usage.md
Improve the English in the Usage manual.
=> docs: Clarify Usage

helpers/emoji.go, helpers/emoji_test.go
=> helpers: Fix bug in emoji renderer

helpers/content_renderer.go, hugolib/shortcode.go, hugolib/shortcode_test.go
This is the nth attempt to fix an issue by changing the placeholder token pattern, but
now we actually have tests for all the historic trouble cases.
Fixes #2223
=> Fix shortcode vs pygments

tpl/template_funcs.go, tpl/template_funcs_test.go
Refactor and extend where to iterate over maps.
=> tpl: Extend where to iterate over maps

docs/content/content/multilingual.md, docs/content/overview/configuration.md, hugolib/config.go, tpl/template_i18n.go
=> tpl: Add EnableMissingTranslationPlaceholders option

docs/content/extras/analytics.md, docs/content/extras/authors.md, docs/content/extras/builders.md, docs/content/templates/variables.md
=> docs: Add documentation for author profiles

docs/content/content/multilingual.md, docs/content/overview/configuration.md, tpl/template_i18n_test.go
Last bit of work I'll do on this for a while. :)
- Rewrote tests to be declarative and safer
- Added test case for passing the context to i18n
- Revised docs to describe the full behaviour of i18n when translations are missing
=> tpl: Improve tests and docs for i18n

hugolib/shortcodeparser.go, hugolib/shortcodeparser_test.go
=> Fix half-broken self-closing shortcodes

.travis.yml
=> travis: Reintroduce asciidoctor to build

hugolib/embedded_shortcodes_test.go
Overload `getJSON` and return mock response.  Also standardized error
reporting strings in tests.
Fixes #2359
=> hugolib: Prevent TestShortcodeTweet from accessing network

helpers/content.go, helpers/general.go, helpers/general_test.go, hugolib/multilingual.go, hugolib/page.go, hugolib/site_test.go, vendor/vendor.json
There are still work to be done in the case department, but that will have to be another day.
Fixes #2581
See https://github.com/spf13/viper/issues/261
=> Fix case issue Viper vs Blackfriday config

commands/hugo.go
And clean up flag variables
IMHO InitializeConfig is clearer now
=> commands: Move initialization of flags in separate function

commands/convert.go, commands/hugo.go, helpers/pygments.go, hugolib/config.go, hugolib/handler_page.go, hugolib/page.go, hugolib/site.go, tpl/template_i18n.go, tpl/template_resources.go
And delete some blank lines.
It's clone of #2665 without the path commit
=> commands, tpl: Get rid of repeating viper accesses

commands/benchmark.go
* Add information about average time, memory consumption and
allocations.
* Fix situation, when user provides memprofile and cpuprofile, but
cpuprofile will not created.
Fixes #2432
I want to make benchmark command more useful and see, how many memory hugo consumes and average time per build.  It's just a concept, so if you have any offers, don't hesitate to express them.
=> commands: Make benchmark command more useful

commands/env.go, commands/hugo.go, commands/import_jekyll.go, commands/list.go, commands/list_config.go, commands/server.go, commands/version.go, helpers/url.go
This is an attempt to unify method for printing. I tried to discuss about these theme [here](https://discuss.gohugo.io/t/jww-vs-fmt-what-should-one-use-for-printing/4592). Yes, maybe it's not very important theme. But it's very ambiguous for new developers to understand which method should you use for printing. I want to contribute to `hugo` and make really significant contributions, but for a start I should understand and clarify some ambiguous but important moments like this or [solved problem with keys for viper](https://github.com/spf13/hugo/pull/2571).
I hope, you merge it. But if there are some problems or bugs in this PR, please tell me, I will try to fix it.
=> all: Use jww instead of fmt for printing

commands/convert.go, commands/hugo.go, commands/undraft.go, hugolib/page.go, hugolib/site.go, parser/frontmatter.go, source/inmemory.go, target/page.go, tpl/template_funcs.go, tpl/template_i18n.go
Just some obvious and insignificant PR. But maybe it can improve the reading of code and performance, especially in hugolib/site.go.
=> all: Work around fmt statements

helpers/emoji.go, helpers/language.go, helpers/path.go, hugolib/pageGroup.go, hugolib/path_separators_test.go, hugolib/site.go, hugolib/sitemap_test.go, source/file.go, source/filesystem.go, tpl/template.go, tpl/template_funcs.go
Fix 16 (9%) golint warnings
See #2014
=> all: Fix some golint warnings

examples/blog/layouts/partials/header.html
Use RSSLink instead of deprecated RSSlink
=> examples: Update blog example

helpers/url.go, helpers/url_test.go, hugolib/embedded_shortcodes_test.go, hugolib/menu_test.go, hugolib/node_as_page_test.go, hugolib/page.go, hugolib/site.go, hugolib/site_render.go, target/page.go
=> hugolib: Fix regressions with uglyURLs

tpl/template_ast_transformers.go, tpl/template_ast_transformers_test.go
=> tpl: Fix params case issue with nested template funcs

commands/hugo.go, docs/content/commands/hugo.md, docs/content/commands/hugo_benchmark.md, docs/content/commands/hugo_server.md, docs/content/overview/configuration.md, docs/content/overview/usage.md
Includes updates to docs.
Fixes #2749
Requires https://github.com/spf13/fsync/pull/9.  Will need a vendor update after fsync merge.
=> commands: Add noChmod option to disable perm sync

docs/content/templates/variables.md
https://discuss.gohugo.io/t/basefilename-of-a-translated-page/4761
=> docs: Update File variables

hugolib/node_as_page_test.go, hugolib/site.go
By delaying the menu assembly.
Fixes #2770
=> Fix menu URL for node type pages

docs/content/templates/variables.md
=> docs: Add .Site.RegularPages docs

docs/content/templates/functions.md, docs/content/templates/partials.md
=> docs: Document partialCached func

docs/content/templates/variables.md
=> docs: Fix Ref and RelRef syntax

docs/content/templates/go-templates.md
=> docs: Fix pipe examples

docs/content/templates/content.md
=> docs: Clarify single page template search path

docs/content/templates/partials.md
Updated some instances of the path from `layout` -> `layouts`
=> Docs: updated layouts path name

vendor/vendor.json
=> vendor: Update go-toml

tpl/template_funcs.go, tpl/template_funcs_test.go
=> tpl: Update funcs to accept interface{} params

commands/hugo.go, helpers/path.go
=> helpers: Remove "no theme set" warning

hugolib/hugo_sites.go, hugolib/node_as_page_test.go, hugolib/page.go, hugolib/site.go
=> hugolib: Fix preserveTaxonomyNames regressions

.travis.yml
=> travis: Add GOARCH 386 test

hugolib/hugo_sites_build_test.go, hugolib/pagination.go, hugolib/pagination_test.go
=> hugolib: Avoid double-encoding of paginator URLs

hugolib/embedded_shortcodes_test.go, hugolib/handler_base.go, hugolib/handler_file.go, hugolib/handler_meta.go, hugolib/handler_page.go, hugolib/hugo_sites.go, hugolib/hugo_sites_build.go, hugolib/page.go, hugolib/shortcode.go, hugolib/shortcode_test.go, hugolib/site.go, hugolib/site_test.go, tpl/template.go, tpl/template_ast_transformers_test.go, tpl/template_funcs.go, tpl/template_funcs_test.go, tpl/template_test.go, vendor/vendor.json
=> all: Refactor to nonblogal template handling

.travis.yml, Makefile, appveyor.yml
=> Clean up Makefile

docs/content/tools/_index.md
I've written a DokuWiki to hugo conversion tool in python to migrate my blog content to Hugo. I hope others will also benefit from it. Feel free to take a look and give some feedback.
=> dokuwiki to hugo conversion tool

snapcraft.yaml
=> Add pygmentize to the hugo snap

docs/content/overview/introduction.md
Netlify is a solid solution similar to surge and aerobatic and they have a great free plan and pro plan for open source projects.
=> Added netlify to the list of static hosting solutions

docs/content/community/press.md
Hi everyone, I've written an article which describes how to use Cloud9 IDE to make a Hugo site and then deploy it to Google App Engine. Please feel free to review and approve this PR if you think it adds value. Thanks.
=> Add Article to the list

docs/content/tutorials/github-pages-blog.md
Just some simple documentation related change that I find to be useful - let me know if you prefer me to do this in a different way.
=> Adding instructions about using customized domain

tpl/template_funcs.go, tpl/template_funcs_test.go
=> tpl: Accept limit as interface in findRE func

hugolib/hugo_sites.go, hugolib/taxonomy_test.go
=> hugolib: Add tests for taxonomies with and without content page

Dockerfile
* use go 1.8
* switch to alpine for faster build and smaller image
=> new go-version, switch to alpine (reduce size by 500mb)

tpl/tplimpl/template_embedded.go
=> tpl: Add title meta tag to twitter card template

docs/content/tutorials/automated-deployments.md
Fixes error seen here: https://ci.appveyor.com/project/spf13/hugo/build/1.0.4972 caused by this PR: https://github.com/spf13/hugo/pull/3103
=> Correct last modified date for Automated Deployment tutorial

tpl/tplimpl/template_funcs.go, tpl/tplimpl/template_funcs_test.go
=> tplimpl: return an error on unsupported type in isSet

docs/content/community/press.md
https://habd.as/zero-to-http-2-aws-hugo/
=> [Press] Add blog post from After Dark creator

hugolib/hugo_sites.go, hugolib/site.go, hugolib/translations.go
Found by github.com/mvdan/unparam
=> hugolib: Remove reduntant params

hugolib/config.go, hugolib/site_render.go
=> hugolib: Default rssLimit to unlimited

hugolib/handler_base.go, hugolib/page.go
=> hugolib: Clean up redundant frontmatter error logging

parser/frontmatter.go, vendor/vendor.json
Relates to https://github.com/spf13/hugo/issues/3142
And https://github.com/spf13/hugo/issues/3146
=> Investigate go-toml issues

docs/content/templates/functions.md
=> Fix typo in templates/functions.md

commands/new.go, create/content.go
Also make easier code to read
Updates #2728
=> create: Delete redundant viper calls 

tpl/tplimpl/template_resources.go, tpl/tplimpl/template_resources_test.go
=> tplimpl: Fix deadlock in getJSON

vendor/vendor.json
Really fix #2349
b7a672f didn't actually the issue.
=> vendor: Update cobra

vendor/vendor.json
Updates to latest goorgeous changes:
- fixed `/n` rendering issues where every new line was rendered as a paragraph. Now newlines render properly.
- @clockoon added footnotes support.
=> vendor: update goorgeous

docs/content/content/using-index-md.md
remove localhost part from link
=> fix issue #3264

commands/hugo.go, deps/deps.go, helpers/general.go, hugolib/hugo_sites.go, hugolib/page.go, hugolib/site.go, hugolib/site_output.go, hugolib/site_render.go, media/mediaType.go, media/mediaType_test.go, output/layout_base.go, output/outputFormat.go, output/outputFormat_test.go, tpl/tplimpl/template.go
=> Read media types and output formats from config

hugolib/page.go, hugolib/page_output.go, hugolib/permalinker.go, hugolib/site.go, hugolib/site_test.go, tpl/tplimpl/template_embedded.go, tpl/tplimpl/template_funcs.go
=> hugolib: Add optional outputFormat to Ref/RelRef

output/layout_base.go, output/layout_base_test.go, tpl/tplimpl/template.go
=> output: Fix base theme vs project base template logic

hugolib/site.go, hugolib/site_render.go, hugolib/site_test.go, hugolib/testhelpers_test.go
=> hugolib: Don't render Zero-length files

.gitignore, commands/genman.go, commands/hugo.go, commands/release.go, commands/version.go, docs/config.toml, docs/content/release-notes/_index.md, docs/content/release-notes/release-notes.md, docs/layouts/section/release-notes.html, goreleaser.yml, helpers/general.go, helpers/hugo.go, helpers/hugo_test.go, hugolib/hugo_info.go, releaser/git.go, releaser/git_test.go, releaser/github.go, releaser/github_test.go, releaser/releasenotes_writer.go, releaser/releasenotes_writer_test.go, releaser/releaser.go, releaser/releaser_test.go, transform/hugogeneratorinject.go
This commit automates the Hugo release process.
This is actually working pretty great now, but I have to configure all the builds etc. and look into the deb side of it before I wrap it up.
Note that the process outlined also has room for manual release notes intervention.
=> Script Hugo release process

commands/genautocomplete.go, commands/gendocshelper.go, commands/hugo.go, commands/import_jekyll.go, commands/new.go, commands/release.go, vendor/vendor.json
* commands: Make first letter of flags' usage lowercase
* vendor: Update cobra and pflag
Just want to test all updates made to cobra and pflag on hugo.
More in commit messages.
=> commands, vendor: Update

docs/data/docs.json, tpl/cast/docshelper.go, tpl/collections/init.go, tpl/compare/init.go, tpl/crypto/init.go, tpl/data/init.go, tpl/encoding/init.go, tpl/fmt/fmt.go, tpl/fmt/init.go, tpl/images/init.go, tpl/inflect/init.go, tpl/internal/templatefuncRegistry_test.go, tpl/internal/templatefuncsRegistry.go, tpl/lang/init.go, tpl/math/init.go, tpl/os/init.go, tpl/partials/init.go, tpl/safe/init.go, tpl/strings/init.go, tpl/time/init.go, tpl/tplimpl/template_funcs.go, tpl/tplimpl/template_funcs_test.go, tpl/transform/init.go, tpl/urls/init.go
And fix some other minor related issues.
Fixes #3418
=> tpl: Add docshelper for template funcs

docs/data/docs.json, tpl/images/images.go
The embedded Mutex was polluting the namespace.  Don't do that.
=> tpl/images: Fix embedded sync.Mutex

tpl/data/cache.go, tpl/data/cache_test.go, tpl/data/data.go, tpl/data/data_test.go, tpl/data/resources.go, tpl/data/resources_test.go
Several things here.  See commit messages.  Fixes #3395
I still want to clean up the TestScp* functions, but I can do that in a later PR.
=> Clean up tpl/data

i18n/i18n.go
=> i18n: Improve the detection of untranslated string

docs/data/docs.json, tpl/cast/cast.go, tpl/cast/docshelper.go, tpl/internal/templatefuncsRegistry.go
=> tpl: Add some GoDoc info to template func docs

commands/benchmark.go, commands/hugo.go, helpers/path.go
* commands: Use paths from PathSpec for walker
* helpers: Don't clean the path before Join
=> commands, helpers: Small improvements

hugolib/handler_page.go, hugolib/hugo_sites.go, hugolib/hugo_sites_build.go, hugolib/page.go, hugolib/shortcode.go, hugolib/shortcode_test.go, hugolib/site.go, hugolib/site_output_test.go, hugolib/site_render.go, tpl/template.go, tpl/tplimpl/template.go
=> Handle AMP etc. shortcodes

hugolib/site.go, hugolib/site_output_test.go
=> hugolib: Fix RSSLink vs RSS Output Format

docs/content/extras/shortcodes.md
"... your can't **mixed** parameter types ..." --> "... you can't **mix** parameter types ..."
=> docs: Fix minor grammar issue in shortcodes.md

tpl/collections/collections.go, tpl/collections/collections_test.go, tpl/collections/where.go
=> tpl/collections: Add support for interfaces to intersect

docs/content/templates/list.md
_/themes/layouts/`SECTION`/list.html_
should be
_/themes/`THEME`/layouts/`SECTION`/list.html_
=> fix incorrect path in docs of templates/list

tpl/time/init.go, tpl/time/init_test.go
=> tpl/time: Support overlapping namespace and template func

tpl/cast/cast.go, tpl/cast/cast_test.go
Also add tests for ToInt and ToString.
Resolves #3308
=> tpl/cast: Handle template.HTML and friends in ToInt

hugolib/hugo_sites_build_test.go
=> hugolib: Enable leaktest

docs/content/overview/installing.md, docs/content/tutorials/installing-on-mac.md, docs/layouts/index.html
=> docs: Delete `brew update` from docs

docs/content/templates/functions.md, tpl/collections/collections.go, tpl/collections/collections_test.go, tpl/collections/init.go
As I [mentioned in the forums](https://discuss.gohugo.io/t/adding-uniq-to-template-functions/6710).
=> tpl: Add uniq function

hugolib/site_sections.go, hugolib/site_sections_test.go
This commit fixes an issue introduced in the recently released Hugo 0.22.
This logic did not handle the case with root sections with non-section subfolders very well.
Fixes #3586
=> hugolib: Fix section logic for root folders with subfolders

releaser/releasenotes_writer.go, releaser/releaser.go
Hi bep,
This pull request does involve changing some function names, so I thought it is safer to have you review it first rather than me blindly committing it to master.  Many thanks!
Anthony
=> releaser: Fix typo, change "relase" to "release"

create/content_template_handler.go, create/content_test.go
=> create: Preserve shortcodes in archetype templates

Dockerfile
Hi Hugo Team,
thanks for your awesome work!  
Let me help to optimize the Docker build for you.
Optimizations:
- update to latest go and alpine version
- build dependencies on the fly and clean up before hitting the cache layer
- create and run as an unprivileged user for security reasons
You can find a automatic build example here: <https://hub.docker.com/r/ellerbrock/alpine-hugo/>
You can run inside your local hugo folder like this:
```
docker run -it \
-p 127.0.0.1:1313:1313 \
-v ${PWD}:/site \
ellerbrock/alpine-hugo server --bind 0.0.0.0 -w
```
Happy hacking!
Cheers Maik
=> feat(docker): update dockerfile and add docker optimizations

hugolib/site_render.go
=> multilingual: Render 404.html for all languages

tpl/collections/collections.go, tpl/collections/collections_test.go, tpl/collections/reflect_helpers.go, tpl/collections/where.go
=> tpl/collections: Fix In function for JSON arrays

helpers/general.go, helpers/general_test.go, hugolib/permalinks.go, hugolib/site_sections.go, hugolib/site_sections_test.go
* .CurrentSection
* .IsDescendant
* .IsAncestor
Fixes #3591
=> hugolib: Extend the sections API

temp/0.25-relnotes.md
=> releaser: Add release notes draft for 0.25

hugolib/site.go, hugolib/site_test.go
=> hugolib: Support reflinks starting with a slash

tpl/collections/where.go, tpl/collections/where_test.go
=> tpl/collections: Fix intersect on []interface{} handling

temp/0.26-relnotes.md
=> releaser: Add release notes draft for 0.26

helpers/content_renderer.go, helpers/content_renderer_test.go
=> Render task list item inside label for correct accessibility

tpl/transform/transform.go, tpl/transform/transform_test.go
Fixes #3040
This is an alternative take on https://github.com/gohugoio/hugo/pull/3786
=> tpl/transform: Only strip p tag in markdownify if only one paragraph

hugolib/pages_related.go
Signed-off-by: wgliang <liangcszzu@163.com>
=> aquired is a misspelling of acquired

tpl/compare/compare.go, tpl/compare/compare_test.go, tpl/compare/init.go
=> tpl/compare: Add cond (ternary) template func

README.md
Just a couple of minor grammar, spelling, and formatting changes in the README.md
=> Minor README changes - spelling, grammar, etc

helpers/pygments.go, helpers/pygments_test.go, vendor/vendor.json
This depends on https://github.com/alecthomas/chroma/pull/60
Fixes #3915
=> Add table linenos support for Chroma highlighter

Gopkg.lock
Part 2 of
https://github.com/gohugoio/hugo/commit/c61998d3ac2e9c2756ba72d2e7381638cbe01a1f
Related: #3998
=> Update toml dependency revision in Gopkg.lock too

docs/content/content-management/shortcodes.md, hugolib/shortcode_test.go, tpl/tplimpl/template_embedded.go
=> Add support for height argument to figure shortcode

tpl/math/math.go, tpl/math/math_test.go
=> tpl/math: Refactor Mod with cast

i18n/i18n.go, i18n/i18n_test.go, i18n/translationProvider.go
=> The custom language code saga continues

Gopkg.lock, Gopkg.toml, commands/commandeer.go, commands/hugo.go, commands/server.go, commands/server_test.go, commands/static_syncer.go, helpers/language.go, helpers/path.go, helpers/path_test.go, helpers/pathspec.go, helpers/pathspec_test.go, hugolib/config.go, hugolib/hugo_sites.go, hugolib/hugo_sites_build_test.go, hugolib/hugo_sites_multihost_test.go, hugolib/multilingual.go, hugolib/page.go, hugolib/page_output.go, hugolib/page_paths.go, hugolib/pagination.go, hugolib/site.go, hugolib/site_render.go, livereload/livereload.go, source/dirs.go, source/dirs_test.go, tpl/urls/init_test.go, tpl/urls/urls.go
=> Add multilingual multihost support

output/layout_base.go, output/layout_base_test.go
=> output: Fall back to unstranslated base template

hugolib/template_engines_test.go, tpl/tplimpl/ace.go, tpl/tplimpl/template.go
=> Fix broken shortcodes for Ace and Amber

hugolib/hugo_sites_build_test.go, hugolib/hugo_sites_multihost_test.go, hugolib/page_paths.go, hugolib/page_paths_test.go, hugolib/site_render.go
=> hugolib: Make sure everything ends up in its lang root in multihost mode

commands/commandeer.go, commands/server.go
Also make sure to log the correct server URL to the console.
Fixes #4111
=> commands: Fix broken --appendPort=false

Gopkg.lock, Gopkg.toml
Update to goorgeous v1.1.0.
Fixes some rendering issues thanks to @wd and @zzamboni.
=> vendor: update goorgeous@v1.1.0

tpl/tplimpl/template_embedded.go
=> Fix context of opengraph video range

tpl/strings/strings.go, tpl/strings/strings_test.go
=> Make chomp return the type it receives

hugolib/page.go, hugolib/page_bundler_capture_test.go, hugolib/page_bundler_handlers.go, hugolib/page_bundler_test.go, hugolib/page_paths.go, resource/image.go, resource/resource.go
=> Fix non-ASCII path handling for Page resources

commands/hugo.go, hugolib/config.go
=> Correct fix for --cleanDestinationDir flag

hugolib/page_paths.go, hugolib/site.go, hugolib/site_url_test.go
=> Support uglyURLs per section

hugolib/page_output.go, hugolib/site.go, hugolib/site_render.go, output/docshelper.go, output/layout.go, output/layout_test.go
=> layout: Respect Type and Layout for list template selection

hugolib/page.go, hugolib/page_bundler_capture_test.go, hugolib/page_bundler_handlers.go, hugolib/page_bundler_test.go
=> hugolib: Fix handling of pages bundled in sub-folders in ByPrefix etc.

commands/hugo.go, commands/import_jekyll.go, commands/undraft.go, commands/undraft_test.go, hugolib/page.go, hugolib/page_test.go, parser/frontmatter.go, parser/page.go
This fixes Issues #4320 and #4323 and adds a nice test function that sets us up well for future additions to metadata logic. 
It depends on Pull Request #4321, which should be merged first.
=> Correctly handle page without front matter, fix metadata date bugs

create/content_template_handler.go, hugolib/fileInfo.go, hugolib/page.go, hugolib/page_bundler_capture_test.go, hugolib/page_bundler_test.go, source/fileInfo.go, source/fileInfo_test.go, source/filesystem.go
=> Fix handling of top-level page bundles

Gopkg.lock, Gopkg.toml, resource/image.go, resource/image_test.go, resource/smartcrop.go, resource/testhelpers_test.go
Uses https://github.com/muesli/smartcrop
Which does a great job in my tests. Performance is not an issue.
See some update examples here:
http://hugotest.bep.is/section3/2017/11/my-article-2/
Fixes #4375
=> WIP: resource: Add smart cropping

docs/content/contribute/development.md
Minor improvements to the [development contribution doc](https://gohugo.io/contribute/development/) to remove some typos I spotted while reading through.
=> Fix typos in development contribution doc

commands/server.go, helpers/path_test.go, helpers/processing_stats.go, hugolib/hugo_sites.go, magefile.go, resource/image_cache.go, resource/image_test.go, resource/resource.go, resource/resource_test.go
=> Run gofmt -s with Go 1.10

resource/image.go, resource/image_test.go
=> resource: Use Floyd-Steinberg dithering for PNGs

docs/content/getting-started/configuration.md, hugolib/gitinfo.go, hugolib/hugo_sites.go, hugolib/hugo_sites_build.go, hugolib/page.go, hugolib/page_test.go, hugolib/pagemeta/page_frontmatter.go, hugolib/pagemeta/page_frontmatter_test.go, hugolib/testsite/content/first-post.md
=> Refactor the GitInfo into the date handlers

docs/content/content-management/multilingual.md, docs/content/functions/lang.Merge.md, hugolib/hugo_sites_build.go, hugolib/hugo_sites_build_test.go, hugolib/page.go, hugolib/pageCache.go, hugolib/pageCache_test.go, hugolib/pageSort.go, hugolib/pages_language_merge.go, hugolib/pages_language_merge_test.go, hugolib/shortcode_test.go, hugolib/site.go, hugolib/site_test.go, hugolib/testhelpers_test.go, tpl/lang/lang.go
=> Add a way to merge pages by language

.travis.yml
Sorry, I left some cruft in PR #4555 while still experimenting, and would like to clean them up.
Also, for my curiosity sake, I added the `-v` flag to mage calls to more clearly see what is going on.
=> travis: Clean up and increase verbosity

commands/benchmark.go, commands/commands.go, commands/commands_test.go, commands/hugo.go, commands/server.go, commands/server_test.go
=> commands: Fix handling of persistent CLI flags

hugolib/hugo_sites.go
In most cases we could delay the content init until rendering time, but there could be use cases where the templates would depend on state set in the shortcodes (.Page.Scratch.Set), so we  need to do this early.
See #4632
=> hugolib: Init the content and shortcodes early

hugolib/hugo_sites.go, hugolib/orderedMap.go, hugolib/orderedMap_test.go, hugolib/shortcode.go, hugolib/shortcode_test.go
=> hugolib: Process and render shortcodes in their order of appearance

hugolib/hugo_sites.go, hugolib/hugo_sites_build.go, hugolib/hugo_sites_build_test.go, hugolib/page.go, hugolib/page_output.go, hugolib/pagination_test.go, hugolib/site_render.go, hugolib/testhelpers_test.go
@kaushalmodi this fixes your site, and I _kind of_ understand what happens, but I will try to create a failing test for this.
Fixes #4706
=> hugolib: Fix possible .Content cutoff

config/privacy/privacyConfig.go, config/privacy/privacyConfig_test.go, tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/google_analytics.html, tpl/tplimpl/embedded/templates/google_analytics_async.html
=> Add RespectDoNotTrack to GDPR privacy policy for Google Analytics

config/privacy/privacyConfig.go, config/privacy/privacyConfig_test.go, hugolib/config_test.go, tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/shortcodes/youtube.html
=> Add PrivacyEnhanced mode for YouTube to the GDPR Policy

config/privacy/privacyConfig.go, tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/shortcodes/__h_simple_assets.html, tpl/tplimpl/embedded/templates/shortcodes/youtube.html, tpl/tplimpl/embedded/templates/shortcodes/youtube_simple.html
Adapted from the work of @onedrawingperday.
See #4616
=> Add YouTube shortcode simple mode

tpl/tplimpl/embedded/templates/shortcodes/__h_simple_assets.html
=> Fix youtube_simple thumb scaling

tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/shortcodes/__h_simple_assets.html
As the greek saying goes _το δις εξαμαρτείν ουκ ανδρός σοφού_ (making the same mistake twice does not befit the wise) 
-but I did and here is the fix.-
=> Fix vimeo_simple  thumb scaling

config/privacy/privacyConfig.go, config/privacy/privacyConfig_test.go, docs/content/en/about/hugo-and-gdpr.md, docs/content/en/content-management/shortcodes.md, docs/themes/gohugoioTheme/src/js/hljs.js, hugolib/embedded_shortcodes_test.go, hugolib/testhelpers_test.go, tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/shortcodes/speakerdeck.html
=> tplimpl: Remove speakerdeck see #4830

tpl/tplimpl/template_ast_transformers.go, tpl/tplimpl/template_ast_transformers_go1_10.go, tpl/tplimpl/template_ast_transformers_go1_11.go
Thanks to @rjoleary for the investigation.
Fixes #4784
=> tpl: Support text/template/parse API change in go1.11

goreleaser.yml
refs #4432
The config file didn't change much, so this was easy :)
=> bump: goreleaser config

commands/version.go
=> Add "extended" to "hugo version"

goreleaser.yml
refs https://github.com/goreleaser/goreleaser/issues/715
=> fix: nfpm replacements

deps/deps.go, hugolib/hugo_sites_build.go, tpl/partials/init_test.go, tpl/partials/partials.go
=> FLush partialCached cache on rebuilds

hugolib/resource_chain_test.go, resource/transform.go
=> resource: Fix resources.Concat for transformed resources

hugolib/config_test.go, hugolib/hugo_sites.go, hugolib/page.go, hugolib/shortcode_test.go, hugolib/site.go, hugolib/site_test.go, hugolib/testhelpers_test.go
=> Add configurable ref/relref error handling and notFoundURL

hugolib/page_collections.go
=> hugolib: Print a WARNING about relative non-relative ref/relref matches

hugolib/resource_chain_test.go, resource/tocss/scss/tocss.go
Before this commit, only SASS/SCSS  components imported from main.scss at first level can be overwritten by homonymous files in projects or over-preceding theme components.
This commit fixes that by implementing a custom import resolver which will be tried first. This resolver will make sure that the project/theme hierarchy is always respected.
Fixes #5008
=> tocss/scss: Improve SCSS project vs themes import resolution

commands/hugo.go
=> Add configFile(s) back to the watch list after REMOVE event

tpl/tplimpl/template_ast_transformers.go, tpl/tplimpl/template_ast_transformers_test.go
=> tpl/tplimpl: Fix .Site.Params case regression

goreleaser.yml
=> fix: build on armv7

minifiers/minifiers.go
=> Do not strip unrequired end tags (tr, td, li, ... and often p)

.travis.yml, Gopkg.toml, magefile.go, resource/transform.go
=> Update Travis etc. to Go 1.11 and Go 1.10.4

Dockerfile
=> Fix build command in Dockerfile

common/collections/collections.go, hugolib/collections.go, hugolib/collections_test.go, hugolib/page.go, hugolib/pageGroup.go, hugolib/pageGroup_test.go, hugolib/pagination.go, tpl/collections/collections.go, tpl/collections/collections_test.go, tpl/collections/reflect_helpers.go
=> tpl/collections: Improve type handling in collections.Slice

tpl/collections/collections.go, tpl/collections/collections_test.go
=> tpl: Show error on union or intersect of uncomparable types

hugolib/page_collections.go, hugolib/rss_test.go, hugolib/site_render.go
=> WIP: GetPage issue(s)

commands/new.go, commands/new_content_test.go, create/content.go, create/content_template_handler.go, create/content_test.go, hugolib/fileInfo.go, hugolib/hugo_sites.go, hugolib/page_bundler_capture.go, hugolib/site.go
=> Add directory based archetypes

CONTRIBUTING.md
Typo fix and minor formatting tweak.
=> Fix typo and tweak formatting in CONTRIBUTING.md

create/content.go, create/content_test.go, hugolib/filesystems/basefs.go, hugolib/filesystems/basefs_test.go
=> Fix archetype handling of directories in theme

resource/image.go
=> resource: Serialize image processing

hugolib/resource_chain_test.go, resource/transform.go
=> resource: Allow .Data.Integrity to be accessed on its own

common/loggers/loggers.go, common/loggers/loggers_test.go, common/terminal/colors.go
=> common/loggers: Add color to ERROR and WARN

docs/content/en/news/0.50-relnotes/index.md
> Errors will no show up
should be:
> Errors will now show up
=> correct minor typo

hugolib/hugo_sites_build_errors_test.go, hugolib/page.go
=> hugolib: Fix deadlock when content building times out

hugolib/template_test.go, tpl/tplimpl/template.go
=> tpl: Fix BOM issue in templates

hugolib/page.go, hugolib/page_content.go, hugolib/page_test.go, hugolib/testhelpers_test.go, parser/pageparser/pagelexer.go, parser/pageparser/pageparser_intro_test.go
=> Work in progress: hugolib: Fix broken manual summary handling in Org Mode

hugolib/page_test.go, parser/pageparser/pagelexer.go, parser/pageparser/pageparser_intro_test.go
=> Fix shortcode directly following a shortcode delimiter

tpl/collections/complement.go, tpl/collections/complement_test.go, tpl/collections/init.go, tpl/collections/reflect_helpers.go
=> tpl/collections: Add collections.Complement

hugolib/hugo_sites.go, hugolib/page.go
=> hugolib: Fix changing paginators in lazy render

docs/content/en/tools/search.md
=> Add Elasticsearch/bonsai.io to services doc.

.travis.yml
Trying out [early Windows release](https://blog.travis-ci.com/2018-10-11-windows-early-release)
=> Try out Windows builds in Travis

hugolib/pagebundler_test.go, hugolib/resource_chain_test.go, hugolib/testhelpers_test.go
=> Add tests for permalink on Resource with baseURL with path

commands/hugo.go, helpers/pathspec.go, helpers/url.go, hugolib/page_output.go, hugolib/page_paths.go, hugolib/pagebundler_test.go, hugolib/pagination.go, hugolib/paths/paths.go, resource/image_cache.go, resource/resource.go
=> Fix Permalink for resource, baseURL with path and canonifyURLs set

tpl/collections/where.go, tpl/collections/where_test.go
=> tpl/collections: Add float64 support to where

docs/content/en/content-management/shortcodes.md, tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/shortcodes/param.html
=> tpl: Add "param" shortcode

hugolib/page.go, hugolib/pageSort.go, hugolib/pageSort_test.go
=> hugolib: Fall back to title in ByLinkTitle sort

tpl/cast/cast.go, tpl/collections/collections.go, tpl/compare/compare.go, tpl/crypto/crypto.go, tpl/data/data.go, tpl/encoding/encoding.go, tpl/fmt/fmt.go, tpl/images/images.go, tpl/inflect/inflect.go, tpl/lang/lang.go, tpl/math/math.go, tpl/os/os.go, tpl/partials/partials.go, tpl/path/path.go, tpl/resources/resources.go, tpl/safe/safe.go, tpl/strings/strings.go, tpl/templates/init.go, tpl/templates/init_test.go, tpl/templates/templates.go, tpl/time/time.go, tpl/transform/transform.go, tpl/urls/urls.go
Also fix package name in tpl/templates.
=> tpl: Add godoc packages comments

cache/filecache/filecache_test.go
=> WORK IN PROGRESS cache/filecache: Use OS fs for test

cache/filecache/filecache_test.go
=> cache/filecache: Simplify test

go.mod, go.sum
=> Fix "failed to create file caches from configuration: file exists" on Windows

go.sum, hugolib/hugo_sites.go, hugolib/site.go, hugolib/site_render.go
=> hugolib: Remove "double layout" lookup

transform/urlreplacers/absurlreplacer.go, transform/urlreplacers/absurlreplacer_test.go
=> transform/urlreplacers: Support unquoted URLs in canonifyURLs replacer

.circleci/config.yml, .travis.yml, snap/snapcraft.yaml
=> Update to Go 1.11.4

tpl/tplimpl/template_ast_transformers.go, tpl/tplimpl/template_ast_transformers_test.go
=> tpl: Fix case handling in cast params

hugolib/page_paths.go, hugolib/page_permalink_test.go
=> hugolib: Improve logic of output path trimming

cache/namedmemcache/named_cache.go, cache/namedmemcache/named_cache_test.go, deps/deps.go, helpers/general.go, helpers/general_test.go, hugolib/resource_chain_test.go, media/mediaType.go, media/mediaType_test.go, parser/metadecoders/format.go, parser/metadecoders/format_test.go, resource/resource.go, resource/resource_test.go, resource/transform.go, tpl/transform/init.go, tpl/transform/remarshal.go, tpl/transform/remarshal_test.go, tpl/transform/transform.go, tpl/transform/transform_test.go, tpl/transform/unmarshal.go, tpl/transform/unmarshal_test.go
=> tpl/transform: Add transform.Unmarshal func

commands/convert.go, commands/hugo.go, commands/import_jekyll.go, config/configLoader.go, go.sum, hugolib/config.go, hugolib/page_content.go, hugolib/resource_chain_test.go, hugolib/site.go, parser/metadecoders/decoder.go, parser/metadecoders/decoder_test.go, parser/metadecoders/format.go, parser/metadecoders/format_test.go, tpl/transform/remarshal.go, tpl/transform/unmarshal.go, tpl/transform/unmarshal_test.go
=> Work in progress: Add CSV support to transform.Unmarshal

docs/content/en/functions/reflect.IsMap.md, docs/content/en/functions/reflect.IsSlice.md, tpl/tplimpl/template_funcs.go
=> tpl: Add missing reflect import in tplimpl

hugolib/case_insensitive_test.go, tpl/tplimpl/template_ast_transformers.go, tpl/tplimpl/template_ast_transformers_test.go
=> Fix Params case handling in the new site global

.circleci/config.yml, .travis.yml
=> Bump to Go 1.11.5

hugolib/shortcode.go, hugolib/shortcode_test.go, parser/pageparser/pagelexer_shortcode.go, parser/pageparser/pageparser_shortcode_test.go, tpl/tplimpl/template.go
=> Fix some inline shortcode issues

transform/urlreplacers/absurlreplacer.go, transform/urlreplacers/absurlreplacer_test.go
=> Rewrite relative action URLS

resources/image.go, resources/image_test.go, resources/testhelpers_test.go
=> resources: Fix image publish ordering issue

docs/content/en/hugo-pipes/fingerprint.md, resources/resource_transformers/integrity/integrity.go, resources/resource_transformers/integrity/integrity_test.go
=> integrity: Add support for sha384

commands/limit_darwin.go
=> Adjust rlimit logic

.circleci/config.yml, .travis.yml
=> Update to Go 1.12.2 and Go 1.11.7

hugolib/page__paginator.go, hugolib/paginator_test.go, hugolib/site_render.go, tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/pagination.html
* Rewind paginator for server mode
* Add some more related tests.
* Replace the clumsy scratch constructs in internal paginator template with variables
See #5825
=> Misc paginator adjustments

hugolib/hugo_sites.go, hugolib/hugo_sites_build.go, hugolib/hugo_sites_rebuild_test.go, hugolib/page.go, hugolib/page__output.go, hugolib/page__paginator.go, hugolib/site_render.go, hugolib/testhelpers_test.go
=> Fix paginator refresh on server change

hugolib/page_test.go, hugolib/site_sections.go
=> hugolib: Fix dates for sections with dates in front matter

tpl/collections/collections.go, tpl/collections/collections_test.go
=> tpl/collections: Make Pages etc. work in uniq

tpl/collections/collections.go, tpl/collections/collections_test.go
=> tpl/collections: Make Pages etc. work with the in func

hugolib/page__content.go, hugolib/shortcode.go, hugolib/shortcode_test.go
=> hugolib: Fix shortcode version=1 logic

tpl/compare/compare.go, tpl/compare/compare_test.go
=> tpl/compare: Fix nil compare in eq/ne for interface values

lazy/init.go, lazy/init_test.go
=> lazy: Fix concurrent initialization order

deploy/deploy.go, deploy/deployConfig.go, deploy/deploy_test.go
Fixes #5936.
Let me know if you have other test ideas.
=> deploy: Add tests; fix Windows

docs/content/en/tools/migrations.md
Suggesting a simple yet powerful tool for people looking to export their Medium blog to Hugo
=> Medium -> Hugo exporting tool

commands/deploy.go, deploy/deployConfig.go, deploy/deployConfig_test.go, docs/content/en/hosting-and-deployment/hugo-deploy.md
=> docs: Add documentation for "hugo deploy"

commands/deploy.go, deploy/deploy.go, docs/content/en/hosting-and-deployment/hugo-deploy.md
Fixes #6008.
Also added a `FEEDBACK` line that prints the target and URL.
=> deploy: Default to the first deployment target

hugolib/menu_test.go, tpl/collections/collections_test.go, tpl/collections/where.go, tpl/collections/where_test.go
=> tpl/collections: Unwrap any interface value in sort and where

hugolib/page__paths.go, hugolib/pagebundler_test.go, hugolib/testhelpers_test.go, resources/page/page_paths.go
=> hugolib: Fix bundle path when slug is set

examples/blog/README.md
=> update and HTTPS Urls

docs/content/en/content-management/front-matter.md, go.mod, go.sum
Extracted from #6043 as the version update / documentation are useful on their own and I'm unsure how to continue with the remainder.
=> Update go-org version & document org front matter format

tpl/collections/init.go, tpl/collections/merge.go, tpl/collections/merge_test.go
=> tpl/collections: Add Merge function

releaser/git.go
=> Remove unused function

hugolib/image_test.go, resources/image_cache.go
=> resources: Fix image Width/Height regression

hugolib/hugo_modules_test.go, langs/i18n/translationProvider.go
=> Fix i18n project vs theme order

commands/config.go, hugofs/rootmapping_fs.go, hugofs/rootmapping_fs_test.go, hugolib/config.go, hugolib/filesystems/basefs.go, hugolib/filesystems/basefs_test.go, hugolib/hugo_modules_test.go, modules/client.go, modules/collect.go, modules/collect_test.go, modules/config.go
=> WIP: Fix self-mounts on the main project

hugolib/pagebundler_test.go, hugolib/pages_capture.go
=> hugolib: Fix bundle header clone logic

compare/compare.go, compare/compare_strings.go, compare/compare_strings_test.go, hugolib/menu_test.go, hugolib/taxonomy.go, navigation/menu.go, resources/page/pagegroup.go, resources/page/pages_sort.go, tpl/collections/sort.go, tpl/collections/sort_test.go, tpl/compare/compare.go, tpl/compare/compare_test.go, tpl/compare/init.go, tpl/compare/truth_test.go
=> Implement lexicographically string sorting

hugolib/page_kinds.go, hugolib/site_output.go, hugolib/site_output_test.go, resources/page/page_kinds.go, resources/page/page_kinds_test.go
=> hugolib: Fix output format handling of mix cased page kinds

transform/urlreplacers/absurlreplacer.go
Improved performance due to `bytes.Index` repeated calls.
Fixes #5942
=> Cache the next position of `urlreplacer.prefix`

hugolib/pagebundler_test.go
=> Add a branch bundle test case

commands/static_syncer.go, hugofs/rootmapping_fs_test.go, hugolib/filesystems/basefs.go, hugolib/filesystems/basefs_test.go
=> Fix static sync issue with virtual mounts

common/herrors/error_locator.go, deploy/deploy.go, resources/smartcrop.go
Drop error & nil checks where the value can not have changed.
=> Fixed tautological error conditions

hugolib/cascade_test.go, hugolib/collections_test.go, hugolib/hugo_sites_build.go, hugolib/page.go, hugolib/page__common.go, hugolib/page__meta.go, hugolib/page__new.go, hugolib/pagecollections.go, hugolib/pages_map.go, hugolib/site.go, hugolib/testhelpers_test.go
=> Implement cascading front matter

helpers/content_test.go, hugolib/pages_capture.go, tpl/tplimpl/template.go
- Use bytes.Equal instead of bytes.Compare
- Omit range's value where it's unused
=> Simplify code

hugofs/nosymlink_test.go, hugolib/config.go, hugolib/hugo_sites_build_test.go, output/outputFormat_test.go, tpl/collections/collections.go
Dropped/fixed ineffectual assignments after static code analysis.
=> Fixed ineffectual assignments

parser/pageparser/pagelexer.go, resources/page/permalinks.go, tpl/images/images_test.go
No need to convert these types.
=> Avoid unnecessary conversions

hugolib/hugo_modules_test.go, modules/collect.go
=> modules: Do not fail build on errors in theme.toml

hugofs/glob/glob.go, hugofs/glob/glob_test.go, hugolib/site.go, resources/resource_cache.go, resources/resource_cache_test.go, resources/resource_factories/bundler/bundler.go, resources/resource_factories/create/create.go, resources/transform.go
=> Improve the server assets cache invalidation logic

commands/commandeer.go, commands/deploy.go, commands/hugo.go, commands/mod.go, commands/new.go, commands/new_theme.go, commands/server.go, commands/static_syncer.go
Wrap the field to make it accessible after initialization.
Fixes #6193
=> feat: Wrap `commandeerHugoState.hugo`

hugolib/filesystems/basefs.go, hugolib/filesystems/basefs_test.go
=> o Fix live reload mount logic with sub paths

hugolib/pagecollections.go, hugolib/site_test.go
=> Fix mainSections logic

hugolib/page.go, hugolib/pagebundler_test.go, hugolib/pages_capture.go, tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/_default/rss.xml
=> hugolib: Allow index.md inside bundles

go.mod, go.sum
see #6254 and [the test case with explanation](https://niklasfasching.github.io/go-org/#footnotes_in_headline.org)
=> deps: Update go-org (fix footnotes in headlines)

go.mod, go.sum
</dt> and </dd> closing tags were broken, see https://github.com/niklasfasching/go-org/pull/9
also is there any limit to how often i should make pull requests for version updates? it seems like there will be a steady supply of bugs :D
=> deps: Update go-org (fix descriptive lists)

go.mod, go.sum, resources/image.go, resources/image_test.go, resources/images/config.go, resources/images/config_test.go, resources/images/exif/exif.go, resources/images/exif/exif_test.go, resources/images/image.go, resources/resource/resourcetypes.go, resources/resource_spec.go, resources/transform.go
=> Add image.Exif

hugolib/image_test.go, hugolib/testhelpers_test.go, resources/image.go, resources/image_cache.go, resources/image_test.go, resources/resource.go, resources/resource_spec.go, resources/resource_transformers/htesting/testhelpers.go, resources/testhelpers_test.go
=> Cache processed images by their source path

tpl/compare/compare.go, tpl/compare/compare_test.go
=> tpl: Remove eq argument limitation

hugolib/image_test.go, hugolib/testhelpers_test.go, resources/resource.go
=> Avoid writing the same processed image to /public twice

hugolib/hugo_smoke_test.go, hugolib/pagebundler_test.go, resources/transform.go
=> Fix cache key transformed resources

resources/image_test.go
In TestImageOperationsGolden, tolerate slight floating-point rounding
differences due to the use or non-use of "fused multiply and add" (FMA)
instruction on different architectures.
Special thanks to @disintegration for the solution in goldenEqual();
see https://github.com/disintegration/gift/issues/20
Fixes #6387
=> resources: Fix image test error on s390x, ppc64* and arm64

.circleci/config.yml, .travis.yml
=> Update to Go 1.12.10 and 1.13.1

helpers/general.go
=> helpers: Fix data race in global logger init

common/collections/append.go, common/collections/append_test.go
=> common: Fix elements are doubling when append a not assignable type

hugolib/pages_test.go, resources/page/pages_prev_next.go, resources/page/pages_prev_next_test.go, resources/page/pages_sort.go, resources/page/pages_sort_search.go, resources/page/pages_sort_search_test.go, resources/page/pages_sort_test.go, resources/page/testhelpers_test.go, resources/page/weighted.go
=> Make Pages.Prev/Next work like the other Prev/Next methods

media/mediaType.go, media/mediaType_test.go
- See https://discourse.gohugo.io/t/resources-bytype-for-video-files/21285
=> media: Add common video media types

Dockerfile
Hello all! This is tangentially related to #5056. I'm suggesting the following changes to the current `Dockerfile`:
- Use Alpine in both stages for consistency.
- Switch to `mage install` from `go install` as dictated in [the latest docs](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md).
- Easy switch to building Hugo Extended by directly setting `HUGO_BUILD_TAGS` flag at image build time (simpler than the current `99notag` workaround):
```
docker build --build-arg HUGO_BUILD_TAGS=extended .
```
- Update to Go 1.13 and Alpine 3.10.
- The only possibly breaking change: Moved the `hugo` binary in the final stage from `/hugo` to `/usr/bin/hugo` so one can simply run `hugo` without having to search around for its location.
---
I realize these are big changes and I'm honestly not …
=> Dockerfile: Switch to mage builds, various optimizations

hugofs/rootmapping_fs.go, hugofs/rootmapping_fs_test.go, hugolib/language_content_dir_test.go
=> hugofs: Fix crash in multilingual content fs

.travis.yml
As that is what it does at the moment.
=> travis: Allow arm64 to fail

tpl/collections/index_test.go
=> tpl/collections: Add some index map test cases

hugolib/pagebundler_test.go, hugolib/pagecollections.go, hugolib/pages_map.go
=> hubolib: Headless bundles should not be listed in .Pages

docs/content/en/functions/dict.md, tpl/collections/collections.go, tpl/collections/collections_test.go
=> tpl/collections: Allow dict to create nested structures

commands/commandeer.go, commands/commands.go, commands/hugo.go, common/loggers/loggers.go, modules/client.go, modules/collect.go
=> Add some more output if loading modules takes time

markup/highlight/highlight.go, markup/highlight/temphighlighting/highlighting_test.go
Use fmt.Fprint were appropriate instead of Fprintf.  Remove some unused
code.
=> Minor cleanups

hugolib/hugo_sites_build_test.go, hugolib/resource_chain_test.go, tpl/template.go, tpl/tplimpl/template.go, tpl/tplimpl/templateProvider.go
=> Fix language handling in ExecuteAsTemplate

hugolib/cascade_test.go, hugolib/pages_map.go
=> hugolib: Fix cascade in server mode

go.mod, go.sum
Introducing a dependency library bug fix.
#6475
tdewolff/minify#269
=> deps: Update minify

helpers/general.go, helpers/general_test.go, hugolib/template_test.go, resources/image.go, resources/images/filters_test.go, resources/internal/key.go, resources/internal/key_test.go, tpl/partials/partials.go, tpl/partials/partials_test.go
=> tpl/partials: Allow any key type in partialCached

markup/goldmark/toc.go, markup/goldmark/toc_test.go
=> markup: Add typographic chars from goldmark to toc

docs/content/en/getting-started/configuration-markup.md, docs/data/docs.json, hugolib/page__per_output.go, markup/goldmark/toc_test.go, markup/tableofcontents/tableofcontents.go, markup/tableofcontents/tableofcontents_test.go
This commit includes tests and documentation.
=> Create TableOfContents parameter for ordered lists

CONTRIBUTING.md
Add links to the Hugo issues, Hugo docs issues, and Hugo website theme issues.
Close #6233
=> Enhance accessibility to issues

docs/content/en/getting-started/configuration-markup.md, hugolib/content_render_hooks_test.go, markup/converter/hooks/hooks.go, markup/goldmark/convert.go, markup/goldmark/render_link.go
=> Preserve HTML Text for link render hooks

hugolib/filesystems/basefs.go, hugolib/hugo_modules_test.go, hugolib/resource_chain_test.go, modules/collect.go
=> Fix abs path handling in module mounts

hugolib/content_render_hooks_test.go, markup/goldmark/render_link.go
=> Preserve HTML Text for image render hooks

commands/commandeer.go, commands/hugo.go, commands/server.go, hugolib/content_render_hooks_test.go, hugolib/hugo_sites.go, hugolib/page.go, hugolib/site.go, hugolib/testhelpers_test.go
=> hugolib: Improve error and reload handling  of hook templates in server mode

docs/content/en/functions/errorf.md, docs/data/docs.json, tpl/fmt/fmt.go, tpl/fmt/init.go
=> tpl: Add a warnf template func

hugolib/shortcode.go, hugolib/shortcode_test.go
=> hugolib: Fix inline shortcode regression

commands/hugo.go, hugofs/fileinfo.go, hugofs/rootmapping_fs.go, hugofs/rootmapping_fs_test.go, hugolib/filesystems/basefs.go, hugolib/hugo_modules_test.go, hugolib/hugo_sites.go, hugolib/page.go, hugolib/pagecollections.go, hugolib/pages_capture.go
This commit is a general improvement of handling if single file mounts.
Fixes #6684
=> WIP: Support files in content mounts

hugolib/hugo_modules_test.go, hugolib/page.go, hugolib/pagecollections.go, hugolib/testhelpers_test.go
=> hugolib: Fix relative .Page.GetPage from bundle

tpl/internal/go_templates/htmltemplate/hugo_template.go, tpl/internal/go_templates/texttemplate/hugo_template.go, tpl/tplimpl/template_funcs.go
```
name                            old time/op    new time/op    delta
SiteNew/Many_HTML_templates-16    43.4ms ± 0%    42.7ms ± 0%  -1.71%  (p=0.016 n=4+5)
name                            old alloc/op   new alloc/op   delta
SiteNew/Many_HTML_templates-16    17.5MB ± 0%    17.5MB ± 0%    ~     (p=0.690 n=5+5)
name                            old allocs/op  new allocs/op  delta
SiteNew/Many_HTML_templates-16      247k ± 0%      247k ± 0%    ~     (p=0.310 n=5+5)
```
Fixes #6717
=> tpl: Put Go's internal template funcs in Hugo's map

go.mod, go.sum
=> Update to Minify v2.7.0

go.mod, go.sum
This new release improves YAML syntax highlighting.
=> deps: Update github.com/alecthomas/chroma

hugofs/fileinfo.go, hugofs/rootmapping_fs.go, hugofs/rootmapping_fs_test.go, hugolib/content_render_hooks_test.go, hugolib/filesystems/basefs.go, hugolib/hugo_modules_test.go, hugolib/hugo_sites.go, hugolib/hugo_sites_build.go, hugolib/page__per_output.go, hugolib/testhelpers_test.go
=> Fix 0.62.1 server rebuild slowdown regression

hugolib/template_test.go, tpl/tplimpl/template.go, tpl/tplimpl/template_errors.go, tpl/tplimpl/template_test.go
=> Fix baseof with regular define regression

commands/commandeer.go, commands/mod.go, hugolib/config.go, modules/client.go
=> modules: Fix "hugo mod get -u" with no arguments

hugolib/template_test.go, tpl/tplimpl/template.go, tpl/tplimpl/template_test.go
=> Fix base template handling with preceding comments

hugolib/paginator_test.go, hugolib/site_render.go
=> Do not render alias paginator pages for non-HTML outputs

hugofs/decorators.go, hugofs/fileinfo.go, hugofs/nosymlink_test.go, hugofs/rootmapping_fs.go, hugofs/rootmapping_fs_test.go, hugofs/walk.go, hugofs/walk_test.go, hugolib/filesystems/basefs.go, hugolib/filesystems/basefs_test.go, hugolib/hugo_modules_test.go
=> Fix module mount in sub folder

go.mod
=> deps: Update golibsass

commands/commandeer.go, commands/hugo.go
Referencing #6881 and #6880, here is now my pull request with proper commit message.
=> Renaming doWithCommandeer to cfgInit/cfgSetAndInit for clarity, consistency 

docs/content/en/templates/taxonomy-templates.md, hugolib/content_map_page.go, hugolib/page.go, hugolib/site_benchmark_new_test.go, hugolib/taxonomy_test.go, resources/page/page.go, resources/page/page_nop.go, resources/page/testhelpers_test.go
=> Add Page.GetTerms

docs/content/en/readfiles/sectionvars.md, hugolib/404_test.go, hugolib/content_map_page.go, hugolib/page__tree.go
=> Fix crashes for 404 in IsAncestor etc.

hugolib/content_map_page.go, hugolib/taxonomy_test.go
=> Fix panic when home page is drafted

common/hugo/hugo.go, common/hugo/hugo_test.go, docs/content/en/functions/hugo.md
Fixes #6873 
TODO: Add documentation
=> Add hugo.IsProduction shortcut

deploy/deploy.go, deploy/deployConfig.go, deploy/deployConfig_test.go, deploy/deploy_test.go, docs/content/en/hosting-and-deployment/hugo-deploy.md
=> deploy: Implement include/exclude filters for deploy

docs/content/en/hugo-pipes/postcss.md, hugolib/resource_chain_test.go, hugolib/testhelpers_test.go, resources/resource_transformers/postcss/postcss.go, resources/resource_transformers/postcss/postcss_test.go
=> resources: Add basic @import support to resources.PostCSS

hugolib/hugo_sites_rebuild_test.go, tpl/tplimpl/template.go
We have been doing too much work in that case.
Fixes #6968
=> Fix rebuild logic when editing template using a base template

identity/identity.go
=> identity: Preven infinite recursion in server change detection

hugolib/pagecollections.go, hugolib/site.go, hugolib/site_test.go, hugolib/testhelpers_test.go
=> Fix ref/relRef regression for relative refs from bundles

hugolib/pagecollections.go, hugolib/site_test.go
=> Fix ref/relref short lookup for pages in sub-folder

commands/mod.go, config/commonConfig.go, config/commonConfig_test.go, docs/content/en/getting-started/configuration.md, hugolib/resource_chain_test.go, hugolib/site_render.go, langs/language.go, resources/resource_spec.go, resources/transform.go
=> Add build.UseResourceCacheWhen

tpl/collections/collections.go, tpl/collections/collections_test.go
=> {{ in }} should work with html.Template type

deploy/deploy.go, deploy/deploy_test.go, docs/content/en/hosting-and-deployment/hugo-deploy.md
Fix for #7020
First contribution to gohugo and still fairly new to golang so go easy on me 🙇
=> deploy include exclude support for remote

commands/commandeer.go, commands/server.go, config/commonConfig.go, config/commonConfig_test.go
=> Add HTTP header support for the dev server

tpl/collections/collections.go, tpl/collections/collections_test.go, tpl/collections/complement.go, tpl/collections/complement_test.go, tpl/collections/reflect_helpers.go, tpl/collections/symdiff.go
=> Support unComparable args of uniq/complement/in

hugolib/pagecollections.go, hugolib/pagecollections_test.go
=> Fix ambigous error on site.GetPage

docs/content/en/content-management/multilingual.md, langs/config.go, langs/language.go
=> Add languageDirection to language configuration

go.mod, go.sum
=> deps: Update Blackfriday

commands/hugo.go, commands/server.go, commands/server_errors.go, deps/deps.go, hugolib/resource_chain_test.go, resources/resource_spec.go, resources/resource_transformers/htesting/testhelpers.go, resources/resource_transformers/postcss/postcss.go, resources/resource_transformers/postcss/postcss_test.go, resources/testhelpers_test.go, resources/transform.go
=> Improve Tailwind/PostCSS error messages

common/types/convert.go, metrics/metrics.go, metrics/metrics_test.go
Also improve non-string comparisons.
Fixes #7048
=> metrics: Fix --templateMetricsHints

hugolib/content_map.go, hugolib/content_map_page.go, hugolib/page.go, hugolib/page__common.go, hugolib/pagecollections_test.go, resources/page/page.go, resources/page/page_nop.go, resources/page/testhelpers_test.go
=> Add .RegularPagesRecursive

hugolib/resource_chain_test.go, resources/resource_transformers/tocss/scss/client.go, resources/resource_transformers/tocss/scss/client_test.go, resources/resource_transformers/tocss/scss/tocss.go
=> Add workaround for regular CSS imports in SCSS

go.mod, go.sum, markup/goldmark/convert_test.go
This fixes a bug, so there's a small change to tests.
(Actually, tests don't pass for me right now, so I'm hoping CI proves this is all the change that's needed.)
=> Update to goldmark 1.1.25.

hugolib/page.go, hugolib/taxonomy_test.go
Refs #7061 
I don't understand Hugo internals, so this could be a totally bogus fix. But the test is real.
=> Fix GetTerms nil pointer deref?

.circleci/config.yml, .travis.yml
=> Update to Go 1.14.1 and 1.13.9

docs/content/en/content-management/build-options.md, hugolib/content_map.go, hugolib/content_map_page.go, hugolib/disableKinds_test.go, hugolib/page.go, hugolib/page__meta.go, hugolib/site.go, hugolib/testhelpers_test.go, resources/page/pagemeta/pagemeta.go, resources/page/pagemeta/pagemeta_test.go
=> Allow headless bundles to list pages via $page.Pages and $page.RegularPages

commands/gendocshelper.go, commands/hugo.go, docs/content/en/getting-started/configuration.md, docs/data/docs.json, docshelper/docs.go, helpers/docshelper.go, hugolib/hugo_sites.go, hugolib/resource_chain_test.go, markup/markup_config/config.go, media/docshelper.go, minifiers/config.go, minifiers/config_test.go, minifiers/minifiers.go, minifiers/minifiers_test.go, output/docshelper.go, parser/lowercase_camel_json.go, publisher/publisher.go, resources/resource_transformers/minifier/minify.go, resources/resource_transformers/minifier/minify_test.go, tpl/cast/docshelper.go, tpl/resources/resources.go
=> Add minify config

hugolib/content_map_page.go, hugolib/page__new.go, hugolib/site.go
=> Fix cache reset for a page's collections on server live reload

hugolib/content_map.go, hugolib/content_map_page.go, hugolib/disableKinds_test.go, hugolib/page__meta.go, resources/page/pagemeta/pagemeta.go
=> Fix _build.list.local logic

helpers/content.go, helpers/content_test.go
Fixes #7081
where some tags are siblings of p tag
=> [helpers] Fix TrimShortHTML

commands/new_theme.go
See https://github.com/gohugoio/hugoThemes#themetoml
=> Use semver for min_version per recommendations

tpl/encoding/encoding.go, tpl/encoding/encoding_test.go, tpl/encoding/init.go
=> tpl: Extend Jsonify to support options

hugolib/site_test.go, publisher/htmlElementsCollector.go, publisher/htmlElementsCollector_test.go
=> Add a writeStats stress test

publisher/htmlElementsCollector.go, publisher/htmlElementsCollector_test.go
=> Fix some missing JS class collector cases

go.mod, go.sum
=> deps: Update minify to v2.6.2

docs/content/en/functions/math.md, tpl/math/init.go, tpl/math/math.go, tpl/math/math_test.go
=> Add math.Pow

resources/resource_transformers/babel/babel.go
=> Fix Babel on Windows

helpers/path.go, htesting/hqt/checkers.go, hugolib/content_map.go, hugolib/content_map_page.go, hugolib/content_map_test.go, hugolib/page.go, hugolib/page__tree.go, hugolib/pagecollections.go, hugolib/pagecollections_test.go, hugolib/taxonomy_test.go
=> Fix GetPage on section/bundle name overlaps

common/maps/scratch.go, common/maps/scratch_test.go, docs/content/en/functions/scratch.md
=> common/maps: Add Scratch.Values

commands/server.go
=> commands: Fix URL rewrites vs fast render server mode

hugolib/shortcode.go, hugolib/shortcode_test.go
=> Fix crash for closing shortcode with no .Inner set

hugolib/content_map_page.go, hugolib/hugo_sites.go, hugolib/hugo_sites_build.go, hugolib/site.go
=> Fix server data race/nil pointer in withMaps

docs/content/en/templates/partials.md, hugolib/hugo_sites_build_errors_test.go, hugolib/template_test.go, tpl/tplimpl/template.go
=> Add support for inline partials

markup/asciidocext/asciidocext_config/config.go
Added two common extensions to allow my Hugo+Asciidoctor site to build with the new configuration.
=> Update config.go to add two Asciidoctor extensions

docs/content/en/content-management/formats.md
This PR documents the changes made in https://github.com/gohugoio/hugo/pull/7447/files adding two other extensions to the Allowed list.
=> Update formats.md doc for new allowed extensions.

common/types/convert.go, common/types/convert_test.go, go.mod, go.sum, hugolib/openapi_test.go, parser/metadecoders/decoder.go, resources/resource/resourcetypes.go, tpl/openapi/openapi3/init.go, tpl/openapi/openapi3/openapi3.go, tpl/tplimpl/template_funcs.go, tpl/transform/unmarshal.go, tpl/transform/unmarshal_test.go
=> Add openapi3.Unmarshal

go.mod, go.sum, hugolib/js_test.go, media/mediaType.go, media/mediaType_test.go, resources/resource_transformers/js/build.go, resources/resource_transformers/js/build_test.go, tpl/internal/resourcehelpers/helpers.go, tpl/js/init.go, tpl/js/js.go, tpl/resources/resources.go, tpl/tplimpl/template_funcs.go
=> Add js.Build asset bundling

hugolib/hugo_sites_build_errors_test.go, hugolib/template_test.go, tpl/tplimpl/template.go
=> Fix baseof block regression

resources/resource_transformers/js/build.go, resources/resource_transformers/js/build_test.go
=> Add .Defines to js.Build options

docs/content/en/content-management/formats.md, markup/asciidocext/asciidocext_config/config.go, markup/asciidocext/convert.go, markup/asciidocext/convert_test.go
=> Fix Asciidoctor args

publisher/htmlElementsCollector.go, publisher/htmlElementsCollector_test.go
=> publisher: Collect transition attributes as classes

go.mod, go.sum
=> deps: Update Chroma to 0.8.0

tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/pagination.html
=> Fix ellipsis display logic in pagination template

common/loggers/loggers.go, common/loggers/loggers_test.go, hugolib/resource_chain_babel_test.go, hugolib/resource_chain_test.go, modules/client.go, resources/resource_transformers/babel/babel.go, resources/resource_transformers/postcss/postcss.go
=> Improve stderr logginf for PostCSS and simlilar

tpl/strings/init.go, tpl/strings/strings.go, tpl/strings/strings_test.go
=> tpl: Add limit option to replace template function

tpl/collections/init.go, tpl/collections/merge.go, tpl/collections/merge_test.go
=> tpl: Extend merge to accept multiple parameters

deps/deps.go, hugolib/content_map.go, hugolib/hugo_sites.go, hugolib/hugo_sites_rebuild_test.go, hugolib/page.go, hugolib/site.go, hugolib/template_test.go, identity/identity.go, identity/identity_test.go, resources/page/page.go, resources/page/page_nop.go, resources/page/testhelpers_test.go, tpl/fmt/fmt.go, tpl/tplimpl/template_funcs.go
* Fix change detection when .GetPage/site.GetPage is used from shortcode
* Fix stale content for GetPage results with short name lookups on server reloads
Fixes #7623
Fixes #7624
=> Fix some change detection issues on server reloads

.circleci/config.yml, .travis.yml
=> Update to Go 1.15.1 and 1.14.8

commands/mod.go, commands/mod_npm.go, common/hugo/hugo.go, docs/content/en/hugo-pipes/babel.md, hugofs/files/classifier.go, hugofs/rootmapping_fs.go, hugofs/walk_test.go, hugolib/filesystems/basefs.go, hugolib/hugo_modules_test.go, hugolib/resource_chain_test.go, modules/collect.go, modules/config.go, modules/npm/package_builder.go, modules/npm/package_builder_test.go, resources/resource_transformers/babel/babel.go, resources/resource_transformers/postcss/postcss.go
=> Add "hugo mod npm package"

common/hreflect/helpers.go, deps/deps.go, go.mod, go.sum, langs/i18n/i18n.go, langs/i18n/translationProvider.go, tpl/lang/lang.go
=>  langs/i18n: Upgrade to go-i18n v2

docs/content/en/content-management/build-options.md, docs/content/en/content-management/front-matter.md, hugofs/glob/glob.go, hugofs/glob/glob_test.go, hugolib/cascade_test.go, hugolib/content_map_page.go, hugolib/disableKinds_test.go, hugolib/page__meta.go, hugolib/page__paths.go, hugolib/page_test.go, hugolib/pages_capture.go, resources/page/page_matcher.go, resources/page/page_matcher_test.go, resources/page/pagemeta/pagemeta.go, resources/page/pagemeta/pagemeta_test.go, resources/page/testhelpers_test.go
=> Allow cascade to be a slice with a _target discriminator

langs/i18n/i18n.go, langs/i18n/i18n_test.go
=> langs/i18n: Fix i18n .Count regression

htesting/test_helpers.go, hugolib/language_test.go, langs/config.go, langs/i18n/i18n.go, langs/i18n/i18n_test.go, resources/transform_test.go
=> lang/i18n: Fix for language code case issue with pt-br etc.

output/layout.go, output/layout_test.go
```
name      old time/op    new time/op    delta
Layout-2    77.7µs ± 8%    14.0µs ±14%  -81.98%  (p=0.008 n=5+5)
name      old alloc/op   new alloc/op   delta
Layout-2    41.9kB ± 0%     6.3kB ± 0%  -84.88%  (p=0.016 n=5+4)
name      old allocs/op  new allocs/op  delta
Layout-2       487 ± 0%       112 ± 0%  -77.00%  (p=0.008 n=5+5)
```
=> output: Improve layout path construction

tpl/tplimpl/embedded/templates.autogen.go, tpl/tplimpl/embedded/templates/pagination.html
=> embedded: Always show page number when 5 pages or less

common/maps/params.go, common/maps/params_test.go, hugolib/config.go, hugolib/config_test.go, modules/client.go, modules/client_test.go, modules/collect.go, modules/config.go, modules/config_test.go
=> Misc modules improvements/fixes

docs/content/en/content-management/menus.md, docs/content/en/templates/menu-templates.md, hugolib/menu_test.go, navigation/menu.go
Taking a stab at adding params to the menu system for issue #7951 
Any advice or direction greatly appreciated 🙇
=> adding param support to menus for #7951

hugolib/content_render_hooks_test.go, hugolib/page.go, hugolib/site.go, identity/identity.go, markup/goldmark/convert.go, markup/goldmark/render_hooks.go
=> Fix server rebuild issue with partials referenced from render hooks

hugolib/paths/paths.go
I was reading the source code, and found 1 typo(?)
=> fix typo in comments

go.mod, go.sum, hugofs/filter_fs.go, hugofs/noop_fs.go, hugofs/slice_fs.go
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>
=> build(deps): bump github.com/spf13/afero from 1.4.1 to 1.5.1

publisher/htmlElementsCollector.go
=> Fix: #7958 Trim all whitespace in elements written to hugo_stats.json

go.mod, go.sum, resources/resource_transformers/js/options.go
=> deps: Update to esbuild v0.8.39

hugolib/js_test.go, hugolib/resource_chain_babel_test.go, hugolib/resource_chain_test.go
=> github: Enable NPM tests on Windows

go.mod, go.sum
=> deps: Update to Goldmark v1.3.2

docs/content/en/hugo-modules/configuration.md, hugofs/glob/glob.go, modules/client_test.go, modules/collect.go, modules/config.go
=> modules: Add config option modules.vendorClosest

go.mod, go.sum, hugolib/resource_chain_test.go, minifiers/config.go, minifiers/minifiers_test.go
=> deps: Update github.com/tdewolff/minify/v2 v2.6.2 => v2.9.13

docs/content/en/getting-started/configuration-markup.md, hugolib/content_render_hooks_test.go, markup/converter/hooks/hooks.go, markup/goldmark/render_hooks.go
=> WIP: Allow markdown attribute lists to be used in render hooks

markup/goldmark/convert.go, markup/goldmark/convert_test.go, markup/goldmark/render_hooks.go
=> markup: Handle attribute lists in code fences

hugolib/config.go, hugolib/config_test.go
=> Fix OS env override for nested section only available in theme

go.mod, go.sum, minifiers/minifiers_test.go
=> deps: Bump github.com/tdewolff/minify/v2 v2.9.15

output/docshelper.go
=> Fix typo in docshelper.go

publisher/htmlElementsCollector_test.go
=> publisher: Also test minified HTML in the element collector

releaser/releasenotes_writer.go
=> Remove duplicate references from release notes

go.mod, go.sum, hugolib/page_test.go
Updated test per <https://github.com/yuin/goldmark/pull/205>.
Fixes #8377
=> build(deps): bump github.com/yuin/goldmark from 1.3.2 to 1.3.5

media/mediaType.go, media/mediaType_test.go
Introduced in Hugo 0.82.0.
Fixes #8406
=> Regression in media type suffix lookup

tpl/collections/where.go, tpl/collections/where_test.go
=> Fix Params case handling in where with slices of structs (e.g. Pages)

common/hreflect/helpers.go
=> Correct function name in comment

hugolib/shortcode_test.go, tpl/tplimpl/template.go
=> Make the shortcode template lookup for output formats stable

tpl/collections/where.go, tpl/collections/where_test.go
=> tpl/collections: Fix where on type mismatches
