- commands/deploy.go
Fixes #7451.
I verified the bug; `invalidateCDN` and `maxDeletes` both had the trivial values (`false` and `0`) if they were not set at the command line.
I think this is the right fix, although I am not very familiar with how flags and config are processed in Hugo.
I confirmed locally that now `maxDeletes` and `invalidateCDN` now have the appropriate defaults, and that they are modified when command line flags are given.
> deploy: Ensure that non-trivial default flag values are passed through

- markup/goldmark/autoid.go
- markup/goldmark/autoid_test.go
Applicable when autoHeadingIDType is either `github` or `github-ascii`.
When autoHeadingIDType is `blackfriday`, the existing code removes
trailing whitespace while iterating through the characters, using
a boolean "futureDash" mechanism.
Fixes #6798
> Remove trailing hyphen from auto heading ID

- parser/pageparser/doc.go
- parser/pageparser/pagelexer.go
- parser/pageparser/pagelexer_intro.go
- parser/pageparser/pagelexer_shortcode.go
- parser/pageparser/pageparser.go
If you go to the [pageparser documentation](https://pkg.go.dev/github.com/gohugoio/hugo@v0.74.2/parser/pageparser?tab=doc) the short intro text comes up four times. This PR should fix this.
> Make sure documentation intro text only appears once

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/schema.html
Prior to this change, the offset indicator for dates with positive
offsets was rendered as `&#43;` instead of `+`.
Fixes #7495
> Fix date format in internal schema template

- go.mod
- go.sum
fixes a bug in [list item parsing](https://github.com/niklasfasching/go-org/commit/64b2b22270fcf556fc00f281324d47fdd8c5412f/)
> deps: Update go-org to v1.3.1

- magefile.go
Adds the reciprocal target to `mage install`. This is a quick shortcut to deleting a dev binary of Hugo to make it as easy to remove as it was to install.
> mage: Add uninstall target

- deploy/deploy.go
- deploy/deployConfig.go
- deploy/deploy_test.go
> Respect mediatypes for deploy

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/pagination.html
Reverts gohugoio/hugo#7527
This fix removed desirable behavior when pager count > 5.
> Revert "Fix ellipsis display logic in pagination template"

- tpl/strings/init.go
- tpl/strings/regexp.go
- tpl/strings/regexp_test.go
Go stdlib doesn't contain a limited replace in the regexp package, but
we can accomplish the same thing with ReplaceAllStringFunc.
Fixes #7586
> tpl: Add limit support to replaceRE

- go.mod
- go.sum
- resources/resource_transformers/js/build.go
- resources/resource_transformers/js/build_test.go
Added inline source map support to allow debugging during "development".
It's not quite able to send source map into .js.map files but makes debugging a lot easier.
Example:
I didn't want to attach this directly to 7504 because there were additional discussions about code splitting to enable external map files; so I pushed it as the #7607 duplicate.
It's a rather simple addition but would really help to develop javascript since you can use the chrome editor by mapping files.
> js.Build: Add SourceMap flag into js.Build opts which can turn on sourcemap.

- docs/content/en/content-management/toc.md
- markup/asciidocext/convert.go
- markup/asciidocext/convert_test.go
Fill the .TableOfContents template variable when writing Asciidoc content.
This is done by letting Asciidoc render its TOC as HTML, then extract this
HTML rendered TOC, parse it into a tableofcontents.Root and finally remove
it from the HTML content.
This aims to stay in the logic that the Asciidoc parsing is entirely done
by the external helper.
See #1687
> markup/asciidoc: Add support for .TableOfContents

- transform/livereloadinject/livereloadinject.go
- transform/livereloadinject/livereloadinject_test.go
Whilst potentially valid for HTML5 under certain conditions, URLs should be encoded properly. This PR changes 
`<script src="/livereload.js?port=%d&mindelay=10&v=2" data-no-instant defer></script>` to 
`<script src="/livereload.js?port=%d&amp;mindelay=10&amp;v=2" data-no-instant defer></script>`
> Escape `&` in livereload injected code

- docs/content/en/content-management/formats.md
- docs/content/en/content-management/toc.md
- markup/asciidocext/convert.go
- markup/asciidocext/convert_test.go
- markup/tableofcontents/tableofcontents.go
Running this adoc (https://asciidoctor.org/docs/install-toolchain/) through Hugo with Hugo Learn Theme, currently produces:
With this PR:
Fixes #7649
> markup/asciidocext: Fix AsciiDoc TOC with code

- docs/content/en/content-management/syntax-highlighting.md
- markup/highlight/config.go
- markup/highlight/highlight_test.go
Fix #7622 by adding support to the same options that Pygments supported, but now in Chroma. :)
> markup/highlight: Add support to linkable line anchors on Chroma

- hugolib/site.go
- hugolib/site_render.go
if the layout name was specified on the page or section then show it as part of the missing template warning.
Ref: #7617
> tpl: Added simple addition to show layout name

- resources/image.go
- resources/image_test.go
- resources/resource/resourcetypes.go
- resources/transform.go
> resources/image: Fix nilpointer for images with no Exif

- docs/content/en/hugo-pipes/postcss.md
In PostCSS 8 you need to install `postcss` because we move it to `peerDependencies`
> Fix CLI example for PostCSS 8

- config/privacy/privacyConfig.go
- config/privacy/privacyConfig_test.go
- docs/content/en/about/hugo-and-gdpr.md
- resources/page/page_marshaljson.autogen.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/vimeo.html
- tpl/tplimpl/embedded/templates/shortcodes/vimeo_simple.html
Added a Vimeo EnableDNT privacy option to the Hugo config. This will enable the Vimeo 'Do Not Track' flag when either Vimeo shortcode tempalte options are used. When enabled, it will force the Vimeo player to be blocked from tracking any session data, including all cookies and stats.
Fixes #7700
> tpl: Add Do Not Track (dnt) option to Vimeo shortcode

- commands/server.go
- config/commonConfig.go
- docs/content/en/getting-started/configuration.md
> Add force flag to server redirects config

- go.mod
- go.sum
- langs/i18n/i18n_test.go
- langs/i18n/translationProvider.go
Hugo 0.76.0 updated go-i18n from v1 to v2. This allowed us to set the TOML unmarshaler to use, so we set the one we use in other places in Hugo.
But that does not support dotted bare keys, which caused some breakage in the wild.
This commit fixes that by:
* Using go-toml for language files
* Updating go-toml to the latest version
> langs/i18n: Fix for bare TOML keys

- Dockerfile
Golang 1.13 used for build is now EOL, updated to latest 1.15. Updated main image to alpine 3.12 to match alpine used in build.
> update to golang 1.15 and alpine 3.12

- hugolib/content_map.go
- hugolib/disableKinds_test.go
- hugolib/page__paths.go
- hugolib/site_render.go
> Render aliases even if render=link

- markup/highlight/highlight.go
Avoid creating a local copy of the highlight configuration when no
options are passed.
Benchmarks of building the docs site:
```
name        old time/op    new time/op    delta
DocsSite-2     1.94s ± 4%     1.93s ± 4%    ~     (p=0.841 n=5+5)
name        old alloc/op   new alloc/op   delta
DocsSite-2     666MB ± 1%     656MB ± 0%  -1.48%  (p=0.008 n=5+5)
name        old allocs/op  new allocs/op  delta
DocsSite-2     8.85M ± 0%     8.76M ± 0%  -1.04%  (p=0.029 n=4+4)
```
> highlight: Avoid making unnecessary allocation

- docs/content/en/functions/time.md
- tpl/time/init.go
- tpl/time/time.go
- tpl/time/time_test.go
Fixes #7860 
This PR adds an optional [LOCATION] parameter to the Hugo `time` function which will internally utilize Go's `ParseInTimezone()` functionality to return a `time.Time` instance that is associated with a specific timezone.
- ✔️ No breaking changes. (Added functionality only)
- ✔️ Documentation updated.
> tpl: Update Hugo time to support optional [LOCATION] parameter

- common/maps/maps.go
- common/maps/maps_test.go
- hugolib/cascade_test.go
- hugolib/page__meta.go
The TOML lib unmarshals slices of string maps to []map[string]interface{}
whereas YAML and JSON decode to []interface{}
The existing tests only check for TOML working correctly, and _target
with cascade did not work at all for frontmatter defined in other formats.
Add a function to normalize those slices
Fixes #7874
> Allow cascade _target to work with non toml frontmatter

- Dockerfile
- commands/deploy.go
- commands/nodeploy.go
- deploy/cloudfront.go
- deploy/deploy.go
- deploy/deployConfig.go
- deploy/deployConfig_test.go
- deploy/deploy_azure.go
- deploy/deploy_test.go
- deploy/google.go
- magefile.go
Fixes https://github.com/gohugoio/hugo/issues/7826
You can run `HUGO_BUILD_TAGS=nodeploy mage install` or `go install --tags nodeploy` to build `hugo` without the `deploy` command which will make the binary smaller and prevent crashes on certain systems https://github.com/gohugoio/hugo/issues/6324
I kept the command in there by creating `nodeploy.go` that simply returns an error if the user tries to call `hugo deploy`.
```
eric@eric-manjaro-ml ~/p/hugo (feature/build-without-deploy)> hugo deploy
Error: build without HUGO_BUILD_TAGS=nodeploy to use this command
```
Please let me know if you'd like me to remove the `deploy` command all together or keep it like this to warn the user.
> build: allow optional "nodeploy" tag to exclude deploy command from bin

- create/content.go
If newContentEditor has editor name with arguments like `emacsclient -n`, it fails with `executable file not found in $PATH`. This change parses the value correctly and passes it to the given editor.
> create: Pass editor arguments from newContentEditor correctly

- tpl/collections/merge.go
- tpl/collections/merge_test.go
Value.Type().Key() must only be called on map values.
Fixes #7899
> tpl: Fix reflection bug in merge

- tpl/transform/fuzz.go
This PR answers https://github.com/gohugoio/hugo/issues/5710 by adding the first fuzzer to Hugo.
I can confirm that this fuzzer runs on oss-fuzz's infrastructure. I have setup the integration with oss-fuzz which can be found [here](https://github.com/google/oss-fuzz/pull/4589). The build on the oss-fuzz side will fail, and that is because this fuzzer is not merged in yet upstream. Once this fuzzer is merged in here, I will run the integration test again within oss-fuzz and the tests will then pass.
> Add a fuzzer

- docs/content/en/hosting-and-deployment/hosting-on-github.md
GitHub changed their default branch from "master" to "main" earlier this year. This updates the docs to reflect that in the GitHub deployment instructions.﻿
> Update GH docs to say "main" as default branch

- commands/static_syncer.go
- hugolib/filesystems/basefs.go
- hugolib/filesystems/basefs_test.go
- hugolib/site.go
- resources/resource_transformers/js/options.go
- resources/resource_transformers/tocss/scss/tocss.go
This commit fixes some issues where modules in /assets share the same name as in node_modules.
This was not intended, and with this commit the node_modules-components should be isolated. If you want to redefine something inside node_modules, use the `defines` option.
Fixes #7948
> js: Let ESBuild handle all impports from node_modules

- resources/page/page_paths.go
- resources/page/page_paths_test.go
For now, `url` set in frontmatter is sanitized.
This PR tweak the behavior to preserve user-defined `url` value, skipping sanitization.
This is consistent with `aliases`' manner.
I am maintaining a site, where hugo's version is relatively old.
The site has some contents, of which urls are containing "double dash" like `foo--1.md`.
I need any workaround to keep these urls with latest version of hugo.
related #6007 (already closed)
> resources: Preserve url set in frontmatter without sanitizing

- examples/blog/layouts/partials/meta.html
```html
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
```
This was only needed for IE10 and lower (which are no longer supported) and chromeframe which was a Google plugin for IE8 and lower and was discontinued many years ago. So this meta tag can be safely removed.
> remove unneeded meta tag from blog example

- common/maps/params.go
- docs/content/en/getting-started/configuration.md
- hugolib/config.go
- hugolib/config_test.go
> Allow setting the delimiter used for setting config via OS env, e.g. HUGO_

- tpl/strings/strings.go
- tpl/strings/strings_test.go
Fix miscalculations when start is negative.  Results should now match
PHP substr.
Fixes #7993
> tpl: Refactor and fix substr logic

- tpl/strings/strings.go
- tpl/strings/strings_test.go
When length parameter is zero, always return an empty string.
Updates #7993
> tpl: Fix substr when length parameter is zero

- docs/content/en/content-management/shortcodes.md
- hugolib/embedded_shortcodes_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/youtube.html
Allowing the user to specify a meaningful `title` improves the [accessibility](https://dequeuniversity.com/tips/provide-iframe-titles) for YouTube videos.  If no `title` is specified, the current behavior is preserved.
> Add title parameter to YouTube shortcode to allow overriding the default

- tpl/tplimpl/embedded/templates/opengraph.html
When inside front matter you specified series with spaces, then the opengraph template wouldn't detect other articles, because in `.Site.Taxonomies.series` they are stored by urlized key.
Example:
```yaml
series:
- My Series
```
```gohtml
{{/* in a template */}}
{{- $series := index .Site.Taxonomies.series $name }}
{{/* was resolved to */}}
{{- $series := index {'my-series': ...} "My Series" }}
```
> Fix: Invalid series detection in opengraph

- common/para/para_test.go
Give us more visibility into how badly a given host is failing in the
time test.
Updates #6963
> para: Show more detail on failed time test

- docs/content/en/content-management/page-resources.md
- hugolib/content_map_test.go
- hugolib/pagebundler_test.go
- hugolib/resource_chain_test.go
- resources/resource_spec.go
- resources/resource_test.go
The one exception being for the Page, which does not have a MIME type, in which you will get the value `page`.
Fixes #8052
> Fix Resource.ResourceType so it always returns MIME's main type

- SECURITY.md
This file is used by Github as a tab on the repos homepage to access information about how to report security issues. The text is kept simple.
Will solve #8074
> docs: create a SECURITY.md

- resources/page/pagegroup.go
- resources/page/pagegroup_test.go
My goal was to sort my readinglist per year. Here I have three date-params:
- date (just the usual page attribute)
- started (when I started reading the book)
- finished (when I finished the book)
Now I wanted the grouping to happen for the `finished` field in a way similar to how GoodReads does it. So I tried the following code:
```go
{{ range .Pages.GroupByParamDate "finished" "2006" }}
```
Sadly, this resulted in only a single group with the key `0001`. This kind of started smelling like an issue with the date format so I went digging.
Turns out that the `Pages.GroupByParamDate` method converts the parameter to a lower-case representation and tries to convert that into a time.Time if it isn't already of that type. That fails for things like RFC3339-formatted dates because the `T` …
> GroupByParamDate not supporting datetimes

- go.mod
- go.sum
- markup/org/convert.go
- markup/org/convert_test.go
- Add support for pretty urls [1]. Rewrite file links:
1. replace the `.org` extension with `/` (`/foo.org` -> `/foo/`)
2. prefix unrooted links with `../` as relative links start in the fake
subdirectory `/foo/` rather than `/`
- Fix case-sensitivity of org drawer `:end:`
[1] https://gohugo.io/content-management/urls/#pretty-urls
> deps: Update go-org to v1.4.0

- tpl/strings/strings.go
- tpl/strings/strings_test.go
Most other substr implementations don't error out in out-of-bounds cases
but simply return an empty string (or a value that's printed as an empty
string). We'll follow their lead and not exit template execution.  Allow
the user decide what to do with the empty result.
Fixes #8113
> tpl: Do not return errors in substr for out-of-bounds cases

- tpl/partials/partials.go
When tracking for cache hints, track the same template name as the call
to MeasureSince in Execute.  When referencing a partial "foo", the value
of `n` does not match `templ.Name()` (`partials/foo` versus
`partials/foo.html`).  This was causing hints to go untracked since
there was no existing metric to append the hint to.
Fixes #8125
> tpl: Fix metrics hint tracking

- hugolib/js_test.go
- hugolib/resource_chain_babel_test.go
- resources/resource_transformers/babel/babel.go
- resources/resource_transformers/js/build.go
- resources/resource_transformers/js/options.go
- resources/resource_transformers/js/options_test.go
WIP
Hopefully there is a way to make a test binary to validate production creation of source maps. In dev it seems to work as expected. Still needs test scripts.
Added rollup for testing.
Added sourceMaps option for babel. Babel can also read sourcemaps from
the output of an esbuild if they are "inline", it will then
convert the file and remap the source maps and then re-export them
but currently not if they are "external".
Added support for sourcemap = "external" for esbuild.
Ref #8132
> pipes: rollup, babel, esbuild

- docs/content/en/hugo-pipes/js.md
- hugolib/js_test.go
- resources/resource_transformers/js/options.go
https://github.com/gohugoio/hugoTestProjectJSModImports has a running example with shimming when in production.
Fixes #8165
> js: Add Shims option

- tpl/tplimpl/template.go
Copy most of the htmltemplate cloning to the textemplate implementation
in the same function.
> tpl: Fix race condition in text template baseof

- docs/content/en/hugo-pipes/js.md
- hugolib/js_test.go
- resources/resource_transformers/js/build.go
- resources/resource_transformers/js/options.go
> js: Add Inject config option

- tpl/os/os.go
Instead of [adding an option](https://github.com/gohugoio/hugo/pull/8169) that would allow to change the limit, we just remove this limit. 
More context here: https://discourse.gohugo.io/t/error-calling-readfile-file-is-too-big/25460.
Will need to update the docs too.
> tpl/os: remove 1mb limit for readFile.

- docs/content/en/functions/readfile.md
The limit itself was removed in [this PR](https://github.com/gohugoio/hugo/pull/8172).
> content/en/functions: remove mention of a file size limit for readFile.

- tpl/data/data.go
I would like to add a default user-agent header for getJSON function because many API's would like to read user-agent header. For example, I'm developing a simple Instagram shortcode but always getting an error because getjSON function doesn't send User-Agent header
> Add default user-agent header for getJSON requests

- hugolib/site_test.go
- hugolib/sitemap_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/_default/sitemap.xml
Currently, pages with `render = "never"` get listed in sitemap.xml, even though they have no permalink, resulting in sitemap entries with empty URL fields (i.e. with `<loc></loc>`). Such pages should be excluded from the sitemap.
> Sitemap: exclude "no render" pages

- docs/content/en/getting-started/configuration-markup.md
- docs/data/docs.json
- markup/goldmark/convert.go
- markup/goldmark/convert_test.go
- markup/goldmark/goldmark_config/config.go
- markup/goldmark/internal/extensions/attributes/attributes.go
- markup/markup_config/config.go
- markup/markup_config/config_test.go
> markup/goldmark: Add attributes support for blocks (tables etc.)

- go.mod
- go.sum
- hugolib/page__meta.go
- hugolib/site_test.go
- tpl/inflect/inflect.go
- tpl/inflect/inflect_test.go
Close #7912 
This issue was caused by [`markbates/inflect`](https://github.com/markbates/inflect) which is deprecated now. use [github.com/gobuffalo/flect](https://github.com/gobuffalo/flect) instead which is recommended solve this issue and won't break `hugo`.
> Fix: wrong space for humanize func in some case

- common/hugo/hugo.go
- common/hugo/version.go
This PR is intended to add an optional "vendorInfo" string to help pinpoint the exact origin of a Hugo binary when `hugo version` is reported in a GitHub issue.  For example:
```
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2021-02-09T18:47:48Z (debian 0.80.0-6)
```
which may help determine whether an issue is generic (Hugo upstream) or vendor-specific.
Example snippet from debian/rules:
```
include /etc/os-release
PACKAGE := github.com/gohugoio/hugo
VENDOR_INFO := $(ID) $(shell dpkg-parsechangelog --show-field Version)
all:
go build -ldflags '-X "$(PACKAGE)/common/hugo.vendorInfo=$(VENDOR_INFO)"'
```
See https://salsa.debian.org/go-team/packages/hugo/-/blob/debian/sid/debian/rules for a full example.
I have just started using this in the hugo 0.80.0-6 Debian …
> Change version string format, and add VendorInfo to help with issue triaging

- tpl/tplimpl/embedded/templates/opengraph.html
- tpl/tplimpl/embedded/templates/schema.html
This is in response to my previous PR #8186.
* Removed date checking of `PublishDate` and `Lastmod` 
* Merged duplicate `IsPage` blocks in opengraph.html
* Formatted template tags so they're easier to follow. There are a lot of nested blocks and keeping track of what's open and what's closed was extremely tedious. I hope the changes I made makes this easier.
Feel free to cherry pick the date changes and exclude the formatting change.
> Update date logic of opengraph and schema internal templates

- docs/content/en/content-management/formats.md
- markup/asciidocext/asciidocext_config/config.go
- markup/asciidocext/convert.go
- markup/asciidocext/convert_test.go
This PR implements proposal #7698 which allows for arbitrary Asciidoc extensions in unsafe mode expanding the range of possibilities when using this markup language. 
The proposal allows for arbitrary extension when [`SafeMode`](https://docs.asciidoctor.org/asciidoctor/latest/safe-modes/) option is set to `unsafe`.  Any stricter mode would prevent arbitrary extensions and only those listed in the [configuration](https://github.com/gohugoio/hugo/blob/master/markup/asciidocext/asciidocext_config/config.go#L40) would be allowed.
> markup: Allow arbitrary Asciidoc extension in unsafe mode

- Dockerfile
As mentioned in  https://github.com/gohugoio/hugo/issues/8210
Hugo version 0.81.0 only compiles on golang > 1.16
This PR fixes the build error in the current Dockerfile
relates to: #8210
> Upgrade golang version for current Dockerfile

- docs/content/en/about/hugo-and-gdpr.md
- docs/content/en/templates/internal.md
- hugolib/embedded_templates_test.go
- hugolib/testhelpers_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/google_analytics.html
Reopen #8264. I should've created a branch for the PR so that when I rebased master it didn't break everything. @coliff 
>The Google analytics template doesn't work with Google Analytics v4 (gtag.js) #7954. v3 analytics.js is not depreciated so we should support both using hasPrefix to tell the difference.
>It should be noted that gtag uses the async attribute. Which is more like google_analytics_async.html. I'm not sure if we should move the changes to that template instead. The naming of the template is also confusing. See #8261.
>Privacy settings anonymizeIP and respectDoNotTrack are supported while useSessionStorage is not. I could only find one document with instructions for session storage but in my testing it still set cookies.
> Add support for google analytics v4

- hugolib/content_render_hooks_test.go
- hugolib/page.go
- hugolib/page__output.go
- hugolib/page__per_output.go
- markup/converter/converter.go
- markup/converter/hooks/hooks.go
- markup/goldmark/render_hooks.go
> Fix output format handling for render hooks

- .github/ISSUE_TEMPLATE/config.yml
Changed the description for the discourse link to a little more forceful wording. I also suggest to create a `discourse` label that has some description with a link to the discourse to  brush off people to the discourse.
> chore: more explicit support link to discourse

- commands/new_theme.go
`hugo new theme foo` creates theme `foo` in `./themes` and not in current directory.
> Fix `new theme` command description

- docs/content/en/getting-started/configuration-markup.md
- markup/goldmark/convert_test.go
- markup/goldmark/internal/extensions/attributes/attributes.go
> Attributes for code fences should be placed after the lang indicator only

- docs/content/en/content-management/urls.md
- resources/page/permalinks.go
- resources/page/permalinks_test.go
- resources/page/testhelpers_test.go
> Add slice syntax to permalinks config

- publisher/htmlElementsCollector.go
- publisher/htmlElementsCollector_test.go
> publisher: Skip script, pre and textarea content when looking for HTML elements

- hugolib/page_test.go
- hugolib/shortcode_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/figure.html
> Remove extraneous space from figure shortcode

- langs/i18n/i18n.go
- langs/i18n/i18n_test.go
There were some issues introduced with the plural counting when we upgraded from v1 to v2 of go-i18n.
This commit improves that situation given the following rules:
* A single integer argument is used as plural count and passed to the i18n template as a int type with a `.Count` method. The latter is to preserve compability with v1.
* Else the plural count is either fetched from the `Count`/`count` field/method/map or from the value itself.
* Any data type is accepted, if it can be converted to an integer, that value is used.
The above means that you can now do pass a single integer and both of the below will work:
```
{{ . }} minutes to read
{{ .Count }} minutes to read
```
Fixes #8454
Closes #7822
See gohugoio/hugoDocs#1410
> langs/i18n: Revise the plural implementation

- common/types/types.go
- langs/i18n/i18n.go
- langs/i18n/i18n_test.go
The go-i18n library expects plural counts with floats to be represented as strings.
Fixes #8464
> langs/i18n: Improve plural handling of floats

- langs/i18n/i18n.go
- langs/i18n/i18n_test.go
> langs/i18n: Fix warning regression in i18n

- tpl/collections/collections.go
- tpl/collections/collections_test.go
- tpl/collections/init.go
Querify used 'Dictionary' to add key/value pairs to a map to
build URL queries. Changed to dynamically generate ordered
key/value pairs. Cannot take string slice as key (earlier
possible due to Dictionary).
Fixes #6735
> tpl: Modify 'Querify' to take lone slice argument

- common/maps/scratch.go
- common/maps/scratch_test.go
- docs/content/en/functions/scratch.md
**Description**
Add Scratch.DeleteInMap method. This method works similar to Scratch.SetInMap. It takes in two string parameters, `key` and `mapKey` and deletes the value mapped to `mapKey` in `key`
Closes #8504
> common/maps: Add Scratch.DeleteInMap

- hugolib/menu_test.go
- navigation/menu.go
- navigation/menu_cache.go
- navigation/menu_cache_test.go
.Site.Menus is mutated when it is sorted for now and this causes concurrency problem (#7594)
In this patch, each related sort function copies Menu before sorting to prevent
race condition.
Pages already have such a sort and cache logic and this patch is identical to it.
Closes #7594
> navigation: Cache and copy Menu for sotring

- hugolib/shortcode.go
- hugolib/shortcode_test.go
Currently, no name shortcodes (`{{< >}}`) enter unexpected branch and
throw `BUG: template info not set`. This patch checks if shortcode has
name or not earlier and throws specific error.
In addition,
- Add test case
- Modify `CheckShortCodeMatchAndError` a little to assert the error
Closes #6866
> shortcode: Catch incomplete shortcode error

- config/env.go
- hugolib/config_test.go
replace strings.Split with strings.SplitN in config.SplitEnvVar, to keep html.
Environment Variable with html could be cut by '=' in original config.SplitEnvVar.
thanks.
fix issure #8589
> fix(config):env string split

- hugofs/fileinfo.go
Special thanks to both Richard Mortimer (@oldelvet) and
Joshua M. Clulow (@jclulow) for their analysis and suggested fix:
* https://github.com/gohugoio/hugo/issues/6161#issuecomment-574336088
* https://github.com/gohugoio/hugo/issues/6161#issuecomment-596805273
Fixes #6161
---
I am satisfied with the behaviour I see after applying this patch.  The timestamp of `public` folder itself gets updated to "now" for each `hugo` run; the timestamps of the contents inside the public folder look good.  `hugo server` LiveReload still works as expected, whether rendered to memory or to disk.
> Fix invalid timestamp of the "public" folder

- hugolib/embedded_templates_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/pagination.html
These calls are equivalent:
```go-html-template
{{ template "_internal/pagination.html" . }}
{{ template "_internal/pagination.html" (dict "page" .) }}
{{ template "_internal/pagination.html" (dict "page" . "format" "default") }}
```
To use an alternate format:
```go-html-template
{{ template "_internal/pagination.html" (dict "page" . "format" "terse") }}
```
Fixes #8599
> Improve pagination performance

- resources/image.go
The error is logged as a WARNING and nil is returned.
see #8519
> exif: Log warning for metadata decode error

- commands/commands.go
- commands/hugo.go
- commands/server.go
This allows error parsers (VSCode problem matchers) to use the time notification as bounds for detecting errors
(I've never coded in Go before, so if there is a better way to do this, I'm all ears!)
(partially) closes #8403
> Move time notification to after rebuild errors

- hugolib/config.go
- hugolib/config_test.go
By waiting until we've loaded the config dir config before applying the default values.
Fixes #8763
> Fix default values when loading from config dir

- hugolib/embedded_shortcodes_test.go
- hugolib/page_test.go
- markup/goldmark/convert_test.go
- markup/highlight/highlight.go
- markup/highlight/highlight_test.go
Currently the generated `<pre>` element isn't fully accessible as it can't be focused by keyboard users.
An example of syntax highlighting and how the [aXe devTools extension](https://www.deque.com/axe/browser-extensions/) detects this issue:
Additional info:
- [Deque University: Ensure that scrollable region has keyboard access](https://dequeuniversity.com/rules/axe/4.2/scrollable-region-focusable):
> The key to getting a scrollable region to be accessible with the keyboard is to ensure that a keyboard-only user can focus the scrollable region itself or a static text item within the scrollable region.
- [Accessibility insights: scrollable-region-focusable](https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/)
> Thus, scrollable content is keyboard accessible …
> markup: Add tabindex="0" to default <pre> wrapper.

- config/defaultConfigProvider.go
- hugolib/config.go
Note that the deadlock has not been seen earlier, in tests on in real Hugo sites.
Fixes #8792
Fixes #8791
> Deprecate Blackfriday and fix a potential deadlock in config

- common/htime/time.go
- common/htime/time_test.go
- docs/content/en/functions/dateformat.md
- docs/content/en/functions/time.md
- docs/content/en/getting-started/configuration.md
- go.mod
- go.sum
- hugolib/dates_test.go
- hugolib/page__meta.go
- langs/language.go
- resources/page/pagemeta/page_frontmatter.go
- resources/page/pagemeta/page_frontmatter_test.go
- tpl/time/init.go
- tpl/time/init_test.go
- tpl/time/time.go
- tpl/time/time_test.go
> Localize time.Format + time zone support

- commands/commands_test.go
- common/herrors/file_error_test.go
- common/herrors/line_number_extractors.go
- go.mod
- go.sum
- hugolib/config_test.go
- hugolib/configdir_test.go
- langs/i18n/translationProvider.go
- parser/frontmatter.go
- parser/frontmatter_test.go
- parser/metadecoders/decoder.go
- tpl/transform/remarshal_test.go
A benchark building a site with 200 pages with TOML front matter:
```bash
name                                  old time/op    new time/op    delta
SiteNew/Regular_TOML_front_matter-16    48.5ms ± 1%    47.1ms ± 1%  -2.85%  (p=0.029 n=4+4)
name                                  old alloc/op   new alloc/op   delta
SiteNew/Regular_TOML_front_matter-16    16.9MB ± 0%    16.7MB ± 0%  -1.56%  (p=0.029 n=4+4)
name                                  old allocs/op  new allocs/op  delta
SiteNew/Regular_TOML_front_matter-16      302k ± 0%      296k ± 0%  -2.20%  (p=0.029 n=4+4)
```
Note that the front matter unmarshaling is only a small part of building a site, so the above is very good.
Fixes #8801
> Shift to go-toml v2

- common/htime/time.go
- common/htime/time_test.go
- go.mod
- go.sum
- hugolib/language_test.go
- langs/language.go
- tpl/lang/lang.go
- tpl/lang/lang_test.go
- tpl/time/time.go
- tpl/time/time_test.go
Test building with `go build -ldflags="-s -w"`
Hugo 0.86.2: 46MB
Before this commit: 77MB
After this commit: 54MB
Fixes #8839
Fixes #8841
> Reduce binary size vs locale, update to CLDR v36.1

- commands/server.go
> Avoid too many watch file handles causing the server to fail to start

- common/maps/params.go
- config/defaultConfigProvider.go
- config/defaultConfigProvider_test.go
- hugolib/config_test.go
Unless the merge strategy is set up to do so.
For `disableKinds` the current workaround is to make sure the project config has an entry, even if is empty:
```
disableKinds = []
```
Note that this issue only touches root, non-map config-values that either is not set in project config or in Hugo's defaults.
Fixes #8866
> Fix it so disableKinds etc. does not get merged in from theme

- markup/goldmark/convert.go
- markup/goldmark/convert_test.go
- markup/highlight/highlight.go
PR #8568 added `tabindex="0"` to most `<pre>` tags, but it's still missing when using code fences and goldmark-highlighting doesn't highlight that code block. This PR fixes it by making this scenario reuse the same code that was changed in the aforementioned PR.
> highlight: Add tabindex when code is not highlighted

- commands/commandeer.go
- commands/commands.go
- commands/config.go
- commands/convert.go
- commands/deploy.go
- commands/hugo.go
- commands/list.go
- commands/mod.go
- commands/new.go
- commands/new_theme.go
- commands/server.go
- hugolib/hugo_sites.go
> commands: Don't fail on template errors on go mod graph etc.

- go.sum
- resources/resource_transformers/js/options.go
- resources/resource_transformers/js/options_test.go
This is in line with how both Node and ESBuild's native import resolver does it.
The ambiguous situations above were discovered trying to build AlpineJS v3.
Note that the above was never an issue if you used `./foo.js` and similar to import the component.
Fixes #8945
> js: Fix import order for ./foo when both ./foo.js and ./foo/index.js exists

- resources/resource_test.go
The source from NewSource is documented not to be safe for
concurrency, and instead use the eefault source which is documented
as safe.
Fixes #8981
> resources: use default math/rand.Source for concurrency safety

- tpl/lang/lang.go
The documentation of the FormatAccounting and FormatCurrency
functions could be clearer in terms of how the precision param
works. This commit makes it more explicit that adding a precision
of < 2 will not format the return values to include fewer decimals.
Resolves #8858
> Clarify "precision" in currency format functions

- hugolib/resource_chain_test.go
- minifiers/minifiers.go
- minifiers/minifiers_test.go
- resources/resource_transformers/minifier/minify.go
Previously, *minifyTransformation.Transform suppressed the
error returned by t.m.Minify. This meant that when minification
returned an error, the error would not reach the user. Instead,
minification would silently fail. For example, if a JavaScript
file included a call to the Date constructor with:
new Date(2020, 04, 02)
The package that the minification library uses to parse JS files,
github.com/tdewolff/parse would return an error, since "04" would
be parsed as a legacy octal. However, the JS file would remain
un-minified with no error.
Fixing this is not as simple as replacing "_" with an "err" in
*minifyTransformation.Transform, however (though this is
necessary). If we only returned this error from Transform,
then hugolib.TestResourceMinifyDisabled would fail. Instead of
being a …
> Pass minification errors to the user

- README.md
The server for the tracking image for analytics is currently down,
therefore I found it convenient to remove the link in order to maintain our readme
> The tracking image and link removed form redme.md

- tpl/path/path.go
- tpl/path/path_test.go
Add path.clean function as mentioned in #8885.
I'd love to write a more full test suite, but I'm not 100% sure how to emulate windows filepaths effectively. Any tips are appreciated! :D
> Add a path.clean function for #8885

- resources/image_test.go
As documented in commit 30eea3915b67f72611a3b2f4547146d4c6a96864,
some filenames have changed due to cache busting of PNG and Webp images.
This resolves recent TestImageOperationsGolden failure on arm64, ppc64le
and s390x.
See #6387 and #8729
---
Error message (excerpted from https://buildd.debian.org/status/fetch.php?pkg=hugo&arch=arm64&ver=0.86.1-1&stamp=1635264173&raw=0):
```
=== CONT  TestImageOperationsGolden
...
image_test.go:744: resulting image differs from golden: gohugoio8_hu7f72c00afdf7634587afaa5eff2a25b2_73538_73c19c5f80881858a85aa23cd0ca400d.png
image_test.go:744: resulting image differs from golden: gohugoio8_hu7f72c00afdf7634587afaa5eff2a25b2_73538_ae631e5252bb5d7b92bc766ad1a89069.png
image_test.go:744: resulting image differs from golden: …
```
> resources: Rename excepted filenames for image golden testdata

- docs/data/docs.json
- tpl/lang/lang.go
It currently refers to itself as a simple alternative, when it should
refer to lang.FormatNumber.
> Fix description of lang.FormatNumberCustom

- hugofs/fileinfo.go
- hugofs/rootmapping_fs.go
- hugolib/filesystems/basefs.go
> Fix content dir resolution when main project is a Hugo Module

- helpers/general.go
This should be faster for all of our use cases (small string slices), but more important, it makes UniqueStringsReuse allocation free.
```bash
name                                 old time/op    new time/op    delta
UniqueStrings/Safe-16                   776ns ± 0%     305ns ± 0%   -60.68%  (p=0.029 n=4+4)
UniqueStrings/Reuse_slice-16            621ns ± 3%     174ns ± 0%   -72.01%  (p=0.029 n=4+4)
UniqueStrings/Reuse_slice_sorted-16     319ns ± 4%     313ns ± 0%    -2.01%  (p=0.029 n=4+4)
name                                 old alloc/op   new alloc/op   delta
UniqueStrings/Safe-16                    224B ± 0%      128B ± 0%   -42.86%  (p=0.029 n=4+4)
UniqueStrings/Reuse_slice-16            96.0B ± 0%      0.0B       -100.00%  (p=0.029 n=4+4)
UniqueStrings/Reuse_slice_sorted-16     24.0B …
```
> helpers: Make UniqueStringsReuse allocation free

- .gitignore
- cache/filecache/filecache.go
- cache/filecache/filecache_config.go
- cache/filecache/filecache_test.go
- resources/resource_factories/create/create.go
- tpl/data/resources_test.go
This is work in progress; I still get some context canceled errors from  httputil.DumpResponse when testing this, which I assume is:
https://github.com/golang/go/issues/49366﻿
> Add a remote retry for resources.Get

- docs/content/en/functions/transform.Unmarshal.md
- docs/content/en/templates/data-templates.md
- go.mod
- go.sum
- hugolib/resource_chain_test.go
- parser/frontmatter.go
- parser/metadecoders/decoder.go
- parser/metadecoders/decoder_test.go
- parser/metadecoders/format.go
- parser/metadecoders/format_test.go
- tpl/transform/remarshal_test.go
- tpl/transform/unmarshal_test.go
Implement XML data support
Sample usage:
```
{{ with resources.Get "https://www.w3schools.com/xml/note.xml" | transform.Unmarshal }}
{{ .note.body }}
{{ end }}
```
A common usage:
```
{{ with resources.Get "https://example.com/rss.xml" | transform.Unmarshal }}
{{ range .rss.channel.item }}
<strong>{{ .title | plainify | htmlUnescape }}</strong><br />
<p>{{ .description | plainify | htmlUnescape }}</p>
{{ $link := .link | plainify | htmlUnescape }}
<a href="{{ $link }}">{{ $link }}</a><br />
<hr>
{{ end }}
{{ end }}
```
Closes #4470
> Implement XML data support

- lazy/init.go
- lazy/init_test.go
To prevent sticky errors on server rebuilds.
Fixes #7043
Closes #9194
> lazy: Reset error in Reset

- .circleci/config.yml
- resources/resource_factories/create/create.go
> Update to Go 1.17.4 and remove timeout in resources.Get

- Dockerfile
mage uses git, so we should install git before run mage.
close #9261
> fix: default Dockerfile builds fails

- media/mediaType.go
- resources/images/config.go
- resources/resource_factories/create/create.go
> Improve handling of remote image/jpeg resources

- modules/config.go
`path.Join` cleans the final path. Especially with relative paths it could create a key which causes incorrectly ignored mounts.
I had these three mounts:
```yaml
- source: ../src/docs/arithmeticOperators/binary
target: content/bash/arithmetic/binary
lang: en
- source: ../src/docs/arithmeticOperators/binary
target: content/bash/arithmetic/binary
lang: zh-cn
- source: ../src/docs/arithmeticOperators/binary
target: content/bash/arithmetic/binary
lang: de
```
The last two mounts were ignored. This happened because the intermediate path value `zh-cn/../src/docs/arithmeticOperators/binary/content/bash/arithmetic/binary` was cleaned up to `src/docs/arithmeticOperators/binary/content/bash/arithmetic/binary`.
Due to the relative `..` the language was in fact ignored and the last two mounts were …
> Don't use path.Join to calculate the unique key for mounts

- hugolib/template_test.go
- tpl/partials/partials.go
- tpl/tplimpl/template_ast_transformers.go
Partials with returns values are parsed, then inserted into a
partial return wrapper via wrapInPartialReturnWrapper in order
to assign the return value via *contextWrapper.Set. The
predefined wrapper template for partials inserts a partial's nodes
into a "with" template action in order to set dot to a
*contextWrapper within the partial. However, because "with" is
skipped if its argument is falsy, partials with falsy arguments
were not being evaluated.
This replaces the "with" action in the partial wrapper with a
"range" action that isn't skipped if .Arg is falsy.
Fixes #7528
> Allow for return partials with falsy arguments

- config/security/securityConfig.go
- config/security/securityonfig_test.go
- docs/data/docs.json
There have been one report in the wild suggesting that this needs to be tested better before doing:
https://discourse.gohugo.io/t/hugo-mod-failing-in-v0-91-1-but-works-in-v0-91-0/36180/5
This reverts commit fca266ebbb81af3d4479873a7a79759033c7ce25.
> Revert "config/security: Add HOME to default exec env var whitelist"

- hugolib/site_output_test.go
- resources/page/page_outputformat.go
In page.NewOutputFormat, we take an output.Format f and use it to
create a page.OutputFormat. If the format is canonical, we assign
the final OutputFormat's Rel to "canonical" rather than using
f.Rel. However, this leads to unexpected behavior for custom
output formats, where a user can define a "rel" for a format
via the config file.
For example, the standard for "humans.txt" files requires using
rel="author" in HTML "link" elements. Meanwhile, humans.txt is
usually the only format used for its content. As a result, for
Hugo configurations that define a humans.txt custom output format,
Hugo will render "link" elements to content in this format with
rel="canonical," rather than "author" as required by the standard.
This commit changes page.NewOutputFormat to check whether a given
format …
> Fix surprise OutputFormat.Rel overwriting

- commands/commands.go
- commands/helpers.go
- common/loggers/loggers.go
- helpers/general.go
> Add --panicOnWarning flag

- hugolib/page.go
- hugolib/page_test.go
- resources/page/page_lazy_contentprovider.go
When a template calls the .Translations function and a
Hugo environment is using multiple output formats,
a template that calls methods like .Summary and .Len on
each translation will unexpectedly show empty return
values for these methods.
This is because each pageOutput's ContentProvider is
assigned to a page.NopPage in newPageOutput. When
*HugoSites.render assigns pageContentOutputs to
pageOutputs in *pageState.shiftToOutputFormat, it
reuses pageContentOutputs from other pageOutputs,
leaving some pageContentOutputs as NopPages. While this
approach conserves resources, sometimes it means that
a template will unexpectedly call a method on a
pageContentOutput that is actually a NopPage.
In the case of ContentProvider methods called on
translations for alternative output formats, the …
> Fix missing page data for alternative formats

- helpers/general.go
- helpers/general_test.go
The function printIfNotPrinted() defined for DistinctLogger unlocked the mutex within
the logger only after the print() function ran. If print panics, the mutex would stay
locked and future attempts to read or write from the logger mutex would cause the goroutine
to hang indefinitely.
Deferred the unlocking of the mutex to prevent this. Also, put l.m[key] before the print()
call since this will prevent another bug where the same warning potentially gets logged
multiple times if the print() call panics.
Fixes #9380
> general: Fix issue causing log threads to hang indefinitely

- hugolib/page.go
- hugolib/page__common.go
- hugolib/page__new.go
- hugolib/page__output.go
- hugolib/page__per_output.go
- hugolib/page_test.go
- resources/page/page_lazy_contentprovider.go
PR #9342 introduced a regression in which calling .Translations in a
template and calling RenderString on a translated Page caused a nil
pointer dereference. The issue was that some Pages returned from
.Translations had a nil cp field at the time the calling template was
being executed.
While PR #9342 had attempted to ensure that all ContentProviders were
initialized for translations at build time, it only performed the
initialization for receivers of ContentProvider methods such as
.Summary. However, the ContentProvider's *pageState.pageOutput.cp would
remain uninitialized, causing the nil pointer dereference.
This change edits the .Translations and .AllTranslations methods to
ensure that all of a page's translations have an initialized
content provider in time for a template to be …
> Ensure page translation CPs are initialized

- hugolib/content_render_hooks_test.go
- hugolib/page__meta.go
> Fix erroneous warning with .Page.RenderString on a page without a backing file

- go.mod
- go.sum
> deps: Update github.com/pelletier/go-toml/v2 to v2.0.0-beta.6

- tpl/compare/compare.go
- tpl/compare/compare_test.go
> Validate comparison operator argument count

- hugolib/page__common.go
- hugolib/page__new.go
- resources/page/page.go
- resources/page/page_generate/generate_page_wrappers.go
- resources/page/page_marshaljson.autogen.go
- resources/page/page_wrappers.autogen.go
They have been deprecated for a very long time, first with a warning, then with an ERROR. Now they are removed.
Closes #4117
> Finally remove deprecated Page methods

- go.mod
- go.sum
- hugolib/resource_chain_test.go
Fixes #9244
Fixes #9132
Fixes https://discourse.gohugo.io/t/36523
> deps: Update github.com/tdewolff/minify/v2 v2.9.22 => v2.9.29

- markup/goldmark/integration_test.go
- markup/goldmark/render_hooks.go
> Exclude event attributes from markdown render hook

- htesting/hqt/checkers.go
- tpl/math/math.go
- tpl/partials/init.go
- tpl/partials/init_test.go
- tpl/partials/integration_test.go
- tpl/partials/partials.go
This commit revises the locking strategy for `partialCached`. We have added a benchmark that may be a little artificial, but it should at least show that we're not losing any performance over this:
```bash
name              old time/op    new time/op    delta
IncludeCached-10    12.2ms ± 2%    11.3ms ± 1%   -7.36%  (p=0.029 n=4+4)
name              old alloc/op   new alloc/op   delta
IncludeCached-10    7.17MB ± 0%    5.09MB ± 0%  -29.00%  (p=0.029 n=4+4)
name              old allocs/op  new allocs/op  delta
IncludeCached-10      128k ± 1%       70k ± 0%  -45.42%  (p=0.029 n=4+4)
```
This commit also revises the template metrics hints logic a little, and add a test for it, which output is currently this:
```bash
cumulative       average       maximum      cache  percent  cached  total …
```
> tpl/partials: Make sure a cached partial is invoked only once

- docs/content/en/hugo-modules/configuration.md
- modules/client.go
- modules/config.go
Sets `GOWORK` env var for Go 1.18.
> modules: Add modules.Workspace config for Go 1.18

- commands/commandeer.go
- commands/commands_test.go
- commands/server_test.go
- hugolib/hugo_sites.go
And now with a proper server test.
Fixes #9518
Fixes #9530
Fixes #9539
> commands: Fix server panic regression

- docs/content/en/content-management/image-processing/index.md
- docs/layouts/shortcodes/imgproc.html
- resources/errorResource.go
- resources/image.go
- resources/image_test.go
- resources/images/config.go
- resources/images/image.go
- resources/resource/resourcetypes.go
- resources/transform.go
Introduces the Crop method for image processing which implements gift.CropToSize. Also allows a smartCrop without resizing, and updates the documentation.
Fixes #9499
> Allow images to be cropped without being resized

- tpl/tplimpl/embedded/templates/disqus.html
The variable `disqus_config` doesn't work if we use `hugo --minify` because Hugo changes the name.
We can use `window.disqus_config` instead, and it won't be renamed.
Reference: https://developer.mozilla.org/en-US/docs/Glossary/Global_object
> Change `disqus_config` to `window.disqus_config`

- helpers/path.go
- helpers/path_test.go
Improve handling of existing hyphens in input to UnicodeSanitize.
This commit accomplishes three things:
1. Explicitly allow hyphens
2. Avoid appending a hyphen if a preceeding hyphen is found
3. Avoid prepending a hyphen if a trailing hyphen is found
Fixes #7288
> helpers: Allow hyphens in UnicodeSanitize

- markup/goldmark/convert_test.go
Fixes https://github.com/gohugoio/hugo/issues/9385.
> Add test for line anchor attributes with code fences

- hugolib/site.go
The string `unable to process menus in site config` made me think that menus aren't allowed to be in `config.toml` at all, period, but actually I was just missing the `[menu]` header (that is, I tried to put `[[menus.main]]` without `[menu]`). The language `menus in site config contain errors` seems more neutral, and won't lead users to believe they're **required** to make a separate menus file like I thought.
It might be better to have specific handling that detects the lack of `[menu]` and calls that out specifically, but at least this is a small change that will hopefully help people avoid the trouble that I had.
> Update error message about failed menus in config.toml

- markup/goldmark/convert_test.go
- markup/highlight/config.go
- markup/highlight/highlight.go
The `Ordinal` starts at 0, so with a `hl-` prefix, this gives `hl-0-1` as a starting point.
Fixes #9567
> markup/goldmark: Use Ordinal to create default lineanchors

- common/hreflect/helpers.go
- tpl/collections/apply.go
- tpl/collections/apply_test.go
- tpl/collections/integration_test.go
As introduced in `partial` and `partialCached` in Hugo 0.93.0.
Fixes #9585
> tpl/collections: Fix apply when function have Context as first arg

- tpl/partials/integration_test.go
- tpl/partials/partials.go
This is a rollback of  0927cf739fee9646c7fb917965799d9acf080922
We cannot do that change until we either completes #9570 or possibly also use the new TryLock in GO 1.18.
Fixes #9588
Opens #4086
> tpl/partials: Fix partialCached deadlock regression

- markup/goldmark/integration_test.go
- markup/goldmark/render_hooks.go
> markup/goldmark: Escape image alt attribute

- hugolib/filesystems/basefs.go
There have been a site breakage reported in the wild after 0.93.1. With this commit we shoudl be back to how it behaved in 0.92.2.
Closes #9609
> Remove the decorator from the fs used in ReadDir

- commands/commandeer.go
- commands/hugo.go
- commands/server.go
- commands/static_syncer.go
- hugofs/fs.go
- hugolib/filesystems/basefs.go
- hugolib/pages_process.go
- hugolib/site.go
> Allow rendering static files to disk and dynamic to memory in server mode

- hugolib/page.go
- markup/goldmark/codeblocks/integration_test.go
For the Position in code blocks we try to match the .Inner with the original source. This isn't always possible.
This commits avoids panics in these situations.
Fixes #9627
> markup/goldmark/codeblocks: Fix slice bounds out of range

- markup/highlight/config.go
- markup/highlight/highlight.go
- markup/highlight/integration_test.go
- markup/internal/attributes/attributes.go
If set to true, the highlighted code will not be wrapped in any div.
Closes #9442
> markup/highlight: Add hl_inline option

- markup/goldmark/convert.go
- markup/goldmark/goldmark_config/config.go
- markup/goldmark/integration_test.go
- markup/goldmark/render_hooks.go
> markup/goldmark: Default to https for linkify

- modules/client.go
I believe I have implemented the required fix #9127. 
I changed the aforementioned if-statement to check whether the supplied argument contains `-u`, as opposed to whether the supplied argument is identical to `-u`.  A flag called `patch`, similar to the `update` flag, was added. The `patch` flag will be true if the supplied argument is exactly  `-u=patch`. The appropriate command is then passed down.
I am unsure of how to add tests for this fix, so any pointers on how to get started writing tests would be highly appreciated @bep .
> Fixes #9127: Support '-u=patch' in hugo mod get

- .github/workflows/test.yml
- CONTRIBUTING.md
- Dockerfile
- snap/snapcraft.yaml
* snap: Make it build with Go 1.18
Tested to work with hugo's `stable` branch; see the recent builds for ["hugo"](https://launchpad.net/~gohugoio/+snap/hugo) and ["hugo-extended"](https://launchpad.net/~gohugoio/+snap/hugo-extended) on Ubuntu/Canonical's Launchpad
* Dockerfile: Make it build with Go 1.18
* Update CONTRIBUTING.md to use `go install` to install mage.
In Go 1.18, `go get` no longer builds packages.
> Make Snap and Docker build with Go 1.18

- hugolib/page.go
- hugolib/resource_chain_test.go
- resources/errorResource.go
- resources/page/page_nop.go
- resources/page/testhelpers_test.go
- resources/resource.go
- resources/resource/resourcetypes.go
- resources/resource_factories/create/remote.go
- resources/transform.go
- tpl/resources/resources.go
This commit adds a .Data object (a map with `Body`, `StatusCode` etc.) to the .Err returned from `resources.GetRemote`, which means you can now do:
```
{{ with .Err }}
{{ range $k, $v := .Data }}
{{ end }}
{{ end }}
```
Fixes #9708
> resources: Add more details to .Err

- deploy/deploy.go
Improves https://github.com/gohugoio/hugo/issues/9735
During Hugo deploy when a remote MD5 is invalid (e.g due to multipart etag) hugo reads the entire remote file and calculates the md5 again which can be slow.
- Updates file upload so that it will also store an md5 hash in the cloud providers attributes. e.g in aws this looks like `x-amz-meta-md5chksum: 26fe392386a8123bf8956a16e08cb841`
- Updates the walkremote so that if an MD5 is nonexistent/invalid then it attempts to read the attribute md5 before falling back to reading the entire remote file
Hugo deploy will be faster in the diffing stage between remote and local. 
**_IF_** files come through with `len(obj.MD5) == 0` but store an attribute md5.
Only files uploaded with hugo will have this attribute. 
**Existing users**
Existing …
> hugo deploy also sets an md5 attribute & checks it

- hugolib/site.go
- hugolib/taxonomy.go
- langs/language.go
- langs/language_test.go
- resources/page/integration_test.go
- resources/page/pagegroup.go
- resources/page/pages_sort.go
- tpl/collections/collections_test.go
- tpl/collections/sort.go
- tpl/collections/sort_test.go
- tpl/compare/compare.go
> Make string sorting (e.g. ByTitle, ByLinkTitle and ByParam) language aware 

- common/maps/maps.go
- common/maps/maps_test.go
- docs/content/en/hugo-pipes/introduction.md
- resources/resource_factories/create/remote.go
- resources/resource_factories/create/remote_test.go
If set, `key` will be used as the only cache key element for the resource.
The default behaviour is to calculate the key based on the URL and all the options.
This means that you can now do:
```
{{ $cacheKey := print $url (now.Format "2006-01-02") }}
{{ $resource := resource.GetRemote $url (dict "key" $cacheKey) }}
```
Fixes #9755
> resources: Add `key` to reources.GetRemote options map

- commands/import_jekyll.go
Just use `afero.OsFs` without building site.
Close #9817
> import: Fix importing jekyll site

- commands/commands.go
- commands/hugo.go
- hugolib/filesystems/basefs.go
If the flag is enabled, `.hugo_build.lock` will not be created.
This ensures safe running on read-only filesystem etc.
Close #9780
> basefs: add `noBuildLock` flag

- metrics/metrics.go
- metrics/metrics_test.go
Under certain conditions, `howSimilarString` could reach a divide-by-
zero situation which causes bogus values to print in the cache potential
column of the template hints output.  This situation essentially causes
a `int(math.NaN())` value to be returned and hilarity ensues thereafter.
> metrics: Fix divide by zero error

- .github/workflows/test.yml
- magefile.go
- modules/config_test.go
- resources/resource_transformers/tocss/scss/integration_test.go
Also fix TestDecodeConfig/Basic which started to fail in the extended build in 0.99.1.
Closes #9935
> github: Set HUGO_BUILD_TAGS: extended when running tests

- resources/resource_transformers/postcss/postcss.go
- resources/resource_transformers/postcss/postcss_test.go
- tpl/resources/resources.go
By using the input map as the basis, which means the hash will not change if we add/rename/remove options.
This happened in Hugo 0.99, as we added a new options. This is unortunate.
Unfortunately this means that the cache keys for PostCSS will change one more time in 0.100, but will be stable going forward.
Note that we have implemented this pattern in all the other resource transformers.
Updates #9787
> postcss: Make the resource cache key more stable

- hugolib/content_map_test.go
- hugolib/menu_test.go
- hugolib/page__tree.go
Fix HasMenuCurrent and IsDescendant/IsAncestor when comparing to itself
There may be sites in the wild that depends on the faulty behaviour of IsDescendant/IsAncestor when comparing to itself, but
* The documentation and common sense says that a thing cannot be descendant or ancestor to itself.
* The bug introduced in `HasMenuCurrent` comes directly from that confusion.
Fixes #9846
> Fix HasMenuCurrent and IsDescendant/IsAncestor when comparing to itself

- docs/content/en/variables/shortcodes.md
- hugolib/shortcode.go
- hugolib/shortcode_test.go
- tpl/tplimpl/embedded/templates/shortcodes/highlight.html
- tpl/tplimpl/template_ast_transformers.go
> Fix indentation in highlight shortcode

- commands/hugo.go
- commands/server.go
This fixes an issue with the `resources.GetRemote` call that fails for some media types, even when these are included in the default Hugo configuring. This is because the media types only get registered when running Hugo as a server and after the build is completed.
Fixes: #9971
> resources: Register MediaTypes before build

- livereload/livereload.go
Codespace has 2 types of usage
1. in browser
2. vscode on local computer
As long as you select 2 (on local), Hugo handles livereload expectedly.
But if you use it in browser, Hugo does not reload on file change, as #9936 said.
This issue happens because `CheckOrigin` always fails.
Remote server could rewrite request host name.
Fix this by respecting `X-Forwarded-Host` header during origin checking
After merging this, you can preview changes lively with codespaece in browser.
```sh
hugo server --liveReloadPort 443
```
Close #9936
> livereload: Use `X-Forwarded-Host` for Codespace livereload

- deploy/deployConfig.go
- go.mod
- go.sum
For some reasons, dependabot did not pick up on this, probably because of the following test errors:
```
--- FAIL: TestEmptyTarget (0.00s)
deployConfig_test.go:184: 
error:
got nil value but want non-nil
got:
nil
stack:
/mnt/easystore/git/hugo/deploy/deployConfig_test.go:184
c.Assert(err, qt.Not(qt.IsNil))
--- FAIL: TestEmptyMatcher (0.00s)
deployConfig_test.go:198: 
error:
got nil value but want non-nil
got:
nil
stack:
/mnt/easystore/git/hugo/deploy/deployConfig_test.go:198
c.Assert(err, qt.Not(qt.IsNil))
```
due to
* pelletier/go-toml#755 (v2.0.0-beta.8 and newer)
I ended up modifying deploy/deployConfig.go (with help from <https://stackoverflow.com/questions/28447297/how-to-check-for-an-empty-struct>) to get the "empty deployment target/matcher" tests work with …
> deps: Update to github.com/pelletier/go-toml/v2 v2.0.1

- common/hreflect/helpers.go
- common/htime/time.go
- hugolib/dates_test.go
- tpl/collections/append_test.go
- tpl/collections/apply_test.go
- tpl/collections/collections.go
- tpl/collections/collections_test.go
- tpl/collections/complement_test.go
- tpl/collections/index_test.go
- tpl/collections/merge_test.go
- tpl/collections/reflect_helpers.go
- tpl/collections/sort.go
- tpl/collections/symdiff_test.go
- tpl/collections/where.go
- tpl/collections/where_test.go
- tpl/compare/compare.go
- tpl/compare/compare_test.go
- tpl/compare/init.go
Note that this has only been a problem with "raw dates" in TOML files in /data and similar. The predefined front matter
dates `.Date` etc. are converted to a Go Time and has worked fine even after upgrading to v2 of the go-toml lib.
Fixes #9979
> Fix raw TOML dates in where/eq

- resources/resource_transformers/js/options.go
- resources/resource_transformers/js/options_test.go
Same logic as for `index.{js,ts...}` files applies; if both `index.esm.js` and `index.js` exists (unlikely), you need to use the name
with extension when importing, else the `index.js` will win.
Fixes #8631
> js: Resolve index.esm.js

- helpers/pathspec_test.go
- helpers/url.go
- helpers/url_test.go
- hugolib/paths/paths.go
> Fix relURL with leading slash when baseURL includes a subdirectory

- docs/content/en/content-management/urls.md
- resources/page/permalinks.go
- resources/page/permalinks_test.go
Fixes #4739, #385
It adds a new `:slugelsefile` attribute that behaves the same way as `:slug`
with the only difference being that it fallbacks to filename instead of title.
Both issues are closed because they got marked as stale… but I don't see any
point in opening an another issue.
> resources/page: Add :slugorfilename attribute

- common/hugo/hugo.go
- common/hugo/version.go
> Accept vendor-specified build date if .git/ is unavailable

- markup/goldmark/codeblocks/integration_test.go
- markup/goldmark/codeblocks/render.go
> markup/goldmark/codeblock: get attribute in no language identifier in CodeBlock

- transform/livereloadinject/livereloadinject.go
- transform/livereloadinject/livereloadinject_test.go
Currently, Hugo does not inject `livereload` script if html does not contain `<head>` or `<body>`.
This sometimes happens if you create new sites without `theme` and it is hard to catch the cause soon.
This PR:
* Inject livereload script even if html does not include `<head>`, `<body>`, or `<html>`
- Modern browsers execute scripts even if they are outside `<html>`
- Some js frameworks (confirmed with vite) inject HRM script without `<html>` tag
* Append warning script to html if `<head>` or `<body>` is not in html
* Fix bug that livereload cannot be appended to the tags with attrs
Close #10105
> livereload: Inject script without head or body tag

- README.md
There was a few references to Go, without the link - so I've added those.
I've set the links to [https://go.dev/](https://go.dev/), but left the link in the tools section to the Go download page.
> Updated links to Golang in README

- snap/snapcraft.yaml
Git:
- Set GIT_EXEC_PATH and include usr/lib/git-core so that git can find the git-remote-https helper (needed by e.g. `go mod download`).
Go:
- Put Go in its own snap part, and use stage-snaps instead of build-snaps so that it is included in the final snap.
- Set GOCACHE to a writable directory. (In a previous commit, HOME is set to $SNAP_REAL_HOME which is unwritable.)
Hugo:
- Patch config/security/securityConfig.go `[security.exec] osEnv` whitelist (during snap build) so that external dependencies can use the required environment variables to run properly from within the snap.
Asciidoctor:
- Replace shebang line in `asciidoctor` so it can find the `ruby` executable.
- Set RUBYLIB so that Ruby can find its libraries.
Caveat/TODO: The Ruby version is hardcoded in our custom RUBYLIB. …
> snap: Make external dependencies actually work

- releaser/releaser.go
- snap/snapcraft.yaml
This, together with `snapcraftctl set-version`, negates the need to modify snap/snapcraft.yaml upon each release,
so the corresponding code is removed from releaser/releaser.go.
Also, `vendorInfo` is extended to include the snap version number.
See #10225
> snap: Use "snapcraftctl set-grade"

- hugolib/page.go
- hugolib/shortcode.go
- hugolib/shortcode_test.go
- parser/pageparser/pagelexer.go
- parser/pageparser/pageparser_shortcode_test.go
This issue was introduced in `v0.102.0`.
In 223bf2800488ad5d38854bbb595d789bc35ebe32 we removed the byte source from the parsed page result, which
meant we had to preserve exact positioning for all elements. This introduced some new `TypeIgnore` tokens
which we, wrongly, assumed didn't matter where we put in the result slice (they should be ignored anyway).
But it seems that this broke the logic where we determine if it's positional or named params in the case
where the paramater value contains escaped quoutes.
This commit makes sure that these ignore tokens (the back slashes) are never sent back to the client, which is how it was before `v0.102.0`.
This commit also fixes some lost error information in that same commit.
Fixes #10236
> Fix shortcode parser regression with quoted param values

- .github/workflows/stale.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- resources/resource_transformers/tocss/scss/tocss.go
Simple sites may only have one css file. Update the replace directive to
correctly match single-file sourcemaps and multi-file sourcemaps.
Verified locally with and without SASS and CSS imports.
Fixes #8174
> scss: Handle single-file sourcemaps correctly

- hugofs/glob.go
- hugofs/glob/filename_filter.go
- hugofs/glob/filename_filter_test.go
- hugofs/glob/glob.go
- hugofs/glob/glob_test.go
- hugofs/glob_test.go
- resources/resource_factories/create/create.go
Looking at the code as a whole, we ended up with a little to much "buttons". It turns out that doing case insensitive matching (lower both pattern and strings to match) performs just fine. Or at least, it
gives the penalty to the people who uses mixed case filenames.
```
GetGlob/Default_cache-10                          10.6ns ± 2%    10.6ns ± 1%   ~     (p=0.657 n=4+4)
GetGlob/Filenames_cache,_lowercase_searchs-10     10.6ns ± 2%    10.6ns ± 0%   ~     (p=1.000 n=4+4)
GetGlob/Filenames_cache,_mixed_case_searchs-10    29.7ns ± 1%    29.6ns ± 1%   ~     (p=0.886 n=4+4)
GetGlob/GetGlob-10                                13.7ns ± 1%    13.7ns ± 0%   ~     (p=0.429 n=4+4)
name                                            old alloc/op   new alloc/op   delta
GetGlob/Default_cache-10 …
```
> Consolidate the glob case logic

- commands/hugo.go
- deps/deps.go
- hugofs/fs.go
- hugofs/hasbytes_fs.go
- hugolib/filesystems/basefs.go
- hugolib/pages_process.go
In `v0.103.0` we added support for `resources.PostProcess` for all file types, not just HTML. We had benchmarks that said we were fine in that department, but those did not consider the static file syncing.
This fixes that by:
* Making sure that the /static syncer always gets its own file system without any checks for the post process token.
* For dynamic files (e.g. rendered HTML files) we add an additional check to make sure that we skip binary files (e.g. images)
Fixes #10328
> Fix /static performance regression from Hugo 0.103.0

- parser/frontmatter.go
> commands: Remove extraneous newline from result of convert toTOML

- commands/server_test.go
Set `getNumHomes: 1` to enable the 567 ms or 2 seconds of wait for the server to be ready in `TestServerPathEncodingIssues/Unicode_paths` and `TestServerPathEncodingIssues/Windows_multilingual_404`.
Fixes #10332
---
Hi @bep, I hope this is the right fix.  Besides waiting for the GitHub Actions CI test result, I'll be uploading 0.104.2-2 to Debian shortly and will report back if these tests pass the very first time on all architectures.
> server: Fix flaky TestServerPathEncodingIssues tests

- .github/workflows/test.yml
I changed the workflow to cache dependencies using [actions/setup-go](https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs). `actions/setup-go@v3` or newer has caching **built-in**.
```yml
- name: Install Go
uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
with:
go-version: ${{ matrix.go-version }}
```
```yml
- name: Install Go
uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
with:
go-version: ${{ matrix.go-version }}
cache: true
```
> It’s literally a one line change to pass the `cache: true` input parameter.
- [https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
- …
> Use setup-go action to cache dependencies

- .github/workflows/test.yml
Fixed #10359
```yml
- name: Install Go
uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
with:
go-version: ${{ matrix.go-version }}
cache: true
- name: Checkout code
uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
```
```yml
- name: Checkout code
uses: actions/checkout@v3
- name: Install Go
uses: actions/setup-go@v3
with:
go-version: ${{ matrix.go-version }}
cache: true
cache-dependency-path: |
**/go.sum
**/go.mod
```
> hotfix: Resolve dependency-path not found error in workflow

- common/hugo/hugo.go
- docs/content/en/functions/hugo.md
- transform/metainject/hugogenerator.go
- transform/metainject/hugogenerator_test.go
Remove self-closing tags to conform to W3C recommendations: Self-closing tag syntax in text/html documents is widely discouraged
<https://html.spec.whatwg.org/multipage/semantics.html#meta-generator>
> HTML5 standard: don't use self closing tags

- hugolib/page.go
- hugolib/page__output.go
- hugolib/page__per_output.go
- hugolib/shortcode.go
- hugolib/shortcode_test.go
- resources/page/page.go
- resources/page/page_lazy_contentprovider.go
- resources/page/page_nop.go
This PR is an attempt to fix #10391, while the changes pass the test my biggest concern is if this is the correct approach? I'm not really sure why a cp would be nil at this point.
> nil fix for 10391

- README.md
Changed installation method to reflect Go 1.16+, as cloning the repo and doing a go install achieves the same process.
Also changed "Advanced Installation" to "Using the Go toolchain"
> Added Go 1.16+ install method to README

- parser/pageparser/item.go
- parser/pageparser/item_test.go
> hugo/parser: Fix shortcode boolean param parsing

- hugolib/page__per_output.go
- markup/goldmark/codeblocks/render.go
- markup/highlight/chromalexers/chromalexers.go
- markup/highlight/highlight.go
- tpl/transform/transform.go
```
name                            old time/op    new time/op    delta
Codeblocks/Default-10              152ms ±11%      12ms ± 1%  -92.44%  (p=0.029 n=4+4)
Codeblocks/Hook_no_higlight-10     142ms ± 0%       7ms ± 0%  -95.36%  (p=0.029 n=4+4)
name                            old alloc/op   new alloc/op   delta
Codeblocks/Default-10             11.9MB ± 0%    11.7MB ± 0%   -1.59%  (p=0.029 n=4+4)
Codeblocks/Hook_no_higlight-10    4.62MB ± 1%    4.43MB ± 0%   -4.08%  (p=0.029 n=4+4)
name                            old allocs/op  new allocs/op  delta
Codeblocks/Default-10               209k ± 0%      209k ± 0%   -0.03%  (p=0.029 n=4+4)
Codeblocks/Hook_no_higlight-10     68.4k ± 0%     68.3k ± 0%   -0.06%  (p=0.029 n=4+4)
```
> Add a cache for lexers.Get

- tpl/collections/init.go
- tpl/debug/init.go
- tpl/math/init.go
- tpl/path/init.go
- tpl/strings/init.go
- tpl/transform/init.go
Consistently use `{{ this }}` instead of `{{this}}` in AddMethodMapping examples.
Most examples were already using this syntax. This just makes the it consistent.
> tpl: Use consistent delimiter spacing in examples

- config/security/securityConfig.go
- config/security/securityConfig_test.go
exemption `CI` enviroment variable
can to implement such a function:
```
{{- if getenv "CI" -}}
{{ /* e.g: save remote image to local */ }}
{{- end -}}
```
see https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
see https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
see https://circleci.com/docs/variables/#built-in-environment-variables
see https://docs.gitlab.com/ee/ci/variables/#debug-logging
see https://www.appveyor.com/docs/environment-variables/
etc CI/CD service providers
> feat: exemption `CI` enviroment variable

- resources/resource_factories/create/create.go
Increase timeout for http.Client in resources.GetRemote  from 10 second to 1 minute
Issue #10478
> resources: Increase timeout for http.Client

- tpl/tplimpl/integration_test.go
- tpl/tplimpl/template.go
Allow alternate comment syntax before block definitions:
```text
{{/* foo */}}
{{- /* foo */}}
{{- /* foo */ -}}
```
Fixes #10495
> tpl/tplimpl: Allow alternate comment syntax

- markup/converter/hooks/hooks.go
- markup/goldmark/convert.go
- markup/goldmark/goldmark_config/config.go
- markup/goldmark/images/integration_test.go
- markup/goldmark/images/transform.go
- markup/goldmark/links/integration_test.go
- markup/goldmark/links/transform.go
- markup/goldmark/render_hooks.go
- markup/internal/attributes/attributes.go
This both:
* Removes any surrounding paragraph nodes
* And transfers any attributes from the surrounding paragraph down to the image node
Closes #8362
Fixes #10492
> markup/goldmark: Add wrapStandAloneImageWithinParagraph option

- tpl/tplimpl/embedded/templates/opengraph.html
Hi, the site builds fails with default taxonomies, the internal Open Graph template requires `series` taxonomy, but I didn't find documentations about the `og:see_also` tag.
It would be great that print a more specified ERROR message if the `series` is required, for users who forgot to config.
```
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template:
_internal/opengraph.html:37:17: executing "_internal/opengraph.html" at <index $siteSeries ($name | urlize)>: error calling index: index of untyped nil
```
> Change Open Graph's series as optional

- commands/hugo.go
- docs/content/en/hugo-modules/configuration.md
- hugolib/config.go
- hugolib/hugo_sites_build_test.go
- hugolib/page_permalink_test.go
- modules/collect.go
- modules/config.go
- modules/config_test.go
- modules/module.go
- modules: Make the module.workspace=off as default (note)
- Add any configured Go Workspace file to the config watcher
> Misc Go Workspace fixes

- resources/resource_transformers/tocss/dartsass/client.go
- resources/resource_transformers/tocss/dartsass/integration_test.go
- resources/resource_transformers/tocss/dartsass/transform.go
- resources/resource_transformers/tocss/internal/sass/helpers.go
- resources/resource_transformers/tocss/scss/client.go
- resources/resource_transformers/tocss/scss/integration_test.go
- resources/resource_transformers/tocss/scss/tocss.go
This commit adds a new `vars` option to both the Sass transpilers (Dart Sass and Libsass).
This means that you can pass a map with key/value pairs to the transpiler:
```handlebars
{{ $vars := dict "$color1" "blue" "$color2" "green" "$font_size" "24px" }}
{{ $cssOpts := (dict "transpiler" "dartsass" "outputStyle" "compressed" "vars" $vars ) }}
{{ $r := resources.Get "scss/main.scss" |  toCSS $cssOpts }}
```
And the the variables will be available in the `hugo:vars` namespace. Example usage for Dart Sass:
```scss
@use "hugo:vars" as v;
p {
color: v.$color1;
font-size: v.$font_size;
}
```
Note that Libsass does not support the `use` keyword, so you need to `import` them as global variables:
```scss
@import "hugo:vars";
p {
color: $color1;
font-size: $font_size;
}
```
Hugo will:
* Add a …
> tocss: Add vars option

- commands/commandeer.go
- common/hugo/hugo.go
- docs/content/en/hugo-pipes/postprocess.md
- hugolib/config.go
- resources/resource_transformers/postcss/integration_test.go
So you can do  `process.env.HUGO_PUBLISHDIR` in your `postcss.config.js` to figure out where Hugo publishes
its files.
Note that the value will always be an absolute file path and will point to a directory on disk even when running `hugo server` in memory mode.
If you write to this folder from PostCSS when running the server, you could run the server with one of these flags:
```
hugo server --renderToDisk
hugo server --renderStaticToDisk
```
Fixes #10554
> Add HUGO_PUBLISHDIR to the Node environment

- docs/content/en/content-management/sections.md
- docs/content/en/variables/page.md
- hugolib/page__tree.go
- hugolib/site_sections_test.go
- resources/page/page.go
- resources/page/page_nop.go
- resources/page/testhelpers_test.go
Add parents property on page, simplify breadcrumb navigation implementation complexity
community tricks see: https://discourse.gohugo.io/search?q=breadcrumb
---
in HTML:
```html
{{- $page := . -}
<nav class="breadcrumb">
<ul>
{{- range .Parents.Reverse }}
<li><a href="{{ .Permalink }}">{{ .LinkTitle }}</a></li>
{{- end }}
<li class="active">{{ .LinkTitle }}</li>
</ul>
</nav>
```
---
in JSON-LD:
see https://developers.google.com/search/docs/appearance/structured-data/breadcrumb
```html
{{- $breadcrumbItems := slice -}}
{{- range $index, $page := append .Parents.Reverse . -}}
{{-
$item := dict
"@type" "ListItem"
"position" (add $index 1)
"name" $page.Title
"item" $page.Permalink
-}}
{{- $breadcrumbItems = append $breadcrumbItems $item -}}
{{- end -}}
<script type="application/ld+json">
{{- …
```
> feat: add parents property on page

- go.mod
- go.sum
- resources/resource_transformers/js/integration_test.go
Also add a test to make sure legal comments are preserved in JS bundles.
Closes #10536
> deps: Upgrade github.com/evanw/esbuild v0.15.18 => v0.17.0

- commands/commands.go
- commands/new_site.go
- config/configLoader.go
- hugolib/config.go
- hugolib/config_test.go
- hugolib/integrationtest_builder.go
- modules/collect.go
Both will of course work, but hugo.toml will win if both are set.
We should have done this a long time ago, of course, but the reason I'm picking this up now is that my VS Code setup by default picks up some
JSON config schema from some random other software which also names its config files config.toml.
Fixes #8979
> Make hugo.toml the new config.toml

- snap/snapcraft.yaml
Besides the `$HOME/.gitconfig` and `$HOME/.config/git/config` files that git reads by default, grant read access for `$HOME/.gitconfig.local` file and `$HOME/.config/git` directory too, in `hugo:gitconfig` plug (`personal-files` interface), for the end users who need the flexibility of using (somewhat arbitrary named) additional custom git config files.
Fixes #10337
> snap: Add read access for ~/.gitconfig.local and ~/.config/git/* too

- snap/snapcraft.yaml
See https://github.com/sass/dart-sass-embedded/releases/tag/1.54.7 which "Add[ed] support for 32-bit ARM releases on Linux" on 2022-08-30.
> snap: Install dart-sass-embedded for 32-bit ARM (armhf) too

- publisher/htmlElementsCollector.go
- publisher/htmlElementsCollector_test.go
```
name                           old time/op    new time/op    delta
ElementsCollectorWriterPre-10    25.2µs ± 1%     3.4µs ± 0%  -86.54%  (p=0.029 n=4+4)
name                           old alloc/op   new alloc/op   delta
ElementsCollectorWriterPre-10      624B ± 0%      142B ± 0%  -77.18%  (p=0.029 n=4+4)
name                           old allocs/op  new allocs/op  delta
ElementsCollectorWriterPre-10      16.0 ± 0%       6.0 ± 0%  -62.50%  (p=0.029 n=4+4)
```
Fixes #10698
> Fix slow HTML elements collector for the pre case

- markup/highlight/config.go
- markup/highlight/config_test.go
This fixes a regression introduced in v0.93.0 where previously, a
mixed-case key for lineNos would be successfully parsed. This change
moves the configuration key lowercasing step into the configuration
normalization stage, which is called whether the highlighting config
is being parsed from a `string` or a `map`.
Fixes #10682
> markup: fixes regression for linenos codeblock hl option

- hugolib/content_render_hooks_test.go
- hugolib/integrationtest_builder.go
- hugolib/page__per_output.go
- hugolib/shortcode.go
- markup/asciidocext/convert.go
- markup/converter/converter.go
- markup/goldmark/convert.go
- markup/goldmark/convert_test.go
- markup/org/convert.go
- markup/pandoc/convert.go
- markup/rst/convert.go
- resources/page/page.go
- resources/page/page_lazy_contentprovider.go
- resources/page/page_nop.go
This also speeds up situations where you only need the fragments/toc and not the rendered content, e.g. Related
with fragments type indexing:
```bash
name            old time/op    new time/op    delta
RelatedSite-10    12.3ms ± 2%    10.7ms ± 1%  -12.95%  (p=0.029 n=4+4)
name            old alloc/op   new alloc/op   delta
RelatedSite-10    38.6MB ± 0%    38.2MB ± 0%   -1.08%  (p=0.029 n=4+4)
name            old allocs/op  new allocs/op  delta
RelatedSite-10      117k ± 0%      115k ± 0%   -1.36%  (p=0.029 n=4+4)
```
Fixes #10750
> Split parse and render for Goldmark

- resources/resource_transformers/tocss/dartsass/integration_test.go
- resources/resource_transformers/tocss/dartsass/transform.go
Applicable to Dart Sass only:
- Sass imports with the .css extension indicate a plain CSS @import.
- Sass imports without the .css extension are imported at compile time.
Fixes #10592
> dartsass: Import CSS without extension at compile time

- temp/0.86.1-relnotes-ready.md
Looks like the `temp` directory is not longer stores release notes and can be removed.
> Remove unused temp directory

- tpl/tplimpl/embedded/templates/google_news.html
This was deprecated, with a warning message, on 21 Nov 2021.
Reference #9190
> tpl/tplimpl: Remove the Google News internal template

- cache/filecache/filecache.go
- commands/commands_test.go
- commands/server.go
- commands/server_test.go
- common/para/para.go
- config/security/whitelist.go
- helpers/pathspec.go
- hugofs/glob/glob.go
- hugolib/content_map.go
- hugolib/filesystems/basefs.go
- hugolib/hugo_sites.go
- hugolib/pagecollections.go
- hugolib/site.go
- langs/language.go
- markup/goldmark/autoid.go
- markup/internal/attributes/attributes.go
- media/mediaType.go
- parser/metadecoders/format.go
- resources/page/page_kinds.go
- resources/page/pages_prev_next.go
- resources/page/site.go
- resources/resource_transformers/js/options.go
- source/fileInfo.go
- source/filesystem.go
- tpl/internal/go_templates/texttemplate/hugo_template.go
- tpl/tplimpl/template.go
This PR fixes word typos in comments for the Go code.
> Correct typos in Go comments

- cache/filecache/filecache_pruner.go
- cache/filecache/integration_test.go
- hugolib/integrationtest_builder.go
This applies two related fixes/improvements:
* The --gc now keeps empty `_resources/_gen/images` etc folders, even if empty. This should have been the behaviour
from the start.
* Also, if removal of an empty dir on Windows fails with the "used by another process" error, just ignore it for now.
Fixes #10781
> Work around --gc failure on Windows <= 10

- cache/filecache/filecache_pruner.go
- cache/filecache/integration_test.go
On Windows, we must close the directory before removing it. This fixes
```
Error: failed to prune cache "getjson": remove
C:\Users\photo\AppData\Local\Temp\hugo_cache\quickstart\filecache\getjson:
The process cannot access the file because it is being used by another
process.
```
> cache: Fix --gc failure on Windows 

- lazy/init.go
- lazy/init_test.go
- resources/transform.go
- tpl/partials/integration_test.go
- tpl/partials/partials.go
Make sure the context used for partial timeouts isn't created based on the incoming
context, as we have cases where this can cancel the context prematurely.
Fixes #10789
> Fix "context canceled" with partial

- commands/deploy.go
- commands/hugo.go
- deploy/deploy.go
- docs/content/en/commands/hugo_deploy.md
The current hugo deploy limits the number of parallel requests by 10 with `nParallel = 10`
This PR allows customization of this value by providing another flag called transfers
It can sometimes be useful to set this to a smaller number if the remote is giving a lot of timeouts or bigger if you have lots of bandwidth and a fast remote.
In my testing setting this to 100 in one of our bigger deployment runners reduced our time to deploy to s3 from `1min 50s` to `32s`
Exiting users should see no change as it will default to 10
```bash
hugo deploy --target foo --workers 20
```
> Hugo deploy customize parallel transfer count

- docs/content/en/functions/hasPrefix.md
- docs/content/en/functions/hasSuffix.md
- tpl/strings/init.go
strings.HasPrefix already has an alias of hasPrefix but strings.HasSuffix has no such alias.
This PR adds a hasSuffix alias to the funcs mapping with corresponding documentation.
It also adds a minor update to the hasPrefix function documentation re: keywords and relatedfuncs.
Completes https://github.com/gohugoio/hugo/issues/10474
> tpl: Add hasSuffix alias

- commands/server_test.go
This PR changes imports of `golang.org/x/net/context` to `context` by running the command `go fix -fix context ./...`
> server: Replace golang.org/x/net/context with context

- hugolib/shortcode.go
- hugolib/shortcode_test.go
Following up on this [thread](https://discourse.gohugo.io/t/hugo-0-111-2-failure-with-unclosed-shortcodes/43368) in hugo discourse, this PR aims at improving the error message printed out when hugo encounters an unclosed shortcode with inner content. The message is now in line with the [wording](https://gohugo.io/templates/shortcode-templates/#inner) in the official hugo docs.
> Unclosed shortcode with inner content: improved error message

- docs/content/en/functions/math.md
- tpl/math/math.go
- tpl/math/math_test.go
allow multi numbers of add (`+`) / sub (`-`) / mul (`*`) / div (`/`) / min value / max value
refactor before:
```
add 1 2 | add 3 | add 4 // equivalent to: 1 + 2 + 3 + 4
sub 1 2 | sub 3 | sub 4 // equivalent to: 1 - 2 - 3 - 4
mul 1 2 | mul 3 | mul 4 // equivalent to: 1 * 2 * 3 * 4
div 1 2 | div 3 | div 4 // equivalent to: 1 / 2 / 3 / 4
math.Min 1 2 | math.Min 3 | math.Min 4
math.Max 1 2 | math.Max 3 | math.Max 4
```
refactor after:
```
add 1 2 3 4
sub 1 2 3 4
mul 1 2 3 4
div 1 2 3 4
math.Min 1 2 3 4
math.Max 1 2 3 4
```
> refactor: improve math

- go.mod
- go.sum
- markup/org/convert.go
among other things, fixes a race condition in html writer and bug preventing explicit line breaks immediately following emphasis
> deps: Update go-org to v1.6.6

- docs/content/en/content-management/syntax-highlighting.md
> Add missing space in documentation

- docs/content/en/content-management/syntax-highlighting.md
Merged into wrong repository. Superseded by https://github.com/gohugoio/hugoDocs/commit/77b5009fd1052cccc311255ab6e099f36f308a4b
> Revert "Update syntax-highlighting.md (#10929)"

- helpers/path_test.go
This PR refactors path tests with `T.TempDir()` that automatically clears a temp directory.  This allows removing the `deleteFileInTempDir` function.
> helpers: Simplify path tests with T.TempDir

- tpl/lang/init.go
- tpl/lang/lang.go
> tpl/lang: Document delimiter option for FormatNumberCustom

- common/herrors/errors.go
- common/herrors/file_error.go
- common/maps/params.go
- config/security/whitelist.go
- deps/deps.go
- helpers/general.go
- hugofs/fs.go
- hugolib/page.go
- hugolib/pagecollections.go
- identity/identity.go
- langs/i18n/translationProvider.go
- lazy/init.go
- markup/asciidocext/asciidocext_config/config.go
- markup/converter/hooks/hooks.go
- markup/goldmark/codeblocks/transform.go
- markup/goldmark/goldmark_config/config.go
- markup/highlight/highlight.go
- markup/internal/attributes/attributes.go
- markup/tableofcontents/tableofcontents.go
- resources/page/page.go
- resources/page/site.go
- resources/postpub/postpub.go
- resources/resource_transformers/tocss/dartsass/client.go
- tpl/compare/compare.go
This PR changes comments for functions and packages, so that function/package names in comments and code are synchronized.
> all: Fix comments for exported functions and packages

- config/allconfig/allconfig.go
This PR fixes the warn message about custom params on the language top level. It also corrects 2 typos I spotted on the way.
> Fix warn message about custom params on the language top level

- config/allconfig/allconfig.go
- config/allconfig/load.go
- hugolib/config_test.go
> Make language merging of markup etc. config without values in the root

- commands/list.go
- testscripts/commands/list.txt
Also, always include the CSV header.
Updates #10953
> commands: Make all list commands list what 'all' did before

- hugolib/filesystems/basefs.go
- resources/resource_transformers/babel/babel.go
- resources/resource_transformers/postcss/postcss.go
This PR follows up on #10846. It adds validation for the `config` option: if the value given for 'config` is not a directory, a warning is emitted.
**With this patch applied:**
```
git clone --single-branch -b hugo-github-issue-10846 https://github.com/jmooring/hugo-testing hugo-github-issue-10846
cd hugo-github-issue-10846
npm ci
hugo_0.112.dev
Start building sites … 
hugo v0.112.0-DEV-720f41aab4fa9185957be65c5c7a92261715e297+extended linux/amd64 BuildDate=2023-03-25T20:05:11Z
WARN 2023/03/25 21:35:33 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/03/25 21:35:33 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup …
```
> postCSS: improve validation of option 'config'

- commands/commandeer.go
- commands/config.go
- commands/hugobuilder.go
- commands/new.go
- commands/server.go
- hugolib/config_test.go
- hugolib/site_new.go
- langs/config.go
- langs/language.go
- resources/page/site.go
- testscripts/commands/hugo__configdir.txt
- testscripts/commands/hugo__flags.txt
- testscripts/commands/hugo__noconfig.txt
- testscripts/commands/new.txt
- testscripts/commands/server_render_static_to_disk.txt
- commands: Move the --format flag to only the commands that support it
- commands: Re-introduce the -f shorthand for hugo new site
- Fix --renderStaticToDisk regression
- Add language.LanguageCode
- langs: Remove the Language.Params deprecation message for now
- commands: Fail the build when no config file or config dir
> Misc regression fixes

- markup/goldmark/convert_test.go
- markup/goldmark/render_hooks.go
> Prevent double escaping of image alt-text in Goldmar typographer

- hugolib/menu_test.go
- hugolib/site.go
- testscripts/commands/hugo__watch.txt
- Don't inject livereload script on hugo -w
- Fix menuItem.URL when pageRef is not set
> Misc bug fixes

- helpers/url.go
```
RelURL-10            159ns ± 5%      18ns ± 4%   -88.89%  (p=0.029 n=4+4)
AbsURL/relurl-10     532ns ± 0%     537ns ± 0%    +1.09%  (p=0.029 n=4+4)
AbsURL/absurl-10     142ns ± 0%       4ns ± 3%   -96.91%  (p=0.029 n=4+4)
name              old alloc/op   new alloc/op   delta
RelURL-10             144B ± 0%        0B       -100.00%  (p=0.029 n=4+4)
AbsURL/relurl-10      544B ± 0%      544B ± 0%      ~     (all equal)
AbsURL/absurl-10      144B ± 0%        0B       -100.00%  (p=0.029 n=4+4)
name              old allocs/op  new allocs/op  delta
RelURL-10             1.00 ± 0%      0.00       -100.00%  (p=0.029 n=4+4)
AbsURL/relurl-10      10.0 ± 0%      10.0 ± 0%      ~     (all equal)
AbsURL/absurl-10      1.00 ± 0%      0.00       -100.00%  (p=0.029 n=4+4)
```
> helpers: Avoid url.Parse in RelURL and AbsURL if we can

- commands/commandeer.go
- docs/content/en/commands/hugo.md
- docs/content/en/commands/hugo_config.md
- docs/content/en/commands/hugo_config_mounts.md
- docs/content/en/commands/hugo_mod_clean.md
- docs/content/en/commands/hugo_mod_graph.md
- docs/content/en/commands/hugo_mod_init.md
- docs/content/en/commands/hugo_mod_npm_pack.md
- docs/content/en/commands/hugo_mod_tidy.md
- docs/content/en/commands/hugo_mod_vendor.md
- docs/content/en/commands/hugo_mod_verify.md
- docs/content/en/commands/hugo_new_content.md
- docs/content/en/commands/hugo_server.md
- docs/content/en/getting-started/configuration.md
- docs/content/en/templates/data-templates.md
- helpers/path.go
Change the default cache directory to `$TMPDIR/hugo_cache_$USER`, so that multi-user systems do not have caches that interfere with each other.  The other cache-choosing logic (e.g. Netlify exceptions, configuration options) are not affected.
Fixes #7391
> cache: Set default cache path based on $USER

- tpl/math/math.go
- tpl/math/math_test.go
* Update math.Min and math.Max to allow 1 or more args, either scalar or slice, or combination of the two
* Add math.Sum (allow 1 or more args, either scalar or slice, or combination of the two)
* Add math.Product (allow 1 or more args, either scalar or slice, or combination of the two)
Fixes #11030
> tpl/math: Allow variadic math functions to take slice args, add math.Product, math.Sum

- snap/snapcraft.yaml
- Syntax changes
- Bump Go from 1.19 to 1.20
- Remove unused build tag logic (we only build the extended version)
> snap: Transition base snap from core20 to core22

- config/allconfig/load.go
- config/security/securityConfig.go
- config/security/securityConfig_test.go
- tpl/internal/go_templates/htmltemplate/context.go
- tpl/internal/go_templates/htmltemplate/css.go
- tpl/internal/go_templates/htmltemplate/css_test.go
- tpl/internal/go_templates/htmltemplate/doc.go
- tpl/internal/go_templates/htmltemplate/error.go
- tpl/internal/go_templates/htmltemplate/escape.go
- tpl/internal/go_templates/htmltemplate/escape_test.go
- tpl/internal/go_templates/htmltemplate/html.go
- tpl/internal/go_templates/htmltemplate/hugo_template.go
- tpl/internal/go_templates/htmltemplate/js.go
- tpl/internal/go_templates/htmltemplate/js_test.go
- tpl/internal/go_templates/htmltemplate/jsctx_string.go
- tpl/internal/go_templates/htmltemplate/state_string.go
- tpl/internal/go_templates/htmltemplate/transition.go
- tpl/internal/go_templates/testenv/exec.go
- tpl/internal/go_templates/testenv/testenv.go
- tpl/internal/go_templates/testenv/testenv_test.go
- tpl/internal/go_templates/texttemplate/exec.go
- tpl/internal/go_templates/texttemplate/exec_test.go
- tpl/template.go
- tpl/tplimpl/integration_test.go
Fix upstream Go templates bug with reversed key/value assignment
The template packages are based on go1.20.5 with the patch in befec5ddbbfbd81ec84e74e15a38044d67f8785b  added.
This also includes a security fix that now disallows Go template actions in JS literals (inside backticks).
This will throw an error saying "... appears in a JS template literal".
If you're really sure this isn't a security risk in your case, you can revert to the old behaviour:
```toml
[security]
[security.gotemplates]
allowActionJSTmpl = true
```
See https://github.com/golang/go/issues/59234
Fixes #11112
> Fix upstream Go templates bug with reversed key/value assignment

- commands/deploy.go
- deploy/deployConfig.go
- testscripts/commands/deploy.txt
This was broken in the config rewrite in Hugo 0.112.0.
The workaround is to be explicit about setting these flag values (even if just using the defaults), e.g.:
```
hugo deploy --invalidateCDN --maxDeletes 256
```
Fixes https://github.com/gohugoio/hugo/issues/11127
> Fix deploy defaults for non-zero flag values (e.g. maxDeletes, invalidateCDN)

- cache/docs.go
- cache/filecache/filecache_config.go
- commands/commandeer.go
- commands/convert.go
- common/herrors/error_locator.go
- common/herrors/file_error.go
- common/hexec/exec.go
- common/paths/path.go
- config/allconfig/allconfig.go
- config/commonConfig.go
- helpers/emoji.go
- helpers/emoji_test.go
- htesting/test_helpers.go
- hugofs/filter_fs.go
- hugofs/fs.go
- hugofs/glob/filename_filter_test.go
- hugolib/config_test.go
- hugolib/configdir_test.go
- hugolib/datafiles_test.go
- hugolib/embedded_shortcodes_test.go
- hugolib/hugo_sites_build.go
- hugolib/pagecollections_test.go
- hugolib/site.go
- langs/language.go
- livereload/livereload.go
- resources/jsconfig/jsconfig.go
- resources/resource_transformers/js/options.go
This PR corrects typos in unexported function names, variable names, testcase names, and comments.
> all: Fix typos in function names, tests and comments

- go.mod
- go.sum
This reverts commit 409c6c3fcd46a57c2f469663bb0106a1a3cf4469.
See #11132
> Revert "deps: Update github.com/tdewolff/minify/v2 v2.12.5 => v2.12.6"

- commands/import.go
Update CLI output after a successful Jekyll import to suggest a maintained theme and include clearer steps to running a server locally.
Fixes #10715.
I followed the suggestion made by @jmooring to clarify the next steps.
> commands: Update Jekyll post-import output

- snap/snapcraft.yaml
- Continues to get latest version of Dart Sass during each build
- Removes superfluous BUILD_TAGS logic (we only build extended)
> snap: Switch from Embedded Dart Sass to Dart Sass

- tpl/tplimpl/template.go
> tpl/tplimpl: Fix typo in global variable name

- commands/hugobuilder.go
- hugolib/hugo_sites_build.go
- testscripts/commands/hugo__path-warnings-postprocess.txt
- testscripts/commands/hugo__path-warnings.txt
> Fix false path warnings with resources.PostProcess

- commands/convert.go
- commands/gen.go
- commands/import.go
- commands/list.go
- commands/new.go
This PR aims to fix [this](https://github.com/gohugoio/hugo/issues/11165) issue.
Starting from release [v0.112.0](https://github.com/gohugoio/hugo/releases/tag/v0.112.0) and via this [commit](https://github.com/gohugoio/hugo/commit/241b21b0fd34d91fccb2ce69874110dceae6f926), `import`, `new`, `convert`, `list` and `gen` commands produce no output when triggered with no flags.
This PR reverts to the old behaviour by printing the help message by default.
> Print help message when command is triggered with no flags

- config/allconfig/alldecoders.go
- hugofs/files/classifier.go
- hugolib/content_map.go
- hugolib/integrationtest_builder.go
- hugolib/page__paths.go
- hugolib/site_url_test.go
- resources/page/permalinks.go
- resources/page/permalinks_integration_test.go
- resources/page/permalinks_test.go
- resources/page/zero_file.autogen.go
- source/fileInfo.go
Fixes #9448
Fixes #11184
See #8523
> Misc permalinks adjustments

- commands/commandeer.go
- commands/helpers.go
- commands/hugobuilder.go
- config/allconfig/allconfig.go
- config/allconfig/configlanguage.go
- config/allconfig/integration_test.go
- config/allconfig/load.go
- config/configProvider.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- langs/i18n/i18n.go
We could reset and rerun it on server rebuilds, but that report needs a full build to make sense.
Also clean up the config vs flags in this area: Make all config settings match the flags e.g. `printPathWarnings`, but set up aliases for the
old.
Fixes #11187
> Only print the path warnings once

- snap/snapcraft.yaml
> snap: Restore security.exec.osenv whitelist

- snap/snapcraft.yaml
> snap: Explicitly set security.exec.osenv during build

- config/security/securityConfig.go
- config/security/securityConfig_test.go
To better support private Hugo modules and automatically
launching a text editor on content creation, this change
adds the following environment variables to the default
security policy:
- HOME
- XDG_CONFIG_HOME
- USERPROFILE
- SSH_AUTH_SOCK
- DISPLAY
- LANG
Fixes https://github.com/gohugoio/hugo/issues/9333
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>
> config: expand default security.exec.osEnv policy

- resources/resource_transformers/js/build.go
- resources/resource_transformers/js/integration_test.go
This passes tsconfig.json to esBuild if it exists in the project root or in assets/_jsconfig.
Note that esBuild only inspects/honors certain fields.
See https://esbuild.github.io/content-types/#tsconfig-json.
Fixes #11232
> js: Pass tsconfig.json to esBuild

- hugolib/config_test.go
- hugolib/hugo_sites.go
- hugolib/page__per_output.go
- hugolib/page_test.go
- hugolib/site_render.go
> Misc fixes

- hugolib/hugo_modules_test.go
- hugolib/hugo_sites.go
Fixes #10681
Before this change, data files from Hugo modules were always mounted at the
root of the `data` directory. The File and FileMetaInfo structs for modules
are different from 'native' data directories.
This changes how the keyParts for data files are generated so that data
from modules or native directories are treated the same.
> **Note**
>
> This might not be the best way of solving this issue. Perhaps it's preferred
> to change how file metadata gets created, so that the properties for native
> and module data directories are the same. I just couldn't figure out how to
> do that.
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>
> fix: dotpath for Hugo modules mounted as data

- config/allconfig/alldecoders.go
- config/allconfig/load.go
- hugolib/config_test.go
- parser/metadecoders/decoder.go
So you can do
```
HUGO_OUTPUTS="home: [rss]"  hugo
```
And similar.
Fixes #11249
> Fix setting config from env with complex (e.g. YAML) strings

- config/allconfig/allconfig.go
- helpers/path.go
- main_test.go
- testscripts/commands/config__cachedir.txt
We will now try
1. cacheDir (or, commonly set in environment as `HUGO_CACHEDIR`)
2. if on Netlify we use `/opt/build/cache/hugo_cache/`
3. os.UserCacheDir
4. A temp dir
Storing the cache, especially the module cache, in a temporary idea has had lots of hard to debug issues, especially on MacOS,
which this commit tries to fix.
This should also make it easier to locate the Hugo cache:
>UserCacheDir returns the default root directory to use for user-specific cached data. Users should create their own
application-specific subdirectory within this one and use that.
>
>On Unix systems, it returns $XDG_CACHE_HOME as specified by
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if non-empty, else $HOME/.cache. On Darwin, it
returns $HOME/Library/Caches. On Windows, it …
> Use os.UserCacheDir as first fallback if cacheDir is not set

- tpl/collections/apply.go
The collections.Apply template function cannot be used with maps.
> tpl/collections: Fix description of apply function

- tpl/collections/integration_test.go
- tpl/collections/where.go
Enables constructs such as:
```text
{{ range where site.RegularPages "Params.foo" "like" "^ab" }}
<h2><a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a></h2>
{{ end }}
```
Will submit documentation change to the documentation repository is this is merged.
Closes #11279
> tpl/collections: Add like operator to where function

- commands/commandeer.go
Removed description of `cacheDir` default value instead of trying to describe it.
> commands: Update cacheDir description

- README.md
bep's github profile url was set to spf13's.
> Fixed/Updated Github Profile URL of Bjørn Erik Pedersen (bep)

- hugolib/page.go
- hugolib/page__new.go
- hugolib/page__output.go
- hugolib/page__per_output.go
- hugolib/page_test.go
- hugolib/rendershortcodes_test.go
- hugolib/shortcode.go
- hugolib/shortcode_page.go
- hugolib/shortcode_test.go
- resources/page/page.go
- resources/page/page_nop.go
- resources/page/testhelpers_test.go
- tpl/internal/go_templates/texttemplate/hugo_template.go
- tpl/template.go
A layouts/shortcodes/include.html shortcode may look like this:
```html
{{ $p := site.GetPage (.Get 0) }}
{{ $p.RenderShortcodes }}
```
Fixes #7297
> Add Page.RenderShortcodes

- resources/resource_factories/create/integration_test.go
- resources/resource_factories/create/remote.go
> Return original error on resources.GetRemote retry timeouts

- docs/data/docs.yaml
- output/docshelper.go
- Always include example for "with layout/type set"
- Use lowercase for "set to" examples (lookup is case sensitive)
- Consistent use of taxonomy and term
Fixes gohugoio/hugoDocs#1734
> docshelper: Improve template lookup order descriptions

- hugolib/hugo_sites_build.go
- hugolib/site_test.go
> Avoid escaping HTML chars inside hugo_stats.json

- deploy/cloudfront.go
This PR refactors `InvalidateCloudFront` by replacing `session.NewSessionWithOptions` with `gcaws.NewDefaultSession`.
> deploy: Update InvalidateCloudFront to use Go CDK helper

- modules/client.go
Leave newly-created directories in the module cache read-write instead of making them read-only.
Closes # 11369
> modules: Make new cache directories read/write

- config/allconfig/configlanguage.go
- config/allconfig/load.go
- hugolib/paths/paths.go
- modules/client.go
- modules/collect.go
- modules/module.go
- testscripts/commands/mod__disable.txt
- testscripts/commands/mod_vendor.txt
The motivation behind the original implementation was probably to show disabled modules when running `hugo mod graph`.
Fixes #11376
> Fix it so disable a module does not disable transitive dependency required by others

- common/loggers/logger.go
- common/loggers/logger_test.go
- hugolib/site_new.go
- resources/page/permalinks.go
This PR fixes typos in the struct field and variable names.
> common/loggers: Fix typo in log option name

- deploy/cloudfront.go
- deploy/deploy.go
This allows the AWS credentials to be picked up from the configured target URL (like blob does) rather than the current behaviour of only relying on the defaults.
Relying on the defaults here means having to specify credentials twice (once in the URL for the blob, once in the environment for this code path) when non-default AWS credentials are in used (e.g. via a profile).
> deploy: Create AWS session for CloudFront invalidation via Go CDK

- create/skeletons/theme/layouts/partials/head.html
Remove initial-scale=1.0 (this is the browser default)
Remove minimum-scale=1.0 (opinionated, can throw WCAG warning)
> create/skeletons: Improve viewport meta tag

- .circleci/config.yml
- scripts/fork_go_templates/main.go
- tpl/internal/go_templates/htmltemplate/context.go
- tpl/internal/go_templates/htmltemplate/escape.go
- tpl/internal/go_templates/htmltemplate/escape_test.go
- tpl/internal/go_templates/htmltemplate/state_string.go
- tpl/internal/go_templates/htmltemplate/transition.go
See https://github.com/golang/go/issues?q=milestone%3AGo1.21.1+label%3ACherryPickApproved
Fixes #11474
Fixes #11414
> Upgrade to Go 1.21.1

- common/hstrings/strings.go
- docs/content/en/content-management/image-processing/index.md
- docs/content/en/functions/images/index.md
- helpers/general.go
- hugolib/site_output_test.go
- resources/errorResource.go
- resources/image.go
- resources/image_test.go
- resources/images/config.go
- resources/images/config_test.go
- resources/images/filters.go
- resources/images/image.go
- resources/images/image_resource.go
- resources/images/process.go
- resources/integration_test.go
- resources/page/permalinks.go
- resources/transform.go
Which supports all the existing actions: resize, crop, fit, fill-
But it also allows plain format conversions:
```
{{ $img = $img.Process "webp" }}
```
Which will be a simple re-encoding of the source image.
Fixes #11483
> Add $image.Process

- common/constants/constants.go
This PR no longer used constants `ErrIDAmbigousDisableKindTaxonomy` and `ErrIDAmbigousOutputKindTaxonomy`.
> common: Remove unused constants

- tpl/lang/lang.go
Use lang.FormatNumberCustom instead.
> tpl/lang: Formally deprecate lang.NumFmt

- commands/server.go
- common/paths/url.go
- tpl/math/round.go
- tpl/tplimpl/template_ast_transformers.go
This PR formats files with `gofmt`. We need this to fix `mage fmt`.
The problem appeared when the PR https://github.com/gohugoio/hugo/pull/11521 had been accepted.
> all: Format files with gofmt

- docs/content/en/templates/internal.md
- tpl/tplimpl/embedded/templates/opengraph.html
- tpl/tplimpl/embedded/templates/twitter_cards.html
This is the first step in deprecating the `social` key in site configuration. Our internal exposure is limited to the opengraph and twitter_cards templates. Site authors will receive a warning, generated by the relevant internal template, if they are using:
```
[social]
facebook_admin= 'foo'
```
or 
```
[social]
twitter = 'bar'
```
They will be instructed to change these to:
```
[params.social]
facebook_admin= 'foo'
```
and 
```
[params.social]
twitter = 'bar'
```
After this has been running in the field for a while, and site authors have made the change, we can:
1. Deprecate `func (s *Site) Social()`, and simultaneously
2. Remove `site.Social.facebook_admin` and `site.Social.twitter` from the affected templates
The `social` key in site configuration is not documented[^1], so, other than …
> tpl/tplimpl: Deprecate .Site.Social usage with internal templates

- tpl/tplimpl/embedded/templates/_default/rss.xml
This is the first step in deprecating the `author` key in site configuration. Our internal exposure is limited to the RSS template. Site authors will receive a warning, generated by the RSS template, if they are using:
```
[author]
name = 'John Doe'
email = 'jdoe@example.org'
```
They will be instructed to change this to:
```
[params.author]
name = 'John Doe'
email = 'jdoe@example.org'
```
After this has been running in the field for a while, and site authors have made the change, we can:
1. Deprecate `func (s *Site) Author()`, and simultaneously
2. Remove `site.Author.email` and `site.Author.name` from the RSS template
The `author` key in site configuration is not documented, so, other than its usage in the RSS template, our external exposure should be limited.
> tpl/tplimpl: Deprecate .Site.Author usage in RSS template

- docs/content/en/getting-started/configuration.md
- docs/content/en/templates/internal.md
- docs/content/en/variables/site.md
- hugolib/site_new.go
- resources/page/site.go
- tpl/tplimpl/embedded/templates/google_analytics.html
- tpl/tplimpl/embedded/templates/google_analytics_async.html
Use .Site.Config.Services.GoogleAnalytics.ID instead.
> hugolib: Deprecate .Site.GoogleAnalytics

- deps/deps.go
- hugolib/hugo_sites_build.go
- tpl/debug/debug.go
- tpl/debug/integration_test.go
> tpl/debug: Add debug.Timer

- CONTRIBUTING.md
Because the issue https://github.com/visualfc/liteide/issues/986 was resolved a long time ago.
> docs: Remove outdated note from CONTRIBUTING.md

- watcher/filenotify/fsnotify.go
- watcher/filenotify/poller.go
- watcher/filenotify/poller_test.go
The PR fixes docs for the [`filenotify`](https://pkg.go.dev/github.com/gohugoio/hugo/watcher/filenotify).
Before:
After:
> watcher/filenotify: Remove redundant duplicated comments

- modules/client.go
- testscripts/commands/mod_get.txt
- testscripts/commands/mod_get_u.txt
Currently, `hugo mod get` won't update indirect import modules.
```toml
// site config
[[module.imports]]
path = "example.org/vendor/foo"
```
```toml
// example.org/vendor/foo module config
[[module.imports]]
path = "example.org/vendor/bar"
```
`hugo mod get` won't update the `example.org/vendor/bar` module.
Related issue/discussion: https://discourse.gohugo.io/t/unable-to-update-modules-those-imported-indirectly/46707.
I'm not sure if this PR is good, or should I create another command instead of overriding the original for this?
> commands/mod: update all active modules

- commands/commandeer.go
- common/hugo/hugo.go
- common/hugo/hugo_test.go
- common/hugo/version.go
- config/allconfig/allconfig.go
- helpers/general.go
- hugolib/hugo_sites_build.go
- hugolib/page__meta.go
- hugolib/site_new.go
- source/fileInfo.go
- tpl/collections/collections.go
- tpl/lang/lang.go
This introduces a more automatic way of increasing the log levels for deprecation log statements based on the version it was deprecated.
The thresholds are a little arbitrary, but
* We log INFO for 6 releases
* We log WARN for another 6 releases
* THen ERROR (failing the build)
This should give theme authors plenty of time to catch up without having the log filled with warnings.
> Revise the deprecation logging

- go.mod
- go.sum
- markup/goldmark/convert.go
- markup/goldmark/convert_test.go
- markup/goldmark/goldmark_config/config.go
This commit follows https://github.com/yuin/goldmark/pull/411
> markup/goldmark: update the CJK extension to allow specifying line break styles

- transform/livereloadinject/livereloadinject.go
- transform/livereloadinject/livereloadinject_test.go
This PR addresses all the concerns I raised in issue https://github.com/gohugoio/hugo/issues/11562 and then some.
It changes the behavior of the livereloadinject transformer to read the HTML document from the start, consuming any comments and whitespace as well as the doctype, html start tag and head start tag in that order, stopping the moment another tag or text content is encountered, and injecting the livereload script there. Compared to the current code, it specifically:
- Allows mixed casing in tag names.
- Always injects at the start of the head even when tags are omitted, meaning the browser can download the script faster.
- Always attempts to inject, and never with a warning. Browsers already warn the user if the HTML is malformed.
- Requires whitespace before attributes, so …
> livereloadinject: Use more robust injection method

- hugolib/integration_test.go
- hugolib/page__meta.go
> hugolib: Display correct markup identifier in error message

- create/skeletons/theme/layouts/partials/menu.html
Check identifier existence before calling lang.Translate to prevent empty warnings when using the --printI18nWarnings flag.
Closes #11519
> create/skeletons: Fix menu template

- tpl/tplimpl/embedded/templates/_default/rss.xml
Modified to handle any of the following existing site configs. 
```text
[params]
author = 'jdoe'
```
```text
[author]
name = 'jdoe'
email = 'jdoe@example.org'
```
```text
[params.author]
name = 'jdoe'
email = 'jdoe@example.org'
```
> tpl/tplimpl: Fix deprecation logic in RSS template

- common/loggers/loggerglobal.go
- config/allconfig/load.go
- hugolib/hugo_sites_build.go
- testscripts/commands/deprecate.txt
- tpl/debug/debug.go
> Fix deprecation printing on info level

- resources/integration_test.go
- resources/resource/resource_helpers.go
> resources/resource: Fix GroupByParamDate with raw TOML dates

- main_test.go
This picks up a dropped `err` variable and simplifies surrounding test logic.
> fix: dropped test error

- common/paths/url.go
- common/paths/url_test.go
> tpl/urls: Retain query and fragment with absURL and absLangURL

- docs/content/en/functions/transform/Unmarshal.md
- parser/metadecoders/decoder.go
- tpl/transform/integration_test.go
If true, a quote may appear in an unquoted field and a non-doubled quote may appear in a quoted field. It defaults to false.
Closes #11884
> parser/metadecoders: Add CSV lazyQuotes option to transform.Unmarshal

- docs/data/docs.yaml
- go.mod
- go.sum
- minifiers/config.go
- minifiers/config_test.go
- minifiers/minifiers_test.go
KeepConditionalComments was deprecated in the upstream library and replaced with KeepSpecialComments. This new option reflects that both conditional comments and Server Side Include comments can be optionally stripped by the minifier. As with KeepConditionalComments, the minifier is configured not to strip them by default.
> deps: Update github.com/tdewolff/minify/v2 v2.20.9 => v2.20.13

- docs/content/en/content-management/front-matter.md
- parser/metadecoders/decoder.go
- parser/metadecoders/decoder_test.go
Hey all! What are your thoughts on this change?
The [keywords](https://orgmode.org/worg/org-syntax.html#Keywords) definition from the org syntax specification doesn't say we can't repeat keywords. 
This change will also enable terms in org mode to have space. 
Currently, repeated keywords are concatenated: `#+title: foo\n#+title: bar` would render as `foo bar`. With this change, it just doesn't render anything but hugo is not crashing either.
> parser/metadecoders: Accumulate org keywords into arrays

- modules/collect.go
This PR prints more info about required Hugo version.
```sh
$ hugo | grep compatible                           
WARN  Module "a" is not compatible with this Hugo version; run "hugo mod graph" for more information.
$ hugo-dev | grep compatible
WARN  Module "a" is not compatible with this Hugo version: Min 0.130.0; run "hugo mod graph" for more information.
```
> modules: Print required Hugo version for incompatible modules

- hugolib/page__meta.go
- hugolib/params_test.go
- resources/page/page_matcher.go
This is deliberately very simple, but should not break anything. We need to introduce this in baby steps, but this should allow us to introduce this in the documentation.
Note that the `params` section's key/values will be added to `.Params` last. This means that you can have different values for "Hugo's summary" and the custom ".Params.summary" if you want to.
Updates #11055
> Add the [params] concept to front matter

- hugofs/glob/filename_filter_test.go
Fix dropped `err` variable in the tests for `hugofs/glob`.
> hugofs/glob: fix dropped test error

- check_gofmt.sh
- common/paths/path.go
- common/types/types.go
- config/allconfig/allconfig.go
- hugolib/content_render_hooks_test.go
- hugolib/page__per_output.go
- hugolib/pagecollections.go
- hugolib/pagecollections_test.go
- magefile.go
- markup/goldmark/goldmark_config/config.go
- tpl/template_info.go
- tpl/tplimpl/embedded/templates/_default/_markup/render-image.html
- tpl/tplimpl/embedded/templates/_default/_markup/render-link.html
- tpl/tplimpl/template.go
- tpl/tplimpl/template_errors.go
> Create default link and image render hooks

- hugofs/component_fs.go
- hugolib/content_map_test.go
We do a slight normalisation of the content paths (lower case, replacing " " with "-") and remove andy language identifier before inserting them into the content tree.
This means that, given that that the default content language is `en`:
```
index.md
index.html
Foo Bar.txt
foo-bar.txt
foo-bar.en.txt
Foo-Bar.txt
```
The bundle above will be reduced to one content file with one resource (`foo-bar.txt`).
Before this commit, what version of the `foo-bar.txt` you ended up with was undeterministic. No  we pick the first determined by sort order.
Note that the sort order is stable, but we recommend avoiding situations like the above.
Closes #11946
> Filter out duplicate content resource files

- config/security/securityConfig.go
- config/security/securityConfig_test.go
SYSTEMDRIVE is a Windows environment variable required when rendering the asciidoc content format.
See <https://discourse.gohugo.io/t/hugo-asciidoc-on-windows-triggering-warn-messages-about-gemrc-not-being-found/48061>
> config/security: Add SYSTEMDRIVE to OsEnv allowlist

- hugolib/page__meta.go
- source/fileInfo.go
Use .Page.Language.Lang instead.
> all: Deprecate .Page.Lang and .Page.File.Lang

- common/hugio/readers.go
- config/allconfig/allconfig.go
- config/allconfig/alldecoders.go
- hugolib/cascade_test.go
- hugolib/content_map_page.go
- hugolib/page__meta.go
- hugolib/page__new.go
- hugolib/params_test.go
- resources/page/page_matcher.go
- resources/page/page_matcher_test.go
- resources/resource.go
- resources: Optimize reading resource Content when it's already a string
- Handle resource changes when the resource is already evicted from cache
- Handle build vs _build in front matter
> Misc 0.123.0 fixes

- hugolib/page__position.go
Use .Page.Next and .Page.Prev instead.
Housecleaning... these were originally deprecated in v0.57.0 according to comments:
https://github.com/gohugoio/hugo/blob/46575baa02562e4ad05c89f4250287413e38627a/resources/page/page.go#L341-L345
> hugolib: Formally deprecate .Page.NextPage .Page.PrevPage

- commands/deploy.go
- config/allconfig/allconfig.go
- config/allconfig/alldecoders.go
- deploy/cloudfront.go
- deploy/deploy.go
- deploy/deploy_test.go
- deploy/deployconfig/deployConfig.go
- deploy/deployconfig/deployConfig_test.go
Test:
```
go list -tags nodeploy ./... | grep deploy
```
Fixes #12009
> Avoid impporting deploy from config when nodeploy tag is set

- .circleci/config.yml
- .github/workflows/test-dart-sass-v1.yml
- .github/workflows/test.yml
> Upgrade to Go 1.22

- helpers/general.go
- hugolib/integrationtest_builder.go
- hugolib/page_test.go
- hugolib/pagebundler_test.go
- hugolib/pages_capture.go
- hugolib/site_test.go
- parser/pageparser/pagelexer.go
- parser/pageparser/pagelexer_intro.go
- parser/pageparser/pageparser_intro_test.go
This currently only contains a test that illustrates the issue.
Without digging down trying to find the reason why this has changed, I think we agree that the current behaviour is less than useful, and that if we're going to break anything, we might as well break it in the direction of useful.
What if we say that we start **treating all content files the same (Markdown, HTML, Asciidoc etc.)**.
Does that sound like a plan?
> Make HTML behave exactly like other content formats

- hugofs/component_fs.go
- hugolib/pagebundler_test.go
- hugolib/pages_capture.go
Move the removal of duplicate content and resource files after we have determined if we're inside a leaf bundle or not.
Note that these would eventually have been filtered out as duplicates when  inserting them into the document store, but doing it here will preserve a consistent ordering.
Fixes #12013
> Move the duplicate page/resource filter

- hugolib/site.go
The current implementation of Hugo always sets a parameter `charset` to `utf-8` for all MIME types. This is not always correct, as some MIME types are not text-based and do not have a charset paramter.
Why does it matter? Some browsers have strict checking and will throw an error if the `charset` parameter is set to `utf-8` for a non-text MIME type.
For reference see the [RFC2045 Section 5](https://datatracker.ietf.org/doc/html/rfc2045#section-5): `For example, the "charset" parameter is applicable to any subtype of "text"...`, and Mozilla's docs for
[Structure of a MIME Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#structure_of_a_mime_type).
As documented in
[mime/type.go:L110](https://cs.opensource.google/go/go/+/master:src/mime/type.go;l=110),
on the …
> Correctly handle charset parameter to MIME types.

- hugolib/content_map_page.go
- hugolib/taxonomy_test.go
By just removing the term page and all of its page entries.
Which is a little of a coin flip, we could possibley also do like we handle the taxonomy nodes, e.g. disable them.
The reason this didn't just work is the way we need to wait until the end of the chain before we can apply the fully cascaded metadata to these nodes (e.g. the draft flag).
Fixes #12055
> Fix handling of draft term pages

- hugolib/content_map_page.go
- hugolib/rebuild_test.go
The partial rebuilds works by calaulating a baseline from a change set.
For new content, this doesn't work, so to avoid rebuilding everything, we first
try to collect a sample of surrounding identities (e.g. content files in the same section).
This commit fixes a flaw in that logic that in some cases would return a too small sample set.
Fixes #12054
> Fix sample logic when adding content files in server

- hugolib/pagebundler_test.go
- resources/resource/resources.go
Same as we do in .Get.
Fixes #12076
> Fall back to original name in Resources.GetMatch/Match

- helpers/general.go
- hugofs/rootmapping_fs.go
- hugolib/filesystems/basefs_test.go
- hugolib/integrationtest_builder.go
- testscripts/commands/hugo__static_composite.txt
But note that the overlay file system is set up horizontally (project -> module1 -> module2), so I would not recommend too complex overlapping mount setups within the same module.
But this worked in v0.122.0, so we should fix it.
Fixes #12103
> Fix regression on handling of overlapping file mounts

- config/allconfig/allconfig.go
- config/allconfig/load.go
- hugolib/page__meta.go
- hugolib/page__meta_test.go
Whether to capitalize automatic page titles, applicable to section, taxonomy, and term pages. Default is true.
Closes #9793
Closes #12115
> hugolib: Add capitalizeListTitles config option

- docs/content/en/functions/js/Build.md
- docs/content/en/hugo-pipes/js.md
- resources/resource_transformers/js/options.go
- resources/resource_transformers/js/options_test.go
As discussed in #12118, these two options make it easier to have React and non-React libraries automatically imported when using JSX.
When running `mage -v check`, I get an error in `TestImageOperationsGolden`. However, I get the same problem on `master`, so I'm assuming it isn't related to my changes.
<details>
<summary>Test error</summary>
```
panic: test timed out after 1m0s
running tests:
TestImageOperationsGolden (34s)
goroutine 11105 [running]:
testing.(*M).startAlarm.func1()
/usr/lib/go-1.21/src/testing/testing.go:2259 +0x1fc
created by time.goFunc
/usr/lib/go-1.21/src/time/sleep.go:176 +0x45
goroutine 1 [chan receive]:
testing.tRunner.func1()
/usr/lib/go-1.21/src/testing/testing.go:1561 +0x8cc
testing.tRunner(0xc0000e4b60, 0xc000629b08)
/usr/lib/go-1.21/src/testing/testing.go:1601 …
```
> js: Support JSX and JSXImportSourceOptions

- hugolib/pagecollections.go
- hugolib/pagecollections_test.go
> hugolib: Fix a .Page.GetPage from bundle case

- hugolib/content_map_page.go
- hugolib/pagebundler_test.go
- resources/image.go
- resources/resource.go
- resources/resource/resources.go
- resources/resource/resourcetypes.go
- resources/resource_metadata.go
- resources/resource_spec.go
- resources/testhelpers_test.go
- resources/transform.go
Which means that .Name now returns the same as it did in 0.122.0.
Closes #12142
> resource: Revert the normalization of Resource.Name

- config/allconfig/allconfig.go
- config/allconfig/alldecoders.go
- hugolib/cascade_test.go
- hugolib/integrationtest_builder.go
- hugolib/site_new.go
- resources/page/page_matcher.go
Also clean up the log handling in the integration tester, most notably lost logs during the config loading.
Fixes #12151
> Fix cascade-pattern-with-extension for cascade in site config

- hugofs/rootmapping_fs.go
- hugofs/rootmapping_fs_test.go
- hugolib/filesystems/basefs.go
- hugolib/hugo_sites_build.go
- hugolib/integrationtest_builder.go
- resources/resource_transformers/tocss/dartsass/dartsass_integration_test.go
- resources/resource_transformers/tocss/scss/scss_integration_test.go
This fixes the reverse filesystem lookup (absolute filename to path relative to the composite filesystem).
The old logic had some assumptions about the locality of the actual files that didn't work in more complex scenarios.
This commit now also adds the popular Bootstrap SCSS Hugo module to the CI build (both for libsass and dartsass transpiler), so we can hopefully avoid similar future breakage.
Fixes #12178
> Fix and add integration test for the Bootstrap SCSS module for both Dart Sass and Libsass

- tpl/tplimpl/embedded/templates/_default/_markup/render-image.html
- tpl/tplimpl/render_hook_integration_test.go
> tpl/tplimpl: Honor markdown attributes in embedded image render hook

- commands/server.go
- docs/content/en/commands/hugo_server.md
This PR fixes the grammar in synopsis of command 'hugo server'.
> docs: Fix hyphens and grammar in synopsis of command 'hugo server'

- markup/goldmark/convert.go
- markup/goldmark/toc.go
- markup/goldmark/toc_integration_test.go
Configure the TOC (table of contents, `toc.go`) goldmark renderer instance to always enable the Strikethrough extension.
This allows handling `ast.KindStrikethrough` within an AST node avoiding a crash.
Fixes #7169
Fixes #8087
Fixes #11783
> markup/goldmark: Render strikethrough and emojis in TOC entries

- hugolib/hugo_sites_build.go
- hugolib/pages_capture.go
- hugolib/site.go
This commit also optimizes for the case where change events for both file (e.g. `_index.md`) and the container directory comes in the same event batch.
While testing this on Windows 11 (ARM64), I notice that Windows behaves a little oddly when dumping a folder of files into the content tree; it works (at least after this commit), but it seems like the event batching behaves differently compared to other OSes (even older Win versions).
A related tip would be to try starting the server with polling, to see if that improves the situation, e.g.:
```
hugo server --poll 700ms
```
Fixes #12230
> Fix server rebuilds when adding sub sections especially on Windows

- config/allconfig/allconfig.go
- hugolib/page__meta.go
- hugolib/site_new.go
- resources/page/page.go
- resources/page/page_author.go
- resources/page/page_nop.go
- resources/page/site.go
- resources/page/testhelpers_test.go
- tpl/tplimpl/embedded/templates/opengraph.html
- tpl/tplimpl/embedded/templates/twitter_cards.html
> hugolib: Deprecate site methods Author, Authors, and Social

- hugolib/site.go
It's not in use and after #12266 it's also not corret to use on its own (use .Site.Home.Permalink).
> hugolib: Remove Site.HomeAbsURL

- commands/commandeer.go
- config/allconfig/allconfig.go
- config/allconfig/alldecoders.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/page.go
- hugolib/segments/segments.go
- hugolib/segments/segments_integration_test.go
- hugolib/segments/segments_test.go
- hugolib/site_render.go
Named segments can be defined in `hugo.toml`.
* Eeach segment consists of zero or more `exclude` filters and zero or more `include` filters.
* Eeach filter consists of one or more field Glob matchers.
* Eeach filter in a section (`exclude` or `include`) is ORed together, each matcher in a filter is ANDed together.
The current list of fields that can be filtered are:
* path as defined in https://gohugo.io/methods/page/path/
* kind
* lang
* output (output format, e.g. html).
It is recommended to put coarse grained filters (e.g. for language and output format) in the excludes section, e.g.:
```toml
[segments.segment1]
[[segments.segment1.excludes]]
lang = "n*"
[[segments.segment1.excludes]]
en     = "en"
output = "rss"
[[segments.segment1.includes]]
term = "{home,term,taxonomy}" …
```
> Add segments config + --renderSegments flag

- resources/image_test.go
This fixes the following TestImageOperationsGolden "values are not deep equal" error on riscv64 with Go 1.22 and above:
```
=== NAME  TestImageOperationsGolden
image_test.go:790: expectedly differs from golden due to dithering: giphy_hu3eafc418e52414ace6236bf1d31f82e1_52213_200x0_resize_box_1.gif
...
image_test.go:799: 
error:
values are not deep equal
diff (-got +want):
(*os.unixDirent)(
- 	&{
- 		parent: "/tmp/hugores955611955/resources/_gen/images/a",
- 		name:   "giphy_hu3eafc418e52414ace6236bf1d31f82e1_52213_200x0_resize_box_1.gif",
- 	},
+ 	&{
+ 		parent: "testdata/golden",
+ 		name:   "giphy_hu3eafc418e52414ace6236bf1d31f82e1_52213_200x0_resize_box_1.gif",
+ 	},
)
got:
s"- giphy_hu3eafc418e52414ace6236bf1d31f82e1_52213_200x0_resize_box_1.gif"
want:
s"- …
```
> Set usesFMA as true for riscv64 too

- hugolib/site_new.go
Suppress the .Site.Author deprecation notice unless the Author key is present and not empty in the site configuration.
Closes #12297
> hugolib: Conditionally suppress .Site.Author deprecation notice

- tpl/debug/debug.go
- tpl/debug/debug_integration_test.go
- tpl/debug/init.go
This replaces the current implementation with `json.MarshalIndent` which doesn't produce the same output, but at least it doesn't crash.
There's a bug in the upstream `litter` library. This can probably be fixed, but that needs to wait.
I have tested `go-spew` which does not crash, but it is very data racy in this context.
FIxes #12309
> Fix panic with debug.Dump with Page when running the server

- hugolib/embedded_templates_test.go
- tpl/tplimpl/embedded/templates/schema.html
Changes:
- Remove trailing comma from list of keywords.
- Improve keywords precedence:
1. Use "keywords" term page titles.
2. Use "keywords" from front matter if "keywords" is not a taxonomy.
3. Use "tags" term page titles.
4. Use term page titles from all taxonomies.
- Enable schema for all page kinds, previously limited to kind = page.
- Remove trailing slashes from void elements.
- Improve readability.
Closes #7570
Co-authored by: 0urobor0s <0urobor0s@users.noreply.github.com>
> tpl/tplimpl: Update schema template

- tpl/tplimpl/embedded/templates/_default/rss.xml
- Use publication date for pubdate
- Include version in generator element
Closes #3918
Closes #11692
> tpl/tplimpl: Update RSS template

- config/commonConfig.go
- docs/data/docs.yaml
- hugolib/config_test.go
- hugolib/sitemap_test.go
- tpl/tplimpl/embedded/templates/_default/sitemap.xml
- tpl/tplimpl/tplimpl_integration_test.go
Define global inclusion/exclusion in site configuration, and override via front matter. For example, to exclude a page from the sitemap:
[sitemap]
disable = true # default is false
Closes #653
Closes #12282
> tpl/tplimpl: Optionally exclude content from sitemap

- tpl/tplimpl/embedded/templates/opengraph.html
Changes:
- Add tags per documentation
- Prefer site.Title over site.Params.title
- Plainify titles, tags, and descriptions
- Add fallback values for locale
- Fix pages related by series
- Improve readability
Closes #8296
Closes #8698
Closes #8991
Closes #9818
Closes #9866
Closes #10647
> tpl/tplimpl: Improve embedded opengraph template

- resources/page/page_paths.go
- resources/page/path_integration_test.go
When creating a link to a file with a `#` in the filename, the link gets truncated. This happens because the filename is eventaully is passed to `url.Parse` which (correctly!) interprets the `#` as fragment separator.
This commit escapes the `#` in the filename before creating the link.
Fixes #12342
> resources/page: Escape hash sign in permalinks

- hugolib/page__content.go
- hugolib/page_test.go
Since v0.123, Hugo will use the automatic summary generation when the manual summary results in an empty string, even if there is a `` summary divider.
This PR fixes that regression to allow empty summary, restoring the intended functionality and flexibility provided by the manual summary divider.
Note about implementation in v0.122:
<https://github.com/gohugoio/hugo/blob/v0.122.0/hugolib/page__per_output.go#L791>
> hugolib: Fix regression in summary generation behavior since v0.123

- commands/server.go
- helpers/path.go
- hugolib/content_map.go
- hugolib/content_map_page.go
- hugolib/page__meta.go
- langs/i18n/i18n.go
- markup/goldmark/goldmark_config/config.go
- resources/errorResource.go
- testscripts/commands/server.txt
For reference, to find these I used cSpell CLI - running:
`npx cspell \"**/*.*\" --no-progress --quiet`
with the following `.cspell.json` config in the root folder. There are still many false-positives in the comfig I used though.
```json
{
"version": "0.2",
"allowCompoundWords": true,
"flagWords": [
"alot",
"hte",
"langauge",
"reccommend",
"seperate",
"teh"
],
"ignorePaths": [
"**/*.css",
"**/*.ics",
"**/*.jpe",
"**/*.js",
"**/*.md",
"**/*.svg",
"**/*.yaml"
],
"ignoreRegExpList": [
"# cspell: ignore fenced code blocks",
"^(\\s*`{3,}).*[\\s\\S]*?^\\1",
"# cspell: ignore words joined with dot",
"\\w+\\.\\w+",
"# cspell: ignore strings within backticks",
"`.+`",
"# cspell: ignore strings within single quotes",
"'.+'",
"# cspell: ignore strings within double quotes",
"\".+\"",
"# cspell: …
```
> Typo fixes

- commands/server.go
- config/allconfig/allconfig.go
- hugolib/hugo_sites_build.go
Closes #12359
Console after change (single-host site):
```text
Change detected, rebuilding site (#1).
2024-04-13 09:44:27.212 -0700
Source changed /posts/post-1.en.md
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Total in 1 ms
```
Console after change (multihost site):
```text
Change detected, rebuilding site (#1).
2024-04-13 09:45:56.576 -0700
Source changed /posts/post-1.de.md
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) en
Web Server is available at http://localhost:1314/ (bind address 127.0.0.1) de
Web Server is available at http://localhost:1315/ (bind address 127.0.0.1) fr
Web Server is available at http://localhost:1316/ (bind address 127.0.0.1) es
Total in 2 ms
```
> hugolib: Display server address after each rebuild

- hugolib/content_map_page.go
- hugolib/page__content.go
- hugolib/page__meta.go
- hugolib/page__per_output.go
- hugolib/rendershortcodes_test.go
- hugolib/shortcode.go
- markup/converter/converter.go
- markup/converter/hooks/hooks.go
- markup/goldmark/codeblocks/render.go
- markup/goldmark/convert.go
- markup/goldmark/hugocontext/hugocontext.go
- markup/goldmark/hugocontext/hugocontext_test.go
- markup/goldmark/internal/render/context.go
- markup/goldmark/render_hooks.go
- resources/page/pagemeta/page_frontmatter.go
- tpl/template.go
- tpl/tplimpl/embedded/templates/_default/_markup/render-image.html
- tpl/tplimpl/embedded/templates/_default/_markup/render-link.html
The main use case for this is to resolve links and resources (e.g. images) relative to the included `Page`.
A typical `include` would similar to this:
```handlebars
{{ with site.GetPage (.Get 0) }}
{{ .RenderShortcodes }}
{{ end }}
```
And when used in a Markdown file:
```markdown
{{% include "/posts/p1" %}}
```
Any render hook triggered while rendering `/posts/p1` will get `/posts/p1` when calling `.PageInner`.
Note that
* This is only relevant for shortcodes included with `{{%` that calls `.RenderShortcodes`.
* `.PageInner` is available in all render hooks that, before this commit, received `.Page`.
* `.PageInner` will fall back to the value of `.Page` if not relevant and will always have a value.
Fixes https://github.com/gohugoio/hugo/issues/12356
> Pass .RenderShortcodes' Page to render hooks as .PageInner

- common/hstrings/strings.go
- resources/errorResource.go
- resources/image.go
- resources/image_test.go
- resources/images/color.go
- resources/images/color_test.go
- resources/images/config.go
- resources/images/config_test.go
- resources/images/filters.go
- resources/images/image_resource.go
- resources/images/text.go
- resources/transform.go
To sort an image's colors from darkest to lightest, you can then do:
```handlebars
{{ $colorsByLuminance := sort $image.Colors "Luminance" }}
```
**Note:** The sort above will recompute the Luminance over and over again, which is not a particulary costly thing with images (the color slice is small), but the Color type should be something other than a string so we could optimize for this. That can wait, I guess.
Fixes #10450
> Add Luminance to Color

- tpl/tplimpl/embedded/templates/shortcodes/youtube.html
So they can be silenced.
Fixes #12383
> tpl: Use erroridf for remote YouTube errors

- tpl/tplimpl/embedded/templates/_default/rss.xml
- tpl/tplimpl/embedded/templates/shortcodes/youtube.html
- Do not call the YouTube oEmbed API
- Do not include the Hugo version in RSS feeds
Closes #12396
> tpl/tplimpl: Improve embedded templates

- hugolib/content_render_hooks_test.go
- tpl/tplimpl/embedded/templates/_default/_markup/render-image.html
- tpl/tplimpl/embedded/templates/_default/_markup/render-link.html
These templates were added in Hugo v0.123.0, and in the common case disabled by default, see https://gohugo.io/getting-started/configuration-markup/#renderhooksimageenabledefault
> tpl: Escape .Title in built-in image and link render hooks

- tpl/tplimpl/embedded/templates/opengraph.html
- tpl/tplimpl/tplimpl_integration_test.go
- Do not escape HTML entities
- Use consistent formatting for title and description with opengraph, schema, and twitter_cards
- Improve readability of twitter_cards
Closes #12418
> tpl/tplimpl: Fix double-escaping in opengraph template

- hugolib/cascade_test.go
- hugolib/hugo_sites_build.go
- hugolib/page__meta.go
- hugolib/pages_capture.go
- hugolib/rebuild_test.go
And also avoid reading sub directories on simple changes to branch `_index.md` files.
Fixes #12449
> Fix rebuilds on cascade deletes/renames

- hugolib/hugo_sites_build.go
- resources/resource_transformers/tocss/scss/scss_integration_test.go
- resources/transform.go
This is how we should have fixed #1239.
Fixes #12456
> Fix one more resource change eviction logic issue

- go.mod
- go.sum
We have received reports from  users of Hugo's `openapi3.Unmarshal` about breaking behavior in the mentioned `kin-openapi` version, so revert for now, pending further investigation.
> deps: Downgrade github.com/getkin/kin-openapi v0.124.0 => v0.123.0

- tpl/tplimpl/embedded/templates/_default/_markup/render-image.html
- tpl/tplimpl/render_hook_integration_test.go
> tpl/tplimpl: Retain query string and fragment in render-image.html

- hugolib/page__new.go
- hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go
- resources/page/pagemeta/page_frontmatter.go
- **Fix paths with dots issue with content adapters**
- **Fix mixed case Page params handling in content adapters**
> Misc content adapter fixes

- tpl/tplimpl/embedded/templates/_default/_markup/render-image.html
- tpl/tplimpl/embedded/templates/_default/_markup/render-link.html
- tpl/tplimpl/render_hook_integration_test.go
> tpl/tplimpl: Resolve render hook destinations with leading ./

- commands/list.go
- testscripts/commands/gen.txt
- Improve help text
- Add "kind" and "section" to CSV output
- Add a "published" subcommand to list content that is not draft, expired, or future.
Closes #12520
> commands: Improve list command

- hugolib/content_map.go
- hugolib/hugo_sites_build.go
- hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go
> content adapter: Fix server crash on partial edit

- hugolib/page__per_output.go
- hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go
- parser/pageparser/pagelexer.go
- parser/pageparser/pagelexer_intro.go
- parser/pageparser/pageparser.go
- parser/pageparser/pageparser_test.go
> content adapter: Handle <!--more--> separator in content.value

- commands/hugobuilder.go
- hugolib/content_map.go
- hugolib/hugo_sites_build.go
- hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go
* Recover from server errors
* Improve go adapter rebuilds when adding new content
See #12502
Fixes #12570
> Misc remote HTTP/content adapter enhancements

- go.mod
- go.sum
- resources/resource_transformers/js/options.go
- resources/resource_transformers/js/options_test.go
- **deps: Upgrade github.com/evanw/esbuild v0.20.2 => v0.21.4**
- **js: Support more recent targets with js.Build / esbuild**
> Misc js.Build

- config/allconfig/allconfig.go
- config/allconfig/allconfig_integration_test.go
- config/allconfig/alldecoders.go
- config/allconfig/configlanguage.go
- config/allconfig/load.go
- config/commonConfig.go
- config/configProvider.go
- hugolib/site_render.go
- resources/page/pagination.go
Also consolidate the pagination configuration into a struct.
Closes #12572
> Add option to not generate aliases for first page of pagination pages

- hugolib/site_test.go
- resources/page/pagegroup.go
- resources/page/pagegroup_test.go
> resources/page: Let GroupByParam return nil instead of error

- config/allconfig/allconfig.go
- config/allconfig/allconfig_integration_test.go
- config/allconfig/alldecoders.go
- config/commonConfig.go
- resources/page/pagination.go
- resources/page/pagination_test.go
This was recently introduced. so no breaking change.
The thing is:
* We do not commonly use the prefix Default* even if it can be overridden in the templates.
* PagerSize makes more sense and is also the term used in the code.
> Rename DefaultPageSize => PagerSize

- resources/resource_transformers/tocss/dartsass/transform.go
- resources/transform.go
The migration from Embedded Dart Sass to Sass began a little over a year ago. This updates the "not installed" error message to reflect that change.
> resources: Update Dart Sass error message

- commands/hugobuilder.go
This seems to be a browser bug (tested in both Chrome and Safari on MacOS), but it seems that doing a `window.location.reload()` (or `window.location.reload(true)`) doesn't refresh the CSS changes, even if HTTP caching is disabled.
This commit works around this by doing additional refreshes of the CSSes.
Closes #12600
> Fix live reload when both CSS and HTML changes

- docs/data/docs.yaml
- go.mod
- go.sum
- markup/goldmark/convert.go
- markup/goldmark/goldmark_config/config.go
- markup/goldmark/goldmark_integration_test.go
With Goldmark v1.7.1 and earlier, the Goldmark "strikethrough" extension was triggered by wrapping text within a pair of double-tilde characters. With Goldmark v1.7.2 and later, to provide full GFM compatibility, the Goldmark "strikethrough" extension is triggered by wrapping text within a pair of single- or double-tilde characters.
This change created a conflict with the Hugo Goldmark Extras "subscript" extension.
When enabling the Hugo Goldmark Extras "subscript" extension, if you want to render subscript and strikethrough text concurrently, you must:
1. Disable the Goldmark "strikethrough" extension
2. Enable the Hugo Goldmark Extras "delete" extension
Closes #12597
> markup/goldmark: Add the Hugo Goldmark Extras "delete" extension

- hugolib/content_map_page.go
- hugolib/taxonomy_test.go
```text
name                               old time/op    new time/op    delta
TaxonomiesGetTerms/pages_100-10      5.25ms  5%    5.13ms  4%     ~     (p=0.486 n=4+4)
TaxonomiesGetTerms/pages_1000-10     30.1ms  1%    26.8ms  1%  -11.13%  (p=0.029 n=4+4)
TaxonomiesGetTerms/pages_10000-10     1.33s 24%     0.29s  2%  -78.42%  (p=0.029 n=4+4)
TaxonomiesGetTerms/pages_20000-10     5.50s 12%     0.83s 28%  -84.88%  (p=0.029 n=4+4)
name                               old alloc/op   new alloc/op   delta
TaxonomiesGetTerms/pages_100-10      4.08MB  0%    4.06MB  0%   -0.59%  (p=0.029 n=4+4)
TaxonomiesGetTerms/pages_1000-10     25.1MB  0%    24.9MB  0%   -0.87%  (p=0.029 n=4+4)
TaxonomiesGetTerms/pages_10000-10     238MB  2%     233MB  0%   -1.94%  (p=0.029 n=4+4)
TaxonomiesGetTerms/pages_20000-10 …
```
> Speed up GetTerms

- deploy/deploy.go
- deploy/deploy_test.go
- deploy/deployconfig/deployConfig.go
- docs/content/en/hosting-and-deployment/hugo-deploy.md
This new configuration parameter causes paths matching "<dir>/index.html" to be stored as "<dir>/" remotely. This simplifies the cloud configuration needed for some use cases, such as CloudFront distributions with S3 bucket origins. Before this change, users must configure their S3 buckets as public websites (which is incompatible with certain authentication / authorization schemes), or users must add a CloudFormation function to add index.html to the end of incoming requests. After this change, users can simply use an ordinary CloudFront distribution (no additional code) with an ordinary S3 bucket origin (and not an S3 website).
This adds tests to ensure that functionality like matchers is unaffected by this change. I have also tested that the functionality works as expected when …
> deploy: Add stripIndexHtml target option

- common/hexec/exec.go
> common/hexec: Fall back to the binary in PATH if npx fails

- go.mod
- go.sum
Forcing this update now in order to include updated docs with the v0.128.0 release.
> deps: Upgrade github.com/yuin/goldmark-emoji v1.0.2 => v1.0.3

- hugolib/content_map_page.go
- hugolib/dates_test.go
- resources/page/pagemeta/page_frontmatter.go
> Fix it so publishDate rolls up to section, taxonomy, or term pages

- hugolib/pagecollections.go
- hugolib/pagecollections_test.go
> Fix site.GetPage, never do short lookups for paths with leadig slash

- tpl/templates/defer_integration_test.go
- tpl/tplimpl/template_ast_transformers.go
That just doesn't work.
See #12655
> Throw error if resources.PostProcess is used in a deferred template

- docs/content/en/functions/math/Acos.md
- docs/content/en/functions/math/Asin.md
- docs/content/en/functions/math/Atan.md
- docs/content/en/functions/math/Atan2.md
- docs/content/en/functions/math/Cos.md
- docs/content/en/functions/math/Pi.md
- docs/content/en/functions/math/Sin.md
- docs/content/en/functions/math/Tan.md
- docs/content/en/functions/math/ToDegrees.md
- docs/content/en/functions/math/ToRadians.md
- docs/data/docs.yaml
- tpl/math/init.go
- tpl/math/math.go
- tpl/math/math_test.go
Based on top of PR https://github.com/gohugoio/hugo/pull/12660 this adds two simple helper functions than convert between degrees and radians.
The trig functions take arguments in radians (and the inv-trig functions return radians) which is correct from a math perspective. People outside math/engineering contexts tend to think in degrees. Hence we need to convert between the two. These two functions are simple helpers so template authors don't have to think about the correct formulas.
> math: angle helpers

- go.mod
To hopefully resolve dependabot issues.
> deps: Set toolchain go1.21.0 in go.mod

- resources/page/pagegroup_test.go
- resources/resource/resource_helpers.go
Basically just use `maps.GetNestedParam` in `resource.GetParam` and `resource.GetParamToLower`. It only affects the `Pages.GroupByParam` and `Pages.GroupByParamDate` methods since it's only used there. There is no need to check for an error because `maps.GetNestedParam` never returns one. The tests are the same as the not nested version but using a nested field.
Fixes #12289.
> Allow nested params when using Pages.GroupByParam and Pages.GroupByParamDate

- .github/workflows/image.yml
> github: Build and publish Docker image on release

- docs/content/en/functions/transform/Plainify.md
- tpl/transform/transform.go
- tpl/transform/transform_integration_test.go
- tpl/transform/transform_test.go
None of these are useful as plain strings in the templates, which forces the users to do `transform.Plainify "foo" | safeHTML`.
If people have trust issues with the output of these functions, they need to just stop using them.
Closes #8732
> tpl/transform: Make Plainify and ToMath return template.HTML

- hugolib/resource_chain_test.go
- resources/resource_factories/create/remote.go
Previously, only `ERROR failed to fetch remote resource: Forbidden` would be shown when a resource failed to load. In my case, a tweet's author I was embedding using the twitter shortcode switched his profile to private which resulted in my blog failing to build. To figure out where the originates, I added the log to the error message. This should be useful for others too.
> add URI to resource load error

- markup/goldmark/blockquotes/blockquotes.go
- markup/goldmark/blockquotes/blockquotes_integration_test.go
> markup/goldmark/blockquotes: Fix handling of lower/mixed case GitHub alerts

- docs/data/docs.yaml
- output/docshelper.go
> output: Fix docshelper template lookup order for AMP pages

- common/hugo/hugo.go
- common/hugo/hugo_test.go
- common/paths/pathparser.go
- common/types/types.go
- common/types/types_test.go
- helpers/content.go
- helpers/content_test.go
- hugolib/page.go
- hugolib/page__content.go
- hugolib/page__meta.go
- hugolib/page__output.go
- hugolib/page__per_output.go
- hugolib/page_test.go
- hugolib/shortcode_page.go
- hugolib/shortcode_test.go
- resources/page/page.go
- resources/page/page_lazy_contentprovider.go
- resources/page/page_markup.go
- resources/page/page_markup_integration_test.go
- resources/page/page_markup_test.go
- resources/page/page_nop.go
- resources/page/testhelpers_test.go
Edit in 2024-08-16. I have revised my take on this after talking to @jmooring and thinking a little. The (original) primary motivation behind this PR (for me, anyway) was to make it possible to render different versions of a given page's content on, say, the home page. But we also want to make room for further improvements in this area without blowing the scope of this PR out of proportions. I have always wanted to create a map of the rendered content, but that would only be practical for Goldmark (and hard even there, I guess). I think that and similar extensions should be fairly simple to fit in the below.
* I have added `ContentWithoutSummary`, which I know many have asked for
* I have reduced the amount of name changes; `FuzzyWordCount` has been around for a decade and has become a …
> Add Page.Markup with scope support

- tpl/tplimpl/embedded/templates/google_analytics.html
"Editorial" change only: from `{{ ... }}` to `{{- ... }}`, to trim template action trailing whitespace.
> [editorial] google_analytics.html: trim trailing whitespace from tpl actions

- tpl/resources/resources.go
This PR corrects the deprecation warning for resources.ToCSS, where `css.Sass` is spelled incorrectly:
Actual: `css.SASS`
Correct: `css.Sass`
> Fix deprecation warning for resources.ToCSS

- docs/content/en/render-hooks/blockquotes.md
- markup/converter/hooks/hooks.go
- markup/goldmark/blockquotes/blockquotes.go
- markup/goldmark/blockquotes/blockquotes_integration_test.go
- markup/goldmark/blockquotes/blockquotes_test.go
* Make the alert type parsing more flexible to support more types
* Add `AlertTitle` and `AlertSign` (for folding)
Note that GitHub will not render callouts with alert title/sign.
See https://help.obsidian.md/Editing+and+formatting/Callouts
Closes #12805
Closes #12801
> Add support for Obsidian type blockquote alerts

- Dockerfile
updates the Go version in the Dockerfile from 1.21.13 to 1.22.6 to resolve compatibility issues with the go.mod requirements.
> Update Go Version to 1.22.6 in Dockerfile

- commands/commandeer.go
- commands/config.go
- commands/hugobuilder.go
- commands/mod.go
- commands/new.go
- config/allconfig/allconfig.go
- config/allconfig/load.go
- modules/client.go
- modules/collect.go
- testscripts/commands/mod_init.txt
- **commands: Ignore "module does not exist" errors in hugo mod init**
- **modules: Improve console output on hugo mod init**
> Misc module improvements

- config/allconfig/allconfig_integration_test.go
- hugolib/config_test.go
- hugolib/embedded_templates_test.go
- hugolib/hugo_sites_multihost_test.go
- hugolib/hugo_smoke_test.go
- hugolib/paginator_test.go
- hugolib/rebuild_test.go
- hugolib/securitypolicies_test.go
- hugolib/shortcode_test.go
- hugolib/site_output_test.go
- hugolib/site_sections_test.go
- hugolib/site_stats_test.go
- hugolib/site_url_test.go
- hugolib/taxonomy_test.go
- hugolib/template_test.go
- hugolib/testhelpers_test.go
- resources/resource_transformers/tocss/scss/scss_integration_test.go
- tpl/page/page_integration_test.go
Prior to this PR our tests were throwing these errors and warnings:
```text
ERROR deprecated: .Site.Author was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Use taxonomies instead.
ERROR deprecated: .Site.Authors was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Use taxonomies instead.
ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Use hugo.IsMultilingual instead.
ERROR deprecated: .Site.RSSLink was deprecated in Hugo v0.114.0 and will be removed in Hugo 0.137.0. Use the Output Format's Permalink method instead, e.g. .OutputFormats.Get "RSS".Permalink
ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Use .Site.Params instead.
WARN …
```
> tests: Address deprecation warnings and errors

- markup/goldmark/tables/tables.go
- markup/goldmark/tables/tables_integration_test.go
- tpl/tplimpl/embedded/templates/_default/_markup/render-table.html
Change the default table cell alignment from "left" to an empty string.
Closes #12886
> markup/goldmark: Change default cell alignment in table render hook

- resources/page/pagemeta/page_frontmatter.go
- resources/page/pagemeta/pagemeta_integration_test.go
Improve the error message and treat empty strings as zero dates.
Closes #12898
> resources/page: Improve front matter date validation

- tpl/tplimpl/embedded/templates/opengraph.html
- tpl/tplimpl/embedded/templates/schema.html
- tpl/tplimpl/embedded/templates/twitter_cards.html
This PR proposes that we trim whitespace from both ends of descriptions rather than just chomp.
A bit of context for this change: since upgrading to Hugo 0.135.0, opentelemetry.io many page descriptions have been padded with (IMHO unnecessary) whitespace. If the Hugo templates are `chomp`ing the description text, it might as well just `trim` both ends of any whitespace, right? :) 
/cc @svrnm @theletterf
> tpl/tplimpl: trim descriptions rather than just chomp

- .circleci/config.yml
- .github/workflows/image.yml
- Dockerfile
- scripts/docker/entrypoint.sh
- scripts/docker/install_runtimedeps_default.sh
As to the Docker image adjustments, I have tested OK:
On MacOS, an example build line would be:
```
docker run --rm -v .:/project -v $HOME/Library/Caches/hugo_cache:/cache imagename build
```
Starting the server:
```
docker run --rm -v .:/project -v $HOME/Library/Caches/hugo_cache:/cache imagename server --bind="0.0.0.0"
```
This is the entry point file:
```sh
#!/bin/sh
if [ -f hugo-docker-entrypoint.sh ]; then
sh hugo-docker-entrypoint.sh "$@"
exit $?
fi
if [ -f package.json ]; then
if [ ! -d node_modules ]; then
npm i
fi
fi
exec "hugo" "$@"
```
If a custom `hugo-docker-entrypoint.sh` script exists in the root of the Hugo project, that script will be executed instead of the default entrypoint script.
> Misc Docker + Go version upgrade

- hugolib/site.go
As suggested in #12269, this updates this deprecation warning:
> WARN  deprecated: .Site.Author was deprecated in Hugo v0.124.0 and will be removed in a future release. **Use taxonomies instead.**
to instead say
> WARN  deprecated: .Site.Author was deprecated in Hugo v0.124.0 and will be removed in a future release. **Implement taxonomy 'author' or use .Site.Params.Author instead.**
I just needed to fix this and found the clarification in that issue very helpful, so thought it would be useful if those were the official guidelines. 
Fixes #12269
> hugolib: Make .Site.Author deprecation warning clearer

- commands/commandeer.go
- commands/config.go
- commands/convert.go
- commands/deploy.go
- commands/env.go
- commands/gen.go
- commands/import.go
- commands/list.go
- commands/mod.go
- commands/new.go
- commands/server.go
- testscripts/commands/config.txt
- testscripts/commands/convert.txt
- testscripts/commands/deploy.txt
- testscripts/commands/gen.txt
- testscripts/commands/import_jekyll.txt
Adapting to language suggested in - (#12897)
Change-Id: Ib27a4a7b540d45243e6252db769d4b9fb7447718
> commands: Use consistent style when describing subcommands

- resources/page/permalinks.go
- resources/page/permalinks_test.go
Fixes #12918. I didn't improve the error handling because the go date formatting tokens are supported. If you have something like `:example1` it would be a valid format since 1 is the number of the month. I think leaving the invalid token error as is is better.
> Add support for backslash escaping in url and permalinks

- resources/page/permalinks.go
- resources/page/permalinks_integration_test.go
> Remove erroneously permalink validation

- resources/page/page_paths.go
- resources/page/permalinks_integration_test.go
> Never sanitize when set in front matter

- commands/commandeer.go
- commands/server.go
- deps/deps.go
- hugolib/integrationtest_builder.go
Including all the integration tests.
> Make sure that HugoSites is always closed when done

- Dockerfile
I think the `--link` option might've caused a permission issue for the non-root `hugo` user.
Related issues:
- #12970
- #12971
Also noticed that the `/project` workdir was created before we assumed the `hugo:hugo` user, which resulted in that directory being owned by `root`. I reordered the instructions to make sure `/project` is owned by the correct user.
> docker: fix permission issues in Dockerfile

- common/constants/constants.go
- hugolib/collections_test.go
- hugolib/content_map_page.go
- hugolib/integrationtest_builder.go
- hugolib/menu_test.go
- hugolib/page.go
- hugolib/rendershortcodes_test.go
- hugolib/shortcode_page.go
- hugolib/site.go
- lazy/init.go
- lazy/once.go
- markup/goldmark/convert.go
- markup/goldmark/goldmark_integration_test.go
- markup/goldmark/hugocontext/hugocontext.go
- markup/goldmark/hugocontext/hugocontext_test.go
- resources/page/page.go
- resources/page/page_markup_integration_test.go
Closes #12854
Some more notes/tests:
> Misc fixes and improvements

- commands/deploy.go
- commands/deploy_flags.go
- commands/deploy_off.go
- common/hugo/vars_withdeploy.go
- common/hugo/vars_withdeploy_off.go
- common/hugo/version.go
- hugoreleaser.toml
- main_withdeploy_off_test.go
- markup/goldmark/goldmark_integration_test.go
- markup/goldmark/hugocontext/hugocontext.go
- testscripts/withdeploy-off/deploy_off.txt
- **commands: Print the "deploy not available" error message even if flags provided**
- **build: Add missing withdeploy archive for Windows**
- **markup: Goldmark log "Raw HTML omitted" warning also for inline HTML**
> Misc 0.137.0 fixes

- commands/commandeer.go
- common/hugo/hugo_test.go
- config/allconfig/allconfig.go
- hugolib/page__common.go
- hugolib/page__meta.go
- hugolib/page__new.go
- hugolib/site.go
- resources/page/page.go
- resources/page/page_nop.go
- resources/page/site.go
- resources/page/testhelpers_test.go
- source/fileInfo.go
- tpl/collections/collections.go
- tpl/collections/collections_test.go
- tpl/collections/init.go
- tpl/lang/lang.go
These have, once we release this, been logging ERROR for 6 minor versions.
> Remove deprecations <= v0.122.0 (note)

- resources/resource_transformers/cssjs/postcss_integration_test.go
- resources/resource_transformers/tocss/dartsass/client.go
> dartsass: Fix nilpointer on Close when Dart Sass isn't installed

- common/maps/scratch_test.go
This PR refactors `TestScratchSetInMap` and `TestScratchDeleteInMap`:
- `scratch.GetSortedMapValues` returns `any`, so the type of the value to compare was changed to `any`.
- Removed unnecessary indexes `0:`, `1:`, `2:` in the slice initializer as they don't add much to readability.
> common/maps: Simplify TestScratchSetInMap/DeleteInMap

- commands/commandeer.go
- commands/list.go
- common/loggers/handlerterminal.go
- common/loggers/logger.go
- common/loggers/logger_test.go
- deps/deps.go
- hugolib/integrationtest_builder.go
- hugolib/site.go
- modules/client.go
- testscripts/commands/deprecate.txt
- testscripts/commands/hugo__configdir.txt
- testscripts/commands/hugo__path-warnings.txt
- testscripts/commands/hugo_printpathwarnings.txt
- testscripts/commands/hugo_printunusedtemplates.txt
- testscripts/commands/warnf_stderr.txt
The old setup tried to log >= warning to stderr, the rest to stdout.
However, that logic was flawed, so warnings ended up in stdout, which makes `hugo list all` etc. hard to reason about from scripts.
This commit fixes this by making all logging (info, warn, error) log to stderr and let stderr be reserved for program output.
Fixes #13074
> Write all logging to stderr

- resources/resource.go
- resources/resource/resourcetypes.go
- resources/resource_spec.go
- resources/transform.go
- tpl/collections/collections_integration_test.go
- tpl/collections/reflect_helpers.go
> Fix union, complement, symdiff, and intersect for transient resources

- internal/js/esbuild/resolve.go
- resources/resource_transformers/js/js_integration_test.go
> js/esbuild: Don't try to resolve packages in /assets marked as external

- docs/content/en/hosting-and-deployment/hugo-deploy.md
- go.mod
- go.sum
While trying to follow the docs, [Configuring your first
deployment](https://gohugo.io/hosting-and-deployment/hugo-deploy/#configuring-your-first-deployment) gives an
example of using an S3-Compatible endpoint. I could not get this to work with the current codebase.
[gocloud 0.40.0](https://github.com/google/go-cloud/releases/tag/v0.40.0) released on 2024-10-10 includes a
bugfix https://github.com/google/go-cloud/pull/3473 which allows specifying a custom endpoint in an s3 url to
publish to an s3-compatible service, such as MinIO as was linked in that PR
https://github.com/minio/docs/issues/406#issuecomment-1246316964.
I updated the docs to include an s3 URL that works with the updated gocloud library (tested against my MinIO
instance) with example parameters.
Resolves …
> Update gocloud and docs for S3-Compatible Endpoints

- markup/highlight/config.go
- markup/highlight/highlight.go
- markup/highlight/highlight_integration_test.go
The need comes from Tailwind's typography plugin. There's currently no way to turn that off outside of the markup, see https://github.com/tailwindlabs/tailwindcss-typography/pull/363
> markup/highlight: Add wrapperClass option

- hugofs/rootmapping_fs.go
- resources/resource_cache.go
- resources/resource_factories/create/create.go
- testscripts/commands/hugo__path-warnings_issue13164.txt
This may still happen, though, in low memory situations or very big sites, but I'm not sure it's worth spending time on fixing that. Writing the same file more than once isn't harmful, the negative effect is the false path warning. We may find a way to detect that situtation if this becomes a real problem.
Fixes #13164
> Fix same resource file published more than once

- config/allconfig/allconfig.go
- config/allconfig/allconfig_integration_test.go
> config/allconfig: Throw error when output format is not defined

- commands/gen.go
When I was playing around generating chromastyles, I forgot what style I was using during generation. `hugo gen chromastyles [flags] [args]` doesn't print any information about how the styles were generated, which would be beneficial to know.
This pull request prints a comment above the generated css styles showing the cli usage during the chromastyles generation.
Now it ouputs like
```console
$ ./hugo gen chromastyles --style=catppuccin-macchiato
/* Generated using: hugo gen chromastyles --style=catppuccin-macchiato */
/* Background */ .bg { color:#cad3f5;background-color:#24273a; }
/* PreWrapper */ .chroma { color:#cad3f5;background-color:#24273a; }
...
```
> Print cli usage of `hugo gen chromastyles` alongside css

- markup/highlight/config.go
- markup/highlight/highlight.go
- markup/internal/attributes/attributes.go
Closes #9885
We have excluded this option from the documentation for years because all it does is negate `guessSyntax`. And we should consider removing that too (separate issue) because only a handful of lexers provide an Anaylzer.
> markup/highlight: Remove noHl option

- common/hashing/hashing.go
- resources/resource_factories/create/create.go
E.g. when the targetPath already contains a hash or if the resource content is expensive to create.
> resources: Add FromOpts for more effective resource creation

- common/hexec/exec.go
- config/allconfig/load.go
- deps/deps.go
- hugolib/integrationtest_builder.go
- hugolib/testhelpers_test.go
- markup/asciidocext/convert_test.go
- markup/pandoc/convert_test.go
- markup/rst/convert_test.go
- modules/client_test.go
This allows the `tailwindcss` CLI binary to live in the `PATH` for NPM-less projects.
Fixes #13221
> Fix NPX issue with TailwindCSS v4

- docs/content/en/functions/images/Text.md
- resources/images/filters.go
- resources/images/text.go
**_Please note that this is my first contribution to Hugo and also the first time I wrote something in Go. Please let me know if I missed anything and I will try my best to correct it._**
Add an "alignx" option to the images.Text to control whether the value of the "x" option is the left border of the text (current behaviour), the center of each line or the right border.
Fixes #10849
Example with `"alignx" "left"`:
Example with `"alignx" "center"`:
Example with `"alignx" "right"`:
> images.Text: Add option for horizontal alignment

- hugolib/content_render_hooks_test.go
- tpl/tplimpl/embedded/templates/_default/_markup/render-image.html
- tpl/tplimpl/render_hook_integration_test.go
I disabled the Goldmark typographer extension in the affected tests to make the results easier to reason about.
> tpl/tplimpl: Use plain text for image render hook alt attribute

- common/hashing/hashing_test.go
- go.mod
- go.sum
Faster hashing of maps:
```
│ stash.bench  │      deps-hashstructv030.bench      │
│    sec/op    │    sec/op     vs base               │
HashMap-10   198.9µ ± ∞ ¹   142.6µ ± ∞ ¹  -28.31% (p=0.029 n=4)
¹ need >= 6 samples for confidence interval at level 0.95
│  stash.bench  │      deps-hashstructv030.bench       │
│     B/op      │     B/op       vs base               │
HashMap-10   92.38Ki ± ∞ ¹   37.14Ki ± ∞ ¹  -59.80% (p=0.029 n=4)
¹ need >= 6 samples for confidence interval at level 0.95
│ stash.bench  │      deps-hashstructv030.bench      │
│  allocs/op   │  allocs/op    vs base               │
HashMap-10   6.747k ± ∞ ¹   4.748k ± ∞ ¹  -29.63% (p=0.029 n=4)
```
> deps: Upgrade github.com/gohugoio/hashstructure from 0.1.0 to 0.3.0

- config/allconfig/allconfig.go
- hugolib/content_render_hooks_test.go
- hugolib/page__per_output.go
- hugolib/rebuild_test.go
> For render hooks, only fallback to HTML (or the defaultOutputFormat) template

- commands/config.go
Will include zero config values (e.g. "", 0, false) in the output and will be more verbose, but useful if you cant to discover all available config options.
> commands: Add --printZero to the config command

- tpl/tplimpl/embedded/templates/shortcodes/qr.html
All images shortcodes should have a loading attribute (for example for lazy).
> Add loading attribute

- common/hugio/hasBytesWriter_test.go
- common/hugo/hugo.go
Go 1.24 provides stricter checking that forbids passing a variable as a format string to Printf-family functions with no other arguments. Remove instances of this. See also:
https://tip.golang.org/doc/go1.24#vet
> Fix build with Go 1.24

- markup/goldmark/goldmark_integration_test.go
- markup/goldmark/hugocontext/hugocontext.go
We will still not render these comments, so from a safety perspective this is the same, but HTML comments are very common also inside Markdown and too useful to throw away.
Updates #13278
> Do not warn on potentially unsafe HTML comments when unsafe=false

- markup/goldmark/internal/render/context.go
Thanks for #13289! I found a typo while looking it over.
> [editorial] Fix typo in context.go func comment

- resources/resource_factories/create/create_integration_test.go
- resources/resource_factories/create/remote.go
* These response headers will be included in `.Data.Headers` if found.
* The header name matching is case insensitive.
* `Data.Headers` is of type `map[string][]string`
* In most cases there will be only one value per header key, but e.g. `Set-Cookie` commonly has multiple values.
Fixes #12521
> resources: Add responseHeaders option to resources.GetRemote

- tpl/tplimpl/embedded/templates/shortcodes/gist.html
- tpl/tplimpl/shortcodes_integration_test.go
> tpl/tplimpl: Deprecate gist shortcode

- parser/pageparser/pagelexer_shortcode.go
- parser/pageparser/pageparser_shortcode_test.go
Previously, the following self-closing shortcode syntax was incorrectly allowed:
{{% sc / param %}}
Only allow parameters before the self-closing tag
---------------------------------------------------
After some iterations, I believe I found the "intended" solution to this problem (I hope 😅).
Let me know if more tests/changes are needed. Thank you for your work on this project!
> parser/pageparser: Don't allow parameters after closing tag in shortcodes

- commands/hugobuilder.go
- commands/server.go
- common/types/evictingqueue.go
- common/types/evictingqueue_test.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/integrationtest_builder.go
- hugolib/page__paths.go
- hugolib/page__per_output.go
- hugolib/rebuild_test.go
- hugolib/site_render.go
The failing test case here is
* A custom search output format defined on the home page, marked as `noAlternative` and not `permalinkable`
* In fast render mode, when making a change to a data source for that search output format, the JSON file was not refreshed.
There are variants of the above, but the gist of it is:
* The change set was correctly determined, but since the search JSON file was not in the recently visited browser stack, we skipped rendering it.
Running with `hugo server --disableFastRender` would be a workaround for the above.
This commit fixes this by:
* Adding a check for the HTTP request header `Sec-Fetch-Mode = navigation` to the condition for if we should track server request as a user navigation (and not e.g. a HTTP request for a linked CSS stylesheet).
* Making sure …
> Fix some server rebuild issues for non-HTML custom output formats

- tpl/tplimpl/embedded/templates/shortcodes/youtube.html
- tpl/tplimpl/shortcodes_integration_test.go
Hi! Coming from issue opened in my theme, there is an issue rendering `youtube` shortcode if it is nested in another shortcode in `{{% %}}` mode. `youtube` shortcode outputs a leading whitespace, which is then rendered as a blockquote.
Thanks
> tpl/tplimpl: Remove leading whitespaces produced by Youtube shortcode

- hugolib/site.go
This can lead to stale aliases when rebuilding, but that's a trade-off we need to take for snappier rebuilds on bigger sites.
Note that it should be possible to detect alias changes, but I'm not sure it's worth it.
> Don't re-render aliases on server rebuilds

- cache/dynacache/dynacache.go
- cache/dynacache/dynacache_test.go
- hugolib/content_map_page.go
- hugolib/hugo_sites_build.go
- identity/identity.go
- resources/resource_factories/bundler/bundler.go
Two issues:
1. Fixe potential edit-loop in server/watch mode (see below)
2. Drain the cache eviction stack before we start calculating the change set. This should allow more fine grained rebuilds for bigger sites and/or in low memory situations.
The fix in 6c68142cc1338640e2bfe2add661a7b4d7bee6ab wasn't really fixing the complete problem.
In Hugo we have some steps that takes more time than others, one example being CSS building with TailwindCSS.
The symptom here is that sometimes when you:
1. Edit content or templates that does not trigger a CSS rebuild => Snappy rebuild.
2. Edit stylesheet or add a CSS class to template that triggers a CSS rebuild => relatively slow rebuild (expected)
3. Then back to content editing or template edits that should not trigger a CSS rebuild => relatively …
> Fix some server/watch rebuild issues

- hugolib/content_map_page.go
This is a follow up to db28695ff505f84aee69c72dcc9e192f674c86a1 -- that commit dropped the cache items evicted in the LRU process. This was done as performance optimization for large Hugo sites.
That made much sense, but now there's a slight chance that we miss out on a change when rebuilding.
This commit fixes this by applying the same logic to the evicted items as if they were still in the cache. This should preserve the performance gains in db28695ff505f84aee69c72dcc9e192f674c86a1 and close the hole for the possible false negatives.
> Re-introduce the LRU-evicted identities in change set calculation

- magefile.go
This PR refactors `magefile.go`:
- Removed unused `Lint()`.
- Remove outdated for Go 1.22 build tag `// +build mage`.
- Removed `os.Setenv("GO111MODULE", "on")` as it is no longer relevant for Go 1.22.
- Removed `isCi` because `isCI` already exists.
- Used `sync.OnceValues` instead of `sync.Once`.
- Moved `isDarwin` right after `isUnix`.
- Moved `docker` global var to the `Docker` function.
- Replace `f.Write([]byte` with `f.WriteString`.
> mage: simplify magefile

- commands/server.go
- config/commonConfig.go
- config/commonConfig_test.go
New options:
* `FromHeaders`: Server header matching for redirects
* `FromRe`: Regexp with group support, i.e. it replaces $1, $2 in To with the group matches.
Note that if both `From` and `FromRe` is set, both must match.
Also
* Allow redirects to non HTML URLs as long as the Sec-Fetch-Mode is set to navigate on the request.
* Detect and stop redirect loops.
This was all done while testing out InertiaJS with Hugo. So, after this commit, this setup will support the main parts of the protocol that Inertia uses:
```toml
[server]
[[server.headers]]
for = '/**/inertia.json'
[server.headers.values]
Content-Type = 'text/html'
X-Inertia    = 'true'
Vary         = 'Accept'
[[server.redirects]]
force       = true
from        = '/**/'
fromRe      = "^/(.*)/$"
fromHeaders = { "X-Inertia" = "true" } …
```
> Add some more server options/improvements

- commands/deploy.go
- commands/deploy_off.go
- common/hugo/vars_extended.go
- common/hugo/vars_regular.go
- common/hugo/vars_withdeploy.go
- common/hugo/vars_withdeploy_off.go
- deploy/cloudfront.go
- deploy/deploy.go
- deploy/deploy_azure.go
- deploy/deploy_test.go
- deploy/deployconfig/deployConfig_test.go
- deploy/google.go
- main_withdeploy_off_test.go
- main_withdeploy_test.go
- resources/image_extended_test.go
- resources/images/webp/webp.go
- resources/images/webp/webp_notavailable.go
- resources/resource_transformers/tocss/scss/client_extended.go
- resources/resource_transformers/tocss/scss/client_notavailable.go
- resources/resource_transformers/tocss/scss/tocss.go
This PR removes outdated in Go 1.22 `// +build` comments by running the command:
```
go fix -fix buildtag ./...
```
Changes to `tpl/internal/go_templates` were not made.
From https://pkg.go.dev/cmd/go#hdr-Build_constraints:
> Go versions 1.16 and earlier used a different syntax for build constraints, with a "// +build" prefix. The gofmt command will add an equivalent //go:build constraint when encountering the older syntax.
> chore: Remove deprecated build tags

- common/hreflect/helpers.go
- config/allconfig/allconfig.go
- config/allconfig/allconfig_integration_test.go
- config/allconfig/alldecoders.go
- config/allconfig/configlanguage.go
- hugolib/content_map_test.go
- media/config.go
- media/mediaType_test.go
- parser/lowercase_camel_json.go
- resources/page/page_nop.go
- source/fileInfo.go
- tpl/reflect/reflect.go
This is an empty struct for now, but we will most likely expand on that.
```
[contentTypes]
[contentTypes.'text/markdown']
```
The above means that only Markdown will be considered a content type. E.g. HTML will be treated as plain text.
Fixes #12274
> Add ContentTypes to config

- parser/metadecoders/decoder.go
- parser/metadecoders/decoder_test.go
This adds support for filetags by slicing them according to [the org mode tag specification](https://orgmode.org/guide/Tags.html).
Can be used to create taxonomies based on org-mode tags
> parser: handle org-mode filetags as slice

- commands/gen.go
- commands/mod.go
- commands/release.go
- commands/server.go
- testscripts/commands/hugo__errors.txt
This is in support of the documentation site. Currently the short description may or may not end with a period. This removes trailing periods, consistent with help for main command.
> commands: Use punctuation consistently in short description

- config/commonConfig.go
Tiny fix: server.redirects.fromRe was being ignored unless server.redirects.from was also set.
> fix server.redirects.fromRe being ignored unless server.redirects.from set

- markup/goldmark/autoid.go
- markup/goldmark/autoid_test.go
- markup/goldmark/convert.go
- markup/goldmark/goldmark_config/config.go
- markup/goldmark/internal/extensions/attributes/attributes.go
- markup/goldmark/internal/extensions/attributes/attributes_integration_test.go
- markup/goldmark/toc.go
- markup/markup_config/config.go
- markup/tableofcontents/tableofcontents.go
> Add autoID for definition terms

- markup/goldmark/render_hooks.go
- markup/goldmark/toc_integration_test.go
> markup/goldmark: Fix panic on empty Markdown header

- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
This issue was introduced recently in eb7a5aabaaa025b6633b4aff3267b21ebdffb8e9.
Fixes #13420
> Fix --printPathWarnings when site calls templates.Defer

- hugolib/page__meta.go
We effectively aliased "_build" to "build" in v0.123.0, and removed "_build" from the documentation at the same time.
> hugolib: Deprecate _build front matter key in favor of build

- README.md
Make relative gohugo.io links used in Editions section of README absolute so that they resolve successfully.
> readme: Fix relative links in Editions section

- go.mod
- go.sum
- tpl/transform/transform.go
- tpl/transform/transform_integration_test.go
Using this in a content adapter could look like this:
```handlebars
{{ $projectID := "<myproject>" }}
{{ $useCached := true }}
{{ $api := "api" }}
{{ if $useCached }}
{{/* See https://www.sanity.io/docs/api-cdn */}}
{{ $api = "apicdn" }}
{{ end }}
{{ $url := printf "https://%s.%s.sanity.io/v2021-06-07/data/query/production"  $projectID $api }}
{{/* prettier-ignore-start */ -}}
{{ $q :=  `*[_type == 'post']{
title, publishedAt, summary, slug, body[]{
...,
_type == "image" => {
...,
asset->{
_id,
path,
url,
altText,
title,
description,
metadata {
dimensions {
aspectRatio,
width,
height
}
}
}
}
},
}`
}}
{{/* prettier-ignore-end */ -}}
{{ $body := dict "query" $q | jsonify }}
{{ $opts := dict "method" "post" "body" $body }}
{{ $t := debug.Timer "sanity.get" }}
{{ $r := resources.GetRemote …
```
> Add transform.PortableText

- tpl/tplimpl/embedded/templates/shortcodes/instagram.html
- tpl/tplimpl/shortcodes_integration_test.go
This JavaScript will always load over HTTPS so it's best to specify that. Protocol-less loaded resources are an anti-pattern (REF: https://www.paulirish.com/2010/the-protocol-relative-url/)
> tpl: HTTPS the instagram Shortcode JS

- common/paths/pathparser_test.go
- hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go
- resources/page/pages_sort.go
This should:
1. Fix some (rare) tiebreaker issues when sorting pages from multiple content adapters.
2. Improve the sorting for pages without a backing file.
> Use the page path and not the backing filename as the last resort in the default sort

- .github/workflows/image.yml
This PRs adds one variant of the functionality proposed in #13435: 
The Image is built using the "withdeploy" build tag, enabling deploy capability in all containers.
> build docker images with deploy capability

- resources/images/imagetesting/testing.go
See output of `grep FMADD go/test/codegen/floats.go`. This can also be found in the LoongArch Reference Manual: https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html#_fmaddmsubnmaddnmsub_sd
> Mark loong64 as FMA-using architecture

- cache/httpcache/httpcache.go
- cache/httpcache/httpcache_test.go
Previously, compiling the config with partial or missing poll configs
would introduce a panic. This ensures that the default poll configs
are applied in such scenarios.
Fixes #13471
> cache: apply httpcache defaults for polling config

- commands/gen.go
The [revised docs structure](https://github.com/gohugoio/hugoDocs/issues/2996) should go live within the next week or two.
> commands/gen: Set url in command pages to /docs/reference/commands/

- identity/finder.go
Faster:
```
Finder/Find_one-10    172.8n ± 26%   129.3n ± 2%  -25.18% (p=0.002 n=6)
Finder/Find_none-10   174.0n ±  1%   130.6n ± 0%  -24.94% (p=0.002 n=6)
```
> identity: Use clear to clear the finder seen map

- parser/metadecoders/decoder.go
- parser/metadecoders/decoder_test.go
Previously, the XML decoder would panic when encountering a root element with a non-map value due to an unsafe type assertion.
The fix adds proper type checking before the map conversion and provides clear error messages to help users identify and fix invalid XML structures.
Example error for invalid XML like:
<root>just text</root>
Will now return:
"XML root element 'root' must be a map/object, got string"
> fix(decoder): handle non-map XML root values safely

- common/hreflect/helpers.go
- common/hreflect/helpers_test.go
It's much faster when running in parallel:
```
GetMethodByName-10        125.1n ± 6%   181.7n ± 7%  +45.30% (p=0.002 n=6)
GetMethodByNamePara-10   770.10n ± 1%   24.77n ± 9%  -96.78% (p=0.002 n=6)
```
> common/hreflect: Replace the map/RWMutex method cache with sync.Map

- tpl/time/init.go
- tpl/time/time.go
- tpl/time/time_test.go
Closes #13548
As expected, caching makes a big difference:
```text
cpu: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
BenchmarkInWithCaching-12                6309938               288.7 ns/op            16 B/op          1 allocs/op
BenchmarkInWithoutCaching-12              169425              6789 ns/op            3742 B/op          7 allocs/op
```
> tpl/time: Add time.In function

- common/hugo/hugo.go
- config/allconfig/allconfig.go
To prevent warnings leaking into parallel tests.
> config: Use the non-global logger for deprecations when possible

- common/maps/cache.go
- hugolib/alias.go
- hugolib/page.go
- hugolib/page__common.go
- hugolib/page__new.go
- hugolib/page__per_output.go
- hugolib/shortcode.go
- resources/page/page.go
- resources/page/pages_related.go
- tpl/tplimpl/templatestore.go
- tpl/tplimpl/templatestore_integration_test.go
```
│ stash.bench  │          perf-v146.bench           │
│    sec/op    │   sec/op     vs base               │
LookupPartial-10   248.00n ± 0%   14.75n ± 2%  -94.05% (p=0.002 n=6)
│ stash.bench │          perf-v146.bench          │
│    B/op     │   B/op     vs base                │
LookupPartial-10    48.00 ± 0%   0.00 ± 0%  -100.00% (p=0.002 n=6)
│ stash.bench │          perf-v146.bench           │
│  allocs/op  │ allocs/op   vs base                │
LookupPartial-10    3.000 ± 0%   0.000 ± 0%  -100.00% (p=0.002 n=6)
```
THe speedup above assumes reuse of the same partials over and over again, which I think is not uncommon.
This commits also adds some more lookup benchmarks. The current output of these on my MacBook looks decent:
```
BenchmarkLookupPagesLayout/Single_root-10 …
```
> tpl: Add a partial lookup cache

- hugolib/site.go
- tpl/tplimpl/templatestore.go
- tpl/tplimpl/templatestore_integration_test.go
> tpl: Warn and skip non-hook templates inside /layouts/_markup

- common/paths/pathparser.go
- hugolib/content_map_page.go
- tpl/tplimpl/templatestore.go
- tpl/tplimpl/templatestore_integration_test.go
We now use the same code path for all templates re this.
Fixes #13612
> tpl: Fix language handling in partials

- docs/data/docs.yaml
- hugolib/page__meta.go
- markup/goldmark/convert.go
- markup/goldmark/goldmark_config/config.go
- markup/goldmark/goldmark_integration_test.go
- markup/markup_config/config.go
- markup/markup_config/config_test.go
This commit introduces a new option, `enableAutoIDPrefix`, to the Goldmark footnote extension. When enabled, it prepends a unique prefix to footnote IDs, preventing clashes when multiple documents are rendered together. This prefix is unique to each logical path, which means that the prefix is not unique across content dimensions such as language. This change also refactors the extension's configuration from a boolean to a struct.
Closes #8045
> markup/goldmark: Enhance footnote extension with auto-prefixing option

- go.mod
- go.sum
- tpl/transform/transform.go
- tpl/transform/transform_integration_test.go
> Add transform.HTMLToMarkdown

- testscripts/commands/server.txt
- transform/livereloadinject/livereloadinject.go
- transform/livereloadinject/livereloadinject_test.go
building hugo site with root index.html that serves react app with react-router-dom that contains menu, header, footer and breadcrump and other pages that are build inside`internal` folder that contain only parts of html bodies that are expected to be rendered inside root react app body and livereload.js script is not expected to be injected inside these parts. added condition that ignores injection of livereload.js is no relevant tags found
> skip livereload.js injection if no tags found

- hugolib/content_map_page.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/site.go
Mostly to reduce the amount of OSC 9;4 sequences written to stdout.
> Adjust the terminal progress reporter a little
