- hugolib/menu_test.go
This reverts commit e4a22255ccb818f8b55a20f56ddcfda869db250f.
> Revert "Temporarily disable failing menu test"

- hugolib/shortcode.go
- hugolib/shortcode_test.go
> Fix issue with nested shortcodes

- commands/new.go
- Add copyright years and author to the top of the file
- Write the current year from time.Now() to LICENSE.md
- Update theme.toml template to match that listed at https://github.com/spf13/hugoThemes/blob/master/README.md#themetoml
- Correct comment regarding `os.MkdirAll(p, 0777)`
- In createConfig(), split the `map[string]string` definition into multiple lines to facilitate future expansion.  Also add a trailing slash to sample "baseurl" definition.
----
Initially, I experimented with expanding the original `map[string]interface{}`:
```go
in := map[string]interface{}{
"name":        strings.Title(helpers.MakeTitle(filepath.Base(inpath))),
"license":     "MIT",
"licenselink": "",
"description": "",
"homepage":    "",
"tags":        []string{"", ""},
"features":    []string{"", ""}, …
```
> [commands/new.go] Update theme.toml etc.

- commands/benchmark.go
- commands/check.go
- commands/convert.go
- commands/hugo.go
- commands/list.go
- commands/list_config.go
- commands/server.go
This is to ensure that only the relevant command-line flags
for a certain Hugo subcommand is shown to the end user,
reducing clutter and improving user experience.
Fixes #1624 - CLI UX: Flags shouldn't be global
> Change most global flags into local ones

- CONTRIBUTING.md
- README.md
Add an explicit commit message guidelines section to the README.  Keep
all of the guidelines from Chris Beams except for the 72 character line
limit (we don't follow that, nor does the Go team).  Add three new
guidelines: package prefix in subject, references in body, and
encouragement of message body in general.
Add a new section on using Git Remotes.
> hugo: Update contribution section of README

- commands/hugo.go
- source/content_directory_test.go
In emacs, if you edit whatever files, Hugo would always pick up the first auto-save, and sometimes it would be building while you saved the actual file, so the real change would not be picked up. Really annoying :)
This solves it for emacs in the same way spf13 fixed it for vim and other editors.
> Ignore emacs temp files (#filename.md# and .#filename.md)..

- helpers/path.go
- helpers/url_test.go
Using URLize on a string like '100%-true' would cause a panic.
This fixes the issue by verifying that a % is followed by two hex characters in the UnicodeSanitize function in the path helper.
> Fix panic when using URLize

- tpl/template_funcs.go
- tpl/template_funcs_test.go
Test case modified and expanded for `querify` to reflect original bug and changes.
Fixes #2279, but changes escaping behavior for "+" characters.
> Per #2279: `querify` func was double-escaping reserved characters

- docs/content/templates/functions.md
- tpl/template_funcs.go
- tpl/template_funcs_test.go
> Added `htmlescape` and `htmlunescape` template functions

- commands/hugo.go
On 4679fbee41d3, rebuild was disabled on CHMOD filesystem events, but the code is overly aggressive.
In some situations, specially with older Mac's (using a Late 2008 Macbook), the events we receive might be aggregated. On my particular laptop, I get this events:
INFO: 2016/07/26 18:08:51 hugo.go:737: Received System Events: ["<path>": WRITE|CHMOD]
These events are ignored because the code only checks for Chmod. This commit fixes this by checking that the event is also not a Write or Create.
Related to #1587.
----
This is my first contribution to any Go project, so please forgive any Go-newbiness going on. Any comments are appreciated.
I also don't know how to write tests about this. I don't see a `hugo_test.go` and frankly I don't know how to simulate filesystem events to reproduce this. …
> Be less aggressive with CHMOD filesystem events

- commands/server.go
Hugo seems to ignore the meminterval I specify and always uses it's default of 100ms.
This seems to be because Hugo tries to take the meminterval from the command line
(an Int) and converts it to a String and passes it to time.ParseDuration. If you pass a
different meminterval (such as `1000` as above) it will fail (time.ParseDuration requires
some units) and use the default instead.
Changed `meminterval` to be a String and added better documentation for valid time units.
Resolves: #2325
> Fix for meminterval not using specified interval

- source/filesystem.go
- source/filesystem_test.go
> source: Normalize file name to NFC

- tpl/template_funcs.go
- tpl/template_funcs_test.go
The template functions `relURL` and `absURL` currently only accept strings. However, after #889 many template functions like `safeHtml` were opened to accept more than strings. So I suggest that also `relURL` and `absURL` should share this behavior. For example the following code currently throws an error
{{ .RSSLink | relURL }}
because `.RSSLink` is of type `template.HTML` (it throws an error with my version `Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T18:14:17+01:00` shipped with Ubuntu 16.04).
I followed 3a2a4c3b07f . Note that I never programmed in go before, so someone should check my changings :-) I am also not sure whether [code injections](https://en.wikipedia.org/wiki/Code_injection) are possible after the changes in my commit...
> Feature-Request: Make absURL and relURL accept anything

- commands/hugo.go
Fixes #2311
Just like DataDir and LayoutDir, skip StaticDir when the directory does not exist.
> commands: Suppress 'missing static' error

- docs/content/extras/menus.md
Using absolute URLs overrides relative URL behavior. This should be explicit in the docs.
> docs: Update documentation for URLs

- docs/content/tutorials/creating-a-new-theme.md
For the "Creating a New Theme" manual:
1. Clarified the writing;
1. Added more explanation where needed;
1. Slightly reorganized a couple of places, to increase clarity and simplicity;
1. Enriched the sectional structure;
1. Made necessary changes where Hugo functionality has evolved;
1. Updated all the transcribed Hugo output messages;
1. Renamed the formerly introduced term "skins" to "non-content files";
1. Distinguished, and used rigorously, the terms "generate", "render", and "serve";
1. For clarity, led all site-only paths with `./` — but no theme/site paths. Examples: `./content/` and `layouts/`;
1. Began all template paths with `layouts/`;
1. Changed all reported dates to be generic;
1. Thoroughly tested on both Linux and Windows by following along.
In the manual's student web …
> docs: Clarify Creating a New Theme

- docs/content/content/markdown-extras.md
- docs/content/content/summaries.md
- docs/content/overview/configuration.md
- helpers/content.go
- helpers/content_renderer.go
- helpers/content_renderer_test.go
> Add TODO list support for Blackfriday

- hugolib/site.go
Atomic operations with 64 bit values must be aligned for 64-bit on x86-32.
According to the spec:
"The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned."
The above wasn't enough for the `paginationPageCount` on `SiteInfo`, maybe due to how `SiteInfo` is embedded.
This commit adds a 4 byte padding before the `uint64` that creates the correct alignment.
Fixes #2415
> Fix paginator counter on x86-32

- tpl/template_funcs.go
The pair struct used by sortSeq() had two key fields, where only one
is really needed.
> Remove redundant field in sort helper struct

- hugolib/page.go
When Author was called on a Page with no "authors" set in the front-matter,
hugo would panic. This makes sure the "ok" check actually works.
> Prevent panic on empty authorlist

- commands/import_jekyll.go
I ran into the following error:
```
~/Workspace/jelmertiete.com-hugo$ hugo import jekyll ../jelmertiete.com .
Error: Target path should not be inside the Jekyll root, aborting.
```
Note that I'm trying to import into a folder named `jelmertiete.com-hugo` from a folder named `jelmertiete.com`, both in the same directory, which shouldn't throw an error.
Problem was the `HasPrefix` on the full path. Changed it to a `HasPrefix` on the directory instead.
> hugo import jekyll: Fixed target path location check

- docs/content/extras/scratch.md
With hugo's markdown generator a newline is required before a list. Fixing it changes this:
To this
> docs: Fix markdown in content/extras/scratch.md

- docs/content/overview/configuration.md
- docs/layouts/partials/header.html
- docs/static/css/content-style.css
- docs/static/css/style.css
1. Improve the English;
1. Clarify the points;
1. Improve the readability (by CSS styling) of the table which presents the Hugo Blackfriday Markdown options;
1. Segregate that CSS styling, which applies to the HTML inside content files, into a new, small file; and
1. Checked the styling in Firefox, Opera and Internet Explorer 11.
> docs: Improve Overview Configuration manual

- tpl/template_i18n.go
- tpl/template_i18n_test.go
`i18n` now follows the correct logic for missing translations when the default translation file is empty or missing. Previously it just reverted to the `go-i18n` behaviour and spat out the identifier.
I also added test cases for the `i18n` function for various kinds of missing translations.
I noticed one odd consequence of the `EnableMissingTranslationPlaceholders` flag introduced in https://github.com/spf13/hugo/pull/2457: even when it is set, placeholders do not appear if the translation is missing in the current language but present in the default language. It seems that with this new flag we would want to highlight those cases as well.
I think the ideal logic would be:
* _EnableMissingTranslationPlaceholders_: Look for a translation in the current language. If it is missing, always …
> tpl: Fix i18n for missing translations and add tests

- .gitignore
- .travis.yml
- Makefile
- vendor/vendor.json
Doesn't check in vendored packages.  Rewrites Makefile to use govendor helpers.
> Add vendoring with govendor

- Dockerfile
Add the missing github.com/fortytw2/leaktest dependency required for hugo_site_tests.
> Update Dockerfile to pull in missing test dependency

- docs/content/content/archetypes.md
Improve language in the documentation for archetypes. As a new user of Hugo, this documentation is important to me, and I thought I would give it some love. I think making archetypes easy to understand is especially important for users coming from another blogging system that may have its own notion of how to define a "custom post type".
> doc: Improving language in archetypes doc

- helpers/pygments.go
The startinline option is a very handy option for PHP code highlighting (it makes the <?php line optional).
It seems to be removed in a previous commit 26d23f7f4becb2bbfa80d91ae9b27ffc76e13e3a but for no specific reason.
> Whitelist startinline pygments option

- docs/content/meta/release-notes.md
Also trimmed trailing whitespace.
> docs: Fix grammar in v0.17 release notes

- commands/new.go
Changes `%q` to `%s`. `%q` was safely escaping the `\` in windows so that it was printing `\\`. Uses `filepath.Join` for example filepath so that the output is OS specific and since this required splitting up the multiline string, it's refactored into a separate function..
Fixes #2401
> command/new: fixes hugo new for multiple architectures

- commands/hugo.go
- docs/content/extras/datadrivencontent.md
Use case:
I'm using `pygments`, so after every reboot, `hugo` re-runs `pygments` for _every_ code snippet in _any_ page of the blog, which takes quite some time.
Granted, I could set `TPMDIR` before running hugo, or use the command line flag, but I find it convenient to just have `cacheDir = cache` in the config file.
(And of course a matching entry in my blog's `.gitignore`)
Going further, maybe this could be the default?
> Allow to set cache dir in config file

- hugolib/hugo_sites.go
- hugolib/page.go
- hugolib/page_test.go
Also refactor the rendering pages test to accept more than one page source per test run, which wasn't really needed for this issue, but may be in the future.
Closes #2586
Fixes #2538
> Fix a more summary corner case

- helpers/content.go
Add logging of the errors/warnings which rst2html outputs to its stderr
stream when rendering rst documents. Note that rst2html outputs warnings
and errors to stderr but it also adds them to the generated html. ->
hugo logs everything in stderr as error.
Add / complete adding page context (path to file being rendered) to
anything logged by getRstContent and getAsciidocContent.
See #2570
> Add page context to error logging in rendering

- helpers/configProvider.go
- helpers/language.go
- helpers/language_test.go
- helpers/path.go
- helpers/path_test.go
- helpers/pathspec.go
- helpers/pathspec_test.go
- helpers/url.go
- helpers/url_test.go
- hugolib/hugo_sites_test.go
- hugolib/node.go
- hugolib/page.go
- hugolib/pageSort_test.go
- hugolib/page_permalink_test.go
- hugolib/page_test.go
- hugolib/pagination.go
- hugolib/pagination_test.go
- hugolib/permalinks.go
- hugolib/permalinks_test.go
- hugolib/site.go
- hugolib/taxonomy.go
- tpl/template.go
- tpl/template_funcs.go
- tpl/template_funcs_test.go
- tpl/template_i18n.go
- tpl/template_i18n_test.go
The gain, given the "real sites benchmark" below, is obvious:
```
benchmark           old ns/op       new ns/op       delta
BenchmarkHugo-4     14497594101     13084156335     -9.75%
benchmark           old allocs     new allocs     delta
BenchmarkHugo-4     57404335       48282002       -15.89%
benchmark           old bytes       new bytes      delta
BenchmarkHugo-4     9933505624      9721984424     -2.13%
```
Fixes #2495
> Avoid reading from Viper for path and URL funcs

- hugolib/hugo_sites.go
- hugolib/page.go
It is not needed, because it is only used to store temporary data during `preparePagesForRender`.
> get rid of the rawContentCopy field of the Page struct

- hugolib/page.go
- source/file.go
changes:
- in hugolib/page.go, `func permalink` and `func TargetPath`
Fixed the attempt to *replace* the extension of something
that was *already* a basename (without extension) .
- in source/file.go, `func NewFile`
added check for allowed languages before translating filename
Fixes #2555
> fix page names that contain dot

- commands/hugo.go
- docs/config.toml
- docs/layouts/partials/footer.html
- hugolib/config.go
- hugolib/gitinfo.go
- hugolib/hugo_sites.go
- hugolib/page.go
- vendor/vendor.json
This commit adds a `GitInfo` object to `Page` if `EnableGitInfo` is set.
It then also sets `Lastmod` for the given `Page` to the author date provided by Git.
The Git integrations should be fairly performant, but it adds "some time" to the build, somewhat depending on the Git history size.
If you want, you can run without during development and turn it on when deploying to the live server: `hugo --enableGitInfo`.
Fixes #2102
> Add GitInfo

- source/lazy_file_reader.go
- tpl/template_funcs.go
tpl/template_funcs.go:1019:3: the surrounding loop is unconditionally terminated
source/lazy_file_reader.go:66:5: err != nil is always true for all possible
values ([nil:error] != [nil:error])
> source, tpl: fix staticcheck complaints

- docs/content/templates/functions.md
- hugolib/hugo_sites.go
- tpl/template_funcs.go
- tpl/template_funcs_test.go
This allows for more advanced image shortcodes and templates such as those required by AMP.
layouts/shortcodes/amp-img.html
```html
{{ $src := .Get "src" }}
{{ $img := readFile (printf "/static/%s" $src) }}
{{ $config := imageConfig $img }}
<amp-img src="{{$src}}"
height="{{$config.Height}}"
width="{{$config.Width}}"
layout="responsive">
</amp-img>
```
```html
{{< amp-img src="/foo.png" >}}
```
> tpl: Adds imageConfig function which calls image.DecodeConfig and returns the height, width and color mode of the image.

- hugolib/case_insensitive_test.go
- hugolib/page.go
- hugolib/site.go
- tpl/template.go
- tpl/template_ast_transformers.go
- tpl/template_ast_transformers_test.go
There are currently several Params and case related issues floating around in Hugo.
This is very confusing for users and one of the most common support questions on the forum.
And while there have been done some great leg work in Viper etc., this is of limited value since this and similar doesn't work:
`Params.myCamelCasedParam`
Hugo has control over all the template method invocations, and can take care of all the lower-casing of the map lookup keys.
But that doesn't help with direct template lookups of type `Site.Params.TWITTER_CONFIG.USER_ID`.
This commit solves that by doing some carefully crafted modifications of the templates' AST -- lowercasing the params keys.
This is low-level work, but it's not like the template API wil change -- and this is important enough to defend such "bit …
> Fix case issues with Params 

- .gitignore
- hugolib/case_insensitive_test.go
- hugolib/page.go
- hugolib/site.go
- hugolib/site_render.go
- tpl/template.go
- tpl/template_ast_transformers.go
- tpl/template_ast_transformers_test.go
This replaces #2630 -- but it needs some more testing before we try again. There is a inifinite loop lurking in here ...
There are currently several Params and case related issues floating around in Hugo.
This is very confusing for users and one of the most common support questions on the forum.
And while there have been done some great leg work in Viper etc., this is of limited value since this and similar doesn't work:
`Params.myCamelCasedParam`
Hugo has control over all the template method invocations, and can take care of all the lower-casing of the map lookup keys.
But that doesn't help with direct template lookups of type `Site.Params.TWITTER_CONFIG.USER_ID`.
This commit solves that by doing some carefully crafted modifications of the templates' AST -- lowercasing the params keys. …
> Fix case issues with Params

- Dockerfile
Just noticed while browsing this was using spaces while everything else in here was using tabs :-)
> Fix alignment of go gets in Dockerfile

- vendor/vendor.json
Note about updated checksums:  my hunch is that bep had extraneous files in his local gitmap and cast packages that govender used to compile a different checksum.  You can check for extra files with
```bash
cd $GOPATH/src/github.com/bep/gitmap && find . | xargs git check-ignore
```
> vendor: remove afero sftp deps

- hugolib/page.go
- hugolib/site.go
This is a significant performance win for menu heavy sites.
My benchmark tool doesn't show any difference in this area, I will try to add some more sites,  but it seems to shave off about 100 ms+ of the docs build.
See #2728
> hugolib: Avoid repeated Viper loads of sectionPagesMenu

- hugolib/site.go
Changes `%q` to `%s`. `%q` was safely escaping the `\` in windows so that it was printing `\\`.
Fixes [this comment](https://github.com/spf13/hugo/issues/2401#issuecomment-252681480) in #2401.
cc @MarkDBlackwell
> command: fixes rendered empty msg for multiple architectures

- hugolib/handler_page.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build_test.go
- hugolib/page.go
- hugolib/page_test.go
This was a regression introduced in Hugo 0.17.
Fixes #2601
Note: This PR will be benchmarked before merged.
> hugolib: Make RawContent raw again

- docs/content/extras/aliases.md
- docs/content/extras/analytics.md
- docs/content/extras/builders.md
- docs/content/extras/comments.md
- docs/content/extras/crossreferences.md
- docs/content/extras/datadrivencontent.md
- docs/content/extras/datafiles.md
- docs/content/extras/gitinfo.md
- docs/content/extras/highlighting.md
- docs/content/extras/livereload.md
- docs/content/extras/localfiles.md
- docs/content/extras/menus.md
- docs/content/extras/pagination.md
- docs/content/extras/permalinks.md
- docs/content/extras/robots-txt.md
- docs/content/extras/scratch.md
- docs/content/extras/shortcodes.md
- docs/content/extras/toc.md
- docs/content/extras/urls.md
- docs/content/overview/configuration.md
This PR contains an additional commit to cleanup the Extras menu ordering.  It was an ugly mess.  I removed the weights from the pages to allow the sorter to use the Title so that we don't need manage weights by hand.  Make sure I didn't break something by doing that.
PS - Notice the definition list in the GitInfo page.  I'd much rather see us use that structure in pages such as Template Variables.
Fixes #2670
> docs: Add Extras > GitInfo

- helpers/path.go
- hugolib/template_test.go
- tpl/template.go
This commit fixes the base template lookup order to match the behaviour of regular templates.
```
1. <current-path>/<template-name>-baseof.<suffix>, e.g. list-baseof.<suffix>.
2. <current-path>/baseof.<suffix>
3. _default/<template-name>-baseof.<suffix>, e.g. list-baseof.<suffix>.
4. _default/baseof.<suffix>
For each of the steps above, it will first look in the project, then, if theme is set,
in the theme's layouts folder.
```
Fixes #2783
> hugolib: Enable override of theme base template only

- docs/content/meta/release-notes.md
@moorereason @digitalcraftsman @spf13 @anthonyfok and others ... this is just a rough outline. Please edit / add.
> Work in progress: 0.18 release notes

- commands/hugo.go
Currently, I don't see a way to specify themes directory to look for, while running the `hugo` command. So I added this command line argument which takes the path where themes are located. 
Example usage:
$ hugo server --theme=docuapi --themesDir=/Users/avi/snakes/hugo-themes
$ hugo --theme=docuapi --themesDir=/Users/avi/snakes/hugo-themes
> command: Add `themesDir` command argument to specify themes directory

- docs/content/tutorials/installing-on-windows.md
The tutorial for installing on windows didn't mention the exact name of the
hugo executable in windows which is generally hugo_`hugo-version`_ windows _`arch`.exe.
The tutorial mentioned the windows executable's name as hugo.exe, which
can be confusing sometimes. So extra information has been added to
rename the executable to hugo.exe which would be easy to use.
Fixes #2656
> docs: fixed issue on name of the executable in the tutorial for installing hugo on windows

- docs/content/templates/blocks.md
Fixed typo in templates/blocks.md in the docs.
> docs: fix typo in templates/blocks

- tpl/template_funcs.go
- tpl/template_funcs_test.go
defaultImageConfigCache is now initialized statically instead of relying on it
being initialized in the reset function.
Fixes #2806
> tpl: fix crash when using imageConfig

- hugolib/node_as_page_test.go
- hugolib/page.go
> hugolib: Fix redundant URL file extension on taxonomy terms pages

- hugolib/hugo_sites.go
- hugolib/hugo_sites_build_test.go
- hugolib/page.go
The new logic for creating Page objects from old node types
didn't include itself in the translation logic, so
`IsTranslated` returned falsely false for sites with only two languages.
The `AllTranslations` method also returned to few pages in that case.
This commit fixes that.
Fixes #2812
> hugolib: Fix IsTranslated for "old" node types

- docs/content/tools/_index.md
HugoPhotoSwipe is a command line tool to create and manage PhotoSwipe galleries with Hugo. It resizes images for responsive layouts in PhotoSwipe and generates the Markdown necessary for Hugo to create the gallery. I think this can be a useful tool for Hugo users.
> Add link to HugoPhotoSwipe tool

- docs/content/templates/functions.md
- tpl/template_funcs.go
Add a timeNow template function that returns the current time as
time.Time. Also, update related docs.
Don't know what the right way to test this change is (if necessary), so I'm open to suggestions.
Personally, I'm looking to use use the unix timestamp of the current time in the [query string for cache busting](https://css-tricks.com/strategies-for-cache-busting-css/#article-header-id-1) in a theme. 
```
<link rel="stylesheet" href="/css/reset.css?t={{ timeNow.Unix }}">
```
I'm sure hugo users will come up with other creative uses for current time.
> tpl: add now function

- appveyor.yml
- helpers/content.go
- helpers/general.go
- helpers/pygments.go
- hugolib/gitinfo.go
- hugolib/shortcode_test.go
Codified appveyor configuration and mirrored it to the travis configuration. This uncovered a few issues with the Windows build. First was GitInfo pathing was not normalized and second was, generally, external helpers did not properly return LF normalized files. These issues were uncovered by existing unit tests and fixed in this PR.
Fixes #1825 #2697 #920
> Add appveyor.yaml to mirror .travis.yml and fix line ending issues

- docs/config.toml
- docs/layouts/partials/footer.html
- docs/layouts/partials/header.html
Adds a "release" Site param that will be need to be updated for each
release.
Fixes #2857
> docs: Don't use binary version in docs site

- docs/content/templates/sitemap.md
- examples/blog/layouts/sitemap.xml
- hugolib/sitemap_test.go
The documentation and examples for the `sitemap.xml` template were outdated and didn't show the correct internal template. If you used the one provided in the docs, the sitemap.xml always outputted a date for every node, even if that node didn't have a date (like a static page for example).
> Updated documentation and test for sitemap.xml template

- tpl/template_funcs_test.go
> tpl: Fix Unix time test case in TestDateFormat()

- docs/content/content/organization.md
If the idea is to move users/devs of Hugo away from `index.md` to the (in my opinion, better) `_index.md`, I think these changes are substantiated. That said, there is more to do to reduce confusion surrounding `_index.md`, at least from what I've gleaned from the forums.
> Updating to include reference to _index.md

- docs/content/templates/functions.md
- tpl/template_func_truncate.go
- tpl/template_func_truncate_test.go
- tpl/template_funcs.go
- tpl/template_funcs_test.go
This commit adds a truncate template function for safely truncating text without
breaking words. The truncate function is HTML aware, so if the input text is a
template.HTML it will be truncated without leaving broken or unclosed HTML tags.
{{ "this is a very long text" | truncate 10 " ..." }}
{{ "With [Markdown](/markdown) inside." | markdownify | truncate 10 }}
The HTML truncation is based on Django's truncatehtml template helper, so while I would normally be really cautious about doing anything regexp based with HTML, this is a very battle tested implementation. I've also tested it on a corpus of 2600+ blog posts from a large publication.
> Add truncate template function

- hugolib/page.go
- hugolib/page_test.go
> hugolib: Allow arrays of arrays in frontmatter Params

- tpl/template.go
As a followup [this discussion](https://discuss.gohugo.io/t/why-is-this-template-incomplete/5027/4), I'm proposing that when a template gets executed and produces an error, the error is logged with a limit of 512 bytes in length (that length is arbitrary, but I think it should be about right to accommodate most common errors without being screen-fulls of output).
Before this PR the code discards the error altogether, citing [this issue](https://github.com/golang/go/issues/17414) with the Go template engine.  The trouble is, there are a lot of other things that can go wrong, and the template author needs to be able to see what happened.  The issue above is talking about a specific individual error that can be reported by the template engine - but in many cases, this isn't the error being …
> show truncated error message instead of discarding it

- tpl/template_funcs.go
Cached partials that contained cached partials would create a deadlock.
Fixes #2935
> tpl: Fix deadlock in cached partials

- tpl/template_embedded.go
Three major improvements. From the commit message:
- Allow all nodes/pages to use date-related OpenGraph meta tags, not only sites which are using the as-of-yet unfinished .Site.Authors functionality.
- Improve compliance of tags with Facebook's OpenGraph docs for the "website" and "article" types[0][1]. Also, use the proper tag for modification date (`og:update_time` vs `article:modified_time`).
- Generate date published using either `.PublishDate` or `.Date`, and use `.Lastmod` for modification date, which can use the new `enableGitInfo` functionality from Hugo 0.18, but seamlessly falls back to `.Date` if the site does not have this enabled/supported.
Tested on [Facebook's OpenGraph debug tool](https://developers.facebook.com/tools/debug/og/object/) and the new metadata is detected …
> tpl: Improve generation of OpenGraph date tags

- hugolib/pageSort.go
This fixes a few minor spelling errors in `pageSort.go`'s comments.
> Correct repeated spelling errors in `pageSort.go` documentation

- docs/content/templates/list.md
- hugolib/pageSort.go
- hugolib/pageSort_test.go
This allows users to sort by the value of a specified frontmatter key, including anything that would otherwise be available in `.Params`. Comparisons (and thus the resulting sorting) are done on a string basis, so, for example, `xyz123` comes before and not after `xyz23`.
This is useful for general-purpose sorting for which `weight` is either not sufficient or where it duplicates information that's already present in the frontmatter. See discussions [here](https://discuss.gohugo.io/t/can-a-sections-pages-be-sorted-by-arbitrary-frontmatter-variables/5358).
If the committers are happy with this implementation, I'll also add the correspondingly necessary documentation for this feature.
> Add ability to sort by frontmatter parameters

- tpl/tplimpl/template_embedded.go
Instagram doesn't return a valid JSON response when the requested ID is
invalid or not found.
Fixes #3048
> tplimpl: Fix instagram shortcode panic on invalid ID

- docs/content/overview/configuration.md
- hugolib/config.go
- hugolib/rss_test.go
- hugolib/site_render.go
- tpl/tplimpl/template_embedded.go
Add a new rssLimit site configuration option with default of 15.  Prior
to this fix, you could create your own RSS feed to override the default
limit of 15, but we still had a hardcoded limit of 50 items set in
`hugolib.renderRSS()`.
With this option in place, the `range first 15 .Data.Pages` logic is no
longer hardcoded into the embedded RSS template.
Because the size of the slice passed to the template is now limited to
rssLimit instead of 50, this commit is a breaking change for sites
with a custom RSS template that expects more than 15 items.
Fixes #3035
> hugolib: Make RSS item limit configurable

- commands/hugo.go
- hugolib/disableKinds_test.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/hugo_sites_build_test.go
- hugolib/page.go
- hugolib/site.go
- hugolib/site_render.go
This PR adds a new flag or configuration options that takes a slice of page`Kind's` that will not be generated or part of any page collection.
> hugolib: Add disableKinds option

- docs/content/templates/list.md
- docs/content/templates/variables.md
- hugolib/page.go
- hugolib/pageSort.go
- hugolib/pageSort_test.go
- hugolib/page_test.go
Currently, the only way to access params with nested keys is to be explicit and static:
{{ .Params.author.favorites.color }}
This, for example, doesn't work:
{{ $k := "author.favorites.color" }}
{{ .Param $k }} // Param doesn't understand nesting.
This doesn't work either:
{{ $k := slice "author" "favorites" "color" }}
{{ index .Param $k... }} // Go templates don't understand variadic args.
What would be ideal is to be able to say something like:
{{ $k := slice "author" "favorites" "color" }}
{{ .Param $k }}
and have it traverse the `Page.Params` and `Site.Params` maps.
This PR introduces a bound function, `Page.Traverse`, that produces these results. It has behavior identical to `Page.Param`, but it will traverse a map to an arbitrary depth instead of to just the first level, and it …
> Enhance `.Param` to permit arbitrarily nested parameter references

- docs/content/content/summaries.md
- hugolib/handler_page.go
- hugolib/page.go
- hugolib/page_test.go
This fixes the behavior of .Truncated that was introduced with commit
bef496b97e1dc2df8c52b080152d539a58752801 which was later broken.  The
desired behavior is that .Truncated would evaluate to false when there
was nothing after the user defined summary marker.
This also adds a simple unit test to ensure that this feature isn't
broken again.  The check for content after the user defined summary
marker is done on the raw content instead of the working copy because
some of the markup renderers add elements after the marker, making it
difficult to determine if there is actually any content.
The behavior (evaluating to false when there is no content, just
summary) is also now documented.
> Fix regression of .Truncated evaluation in manual summaries

- hugolib/hugo_sites_build.go
- hugolib/site.go
- hugolib/site_test.go
This commit makes sure that the `.Site.LastChange` is fetched from the latest page modification date.
Previously, this value was fetched from the last page in the default page sort, which may not be the last by date if weight is set.
Fixes #2909
Closes #2910
> hugolib: Fix .Site.LastChange

- hugolib/page.go
Otherwise we fail to skip the current language in translations
for paginated pages.
Fixes #2972
> hugolib: discard current language based on .Lang()

- hugolib/hugo_sites.go
- hugolib/page.go
- hugolib/site.go
Enforce usage of PathSpec
Fixes #3060
Updates #2728
Viper usage:
**examples/blog**
```
47 baseurl
31 relativeurls
23 languages
22 builddrafts
20 buildfuture
20 buildexpired
18 disablerss
16 ignorefiles
11 blackfriday
10 usemodtimeasfallback
10 publishdir
10 hascjklanguage
10 footnotereturnlinkcontents
10 footnoteanchorprefix
10 enableemoji
8 taxonomies
8 rssuri
7 defaultcontentlanguage
6 rsslimit
5 sitemap
4 uglyurls
4 theme
4 multilingual
4 defaultextension
4 defaultcontentlanguageinsubdir
4 canonifyurls
3 workingDir
3 disablesitemap
3 defaultContentLanguage
3 baseURL
2 workingdir
2 uglyURLs
2 themesdir
2 themesDir
2 staticdir
2 staticDir
2 social
2 sectionpagesmenu
2 removepathaccents
2 removePathAccents
2 preservetaxonomynames
2 pluralizelisttitles
2 permalinks
2 params
2 paginatepath …
```
> Get rid of some viper.Get* calls

- hugolib/hugo_sites_build.go
- hugolib/hugo_sites_build_test.go
- hugolib/menu.go
- hugolib/menu_old_test.go
- hugolib/menu_test.go
- hugolib/page.go
- hugolib/site.go
- hugolib/taxonomy_test.go
- hugolib/testhelpers_test.go
When using the lazy blogger setting to automatically generate menu
entries from section pages, we now recognize section pages that have
content, and use the weight and linktitle configured in the frontmatter.
This way, we can use the lazy blogger automatic generation, and
influence menu order and translations, directly from the frontmatter.
Fixes #2974
> hugolib: Improve menu generation for section pages with content

- docs/content/content/summaries.md
- docs/content/content/supported-formats.md
- helpers/content.go
- helpers/general.go
- helpers/general_test.go
- hugolib/handler_page.go
- hugolib/page.go
- parser/frontmatter.go
- parser/page.go
- vendor/vendor.json
This PR adds support for Org content, as requested in #936 and #1483.
It doesn't look like much, but it adds a new dependency [https://github.com/chaseadamsio/goorgeous](https://github.com/chaseadamsio/goorgeous), a go org to html package.
Files with the following format with `.org` extensions are supported for 98% of the use cases and 100% of what would be converted from Hugo markdown currently.
It supports `.org` headers at the top of the file as well for frontmatter:
```
#+TITLE: My Hugo Blog Post
#+AUTHOR: Chase Adams
#+DATE: 2016-12-14T10:17:43Z
#+DRAFT: true
```
so there's no need to "manipulate" org files to work with Hugo by including toml, yaml or JSON for frontmatter.
It'd be great to have some folks test it out (I've been generating posts for the past two weeks with this …
> add org content support with org keyword headers as frontmatter

- docs/content/extras/menus.md
> Improve documentation for menu rendering.

- tpl/tplimpl/template_embedded.go
It seems this metadata tag is no longer used by Twitter, as it has been removed from their official [Cards Markup Tag Reference](https://dev.twitter.com/cards/markup). There is a reference to this on the [W3 mailing list in 2013 as well](https://lists.w3.org/Archives/Public/www-validator/2013Oct/0025.html).
Users should remove `.Site.Social.twitter_domain` from their configuration as well.
> tpl: Remove twitter:domain tag from internal shortcode

- hugolib/page.go
- hugolib/page_test.go
Right now, `.Params` is documented as being "everything you put into the frontmatter, except for a long list of specific variables". In particular, values which are otherwise subsumed by `Page` fields generally don't wind up in `.Params`. But this has exceptions -- for instance, `Description` is both a `Page` field and will be present in `Params`, even though the documentation says it _won't_ be present in `Params`.
The net result is that it's a little confusing and inconsistent about what does or does not wind up in `Params`.
This problem makes it difficult to use certain other Hugo functions in your templates. For example, one cannot do `{{ .Param "date" }}` because there is no `date` stored in `Params`, even though `date` is in your frontmatter. That means that if you invoke such …
> Use Page.Params more consistently when adding metadata

- tpl/tplimpl/template_embedded.go
Quick fix for a minor error I found in my earlier [commit improving the OpenGraph tags](https://github.com/spf13/hugo/pull/2979) generated by Hugo's internal opengraph template. The commit message there was correct, but the code left out one of the stated changes: nodes are of type "website" and according to the [Facebook docs](https://developers.facebook.com/docs/reference/opengraph/object-type/website/) they should use `og:updated_time`.
> tpl: Use og:updated_time OpenGraph tag on nodes

- commands/hugo.go
- commands/new.go
- commands/server.go
- hugolib/page.go
- hugolib/site.go
Updates #3064
Viper calls:
**example/blog**
```
69 baseurl
13 disablerss
10 rssuri
9 rsslimit
8 defaultcontentlanguage
5 publishdir
5 languages
5 builddrafts
4 taxonomies
4 pygmentscodefences
4 ignorefiles
4 defaultextension
4 defaultContentLanguage
4 buildfuture
4 buildexpired
3 workingDir
3 theme
3 multilingual
3 blackfriday
3 baseURL
2 uglyurls
2 uglyURLs
2 themesDir
2 staticDir
2 removePathAccents
2 paginatePath
2 layoutDir
2 hascjklanguage
2 footnotereturnlinkcontents
2 footnoteanchorprefix
2 enableemoji
2 disablePathToLower
2 defaultcontentlanguageinsubdir
2 defaultContentLanguageInSubdir
2 contentdir
2 canonifyurls
2 canonifyURLs
1 workingdir
1 verbose
1 title
1 themesdir
1 staticdir
1 social
1 sitemap
1 sectionpagesmenu
1 removepathaccents
1 relativeurls
1 relativeURLs
1 …
```
> Get rid of viper.Get(relativeURLs)

- docs/content/meta/release-notes.md
When mentioning the commit for 'now' template function the previous line's github link is repeated unfortunately. Now you can fix it via this PR
> Correct  commit link for 'now' template function.

- hugolib/hugo_sites.go
- hugolib/node_as_page_test.go
Previously it would only check for existing KindTaxonomyTerm pages
if the taxonomy had any terms defined.  So for a taxonomy with no terms
but a taxonomy terms page it would generate a second empty terms page.
> hugolib: Fix HugoSites.createMissingPages

- docs/content/templates/rss.md
- docs/content/templates/terms.md
- hugolib/node_as_page_test.go
- hugolib/page.go
- hugolib/site.go
- hugolib/site_render.go
- hugolib/taxonomy_test.go
Previously this was left empty, but it is very handy to have a list
of term pages for a given taxonomy.  This list can now be paginated
like other page lists.  It makes it possible to render summary
content from each terms index page for instance.  It also makes it
possible to sort the term pages in the same way that other page
lists can be sorted.
> Taxonomies: Populate the KindTaxonomyTerm Pages list

- commands/import_jekyll.go
- commands/new.go
- commands/undraft_test.go
- hugolib/page.go
- parser/frontmatter.go
- parser/frontmatter_test.go
- parser/page.go
- parser/page_test.go
- vendor/vendor.json
Lots of cleanups here:
- Refactor InterfaceToConfig and InterfaceToFrontMatter to use io.Writer.
- Simplify InterfaceToFrontMatter by wrapping InterfaceToConfig.
- Export FrontmatterType since we return it in DetectFrontMatter.
- Refactor removeTOMLIdentifier to avoid blindly replacing "+++".
- Update HandleJSONMetaData to return an empty map on nil input.
- Add godoc comments.
Coverage for frontmatter.go increased from 10.7% to 90.7%.
Updates #2752
> parser: Refactor frontmatter parser and add tests

- hugolib/hugo_sites.go
- hugolib/page.go
- hugolib/page_collections.go
- hugolib/shortcode.go
- hugolib/shortcode_test.go
- hugolib/site.go
This commit fixes two different, but related issues:
1) Live-reload when a new shortcode was defined in the content file before the shortcode itself was created.
2) Live-reload when a newly defined shortcode changed its "inner content" status.
Fixes #3156
> hugolib: Fix reloading corner cases for shortcodes

- docs/content/content/front-matter.md
- parser/page.go
- parser/parse_frontmatter_test.go
Accept JSON frontmatter without leading "{\n" so that one line frontmatters such as `{"param":"paramvalue"}` no longer silently render empty html.
----------------------------
I ran `bench.sh` and there doesn't seem to be a performance difference even though `determineDelims(...)` no longer uses the length of the slice as a heuristic.
Stylistically, having `{` and `}` on their own line is probably better. However, I was following [this post](https://discuss.gohugo.io/t/creating-static-content-that-uses-partials/265/15) and became frustrated by the blank page generated with no error in the output or logs.
> parser: Accept JSON frontmatter without leading "{\n"

- CONTRIBUTING.md
- docs/content/community/contributing.md
- docs/content/overview/installing.md
- docs/content/tutorials/how-to-contribute-to-hugo.md
Add vendoring and make targets.  Require Go 1.8+ and remove mention of
GOPATH (just assume $HOME/go).
Due to time contraints, the contributing tutorial was only slightly
updated to make obvious corrections.
Fixes #3153
> docs: Update contributing guides

- docs/content/overview/configuration.md
Looks like this was erroneously added two years ago in commit 1827680beaf10c0710b3daed2cf1f6679c9a070a. I suspect the author misinterpreted the `--editor` [command line option](https://github.com/spf13/hugo/blob/1827680beaf10c0710b3daed2cf1f6679c9a070a/commands/hugo.go#L92) which [overrides the `newContentEditor` configuration option](https://github.com/spf13/hugo/blob/1827680beaf10c0710b3daed2cf1f6679c9a070a/commands/hugo.go#L173-L175).
> Fix documentation of non-existent 'editor' config

- commands/import_jekyll.go
- commands/import_jekyll_test.go
This commit changes the translation of the `` tag from Jekyll to be case insensitive, which is supported (in Octopress at least).
I added a test case for this one as well.
> [Import from Jekyll] Case insensitive translation of the 'more' tag

- parser/frontmatter.go
Difference between `toml.Load(string(datum))` and
`toml.LoadReader(bytes.NewReader(datum))`:
```
benchmark           old ns/op     new ns/op     delta
BenchmarkLoad-4     82068         78489         -4.36%
benchmark           old allocs     new allocs     delta
BenchmarkLoad-4     494            493            -0.20%
benchmark           old bytes     new bytes     delta
BenchmarkLoad-4     17009         16913         -0.56%
```
> parser: Improve TOML frontmatter parser performance

- commands/hugo.go
- docs/content/commands/hugo_benchmark.md
- vendor/vendor.json
Add a new option to ignore 'dot' folders when deleting files in destination dir.
Fixes #3208
> commands: Added new option `cleanDestinationDirKeepDotFolder`

- hugolib/page.go
- hugolib/site_test.go
The above example was earlier identified as a section page and not a regular page.
Fixes #3234
> hugolib: Correctly identify "my_index_page.md"

- docs/content/extras/comments.md
Livefyre.com is down.
Livefyre was integrated into Adobe's offering.
The product is now called Adobe Experience Manager Livefyre.
Wikipedia points to web.livefyre.com which redirects to the link I provided in the commit.
> Update Disqus alternative

- docs/content/content/multilingual.md
- examples/multilingual/i18n/en.toml
- examples/multilingual/i18n/en.yaml
- examples/multilingual/i18n/et.toml
- examples/multilingual/i18n/et.yaml
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build_test.go
- i18n/i18n_test.go
- vendor/vendor.json
> all: Add TOML support for language files

- CONTRIBUTING.md
- README.md
- docs/content/community/contributing.md
- docs/content/community/press.md
- docs/content/meta/release-notes.md
- docs/content/tutorials/automated-deployments.md
- docs/content/tutorials/how-to-contribute-to-hugo.md
It's a pet peeve of mine to see words like GitHub not capitalized correctly. I've fixed occurrences of `Github` to `GitHub` everywhere that isn't code.
> Properly capitalize GitHub.

- commands/gendoc.go
- commands/genman.go
- commands/hugo.go
- hugolib/hugo_sites.go
- hugolib/site.go
- hugolib/site_render.go
- transform/hugogeneratorinject.go
> all: Handle all returned errors

- commands/hugo.go
- hugolib/site.go
- hugolib/site_url_test.go
This makes it consistent with how it behaves when it's set in config.toml.
This commit also unifies BaseURL in Site.Info so we now have one source for this value.
Fixes #3262
> hubolib: Do not add missing trailing slash to command line baseURL

- hugolib/site_output_test.go
- output/layout_base.go
This regression was introduced in Hugo 0.20.
Fixes #3333
> hugolib, output: Do not lower case template names

- tpl/tplimpl/template.go
- tpl/tplimpl/templateFuncster.go
- tpl/tplimpl/template_funcs.go
- tpl/tplimpl/template_funcs_test.go
Most obvius benefit of this is to include CSS partials with css file suffix into HTML templates.
A valid workaround would be to rename the file `mystyles.html`, but that doesn't work too good for external editors etc.
The css partial is  a method used in some themes before Hugo 0.20, but then it stopped working.
This commit reintroduces that behaviour.
Note that the regular layout lookups for text templates, i.e. "single.json" will be
prefixed with "_text/" on lookup and will only match in the text collection.
Fixes #3273
> tplimpl: Allow text partials in HTML templates

- Makefile
The check-vendor target will exit with an error if any files in vendor/
differ from what's checked into git.
govendor checksums can get out of sync if extraneous files are in the
local, third-party repo (see kardianos/govendor#129).  govendor also
updates the vendor.json upon "sync."  We can use that quirk to detect
out of sync checksums in CI, so I've added check-vendor to the check
target dependencies.
> Add check-vendor target to Makefile

- commands/import_jekyll.go
- commands/import_jekyll_test.go
This commit introduces support for Octopress image tag, as described here:
http://octopress.org/docs/plugins/image-tag/
It includes tests for several use-cases.
> Import of Octopress image tag

- docs/content/templates/sitemap.md
- tpl/tplimpl/template_embedded.go
For pages with translations, add links with hreflang attributes to the
default sitemap template. This helps Google to show the correct
language page in its search results. The syntax used is based on
Google's example at [1].
Also update the sitemap template docs to reflect the changes in the
default template.
[1] https://support.google.com/webmasters/answer/2620865?hl=en&topic=2370587&ctx=topic
Fixes #2569
> Add translation links to the default sitemap template

- hugolib/site.go
- source/filesystem.go
Partial rebuild does not have the same logic as normal rebuild on
selecting which file to build. This change makes it possible to
share the file select logic between two kinds of build.
Fix #3325.
> Ignore non-source files on partial rebuild.

- helpers/content.go
- helpers/content_renderer_test.go
- helpers/content_test.go
- hugolib/page.go
helpers: Delete RenderingContext.getConfig
helpers, hugolib: Use only non-pointer RenderingContext 
hugolib: Prevent decoding pageParam in common cases
`hugo benchmark -s docs`
Before:
```
Average memory allocated per operation: 119514kB
Average allocations per operation: 2057862
```
After:
```
Average memory allocated per operation: 118679kB
Average allocations per operation: 2042662
```
> helpers, hugolib: Refactoring

- goreleaser.yml
This sets the `-static` ldflag when building Hugo, so that it can be run in a minimal Docker container.
EDIT: Does in fact work fine when building for Windows
Closes #3382
> Set extldflags to static when building

- hugolib/page_paths.go
- hugolib/page_paths_test.go
- hugolib/site_test.go
Hugo 0.20 broke some sites that grouped their blog post and images together in subfolders.
This commit re-introduces that behaviour:
* If the file base name resolves to the same as the base name for the output type (i.e. "index" for HTML), the user probably meant it, so we treat that as an `uglyURL`, i.e. `my-blog-post-1.md`=> `/my-blog-post-1/index.html`
* The main use case for this is to group blog post and images together.
* Note that for the top level folder there will be a potential name conflict with a `section` `index.html` (if enabled)
* This issue will not be relevant for subfolders in sections
* Hugo will soon add support for nested sections, but we will have to find a way to separate them from the rest (`/content/_mysubsection` maybe).
Fixes #3396
> hugolib: Avoid index.md in /index/index.html

- docs/content/tutorials/mathjax.md
MathJax officially informed that [their self-hosted *cdn.mathjax.org* is retired](http://docs.mathjax.org/en/latest/configuration.html#loading-mathjax-from-a-cdn), and they currently recommend to use *cdnjs.cloudflare.com*.
Thus, this PR fixes corresponding MathJax document.
Note: Since *cdnjs.com* does not provide a link to the **latest** version of MathJax, sample snippet specifies to use version 2.7.1 (i.e., the latest version at this moment).
> Replace cdn.mathjax.org with cdnjs.cloudflare.com

- docs/content/content/multilingual.md
Added a bit of documentation on slug translation in the multilingual page. Found that was easy but not intuitive, and for some reason this was not documented. Hope it helps new Hugo users.
> docs: Added documentation on slug translation

- hugolib/config.go
From @bep's recommendation from spf13/hugo/pull/3424, this PR fixes the `hugo server` command not using `ignoreFiles`. Just added the `ignoreFiles` default to the `config.go` and that fixed it. This should close out the `org` issue that @strow was having and then I can get back to making the go org library better. :)
> hugolib: add default config for ignoreFiles

- hugolib/taxonomy.go
People can still say `.Page`, but by embedding it `WeightedPages` can be used interchangeably with `Pages` in templates.
Fixes #3435
> hubolib: Embed Page in WeightedPage

- docs/content/overview/source-directory.md
Hugo looks for the list/single templates of a taxonomy in `/layouts/taxonomy`, not `/layouts/taxonomies` as correctly mentioned in [this doc page](https://gohugo.io/templates/list/). This change is simply a minor reconciliation.
> Fixed incorrect specification of directory structure

- Dockerfile
It's pointless to set `/bin/sh` as entrypoint. `/bin/sh` is already the default command, and on the top of that, setting `/bin/sh` as entrypoint ignores the command.
> Remove ENTRYPOINT from Dockerfile

- commands/hugo.go
> commands: Skip .git directories

- hugolib/site_output.go
- hugolib/site_output_test.go
A common use case for this is to redefine the built-in output format `RSS` to give it a different URL.
Before this commit, that was not possible without also providing an `outputs` definition.
Fixes #3447
> hugolib: Fix output formats override when no outputs definition given

- tpl/tplimpl/template_embedded.go
> tmplimpl: Add support for ellipsed paginator

- docs/data/docs.json
Looks like this was a bad copy/paste where CSV should've been JSON
> docs: update references to JSON

- docs/content/templates/functions.md
- tpl/lang/init.go
- tpl/lang/lang.go
- tpl/lang/lang_test.go
numFormat formats a number with a given precision using the requested decimal,
grouping, and negative characters.
Fixes #1444
> tpl/lang: Add NumFmt function

- tpl/collections/collections.go
- tpl/collections/collections_test.go
Unsupported types are currently silently ignored by IsSet.  An earlier
attempt was made to solve the issue by returning an error.  That attempt
was reverted since it broke some existing themes.
So instead, we'll log an error.  Hopefully, people will stop using IsSet
in this way, and we can eventually return an error outright.
Updates #3092
> tpl/collections: Log an error on unsupported types in IsSet

- docs/content/tools/_index.md
The unmaintained Rango frontend and the Hugopit "experiment" should be removed from the Hugo Tools/Frontends section of the documentation as they are unusable.
Rango can mess up with other dependencies installed in the Go Path as reported here: 
https://github.com/stayradiated/rango/issues/4
Hugopit's developer himself stated that this is an unmaintained experiment and he seemed a bit surprised that it is included in Hugo's documentation over here: https://github.com/sjardim/Hugopit/issues/3
> docs: Remove Unmaintained Frontends from Tools

- hugolib/page_collections.go
- hugolib/site.go
When we know to look into the index pages collection, do that:
```
benchmark              old ns/op     new ns/op     delta
BenchmarkGetPage-4     51483         7072          -86.26%
benchmark              old allocs     new allocs     delta
BenchmarkGetPage-4     71             71             +0.00%
benchmark              old bytes     new bytes     delta
BenchmarkGetPage-4     2648          2648          +0.00%
```
This commit also returns an error if .Site.GetPage is called with the regular Page Kind, as that is currently not supported.
Fixes #3503
> Speed up GetPage

- cache/partitioned_lazy_cache.go
- cache/partitioned_lazy_cache_test.go
- hugolib/page.go
- hugolib/page_collections.go
- hugolib/page_collections_test.go
- hugolib/site.go
- hugolib/site_test.go
> hugolib: Support regular pages in .Site.GetPage

- docs/content/extras/shortcodes.md
Since 'autostart' is not the correct name of the parameter, I changed the words to make this section more clear.
> Fix parameter name in YouTube shortcode section.

- hugolib/site_benchmark_test.go
```
▶ go test -run="NONE" -bench="BenchmarkSiteBuilding.*"  -test.benchmem=true ./hugolib
BenchmarkSiteBuilding/num_root_sections=1/num_pages=10/render=false-4                 2000       1291745 ns/op      344566 B/op        4632 allocs/op
BenchmarkSiteBuilding/num_root_sections=1/num_pages=10/render=true-4                   500       2700312 ns/op      633817 B/op       10775 allocs/op
BenchmarkSiteBuilding/num_root_sections=1/num_pages=100/render=false-4                 200       7501431 ns/op     3242208 B/op       41776 allocs/op
BenchmarkSiteBuilding/num_root_sections=1/num_pages=100/render=true-4                  100      14165829 ns/op     4712458 B/op       73519 allocs/op
BenchmarkSiteBuilding/num_root_sections=1/num_pages=500/render=false-4                  30      37451925 …
```
> hugolib: Add site building benchmarks

- source/file.go
```
benchmark                                                                                                                     old ns/op     new ns/op     delta
BenchmarkSiteBuilding/frontmatter=YAML|num_root_sections=1|num_pages=5000|tags_per_page=0|shortcodes=false|render=false-4     552742744     501838152     -9.21%
benchmark                                                                                                                     old allocs     new allocs     delta
BenchmarkSiteBuilding/frontmatter=YAML|num_root_sections=1|num_pages=5000|tags_per_page=0|shortcodes=false|render=false-4     3047393        2957378        -2.95%
benchmark                                                                                                                     old bytes     new bytes …
```
> source: Cache language config

- commands/new.go
- hugolib/menu_old_test.go
- parser/frontmatter.go
We still have go-toml as a transitive dependency, and it is the way to go eventually, but we care about speed, so let us wait that one out.
Note that the issue this fixes is about taxonomies, but I guess this is a general issue for sites with many pages that uses TOML as front matter.
```
benchmark                                                                                                                      old ns/op     new ns/op     delta
BenchmarkSiteBuilding/frontmatter=TOML,num_root_sections=1,num_pages=5000,tags_per_page=0,shortcodes=false,render=false-4      559588018     519948664     -7.08%
BenchmarkSiteBuilding/frontmatter=TOML,num_root_sections=1,num_pages=5000,tags_per_page=1,shortcodes=false,render=false-4      777332160     517742822     -33.39% …
```
> all: Temporarily revert to BurntSushi for TOML front matter handling

- hugolib/hugo_sites.go
- hugolib/menu_old_test.go
- hugolib/page.go
- hugolib/page_collections.go
- hugolib/site.go
- hugolib/site_render.go
- hugolib/site_sections.go
- hugolib/site_sections_test.go
- hugolib/site_test.go
- hugolib/site_url_test.go
- vendor/vendor.json
Fixes #465 
See http://hugotest.bep.is/ for a demo site.
> hugolib: Enable nested sections

- tpl/collections/collections.go
- tpl/collections/collections_test.go
Fixes #3411 
Also includes an additional commit to add missing uint support to `In`
> tpl/collections: Support interfaces in union

- hugolib/alias.go
So that Googlebot (and other search engine bots) can stop indexing these old URLs.
> Add noindex tag to HTML generated by Hugo Aliases

- docs/content/templates/rss.md
The rel attribute supports specifying a set of values, not only a single
one. Using two link elements can also cause browsers to show the feed
twice in menus.
> docs: Use single link element for RSS in example

- docs/content/templates/terms.md
In the documentation's templates -> terms page, changed **.Site** to **$.Site** because the global context was masked by the term's context created by **range**.
Otherwise, the example in the documentation cannot work.
> docs: in templates/terms, change .Site to $.Site to fix examples

- hugolib/permalinks.go
- hugolib/site_sections_test.go
This enables both the variants below:
Current (first level only):
```
"blog": ":section/:title",
```
Nested (all levels):
```
"blog": ":sections/:title",
```
Should ideally been part of Hugo 0.22, but better late than never ...
Fixes #3580
> hugolib: Support sub-sections in permalink settings

- commands/new.go
- create/content.go
- create/content_template_handler.go
- create/content_test.go
- parser/frontmatter.go
This commit removes the fragile front matter decoding, and takes the provided archetype file as-is and processes it as a template.
This also means that we no longer will attempt to fill in default values for `title` and `date`.
The upside is that it is now easy to create these values in a dynamic way:
```toml
+++
title = {{ .Name | title }}
date = {{ .Date }}
draft = true
+++
```
You can currently use all of Hugo's template funcs, but the data context is currently very shallow:
* `.Type` gives the archetype kind provided
* `.Name` gives the target file name without extension.
* `.Path` gives the target file name
* `.Date` gives the current time as RFC3339 formatted string
The above  will probably be extended in #1629.
Fixes #452
Updates #1629
> create: Use archetype template as-is as a Go template

- commands/new.go
- create/content.go
- create/content_template_handler.go
- create/content_test.go
- helpers/path.go
- helpers/pathspec.go
This commit completes the "The Revival of the Archetypes!"
If `.Site` is used in the arcetype template, the site is built and added to the template context.
Note that this may be potentially time consuming for big sites.
A more complete example would then be for the section `newsletter` and the archetype file `archetypes/newsletter.md`:
```
---
title: "{{ replace .TranslationBaseName "-" " " | title }}"
date: {{ .Date }}
tags:
- x
categories:
- x
draft: true
---
{{ range first 10 ( where .Site.RegularPages "Type" "cool" ) }}
* {{ .Title }}
{{ end }}
```
And then create a new post with:
```bash
hugo new newsletter/the-latest-cool.stuff.md
```
**Hot Tip:** If you set the `newContentEditor` configuration variable to an editor on your `PATH`, the newly created article will be opened.
The …
> commands, create: Add .Site to the archetype templates

- hugolib/config.go
- hugolib/site.go
Note that even with this setting enabled, the aliases themselves are preserved on the pages.
The big motivation for this change is to be able to use the alias definitions to generate `.htaccess` or Netlify's `_redirect` files with server-side redirects.
Fixes #3613
> hugolib: Add disableAliases

- hugolib/page_paths.go
- hugolib/page_paths_test.go
- hugolib/site_output_test.go
- media/mediaType.go
- media/mediaType_test.go
- output/layout.go
- output/layout_test.go
This change is motivated by Netlify's `_redirects` files, which is currently not possible to generate with Hugo.
This commit adds a `Delimiter` field to media type, which defaults to ".", but can be blanked out.
Fixes #3614
> media, hugolib: Support extension-less media types

- create/content.go
- create/content_test.go
- helpers/path.go
It now properly uses the extension of the target file to determine archetype file.
Fixes #3597
Fixes #3618
> Support non-md files as archetype files

- commands/hugo.go
This ensures the new "open 'current content page' in browser" works
on Windows, especially with Emacs and Vim.
Special thanks to @bep for coming up with the idea of the fix.
See #3645
> Make `--navigateToChanged` more robust on Windows

- helpers/content.go
reStructuredText doesn't have explicit section levels but sets them in
the order of appearance. Since level 1 is already set from the title in
the front matter it makes more sense to start with level 2 when
converting with rst2html.
> helpers: add --initial-header-level=2 to rst2html

- tpl/tplimpl/template_embedded.go
1. Set `disqus_identifier`, `disqus_title`, and `disqus_url` only if the user has explicitly provided them in the metadata of a post. Two reasons:
1. If Hugo does not set them explicitly, Disqus knows how to fetch them anyway. The shortname is the only required variable for Disqus, and all other variables are optional.
1. If Hugo sets them, there are two problems:
1. `disqus_identifier` is set to `.Permalink` by default, which is identical to `disqus_url` in the current template. This is not only redundant, but also defeats the purpose of `disqus_identifier`: the identifier is introduced to instruct Disqus to load the same discussion thread for a page even if its URL has been changed. In other words, it is supposed to be a fixed value, independent of the page URL. Ideally this should be …
> Improve the built-in Disqus template

- tpl/tplimpl/template_embedded.go
In accordance to the official guide: https://disqus.com/admin/universal/
> Simplify the Disqus template a little bit

- docs/content/templates/functions.md
- tpl/math/init.go
- tpl/math/math.go
- tpl/math/math_test.go
It might be very useful for building nice tag clouds
Example:
Tag cloud built without log:
Tag cloud built with log:
> Add log function for templates

- tpl/collections/apply.go
- tpl/collections/collections.go
- tpl/collections/collections_test.go
- tpl/collections/reflect_helpers.go
- tpl/collections/where.go
This enables `AND` (`intersect`)  and `OR` (`union`)  filters when combined with `where`.
Example:
```go
{{ $pages := where .Site.RegularPages "Type" "not in" (slice "page" "about") }}
{{ $pages := $pages | union (where .Site.RegularPages "Params.pinned" true) }}
{{ $pages := $pages | intersect (where .Site.RegularPages "Params.images" "!=" nil) }}
```
The above fetches regular pages not of `page` or `about` type unless they are pinned. And finally, we exclude all pages with no `images` set in Page params.
Fixes #3174
> tpl/collections: Add Pages support to Intersect and Union

- commands/undraft.go
- commands/undraft_test.go
> commands: Support human-readable YAML boolean values in undraft

- hugolib/hugo_sites_build_test.go
- hugolib/page.go
- hugolib/shortcode.go
- hugolib/shortcode_test.go
- output/docshelper.go
- output/layout.go
- output/layout_test.go
This applies to both regular templates and shortcodes. So, if the site language is French and the output format is AMP, this is the (start) of the lookup order for the home page:
1. index.fr.amp.html
2. index.amp.html
3. index.fr.html
4. index.html
5. ...
Fixes #3360
> output: Support templates per site/language

- commands/hugo.go
When working with content from IntelliJ IDE, like WebStorm, every file save is followed by two events: "RENAME" and then "CREATE".
This PR adds support for reacting on "CREATE" event for navigating user to that URL.
> commands: Navigate to changed on CREATE

- Makefile
- bench.sh
- benchSite.sh
Add a variable to the makefile and benchmark scripts to let users change the command used to build. Doesn't impact tools like govendor.
> Add GOEXE to support building with different versions of `go`

- helpers/content.go
- hugolib/page_test.go
- hugolib/shortcode_test.go
This will help to understand and fix errors by seeing stacktrace of an error.
> helpers: Add --trace to asciidoctor args

- tpl/data/cache.go
Use a hash for the cache key, to fix 'file name too long' errors when retrieving from long urls
Fixes #3690
> tpl: Use hash for cache key

- Dockerfile
- add [govendor](https://github.com/kardianos/govendor) to build process of hugo
*update for: #3666*
Cheers Maik
> build(go): add govender for the build process

- Dockerfile
Hi @anthonyfok,
i just ask myself:
Few days before we talked about `size matters` and how to optimize it in #3730.
We started with 428M and optimized it to 277M.
What would you say to make it even a little bit smaller and give you a 27M Container without waiting for any Docker releases and just do it the good old way?
cheers maik
> perf(dockerfile): xtrem awesome container size optimization

- commands/hugo.go
- hugolib/config.go
Why:
* first time using hugo I got very little info from --verbose output
but I noticed there is quite a lot of useful DEBUG logging
* asked for in other issues like https://github.com/gohugoio/hugo/issues/3514
This change addreses the need by:
* adding a simple --debug flag which simply turns on debug level in stdout
and logoutput if enabled.
> add --debug option to be improved on over time

- tpl/internal/templatefuncRegistry_test.go
> tpl: Accommodate gccgo in TestMethodToName

- vendor/vendor.json
I realized that some dependencies are not in use anymore. To see which dependencies are still in use I ran [`dep init`](https://github.com/golang/dep) and compared [the results](https://github.com/gohugoio/hugo/files/1187802/Gopkg.toml.txt) to the `vendor.json` file.
All unused dependencies are removed now. All `make` commands are still working.
Hope I'm not missing anything.
> Remove unused dependencies from vendor.json

- docs/content/getting-started/configuration.md
- helpers/general.go
- helpers/general_test.go
- hugolib/config.go
- hugolib/site.go
- tpl/strings/init.go
- tpl/strings/init_test.go
- tpl/strings/strings.go
- tpl/strings/strings_test.go
- vendor/vendor.json
This works for the `title` func and the other places where Hugo makes title case.
* AP style (new default)
* Chicago style
* Go style (what we have today)
Fixes #989
> Make the title case style guide configurable

- hugolib/site.go
- hugolib/site_test.go
- tpl/inflect/inflect.go
- vendor/vendor.json
Original package has received updates the fork hasn't.
Without fork updates are easier to maintain.
Not sure if I'm missing a previous reason why the project was forked.
> Switch from fork bep/inflect to markbates/inflect

- helpers/content_renderer.go
- helpers/content_renderer_test.go
As per the referenced issue, if the task list in Markdown has
nothing before it, it will be rendered wrongly:
```
---
title: "My First Post"
date: 2017-07-29T20:21:57+02:00
draft: true
---
```
is rendered as:
```
<ul> class="task-list"
<li><input type="checkbox" disabled class="task-list-item"> TaskList</li>
</ul>
```
The problem lies in the `List` function of `HugoHTMLRenderer`, it had
a hardocded index of `4` for the first `>` of the list, it is used to
insert the class into the text before the closing bracket, but that
hardcoded index is only right when there is a newline before the
opening bracket, which is the case when there is anything in the
document before the task list, but if there is nothing, then there is
no newline, and the correct index of the first `>` will be `3`.
To fix …
> helpers: Fix broken TaskList in Markdown

- create/content_template_handler.go
- deps/deps.go
- docshelper/docs.go
- helpers/baseURL.go
- helpers/content.go
- helpers/content_renderer.go
- helpers/hugo.go
- helpers/language.go
- helpers/path.go
- hugofs/fs.go
- hugolib/handler_base.go
- hugolib/handler_meta.go
- hugolib/multilingual.go
- hugolib/page_output.go
- media/mediaType.go
- output/layout.go
- releaser/releasenotes_writer.go
- releaser/releaser.go
- source/file.go
- source/inmemory.go
- tpl/fmt/fmt.go
- tpl/math/math.go
- tpl/os/os.go
- tpl/partials/partials.go
- tpl/strings/truncate.go
- tpl/template.go
- tpl/tplimpl/templateProvider.go
- tpl/urls/urls.go
- transform/livereloadinject.go
- watcher/batcher.go
As pointed out by the linter, some exported functions and types are missing doc comments.
The linter warnings have been reduced from 194 to 116.
Not all missing comments have been added in this commit though.
> Add some missing doc comments

- source/file.go
- source/file_test.go
Right now, the UniqueID is calculated with a `\` as path separator in Windows which cause the md5 sum to be different from a Linux build, and so anything relying on UniqueID to break with regards to portability (and local testing when using a different system). This fix this by simply using `filepath.ToSlash` for the md5 sum.
> source: Normalize UniqueID between Windows & Linux

- hugolib/config.go
- hugolib/config_test.go
Our team needs multiple configs for the same doc site to support different delivery channels.
We'd like to have a base config.toml and one or more child config.tomls overriding properties in the config.
I didn't see support for repeating command-line options in Cobra.  
I've added the ability pass multiple config files via `--config` as a comma delimited string.
For example: `hugo --config=base.toml,child1.toml,child2.toml`
Use viper's MergeConfig() to merge changes.
> Added support for multiple config files via --config a.toml,b.toml,c.toml

- hugolib/embedded_shortcodes_test.go
- tpl/tplimpl/template_embedded.go
Web accessibility standards require that iFrame tags have a title explaining what the iFrame does. This is outlined here:
https://dequeuniversity.com/tips/provide-iframe-titles
The new Google auditing tool, Lighthouse, catches iFrames that do not have the title property and scores them with penalty.
The `title="YouTube Video"` should be more than enough when describing a YouTube video under all circumstances.
> Added iFrame Title to the YouTube Shortcode

- hugolib/page.go
- hugolib/page_test.go
```bash
name              old time/op    new time/op    delta
ReplaceDivider-4   9.76µs ±105%    7.96µs ±24%     ~     (p=0.690 n=5+5)
name              old alloc/op   new alloc/op   delta
ReplaceDivider-4    3.46kB ± 0%    1.54kB ± 0%  -55.56%  (p=0.008 n=5+5)
name              old allocs/op  new allocs/op  delta
ReplaceDivider-4      6.00 ± 0%      1.00 ± 0%  -83.33%  (p=0.008 n=5+5)
```
> hugolib: Rewrite replaceDivider to reduce memory allocation

- compare/eq.go
- hugolib/page.go
- tpl/compare/compare.go
- tpl/compare/compare_test.go
And use it in `eq` and `ne` so `Page` values can be compared directly in the templates without thinking about it being a `Page` or a `PageOutput` wrapper.
Fixes #3807
> compare, hugolib, tpl: Add Eqer interface

- tpl/strings/init.go
- tpl/strings/strings.go
- tpl/strings/strings_test.go
These funcs were added during the move to namespaces but were
undocumented.  This commit fixes the order of the arguments and adds the
funcs to the method mapping.
> tpl: Cleanup strings.TrimPrefix and TrimSuffix

- livereload/livereload.go
This fixes #3824: when the current pathname is the same as the one to be loaded, just call `location.reload()` so that the current scroll position can be preserved, instead of assigning to `location.href`, which will cause the scroll position to be lost.
> livereload: Maintain the scroll position if possible

- common/types/types.go
- common/types/types_test.go
- docs/content/content-management/related.md
- hugolib/page.go
- hugolib/pageCache.go
- hugolib/pageCache_test.go
- hugolib/pageGroup.go
- hugolib/pageSort_test.go
- hugolib/pages_related.go
- hugolib/pages_related_test.go
- hugolib/site.go
- related/inverted_index.go
- related/inverted_index_test.go
- tpl/collections/collections.go
- tpl/collections/init.go
Several attempts have been started to fix #98 --  all of them have failed for some reason. It is a hard problem to solve, and I think the main reason for failure has been the bottom-up-approach, i.e. we have started with the hardest problem: Solving [Sherlock's last case](https://github.com/joearms/sherlock).
The reason I'm picking up this ball again now is this Twitter thread:
https://twitter.com/scott_lowe/status/898398437527363585
Using `intersect` and keywords in page params work reasonably well, but it is quadratic and will be slow to unusable for larger sites.
So, instead of solving the hardest problem, I have started on this PR by outlining an interface:
```go
type PageSearcher interface {
Search(args ...interface{}) (Pages, error)
SearchIndex(index string, args ...interface{}) …
```
> Work In Progress: hugolib: Add page search, i.e. related content

- tpl/time/init.go
- tpl/time/time.go
- tpl/time/time_test.go
And with time.Duration with the convenient alias `duration`:
```
{{ mul 60 60 | duration "second" }}
```
Fixes #3828
> tpl/time: Add time.Duration and time.ParseDuration template funcs

- hugolib/site_output_test.go
- tpl/tplimpl/template.go
- tpl/tplimpl/template_test.go
> tpl/tplimpl: Fix escaped HTML Go 1.9 multioutput issue

- tpl/math/math.go
- tpl/math/math_test.go
- tpl/math/round.go
Ceil and Floor are frontends for the stdlib math functions. The Round
implementation is essentially the same thing except that the Go stdlib
doesn't include a Round implementation in a stable release yet.  I've
included the Round function slated for Go 1.10.
Fixes #3883
> tpl: Add math.Ceil, Floor, and Round

- tpl/urls/urls.go
- tpl/urls/urls_test.go
Add a urls.Parse template function that front-ends url.Parse from the Go
stdlib.
Fixes #3849
> tpl: Add urls.Parse function

- snapcraft.yaml
Include the git binaries in the generated snap package so that hugo --enableGitInfo works.
This patch was tested by building a new package with snapcraft, using hugo source at the v0.26 tag.
Fixes #3896
> snap: Add git to snap package for GitInfo

- Dockerfile
Hi, Thanks for this project, very nice using it.
I noticed the Dockerfile at the root of the project, which is nice, and found some little optimisations thanks to  [latest docker updates (17.05:)](https://docs.docker.com/engine/userguide/eng-image/multistage-build/)
This pull request adds support for multi-stage build allowing to have shorter build time when updating hugo code itself.
As a side effect it builds the image from the working directory instead of getting master from github and reduces, in my measurements, the size of the image from 20MB to 16MB
On another hand, I didn't find an _official_ image in the docker registry. Would it be an option to create an automated build from this repo?
> Improve docker image build

- docs/content/functions/float.md
- tpl/cast/cast.go
- tpl/cast/cast_test.go
- tpl/cast/init.go
Add a template function that allows conversion to float. This is
useful, for example, when passing aspect ratios into templates,
which tend to not be integers.
Fixes #3307 
Feedback very welcome, this is the first time I've tampered with the hugo source 🎉
> tpl: Add float template function

- docs/content/functions/fileExists.md
- tpl/os/init.go
- tpl/os/os.go
- tpl/os/os_test.go
This pull request is intended to fix #3839
Currently, I've an issue with the test cases. `fileExists` returns a boolean and an error / `nil`.
Due to the type assertion `false` can become ambiguous: it can either mean that a file does not exist or that an error is expected.  
If the file does not exist, `fileExists` returns `false` (correctly), implicating that no error occurred, but the test fails because `false` is interpreted like an expected error.
Any ideas how this ambiguity can be circumvented?
> tpl: Add os.fileExists template function

- docs/content/getting-started/configuration.md
- helpers/content.go
- helpers/content_test.go
- hugolib/config.go
- hugolib/page.go
Move SummaryLength into the ContentSpec struct and refactor the
relevant summary functions to be methods of ContentSpec. The new
summaryLength struct member is configurable by the summaryLength config
value, and the default remains 70. Also updates hugolib/page to use the
refactored methods.
Resolves #3734
> Change SummaryLength to be configurable

- docs/content/functions/errorf.md
- tpl/fmt/fmt.go
- tpl/fmt/init.go
Add template function that will build a string from the given format
string and arguments, then log it to ERROR. This has an intended
side-effect of causing the build to fail, when executed.
Resolves #3817 
I'm not 100% confident everything is done properly. Things I'm unsure about:
1. Could logging to error during `go test` have bad side effects?
2. Is `jww.ERROR` the correct logger to use for this? I tried to copy the style i saw in tpl/data.
3. Is there a way I can also log the template/content that executed the `errorf` call? I think it should be more verbose.
>  tpl: Add errorf template function

- magefile.go
This closes #3909.  The magefile should be identical in functionality
to the current makefile.  It uses the current master of mage.  I wasn't
sure if I should add mage to the vendor directory or what (probably
should).  Wanted to get this up for others to review.
> Add magefile

- tpl/tplimpl/template_embedded.go
This removes `xmlns:xhtml="http://www.w3.org/1999/xhtml"` from the default sitemap when there are no translation links available. The translation links were added in #3348.
> tplimpl: Output xmlns:xhtml only if there are translations available

- commands/hugo.go
The verbose output for server was not displaying the current
configuration file name. The log used a global 'viper'
variable. Replaced that with the 'config' variable.
With this change, the verbose log now shows:
INFO 2017/10/08 22:21:00 Using config file: config.toml
Note that there's still an issue when using multiple config
files. The routine is hard coded to show only the first file
read.
> Replaced unused 'viper' variable in server log

- commands/commandeer.go
- commands/hugo.go
- commands/server.go
- common/types/evictingqueue.go
- common/types/evictingqueue_test.go
- docs/content/getting-started/quick-start.md
- hugolib/config.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/site.go
- hugolib/site_render.go
Looks promising ... This is **35 times faster** than doing the same thing with the current Hugo. There are some missing pieces in this PR (uglyURLs handling etc.), but it holds water.
/cc @spf13 @budparr and gang.
> Only re-render the view(s) you're working on

- magefile.go
fixes #3990 - gofmt doesn't actually exit with non-zero when it finds unformatted
stuff so we have to check it for non-empty output, and fail on that.
> print gofmt errors in mage

- Gopkg.toml
v0.3.0 was released in March 2017 and is missing few fixes made in toml package
after the fact. So use the master branch instead.
This fixes a regression when switch was made from govendor vendor.json dep
management to Go dep.
Fixes #3998
> Update toml dep to fetch its latest master branch instead of v0.3.0

- docs/content/content-management/taxonomies.md
- docs/content/content-management/urls.md
- hugolib/page.go
- hugolib/page_paths.go
- hugolib/taxonomy_test.go
Return the correct virtual Section for Taxonomy and TaxonomyTerm.
Restrict permalink expansion to only Pages and Taxonomies, but then
actually use expanded permalinks even for non-Pages.
Fixes #1208.
> Handle Taxonomy permalinks

- hugolib/page.go
- hugolib/page_test.go
- hugolib/translations.go
This commit refines the key used to map translations:
* Use `translationKey` set in front matter
* Fall back to path + base filename (i.e. the filename without extension and language code)
Note that the Page Kinde will be prepended to both cases above. It does not make sense to have a section as translation for the home page.
Fixes #2699
> hugolib: Fix .IsTranslated  with identical filenames

- helpers/path.go
- helpers/pathspec.go
- helpers/pathspec_test.go
- hugolib/site.go
* In Hugo there is no single static dir
* It was used as a filter in the content dir, which makes no sense since any overlap here is impossible
> helpers: Remove (now) unused GetStaticDir

- hugolib/shortcodeparser.go
It was clever, but storing the items in a slice is faster -- and it gives room to more goroutines in other places.
```bash
benchmark                     old ns/op     new ns/op     delta
BenchmarkShortcodeLexer-4     180173        79614         -55.81%
benchmark                     old allocs     new allocs     delta
BenchmarkShortcodeLexer-4     309            328            +6.15%
benchmark                     old bytes     new bytes     delta
BenchmarkShortcodeLexer-4     35456         47008         +32.58%
```
> Remove the goroutines from the shortcode lexer

- hugolib/menu.go
- hugolib/menu_old_test.go
- hugolib/menu_test.go
- hugolib/page.go
This PR allows to set a title for a MenuEntry in the site config menus.
This allows to render anchor links in menus which have a title attribute:
```
{{ range .Site.Menus.main }}
<a href="{{ .URL }}" title="{{ .Title }}">
{{ .Pre }}
<span>{{ .Name }}</span>
</a>
{{ end }}
``` 
This feature is useful for screenreaders and SEO.
I didn't implement the same in the frontmatter menu field, because the attribute `title` is too generic. `linkTitle` or `anchortitle` might be better names.
I would love if you could merge this and we figure out if the title attribute is something people need in frontmatter menues. I only use site config menues yet.
> add Title to MenuEntry

- livereload/livereload.go
Compare the original hosts from 'Origin' and 'Host' headers before
attempting to do a port-less comparison.  This helps in the case when
hugo server was started with a '--port=80' so both headers do not
contain a port.
Fixes #4141
> livereload: Fix host comparison when ports aren't present

- helpers/content.go
- helpers/content_renderer_test.go
- helpers/content_test.go
- hugolib/config.go
- hugolib/page.go
- tpl/transform/transform.go
This is in heavy use in rendering, so this makes a difference:
```bash
benchmark                                                                                    old ns/op     new ns/op     delta
BenchmarkSiteBuilding/TOML,num_langs=1,num_pages=500,tags_per_page=5,shortcodes,render-4     124551144     107743429     -13.49%
benchmark                                                                                    old allocs     new allocs     delta
BenchmarkSiteBuilding/TOML,num_langs=1,num_pages=500,tags_per_page=5,shortcodes,render-4     528684         435118         -17.70%
benchmark                                                                                    old bytes     new bytes     delta
BenchmarkSiteBuilding/TOML,num_langs=1,num_pages=500,tags_per_page=5,shortcodes,render …
```
> Reuse the BlackFriday instance when possible

- Gopkg.lock
- Gopkg.toml
- helpers/general.go
- helpers/general_test.go
- resource/image.go
- resource/image_test.go
- resource/resource.go
But only a set of byte chunks spread around in the image file to calculate the fingerprint, which is much faster than reading the whole file:
```bash
BenchmarkMD5FromFileFast/full=false-4         	  300000	      4356 ns/op	     240 B/op	       5 allocs/op
BenchmarkMD5FromFileFast/full=true-4          	   30000	     42899 ns/op	   32944 B/op	       5 allocs/op
```
Fixes #4186
> resource: Use MD5 to identify image files

- helpers/language.go
- hugolib/config.go
Static content was wrongly put into the lang-code subfolder.
Fixes #4221
> Fix multihost detection for sites without language definition

- hugolib/hugo_sites.go
- hugolib/taxonomy_test.go
* We match by path vs taxonomy to determine if we have a content page for that taxonomy
* The taxonomy name is (if `preserveTaxonomyNames` is not set) normalized to `maxmustermann` while you have the disk folder called `MaxMustermann`.
* This isn't a new issue, but I suspect most people will just name the folder `authors/maxmustermann` and it will just work.
* The inconsistent behaviour you see here is that you will end up with two pages with the same target filename, so it is a little random who will win.
This fixes that by also normalizing the taxonomy path when doing the comparison.
Fixes #4238
> hugolib: Fix handling of mixed-case taxonomy folders with content file

- CONTRIBUTING.md
- appveyor.yml
- magefile.go
- snapcraft.yaml
Currently Hugo's mage build targets depend on the Vendor target, meaning that `go get -u github.com/golang/dep/cmd/dep` is executed each and every time. Not only does this unnecessarily slow builds, it prevents builds when one's machine is offline (no internet access). 
Since Mage now supports invoking multiple build targets, there is no longer a need to hardcode the dependency on the Vendor target. For example:
- offline build: `mage Hugo`
- online build, with updated dependencies: `mage Vendor Hugo`
> Support offline builds

- hugolib/node_as_page_test.go
- hugolib/page.go
- hugolib/page_paths.go
This enables some potential foot-shooting, but is needed for some special URL requirements.
Fixes #4263
> hugolib: Allow url in front matter for list type pages

- hugolib/hugo_sites_build_test.go
- hugolib/page_collections.go
You can still use the full path with extensions, but to get the current language version:
* If the content file lives in `/content/blog/mypost.en.md`
* Use `.Site.GetPage "page" "blog/mypost"`
Fixes #4285
> Improve .Site.GetPage for regular translated pages

- hugolib/page.go
- hugolib/page_test.go
`Site.kindFromFilename()` was a bit loose in its logic and inconsistent with `FileInfo.TranslationBaseName()`, which only recognizes language codes explicitly configured for the site. This is illustrated by running the tests I added with the original `page.go` and looking at the failures. It was also a bit inefficient, reparsing file path that had already been parsed before by `FileInfo`. 
I replaced `Site.kindFromFilename(filename string)` with `Site.kindFromFileInfo(fi *fileInfo)` with tighter logic and introduced tests (there was no testing of this logic before).
> Tighten page kind logic, introduce tests

- resource/resource.go
- resource/resource_test.go
```toml
[[resources]]
src = "documents/photo_specs.pdf"
title = "Photo Specifications"
[resources.params]
ref = 90564687
icon = "photo"
[[resources]]
src = "documents/guide.pdf"
title = "Instruction Guide"
[resources.params]
ref = 90564568
[[resources]]
src = "documents/checklist.pdf"
title = "Document Checklist"
[resources.params]
ref = 90564572
[[resources]]
src = "documents/payment.docx"
title = "Proof of Payment"
[[resources]]
src = "documents/*.pdf"
title = "PDF file"
[resources.params]
icon = "pdf"
[[resources]]
src = "documents/*.docx"
title = "Word document"
[resources.params]
icon = "word"
```
In the above `TOML` example, `photo_specs.pdf` will get the `photo` icon, the other pdf files will get the default `pdf` icon.
Note that in the example above, the order matters: It will …
> Merge matching resources params maps

- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/page.go
- hugolib/page_bundler_test.go
- hugolib/page_collections.go
- hugolib/site_render.go
This commit adds  support for `headless bundles` for the `index` bundle type.
So:
```toml
headless = true
```
In front matter means that
* It will have no `Permalink` and no rendered HTML in /public
* It will not be part of `.Site.RegularPages` etc.
But you can get it by:
* `.Site.GetPage ...`
The use cases are many:
* Shared media galleries
* Reusable page content "snippets"
* ...
Fixes #4311
> Add headless bundle support

- hugolib/page_bundler_capture_test.go
- hugolib/page_bundler_test.go
- hugolib/page_collections.go
Given a bundle in `blog/my-bundle/index.en.md` all of these will now worK:
* `blog/my-bundle/index.en.md`
* `blog/my-bundle/index`
* `blog/my-bundle`
* `my-bundle`
The last one is potentially ambigous.
Fixes #4312
> hugolib: Simplify bundle lookup via .Site.GetPage, ref, relref

- commands/server.go
- config/configProvider.go
- helpers/language.go
- hugolib/config.go
- hugolib/fileInfo.go
- hugolib/page_bundler_capture.go
- hugolib/page_bundler_capture_test.go
- hugolib/page_bundler_test.go
- hugolib/site.go
- source/sourceSpec.go
This commit adds a new config setting:
```toml
disableLanguages = ["fr"]
```
If this is a multilingual site:
* No site for the French language will be created
* French content pages will be ignored/not read
* The French language configuration (menus etc.) will also be ignored
This makes it possible to start translating new languages and turn it on when you're happy etc.
Fixes #4297
Fixed #4329
> Add a way to disable one or more languages

- tpl/collections/collections.go
https://github.com/gohugoio/hugo/blob/ed4a00e46f2344320a22f07febe5aec4075cb3fb/tpl/collections/collections.go#L477-L482
in the Line 477,we set the random seed.But there is a situation that the seed will be the same.So the `randomIndices ` we get in the Line 478 will be the same.
eg.
I need to random a background picture for each article.But sometimes the picture will be the same.
So I changed.Set the random seed in the function `init`.
> shuffle random seed

- commands/import_jekyll.go
- commands/import_jekyll_test.go
When importing from Jekyll, Hugo adds the `url` attribute to the frontmatter for _all_ posts and assumes that the final desired permalink structure is `/:year/:month/:day/:title/`.
This may be the case for a lot of peeps, but poses a problem for those that don't use this permalink structure as the `url` attribute takes precedence over the `permalink` attribute in the site-wide configuration meaning it can't be overruled.
This PR resolves this by only setting the `url` attribute if the `permalink` attribute is set in the Jekyll frontmatter.
Tests have been updated to reflect this change in behaviour too.
Whilst I'm at it, I've also removed the duplication of the confirmation message:
Before:
```
Importing...
Congratulations! 459 post(s) imported!
Now, start Hugo by yourself:
$ git clone …
```
> import_jekyll: Only set 'url' if 'permalink' in metadata & remove duplicate confirm msg

- helpers/language.go
- helpers/language_test.go
- hugolib/hugo_sites_build_test.go
- hugolib/multilingual.go
This fixes some issues with language params handling by separating params from configuration values per language.
This means that you can now do this:
```toml
[languages]
[languages.en]
languageName = "English"
weight = 1
title = "My Cool Site"
[languages.en.params]
myParam = "Hi!"
```
This is not a breaking change, but the above is a less suprising way of configuring custom params.
It also fixes some hard-to-debug corner-cases in multilingual sites.
Fixes #4356
Fixes #4352
> Fix language params handling

- hugolib/datafiles_test.go
- hugolib/site.go
- parser/frontmatter.go
Fixes #4361, a regression introduced in Hugo v0.35.
The first commit includes new test code that was also submitted via #4372 against the v0.34 branch to demonstrate that the updates tests did in fact all pass for that release. They will fail in this PR, against v0.35 code, until the second commit with the fix is added. 
The new tests:
*  Add retro-coverage for #4361, the regression fixed by the PR
*  Verify open issues #4138, #3890, #4366, #4083
*  Remove test reliance on the very code it is testing (hugo/parser package).
Expected results are now all built manually / are more precise.
Tests can run against different versions (no linkage errs)
A comprehensive fix is not trivial because Hugo uses three different three unmarshalers that behave differently for the same data structures. In …
> Fix JSON array-based data file handling regression

- hugolib/template_test.go
- tpl/tplimpl/template.go
The tplimpl package was misusing the TemplateLookupDescriptor.WorkingDir
field from the output package. By incorrectly setting it to the theme
directory instead of the site root, the user is unable to override theme
templates in some situations.
Fixes #3505
> tpl: Ensure site templates can override theme templates

- parser/frontmatter.go
- parser/frontmatter_test.go
To support boolean keys, the `yaml` package unmarshals maps to `map[interface{}]interface{}` (see: https://github.com/go-yaml/yaml/issues/139). This behaviour is unexpected in Hugo case and breaks maps ranging and converting to json. This PR follows many `yaml` package dependent projects and changes all maps to `map[string]interface{}` like we would've gotten from `json`. Config exported by https://github.com/go-yaml/yaml would be perfect solution but it looks like it will not come quickly.
Fixes #2441, #4083
> parser: Fix YAML maps key type

- tpl/tplimpl/template_embedded.go
This change is made in the "twitter_cards" internal template.
References:
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image
- https://twittercommunity.com/t/twitter-image-src-or-twitter-image/16085/7
> Use more canonical "twitter:image" property, not "twitter:image:src"

- docs/content/content-management/shortcodes.md
- docs/content/templates/shortcode-templates.md
- hugolib/embedded_shortcodes_test.go
- hugolib/page_test.go
- hugolib/shortcode_test.go
- tpl/tplimpl/template_embedded.go
Also:
- Remove unnecessary space from `figure` tag if no class is specified.
- Update all the related tests.
- Add test cases for the changes made to the figure shortcode.
- Document the newly added target and rel parameters
- Add more detail to the documentation of all figure shortcode parameters.
> Add "target" and "rel" parameters to figure shortcode

- helpers/general.go
- tpl/transform/init.go
- tpl/transform/remarshal.go
- tpl/transform/remarshal_test.go
Usage:
```html
{{ "title = \"Hello World\"" | transform.Remarshal "json" | safeHTML }}
```
Fixes #4389
/cc @regisphilibert
> tpl/transform: Add template func for TOML/JSON/YAML docs examples conversion

- hugolib/datafiles_test.go
- hugolib/site.go
- parser/frontmatter.go
Proposed resolution of #4393, per @bep's comment under that issue:
> And my thoughts are this:
>
> - Front matter and /data are meant to be portable across formats (which was the reason why I closed my eyes and merged the related PR)
> - We even have commands to do conversion between them that kind of does not work because of this
> - People should be able to mix-and-match YAML and TOML etc. content
> - Theme author should be able to write portable templates
> - Having YAML keys as `interface{}` makes sorting random. The lexicographically sort you get with string keys have its own problems, but it is better than random.
>
> So, here is how I **suggest** we do this:
>
> - Keep the implementation as is now (adjust tests)
> - Add a check for non-string keys and print a WARNING to the …
> JSON, YAML and TOML data equivalency, Better array data support

- resource/image.go
- resource/image_cache.go
- resource/image_test.go
- resource/testhelpers_test.go
When doing something like this with the same image from a partial used in, say, both the home page and the single page:
```bash
{{ with $img }}
{{ $big := .Fill "1024x512 top" }}
{{ $small := $big.Resize "512x" }}
{{ end }}
```
There would be timing issues making Hugo in some cases try to process the same image with the same instructions in parallel.
You would experience errors of type:
```bash
png: invalid format: not enough pixel data
```
This commit works around that by adding a mutex per image. This should also improve the performance, sligthly, as it avoids duplicate work.
The current workaround before this fix is to always operate on the original:
```bash
{{ with $img }}
{{ $big := .Fill "1024x512 top" }}
{{ $small := .Fill "512x256 top" }}
{{ end }}
```
Fixes #4404
This PR works, …
> resource: Fix multi-threaded image processing issue

- hugolib/site_sections.go
Site.assembleSections logic assumes that the the home page would always be the first in the Site's list of pages. This is not in fact guaranteed to be true. When it is not, the method can fail to set the parent for some or all root-level pages.  
Fixes #4447
> Fix bug in Site.assembleSections method

- hugolib/site_output.go
- hugolib/site_output_test.go
- output/outputFormat.go
> Allow partial redefinition of the ouputs config

- helpers/general.go
- hugolib/config.go
- hugolib/page.go
- hugolib/page_paths.go
- hugolib/page_test.go
- hugolib/pagemeta/page_frontmatter.go
- hugolib/pagemeta/page_frontmatter_test.go
- hugolib/pagemeta/pagemeta.go
- hugolib/site.go
This commit makes it possible to extract the date from the content filename. Also, the filenames in these cases will make for very poor permalinks, so we will also use the remaining part as the page `slug` if that value is not set in front matter.
This should make it easier to move content from Jekyll to Hugo.
To enable, put this in your `config.toml`:
```toml
[frontmatter]
date  = [":filename", ":default"]
```
This commit is also a spring cleaning of how the different dates are configured in Hugo. Hugo will check for dates following the configuration from left to right, starting with `:filename` etc.
So, if you want to use the `file modification time`, this can be a good configuration:
```toml
[frontmatter]
date = [ "date",":fileModTime", ":default"]
lastmod = ["lastmod" ,":fileModTime", …
```
> hugolib: Extract date and slug from filename

- docs/content/functions/scratch.md
- hugolib/scratch.go
- hugolib/scratch_test.go
Following a [discussion](https://discourse.gohugo.io/t/delimit-and-create-array/11065/11?u=cmal) in the forums, I'm proposing a `Reset` method for Scratch, to remove a Scratch entry. It could be renamed Delete if you prefer.
This is my first time writing some golang so sorry if I'm doing some things wrong. Unfortunately, I'm running golang 1.8.1 from Debian stable so I cannot run the tests. I tried it with the following snippet and it appears to work like a charm:
```
{{ $.Scratch.Set "test" "lol" }}
{{ $.Scratch.Reset "test" }}
{{ $.Scratch.Reset "anothertest" }}
{{ $.Scratch.Add "test" "Bonjour" }}
{{ $.Scratch.Get "test" }}
```
It printed "Bonjour" like expected and did not raise an error when attempting to delete a key that did not exist (I believe this is the desired behaviour).
I …
> Add Reset method to delete key from Scratch

- Gopkg.lock
- Gopkg.toml
- commands/commandeer.go
- commands/hugo.go
- commands/server.go
- helpers/path.go
- hugolib/case_insensitive_test.go
- hugolib/config.go
- hugolib/config_test.go
- hugolib/disableKinds_test.go
- hugolib/page_bundler_test.go
- hugolib/site.go
- hugolib/testhelpers_test.go
See #4490 
This allows a config.toml in the theme to set
1) `params` (but cannot override params in project. Will also get its own "namespace", i.e. `{{ .Site.Params.mytheme.my_param }}` will be the same as `{{ .Site.Params.my_param }}` providing that the main project does not define a param with that key.
2) `menu` -- but cannot redefine/add menus in the project. Must create its own menus with its own identifiers.
3) `languages` -- only `params` and `menu`. Same rules as above.
4) **new** `outputFormats`
5) **new** `mediaTypes`
> Allow some  config from themes

- commands/server.go
- docs/content/variables/site.md
- hugolib/site.go
Fixes #4478.
Docs PR coming shortly.
Update:
Docs PR: gohugoio/hugoDocs#430
> Add .Site.Info.IsServer flag when using built-in Hugo server.

- .travis.yml
Probably related to commit 511d5d3 (moving to Ubuntu Trusty image on Travis CI), "sudo gem install" begins to have random errors like the following on Linux:
ERROR:  While executing gem ... (Errno::EACCES)
Permission denied @ rb_sysopen - /home/travis/.rvm/gems/ruby-2.4.1/cache/asciidoctor-1.5.6.2.gem
Perhaps sudo is no longer necessary, even on OS X?  Let's experiment!  :-)
> [WIP] travis: Run "gem install" without sudo

- hugolib/page_bundler_capture_test.go
- hugolib/page_bundler_test.go
Put guards around TestPageBundlerCaptureSymlinks and
TestPageBundlerSiteWitSymbolicLinksInContent so that they aren't
run on Windows (they both use symbolic links and the Go library
implementation requires administrator mode on Windows).
> Fix two tests that are broken on Windows

- snapcraft.yaml
First commit: Fix empty BuildDate, and add CommitHash for hugo-dev snap builds, by calling `mage hugoNoGitInfo` and `mage hugo` instead of relying the plain `go build` call in snapcraft's go plugin.
Second commit: Add bash completion ((called "completer" in snapcraft.yaml) to hugo snap.
> snap: Fix empty BuildDate and add bash completion

- hugofs/language_fs.go
- hugofs/language_fs_test.go
- source/fileInfo.go
- source/fileInfo_test.go
As in, more dots than just to separate the extension and any language indicator.
Fixes #4559
> Fix handling of content files with "." in them

- .travis.yml
- hugolib/page_test.go
I came across https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth, and suddenly, a light bulb lighted up.  Travis, by default, uses `--depth 50` for git clone, but over 50 commits have happened since commit ce6e4310, so inst
git log --name-only --no-merges --format="format:%ai" hugolib/testsite/content/first-post.md
returns the date of a grafted commit, which currently is "2018-03-15 09:37:30 +0100", instead of 2018-03-11.
Disabling shallow clone should hopefully fix #4584.
(Please don't merge yet; I am making it a PR to trigger a Travis CI test build.)
> [Work in progress] Fix travis

- commands/commandeer.go
- commands/hugo.go
- commands/server.go
- hugolib/config.go
We need to revisit the commands package re globals and tests, but this should fix the init order of flags and languages.
Fixes #4589
>  Fix handling of --contentDir etc. flag

- README.md
I discovered an inconsistency between the website documentation (https://gohugo.io/getting-started/installing/#source) and this README, for installing from source. I checked them both and the website seems to be newer so I would like to propose updating this README to install Hugo using mage (unless it doesn't really matter).
> Update "Advanced Install" in README.md

- docs/content/functions/get.md
- hugolib/shortcode.go
- hugolib/shortcode_test.go
Return empty string instead of crashing when a positional parameter is missing. See discussions in #4619 and [on the forums](https://discourse.gohugo.io/t/optional-shortcode-parameters-conditional-variables-assignment/).
Also, the first commit in the PR is about fixing the function signature which was mentioning `Get` function instead of `.Get`.
> .Get allows optional positional params (fixes #4619)

- deps/deps.go
- helpers/content.go
- hugolib/config.go
- hugolib/embedded_shortcodes_test.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/hugo_sites_build_test.go
- hugolib/page.go
- hugolib/pageSort.go
- hugolib/pageSort_test.go
- hugolib/page_bundler_handlers.go
- hugolib/page_bundler_test.go
- hugolib/page_test.go
- hugolib/page_without_content.go
- hugolib/shortcode.go
- hugolib/shortcode_test.go
- hugolib/site.go
- hugolib/site_render.go
This resolves some surprising behaviour when reading other pages' content from shortcodes. Note that this has never been an issue from regular templates.
Note that it will still not be possible to get **the current shortcode's  page's rendered content**. That would have made Einstein impressed.
So the current simple rules are:
* `.Page.Content` from a shortcode will be empty. The related `.Page.Truncated` `.Page.Summary`, `.Page.WordCount`, `.Page.ReadingTime`, `.Page.Plain` and `.Page.PlainWords` will also have empty values.
* For _other pages_ (retrieved via `.Page.Site.GetPage`, `.Site.Pages` etc.) the `.Content` is there to use as you please as long as you don't have infinite content recursion in your shortcode/content setup. See below.
* `.Page.TableOfContents` is good to go (but …
> Make .Content (almost) always available in shortcodes

- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/page.go
- hugolib/pageSort_test.go
- hugolib/page_test.go
- hugolib/shortcode.go
- hugolib/shortcode_test.go
- hugolib/site.go
This is a follow-up to #4632. There were some assumptions in that implementation that did not hold water in all situations.
This commit simplifies the content lazy initalization making it more robust.
Fixes #4664
> Fix some shortcode vs .Content corner cases

- helpers/content.go
- hugolib/page.go
- hugolib/page_test.go
This bug was introduced in Hugo 0.40. It is when you use the `` summary marker.
Note that this affects the word stats only. The related `PlainWords`, `Plain`, `Content` all return correct values.
Fixes #4675
> Fix .WordCount, .FuzzyWordCount, .ReadingTime when summary marker is set

- docs/content/_index.md
This could either be "check out Hugo's themes" or "check out the Hugo themes". I think the latter reads better.
> Fix index typo

- hugolib/page.go
- hugolib/shortcode.go
Sets Page.markup earlier (as early as possible, when the page is loaded). Sets it once and only once, removing many redundant calls to determineMarkupType().
This kills a sleeping bug that was avoided by the parts of the code depending on this value making those redundant calls. I encountered this bug in my fork, which I could have fixed either by adding another redundant call or making the enclosed change.
> Improve markup determination logic

- hugolib/page.go
A very trivial pull request: I was seeing an extra `\n` at the end of the warning message after adding `Logger: newWarningLogger()` (an excellent suggestion, by the way, thanks @ bep!   See #4672)
```
=== RUN   TestPageBundlerSiteRegular/ugly=false
...
WARN 2018/04/26 20:10:29 WARNING: Timed out creating content for page
"b/my-bundle/index.md" (.Content will be empty). This is most likely a circular
shortcode content loop that should be fixed. If this is just a shortcode calling
a slow remote service, try to set "timeout=20000" (or higher, value is in milliseconds)
in config.toml.\n
...
```
Thanks!
> hugolib: Use double quotes instead of back quotes in timeout warning

- commands/version.go
When hugo is not compiled with Mage, or when hugo is compiled without manually setting the appropriate `-ldflags`, `hugo version` returns a version string with an empty BuildDate.
For example, the current Hugo brew on macOS returns the following version:
Hugo Static Site Generator v0.40.1 darwin/amd64 BuildDate:
where the empty `BuildDate:` is unsettling to me, and probably to others too.
That unsettling feeling finally motivated me to fix the problem in a "reproducible" way (honouring `SOURCE_DATE_EPOCH`) in the Debian/Ubuntu package a while ago:
* https://salsa.debian.org/go-team/packages/hugo/commit/8e6ef376510873e75e5e07b11b38b681447535b8
However, despite our best effort, some users or downstream packagers are just not going to use `mage` or to set the proper `-ldflags`, sometimes due …
> commands: Do not show empty BuildDate in version

- commands/version.go
- hugolib/page_bundler_test.go
So that a timeout warning does appear if it does happen
especially on a slow machine with soft floating-point CPU.
Special thanks to @bep for the solution.
See #4672
> Show site build warning in TestPageBundlerSiteRegular

- hugolib/shortcode.go
- hugolib/shortcode_test.go
The current error handling makes parameter checking in shortcodes too verbose for no good reason.
Fixes #4745
> Do not return error on .Get "class" and vice versa in shortcodes

- config/privacy/privacyConfig.go
- config/privacy/privacyConfig_test.go
- config/services/servicesConfig.go
- config/services/servicesConfig_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/__h_simple_assets.html
- tpl/tplimpl/embedded/templates/shortcodes/instagram.html
- tpl/tplimpl/embedded/templates/shortcodes/instagram_simple.html
See it in action:
http://hugotest.bep.is/scodes/embedded-unstyled/
http://hugotest.bep.is/scodes/embedded/
Source test repo:
https://github.com/bep/hugotest
Note that how it looks depends on the current site configuration.
I have added a flag to turn off inline styling, that I think we want to make a pattern.
* Use Bootstrap 4 markup where possible
* Provide inline styles that looks OK, but can be turned off
Fixes #4748
> Add instagram_simple shortcode

- config/privacy/privacyConfig.go
- config/privacy/privacyConfig_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/google_analytics.html
- tpl/tplimpl/embedded/templates/google_analytics_async.html
The current full set of options for GA is now:
```toml
[privacy]
[privacy.googleAnalytics]
disable = false
respectDoNotTrack = true
anonymizeIP = true
useSessionStorage = true
```
Fixes #4775
> Add no-cookie variants of the Google Analytics templates

- hugolib/page.go
- resource/resource.go
Updated `Page.String()`: There are many cases where a Page has no title. Also it's path is a better identifier since it is unique. 
Added `Resource.String()`: facilitates debugging
Removed unused `genericResource.file` field.
> Enhance Page and Resource String() methods

- config/privacy/privacyConfig.go
- config/privacy/privacyConfig_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/__h_simple_assets.html
- tpl/tplimpl/embedded/templates/shortcodes/vimeo.html
- tpl/tplimpl/embedded/templates/shortcodes/vimeo_simple.html
Based on the work of @bep see: https://github.com/gohugoio/hugo/commit/448081b840db4a23c0c49c2d869ac207dcb6ac40
Related issue: #4749
Added the following:
- A simple variant for Vimeo that fetches both low and high res versions of the video thumbnail.
- Modified the Privacy Config to include the simple mode for Vimeo
- Re-included `__h_simple_assets.html` and changed the classes prefix to `__h_video` since this is meant to be used in both Vimeo and (hopefully) YouTube simple shortcodes.
- Added a SVG play button that I designed and release it under the [Apache 2.0 Licence](https://www.apache.org/licenses/LICENSE-2.0)
- CSS fixes for the standard Vimeo shortcode added `border: 0;` and removed the `top-margin: 30px` from the iframe inline style.
----
**NOTES**
The portion of the existing …
> Add vimeo_simple and CSS fixes for the standard vimeo shortcode

- hugolib/embedded_shortcodes_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/youtube.html
This PR contains the following:
- Removed the frameborder attribute from the iframe because it is [obsolete](https://www.w3schools.com/tags/att_iframe_frameborder.asp) and added `border: 0;` in the inline style
- Also removed frameborder from the test because the test fails if the attribute is not removed ([catch-22](https://www.merriam-webster.com/dictionary/catch-22)).
- On the container div I removed the `padding-top: 30px;`  from the inline style. 
What the `padding-top` CSS property does can be seen at the Hugo Docs [YT display](https://gohugo.io/content-management/shortcodes/#example-youtube-display). 
Basically it expands the `iframe` height and there are 2 scenarios depending on the browser:
1. The iframe will have black bars in the top & bottom
2. The iframe will expand to fill …
> tpl: Remove frameborder attr YT iframe + CSS fixes

- config/privacy/privacyConfig.go
- config/privacy/privacyConfig_test.go
- config/services/servicesConfig.go
- config/services/servicesConfig_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/twitter.html
- tpl/tplimpl/embedded/templates/shortcodes/twitter_simple.html
This PR contains the following:
- Simple variant for the internal Twitter shortcode with a basic set of inline styles (see attached screenshot of proposed display below)
- The CSS classes of the `blockquote` and its contents are provided by the Twitter oEmbed API.
- If the user wishes to disable the inline styles, it is possible to do so with the following configuration:
```
[services]
[services.twitter]
disableInlineCSS = true
```
> Add twitter_simple

- tpl/tplimpl/template.go
> tpl: Prevent isBaseTemplate() from matching "baseof" in dir

- docs/content/en/functions/runelen.md
- docs/content/en/functions/strings.RuneCount.md
- docs/data/docs.json
- tpl/strings/init.go
- tpl/strings/strings.go
- tpl/strings/strings_test.go
Unlike RuneCount, it does not strip HTML or whitespace before counting runes. Useful
for formatting plain text.
> Add runelen function

- hugolib/embedded_templates_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/google_analytics_async.html
This is potentially safer, faster and recommended by Google
REF: https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet
> Always load script over HTTPS

- commands/new.go
- commands/new_site.go
- commands/new_theme.go
commit a7acd073ca9432d1275de05a521e5641c880461b:
>    commands: Move nextStepsText() to new_site.go
commit a036cc8efaada4c4fbf6f7edf392197691dc0775:
>    commands: Make "new theme" feedback more intuitive
commit bdaa62ad8df43e5895a322726873976c748d3ea4
>    commands: Create _default/baseof.html in "new theme"
>    
>    Thanks to @digitalcraftsman, @bep and @rdwatters for providing the
>    actual content of the default baseof.html file.
>    
>    Fixes #3576
commit 691a35756cb0bbebbbfb5d41185abe98022bb30f
>    commands: Create LICENSE rather than LICENSE.md in "new theme"
>    
>    See also #4623
> Tweak "new theme" and "new site" subcommands

- hugolib/page_output.go
- hugolib/site.go
In Hugo 0.42, this could lead to errors of type `runtime error: invalid memory address or nil pointer dereference` in some rare situations.
Note that this was also an issue before 0.42, but the symptom was then potentially stale list content on rebuilds on content changes.
This commit also improves the above error message.
Fixes #4845
> hugolib: Reset the global pages cache on server rebuilds

- .gitattributes
Even on Windows machines, we want *.go files to have LF line
endings (go fmt insists). This leaves other files as auto, but
makes *.go files always be LF on Windows machines. With this
change, running go fmt will be a pleasant operation, not a
painful one.
Note that changing .gitattributes only affects files at initial
checkout. To update an entire working directory after making a
change like this, do this (but only after committing all work in
progress, this will destroy uncommitted changes):
$ git rm --cached -r .
$ git reset --hard
Again - do not do this to a working directory with uncommitted
work in it.
> Adds .gitattributes to force Go files to LF

- commands/new_theme.go
This pull request implements two little improvements to the theme generator. As discussed [here](https://discourse.gohugo.io/t/incomplete-generation-of-a-new-theme/12577/4) the generation of new themes seems to be incomplete to me.
After the generation of a new theme a `head.html` needs to be added, because the `baseof.html` which is generated references this partial. If the partial is missing an error is thrown. This might cause confusion for new users.
Also a doctype is useful in the `baseof.html` template, which was added with this pull request as well.
> Improve new theme generator

- hugolib/site_output_test.go
- hugolib/site_render.go
This is a recent regression in Hugo, where we have started to produce `/page/30/index.json` when the main output format (usually `HTML`) is set up with pagination.
For JSON this is potentially lot of superflous work and hurts performance.
This commit reinstates the earlier behaviour: We only create paginators if in use in the main output format.
And add a test for it to prevent this from happening again.
Fixes #4890
> hugolib: Do not create paginator pages for the other output formats

- hugolib/site_test.go
While packaging Hugo v0.43 for Debian, the Lintian tool informed me of the following:
I: golang-github-gohugoio-hugo-dev: package-contains-empty-directory usr/share/gocode/src/github.com/gohugoio/hugo/hugolib/resources/
This is something new to v0.43.  I wonder what changed.  Hmm...
After some testing, it was found that the hugolib/resources/ directory was created during `go test` run, reproducible by running:
go test -v ./hugolib/... -run TestNewSiteDefaultLang
It is a very trivial issue, and this PR of adding `defer os.Remove("resources")` is likely not the proper fix either, but I thought I should report it nevertheless.
> hugolib: Remove empty resources/ dir after TestNewSiteDefaultLang

- hugolib/config_test.go
- hugolib/page_output.go
- hugolib/page_paths.go
- hugolib/page_paths_test.go
- hugolib/pagination_test.go
- hugolib/shortcode.go
- hugolib/site.go
- hugolib/site_output_test.go
- hugolib/site_render.go
- media/mediaType.go
- media/mediaType_test.go
- output/docshelper.go
- output/layout.go
- output/layout_test.go
- output/outputFormat.go
- output/outputFormat_test.go
- resource/bundler/bundler.go
- resource/minifiers/minify.go
- resource/resource.go
- resource/resource_test.go
Before this commit, `Suffix` on `MediaType` was used both to set a custom file suffix and as a way to augment the mediatype definition (what you see after the "+", e.g. "image/svg+xml").
This had its limitations. For one, it was only possible with one file extension per MIME type.
Now you can specify multiple file suffixes using "suffixes", but you need to specify the full MIME type
identifier:
[mediaTypes]
[mediaTypes."image/svg+xml"]
suffixes = ["svg", "abc ]
In most cases, it will be enough to just change:
[mediaTypes]
[mediaTypes."my/custom-mediatype"]
suffix = "txt"
To:
[mediaTypes]
[mediaTypes."my/custom-mediatype"]
suffixes = ["txt"]
Hugo will still respect values set in "suffix" if no value for "suffixes" is provided, but this will be removed in a future release.
Note that you can …
> media: Allow multiple file suffixes per media type

- hugolib/filesystems/basefs.go
- hugolib/filesystems/basefs_test.go
Multihost is where each language has its own `baseURL`. In this configuration, static files from the theme was not picked up.
This was a regression in Hugo `0.42`. This commit also adds proper tests for this, so that does not happen again.
Fixes #4929
> hugolib: Fix static filesystem for themed multihost sites

- hugolib/resource_chain_test.go
- resource/bundler/bundler.go
- tpl/resources/resources.go
This allows the result of `.Resources.Match` and similar to be concatenated.
Fixes #4934
> Improve type support in resources.Concat

- Gopkg.lock
- resource/create/create.go
- resource/readers.go
- resource/resource.go
- resource/transform.go
Turns out `strings.Reader` implements both `io.Reader` and `io.Seeker`, so we don't need anything special.
Updates #4936
> resource: Clean up the in-memory Resource reader usage

- hugolib/config.go
- hugolib/config_test.go
When the 'allThemes' configuration setting is read, it will panic if
there are no themes. This was a regression introduced in Hugo 0.42.
Also updated a unit test to check for this.
Fixes #4851
> hugolib: Only set 'allThemes' if there are themes in the config file

- docs/content/en/tools/starter-kits.md
I did this change through GitHub's WebUI. I'm not sure why GitHub wants to change the last line in the file but the change is inconsequential.
> Fix addkit link to account for i18n

- hugolib/filesystems/basefs.go
- hugolib/filesystems/basefs_test.go
Which was the reason why `PostCSS` from theme(s) was not picked up.
Fixes #4951
> hugolib/filesystems: Fix theme config for Work Fs

- hugolib/site.go
This is unfortunate, but is needed to re-create the taxonomies collections etc. that may be referenced from them.
Fixes #4965
> hugolib: Mark shortcode changes as content changes in server mode

- hugolib/page_collections.go
I'm not sure what it takes to invoke the "Last try" lookup, as none of the tests get it, but it is clearly a bug.
> Fix typo-logic bug in GetPage

- hugolib/site_test.go
@bep These are tests from my fork that I missed including in my PR for the ref logic changes. It may seem a little redundant with the tests for GetPage, but refLinker does more than simply look up a page based on a ref: 
- It first parses the ref to separate the file path from the fragment identifier (either one, both or neither can be supplied). The current implementation uses a URL parser to parse a file path, so we cannot assume it is correct.
- Instead of returning the Page, it returns its permalink or relative permalink 
- It appends the fragment identifier onto that (tested), possible making sure it is unique (not tested yet)
So I think these tests are worth having. Your call of course.
> Increase refLinker test coverage

- hugolib/filesystems/basefs.go
- hugolib/page_bundler_capture_test.go
- hugolib/page_bundler_test.go
- hugolib/resource_chain_test.go
- hugolib/testhelpers_test.go
- resource/tocss/scss/client.go
- resource/tocss/scss/tocss.go
Takes paths relative to the current working dir.
Fixes #4921
> resource/scss: Add IncludePaths config option

- hugolib/page.go
If a content file contains shortcode(s), we have logic in place to re-render it per output format.
We also have logic in place that avoids making a copy of the content used for this process if we don't need it.
This was before this commit limited to server mode and if the page should be output to multiple formats.
But there is a third case: If a site (language) borrows and renders `.Content` from another language. This would, before this commit, behave oddly for content with shortcodes.
Fixes #4986
> hugolib: Fix "borrow content from another language" issue

- hugolib/page_collections.go
- hugolib/site_sections_test.go
In Hugo 0.44 we simplified the `.Site.GetPage` API and added code to handle the old-style syntax in most cases.
This logic did not handle the lookup of the home page via `.Site.GetPage "section" ""` and similar. This commit fixes that.
Fixes #4989
> hugolib: Fix .Site.GetPage regression

- resource/image_cache.go
- resource/image_test.go
When resizing an image the `sourceFilename` (and thus its `.Contents`) represented the original file _if_ the resized image was not already within Hugo's resource cache. If the resized file was already in the resource cache, `sourceFilename` (and `.Contents`) were set as expected.
This PR defers setting `sourceFilename` until we already have an image, whether it was loaded from cache or created anew.
Fixes #5012
> Fix file paths for uncached transformed images

- deps/deps.go
- langs/language.go
- resource/resource.go
With the newly released Hugo Pipes, resources fetched and processed via `resources.Get` and similar was published to the relevant language sub folder when in multilingual mode.
The thought behind that was maximum flexibility with support for `assetDir` per language.
In practice this was a bad idea:
* You get duplication of identical content, with added processing time
* You end up with path issues that seem to be hard to find a way around (`@fa-font-path` is one example)
This commit changes that. Now there is only one `assetDir` and if you, as one example, need to generate a CSS per langugage, you need to set the paths yourself.
Fixes #5017
> Make resources fetched via resources.Get and similar language agnostic

- tpl/os/init.go
- tpl/os/os.go
- tpl/os/os_test.go
Add `fileStat` method to `os`
`fileStat PATH` returns `os.FileInfo`
Method `readFile` has the size limitation (1MB).
To avoid throwing the error and make a workaround, the size must be got before executing `readFile`.
Under the current condition, this can be done via `[]os.FileInfo` as a result of `readDir`.
However, it is a little complicated because you have to handle an array even though you need just a single `os.FileInfo`.
`fileStat` is useful in such situations.
> Add fileStat to tpl/os/os

- hugolib/alias.go
Use: 
`<meta charset="utf-8">`
instead of the XHTML version:
`<meta http-equiv="content-type" content="text/html; charset=utf-8" />`
less markup :-)
> Use HTML5 <meta charset="utf-8">

- common/hugio/readers.go
- common/hugio/writers.go
- helpers/path.go
- hugolib/hugo_sites_multihost_test.go
- hugolib/page_bundler_handlers.go
- hugolib/paths/paths.go
- hugolib/testhelpers_test.go
- resource/image.go
- resource/image_cache.go
- resource/resource.go
- resource/resource_test.go
- resource/transform.go
In Hugo 0.46 we made the output of what you get from resources.Get and similar static, i.e. language agnostic. This makes total sense, as it is wasteful and time-consuming to do SASS/SCSS/PostCSS processing for lots of languages when the output is lots of duplicates with different filenames.
But since we now output the result once only, this had a negative side effect for multihost setups: We publish the resource once only to the root folder (i.e. not to the language "domain folder").
Fixes #5058
> Fix Resource output in multihost setups

- tpl/tplimpl/template_ast_transformers.go
- tpl/tplimpl/template_ast_transformers_test.go
All `.Params` are stored lowercase, but it should work to access them `.Page.camelCase` etc. There was, however, some holes in the logic with the old transformer.
This commit fixes that by applying a blacklist instead of the old whitelist logic. `.Param` is a very distinct key. The original case will be kept in `.Data.Params.myParam`, but other than that it will be lowercased.
Fixes #5068
> tpl/tplimpl: Reimplement the ".Params tolower" template transformer

- goreleaser-extended.yml
- goreleaser.yml
closes #5022
nfpm has its own name template now.
It seems that the "normal" (not extended) release is using an older version of goreleaser than the extended? Not sure how I can check the logs for that...
Anyway, I've make both files equal, except for the the `build` and `project_name` parts, so it should be easier to compare them in the future...
> fix: goreleaser config

- tpl/tplimpl/amber_compiler.go
Without this patch, amber would try to load templates from the filesystem instead of the layouts virtual filesystem.
For example:
* A file `layouts/partials/mixins.amber`
* A file `layouts/_defaults/single.amber` with the line `import ../partials/mixins`.
Would fail with:
> ERROR 2018/08/12 15:17:15 Failed to add template "_default/single.amber" in path "_default/single.amber": Amber Error in <_default/single.amber>: Unable to read partials/mixins.amber, Error: open partials/mixins.amber: no such file or directory - Line: 15, Column: 5, Length: 25
**Tests:**
As far as I can tell, there are no tests for amber templates. Is there a simple way to test this without implementing an integration testing framweork?
> tlp: Fix compiling amber templates that import other templates

- helpers/path.go
- helpers/path_test.go
- hugolib/hugo_sites.go
- hugolib/page_paths.go
- hugolib/page_paths_test.go
- hugolib/page_taxonomy_test.go
- hugolib/site.go
- hugolib/taxonomy_test.go
This PR attempts to resolve #4090.  The first commit contains tests that demonstrate the problem.
Special thanks to @tsuereth for his initial work on #4092, which laid the groundwork for this PR.
This PR may fix the title issues in #3577, but I haven't tested it yet.
> Fix handling of taxonomy terms containing slashes

- hugolib/config_test.go
- hugolib/page_bundler_test.go
- hugolib/site_output_test.go
- media/mediaType.go
- media/mediaType_test.go
- minifiers/minifiers.go
- minifiers/minifiers_test.go
- output/outputFormat_test.go
This commit also removes the deprecated `Suffix` from MediaType. Now use `Suffixes` and put the MIME type suffix in the type, e.g. `application/svg+xml`.
Fixes #5093
> Improve minifier MIME type resolution

- docs/content/en/content-management/taxonomies.md
- hugolib/site.go
- hugolib/taxonomy_test.go
Doing so was probably a mistake. This may be a breaking change for some people, but it's easy to restore the previous behaviour in the layouts.
Fixes #5172
> hugolib: Do not FirstUpper taxonomy titles

- hugolib/pageGroup.go
- hugolib/pagination.go
This proposal is discussed in issue #4865 (with numerous comments in closed PR #4866)
> New proposal for relaxing Paginate argument

- tpl/data/data.go
- tpl/data/data_test.go
- tpl/data/resources_test.go
The most important part being: Log ERROR, but do not stop the build on remote errors.
Fixes #5076
> tpl/data: Revise error handling in getJSON and getCSV

- minifiers/minifiers.go
- minifiers/minifiers_test.go
[JSON-LD](https://json-ld.org/) is is a standardized format for providing information about a page and classifying the page content. In my use case I am using it for [Google SEO](https://developers.google.com/search/docs/guides/intro-structured-data).
In this pull request I've changed the minifier `mediaTypes` regex to allow for `application/ld+json`.
I wasn't able to find any tests for this section of code and I'm still pretty new to go so I'm unsure of how to add one.
> Make JSON minification more generic

- common/collections/collections.go
- docs/content/en/functions/append.md
- go.sum
- hugolib/collections.go
- hugolib/collections_test.go
- resource/resource.go
- resource/transform.go
- tpl/collections/append.go
- tpl/collections/append_test.go
- tpl/collections/collections.go
- tpl/collections/collections_test.go
- tpl/collections/init.go
- tpl/path/path.go
- tpl/resources/resources.go
Before this commit you would typically use `.Scratch.Add` to manually create slices in a loop.
With variable overwrite in Go 1.11, we can do better. This commit adds the `append` template func.
A made-up example:
```bash
{{ $p1 := index .Site.RegularPages 0 }}{{ $p2 := index .Site.RegularPages 1 }}
{{ $pages := slice }}
{{ if true }}
{{ $pages = $pages | append $p2 $p1 }}
{{ end }}
```
Note that with 2 slices as arguments, the two examples below will give the same result:
```bash
{{ $s1 := slice "a" "b" | append (slice "c" "d") }}
{{ $s2 := slice "a" "b" | append "c" "d" }}
```
Both of the above will give `[]string{a, b, c, d}`.
This commit also improves the type handling in the `slice` template function. Now `slice "a" "b"` will give a `[]string` slice. The old behaviour was to return a …
> tpl/collections: Add collections.Append

- hugolib/permalinks.go
- hugolib/permalinks_test.go
When constructing permalinks, ensure that path segments are normalized
with PathSpec.MakeSegment instead of PathSpec.URLize.
Fixes #4926
> hugolib: Normalize permalink path segments

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/opengraph.html
`safeHTML` should be used when encapsulating entire snippets of HTML including full HTML tags.
For HTML attribute values, we use `safeHTMLAttr`.
> Use safeHTMLAttr instead of safeHTML for HTML attributes.

- docs/content/en/functions/first.md
- tpl/collections/collections.go
- tpl/collections/collections_test.go
> Allow first function to return an empty array.

- .circleci/config.yml
Fixes #5135 
The default working directory on CircleCI is `~/project` which can be seen expanded when the workspace is attached.
> Build on CircleCI outside of GOPATH

- hugolib/resource_chain_test.go
- tpl/collections/collections.go
- tpl/collections/collections_test.go
In Hugo `0.49` we improved type support in `slice`. This has an unfortunate side effect in that `resources.Concat` now expects something that can resolve to `resource.Resources`.
This worked for most situations, but when you try to `slice` different `Resource` objects, you would be getting `[]interface {}` and not `resource.Resources`. And `concat` would fail:
```bash
error calling Concat: slice []interface {} not supported in concat.
```
This commit fixes that by simplifying the type checking logic in `Slice`:
* If the first item implements the `Slicer` interface, we try that
* If the above fails or the first item does not implement `Slicer`, we just return the `[]interface {}`
Fixes #5269
> tpl/collections: Fix handling of different interface types in Slice

- hugolib/site_sections.go
- hugolib/site_sections_test.go
Previously, calls to *Page.Eq(nil) would always return false because the
unwrapPage func didn't support the nil case.  Add support for unwrapping
nil to a *Page.
Fixes #5043
> hugolib: Allow nil to be unwrapped as *Page

- hugolib/site.go
- hugolib/site_test.go
> hugolib: Cast taxonomy weight parameters to int

- tpl/collections/collections.go
- tpl/collections/collections_test.go
Don't assume that the user sends an int as the key when checking against
indexed types.
Fixes #3681
> tpl: Cast IsSet key to int for indexed types

- hugolib/embedded_shortcodes_test.go
- hugolib/page_test.go
- hugolib/shortcode_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/figure.html
1. First commit cleans up the shortcode to make it more readable, and ready it for the second commit. This commit also updates the tests to pass for the white-space changes made in this commit.
2. Second commit renders the Markdown in `caption` and `attr` parameters of the `figure` shortcode. 2 test cases are added for this change too. None of the existing tests (after the prior whitespace fix commit) needed to be modified for this second commit.
Fixes https://github.com/gohugoio/hugo/issues/4406.
---
I found these 13 tests to fail locally before/after building with this PR:
```
--- FAIL: TestPageWithMoreTagOnlySummary (0.43s)
--- FAIL: TestSummaryWithHTMLTagsOnNextLine (0.34s)
--- FAIL: TestWordCountWithIsCJKLanguageFalse (0.48s)
--- FAIL: TestWordCount (0.53s)
--- FAIL: …
```
> Render markup in figure sc caption and attr

- hugolib/page_test.go
TestWordCount incorrectly uses p.WordCount when outputting error for p.FuzzyWordCount()
> FuzzyWordCount test should use p.FuzzyWordCount when outputting error

- hugolib/page_bundler.go
- hugolib/site.go
Hugo now depends on go 1.11
With that bump we no longer need to use `golang.org/x/net/context` and can instead use the one found in stdlib
> Use stdlib context package

- helpers/path.go
- helpers/path_test.go
- hugolib/permalinks.go
In short:
* Avoid double tolower in MakeSegment
* Use MakePathSanitized for taxonomies in pageToPermalinkTitle; this matches what MakeSegment does.
* Move the "double hyphen and space" logic into UnicodeSanitize
The last bullet may be slightly breaking for some that now does not get the "--" in some URLs, but we need to reduce the amount of URL logic.
See #4926
> helpers: Consolidate MakeSegment vs MakePathSanitized

- common/collections/append.go
- common/collections/append_test.go
- common/collections/collections.go
- common/collections/slice.go
- common/collections/slice_test.go
- common/maps/scratch.go
- common/maps/scratch_test.go
- tpl/collections/append.go
- tpl/collections/apply.go
- tpl/collections/collections.go
- tpl/collections/collections_test.go
> common/maps: Improve append in Scratch

- helpers/content.go
Initially, rst2html was called via the python interpreter which would
fail if the script was wrapped in a launcher as on NixOS.
Ideally, on *nix, binaries should be invoked directly to ensure that
shebangs work properly as is being done now.
Handle the case of windows as it doesn't do shebangs.
> helpers/content.go: call rst2html directly on *nix but via python on windows

- resource/integrity/integrity.go
Remove use of fmt.Sprintf for simple string concatenation.  A simple
change for a small perf boost.
```
name         old time/op    new time/op    delta
Integrity-4     525ns ± 2%     268ns ± 2%  -48.92%  (p=0.000 n=10+10)
name         old alloc/op   new alloc/op   delta
Integrity-4      144B ± 0%      112B ± 0%  -22.22%  (p=0.000 n=10+10)
name         old allocs/op  new allocs/op  delta
Integrity-4      5.00 ± 0%      3.00 ± 0%  -40.00%  (p=0.000 n=10+10)
```
> resource: Optimize integrity string generation

- commands/new_site.go
I thought it would be a useful addition to add a `.gitignore` file when the site is first generated using `hugo new site [dir]`.
At present the file contains a single listing for the `public/` directory. This doesn't necessarily need to be committed every time there's a change as most people I've seen add a gitignore file anyway for that directory.
I'm not sure about any other directories/files that should be added to this file. Perhaps the `resources/` directory also as it's generated by a `hugo` command also.
Let me know what you think.
> Generate .gitignore when creating a new site

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/schema.html
> .Date -> .Lastmod

- hugolib/page.go
- hugolib/pagemeta/page_frontmatter.go
- source/fileInfo.go
- source/fileInfo_test.go
The definition of the `BaseFilename` field in the `FrontMatterDescriptor` structure provided to the frontmatter handlers has been changed, so that in the case of a leaf bundle `index.`-file, the name provided is that of the containing bundle folder.
Since the use of the `FrontMatterDescriptor` is localized to the frontmatter handler, this should not have external effects.
To compute the new value of `BaseFilename`, I have added a `ContentBaseName` method to the `File` interface. The `FileInfo` implementation of this interface has been modified to compute the value as part of `lazyinit`. 
This is my first ever `go`-code, so feel free to rewrite as you wish, or let me know if I should implement in another way.
> Date and slug from filename for leaf bundles

- commands/commandeer.go
- commands/hugo.go
- commands/server.go
- common/types/evictingqueue.go
- common/types/evictingqueue_test.go
- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/site_render.go
We do that by re-render visited pages that is not already in the stack. This may potentially do some double work, but that small penalty should be well worth it.
Fixes #5281
> Prevent stale content in Fast Render Mode

- docs/content/en/functions/jsonify.md
- tpl/encoding/encoding.go
- tpl/encoding/encoding_test.go
- tpl/encoding/init.go
Fixes #5040: Allow "jsonify" to pretty print JSON
This PR replaces `json.Marshal` with `json.MarshalIndent`, to return pretty-printed output instead of compact. A sensible spacing of two spaces has chosen for the indentation.
> Allow "jsonify" to pretty print JSON

- common/herrors/error_locator.go
- common/loggers/loggers.go
- common/terminal/colors.go
- go.mod
> Add some color to the relevant filenames in terminal log

- hugolib/hugo_sites_build_errors_test.go
- tpl/template.go
Long identifiers will give errors on the format:
```bash
_default/single.html:5:14: executing "main" at <.ThisIsAVeryLongTitl...>: can't evaluate field ThisIsAVeryLongTitle
```
Hugo use this value to match the "base template or not", so we need to strip the "...".
Fixes #5346
> tpl: Handle truncated identifiers in Go template errors

- common/collections/append.go
- common/collections/append_test.go
- common/maps/scratch_test.go
The type handling in these was improved in Hugo 0.49, but this also meant that it was no longer possible to start out with a string slice and later append `Page` etc. to it.
This commit makes sure that the old behaviour is now possible again by falling back to a `[]interface{}` as a last resort.
Fixes #5361
> common/collections: Allow a mix of slice types in append/Scratch.Add

- common/herrors/error_locator.go
- common/herrors/error_locator_test.go
Will check for an OS environment variable named `HUGO_FILE_LOG_FORMAT`.
The tokens available are `:file` (absolute filename), `:line` (line number) and `:col` (column number).
The default format is: \":file::line::col\"`
How to set OS environment variables is OS specific, but an example on Unix setting an alternative format when running Hugo:
```bash
env HUGO_FILE_LOG_FORMAT="\":file::line\"" hugo
```
The above will include filename and line number quoted.
Fixes #5352
> common/herrors: Make the file error log format configurable

- commands/hugo.go
This is a naive attempt to fix the unexpected behavior with the ignoreFiles config option.
Known caveats:
If the setting exists, then is removed from config.toml, the formerly matching filenames will be sync'ed. If the ignoreFiles does not exist, then hugo server will have to be restarted for filenames to match.
For #4874
> Skip watcher event files if matched in ignoreFiles

- commands/hugo.go
- hugolib/alias.go
- hugolib/page.go
- hugolib/page_content.go
- hugolib/pagebundler_capture.go
- hugolib/site.go
- i18n/i18n.go
- tpl/data/data.go
This commit also pulls down the log level for a set of WARN statements to INFO. There should be no ERRORs or WARNINGs in a regular Hugo build. That is the story about the Boy Who Cried Wolf.
Since the WARN log is now more visible, this commit also improves on some of them, most notably the "layout not found", which now would look something like this:
```bash
WARN 2018/11/02 09:02:18 Found no layout for "home", language "en", output format "CSS": create a template below /layouts with one of these filenames: index.en.css.css, home.en.css.css, list.en.css.css, index.css.css, home.css.css, list.css.css, index.en.css, home.en.css, list.en.css, index.css, home.css, list.css, _default/index.en.css.css, _default/home.en.css.css, _default/list.en.css.css, _default/index.css.css, …
```
> Make WARN the new default log log level

- tpl/collections/complement.go
- tpl/collections/init.go
- tpl/collections/reflect_helpers.go
- tpl/collections/symdiff.go
- tpl/collections/symdiff_test.go
> tpl/collections: Add collections.SymDiff

- tpl/internal/templatefuncRegistry_test.go
When run under gccgo, the test looks for the name that gccgo gives to
a thunk method.  This name is not normally visible, but can be seen
when using reflect.FuncForPC as this code does.  That name changed in
https://golang.org/cl/89555.  Change the test to work with both the
old name "$thunk0" and the new name "thunk0".
Fixes golang/go#28669
> tpl: fix test to pass with gccgo

- commands/commands.go
- commands/new.go
Switches newNewCmd() over to the commandsBuilder+baseBuilderCmd pattern. Also addresses the ignored '--config' option on the 'new' subcommand.
For #5177
> Fix ignored --config flag with 'new' command

- cache/filecache/filecache.go
- cache/filecache/filecache_config.go
- cache/filecache/filecache_config_test.go
- cache/filecache/filecache_pruner_test.go
- cache/filecache/filecache_test.go
- deps/deps.go
- go.sum
- hugolib/filesystems/basefs.go
- hugolib/filesystems/basefs_test.go
- resource/testhelpers_test.go
- tpl/data/resources_test.go
In the newly consolidated file cache implementation, we forgot that we also look in the theme(s) for assets (SCSS transformations etc.), which is not good for Netlify and the demo sites.
Fixes #5460
> Handle themes in the new file cache (for images, assets)

- common/herrors/file_error.go
- docs/content/en/getting-started/configuration.md
- docs/content/en/templates/shortcode-templates.md
- hugolib/config.go
- hugolib/shortcode.go
- hugolib/shortcode_test.go
- hugolib/site.go
- parser/pageparser/item.go
- parser/pageparser/pagelexer.go
- parser/pageparser/pageparser_shortcode_test.go
> Add inline shortcode support

- tpl/tplimpl/embedded/templates/shortcodes/figure.html
As a result of #5276, there is no space between the caption and the attribution link of the `figure` shortcode. I.e. this:
`<p>Image by<a href="http://example.com">Author</a></p>`
renders in browser as:
`Image byAuthor`.
This patch should fix it.
> Fix figure whitespace issue, introduced in PR #5276

- tpl/path/path_test.go
Coverage of path.go goes from 2.6% to 100%.
> tpl/path: Add tests

- go.sum
- hugolib/page_content.go
- hugolib/page_test.go
- parser/pageparser/item.go
- parser/pageparser/pagelexer.go
- parser/pageparser/pageparser_intro_test.go
When the page parser was rewritten in 0.51, this was interpreted literally, but commented out front matter is used in the wild to "hide it from GitHub", e.g:
```
```
Fixes #5478
> parser/pageparser: Fix handling of commented out front matter

- resource/image.go
> resource/image: fix "always false" condition

- commands/import_jekyll.go
- commands/import_jekyll_test.go
This fixes some highlight options from jekyll that were not passed correctly to the imported file.  
For example `hl_lines="1"` was imported verbatim instead of `"hl_lines=1"`.
> importer: fix jekyll import highlight options

- hugolib/resource_chain_test.go
- resource/transform.go
That is, if only `.Content` is accessed.
Fixes #4944
> Prevent resource publishing for transformed inline resources

- docs/content/en/themes/_index.md
Corrects misspelling of sync (synch)
> Fixes typo in themes/_index.md

- commands/server_test.go
Use Golang's subtests to provide a convenient way to run specific tests.
Example:
go test -run=TestFixURL/Basic_production
If you find this one useful, I could go through the codebase and find some other places to add subtests.
> Use subtests with server_test.go

- commands/commands.go
- commands/commands_test.go
- hugolib/paths/paths.go
This commit solves an issue where hugo would ignore the cli -t flag
and only use a theme defined in config.toml.
Also allow -t flag to accept a string slice.
Closes #5569
Closes #5061
Related #4868
> Make hugo server -t work again

- hugolib/pageSort.go
- hugolib/pageSort_test.go
With this commit ByParam takes into account a type of a value under a
key. If both values are numeric then they're coerced into float64 and
then get compared.
If any value isn't numeric, for example it's nil or string, then both
values coerced into string and get compared as strings
(lexicographicaly)
Nil values are always sent to the end.
Numeric values confirm to any type listed below:
uint8, uint16, uint32, uint64, int, int8, int16, int32, int64, float32, float64
Closes #5305
> Support numeric sort in ByParam

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/opengraph.html
In other parts of the opengraph internal template and in the twitter_cards internal template, the template falls back to using site-level parameters when page level parameters are not specified.
This change fixes the opengraph internal template to have this same behavior for the image meta tags.
I believe this was a simple bug, and with this change the behavior now matches what the documentation describes.
> Fix OpenGraph image fallback to site params

- commands/commands.go
- config/configLoader.go
- hugolib/config.go
- hugolib/paths/themes.go
Reduces duplication and defines a single source of truth for config formats.
> Store supported config formats in a variable

- common/herrors/error_locator.go
Old code always returned "." or "" (if filepath.Ext(filename) returned ".").
Now it properly trims the prefix.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
Sorry for the branch name.
GitHub web UI automatically creates branches like `patch-N` when editing from the site.
It's probably a good idea to give them a feature request to provide an imput for a branch name.
> common/herrors: Fix args order in strings.TrimPrefix

- tpl/collections/where.go
- tpl/collections/where_test.go
Before this commit `where` would produce an error and bail building the
site. Now, `where` simply skips an element of a collection and does not
add it to the final result.
Closes #5637
Closes #5416
> Support nested keys/fields with missing values with the `where` function

- .dockerignore
- Dockerfile
I've modified Dockerfile to be a bit more flexible (see example builds, below):
* support "extended" build with `docker build   --build-arg BUILD_TAGS=extended --build-arg CGO=1  . -t hugo:extended`
* support renaming the volume e.g. `docker build --build-arg WORKDIR=/workspace --build-arg . -t hugo` . This was needed for compatibility with GCP Cloud Builders (CI/CD)
* use stretch for build image (final image is still 33mb) -- this is due to a segfault bug with binutils/musl on alpine. See [this bug](https://www.openwall.com/lists/musl/2018/07/18/15)  .  
* rearranged steps to make repeat builds cache-friendly (e.g. separate `go get` , added `Dockerfile` to .dockerignore, moved ENV vars to where they are referenced)
No change from before. Default build is CGO=0, non-extended, …
> build "extended".  support docker args: TAGS, WORKDIR, CGO. speed up repetitive builds

- docs/content/en/readfiles/bfconfig.md
- helpers/content.go
My use-case here is that I have external users which contribute to my hugo site. I want to use this option in order to prevent them from accidentally/unknowingly pasting in arbitrary HTML or JavaScript from potentially unauthorised sources.
I'm unsure if/how a test-case should be added to this. It's my first time ever writing Go. Feel free to tear my PR apart if it doesn't meet your standards!
> add skipHTML option to blackfriday config

- .travis.yml
After forking hugo the travis build fails due to the hard coded path coded into the travis-ci.yml.
```
$ mv $HOME/gopath/src/github.com/gohugoio/hugo $HOME/src
mv: cannot stat ‘/home/travis/gopath/src/github.com/gohugoio/hugo’: No such file or directory
The command "mv $HOME/gopath/src/github.com/gohugoio/hugo $HOME/src" failed and exited with 1 during .
Your build has been stopped.
```
By using the TRAVIS_BUILD_DIR environment variable the build will work for forked projects.
This allows the validation of changes, using ci, on forked hugo builds before submitting PRs.
> Update travis-ci to work for forked builds.

- common/hreflect/helpers.go
- common/hreflect/helpers_test.go
- common/types/types.go
- go.sum
- tpl/compare/init.go
- tpl/compare/truth.go
- tpl/compare/truth_test.go
- tpl/tplimpl/template_ast_transformers.go
- tpl/tplimpl/template_ast_transformers_test.go
Before this commit, due to a bug in Go's `text/template` package, this would print different output for typed nil interface values:
```
{{ if .AuthenticatedUser }}User is authenticated!{{ else }}{{ end }}
{{ if not .AuthenticatedUser }}{{ else }}}User is authenticated!{{ end }}
```
This commit works around this by wrapping every `if` and `with` with a custom `getif` template func with truth logic that matches `not`, `and` and `or`.
Those 3 template funcs from Go's stdlib are now pulled into Hugo's source tree and adjusted to support custom zero values, e.g. types that implement `IsZero`.
This means that you can now do:
```
{{ with .Date }}{{ . }}{{ end }}
```
And it would work as expected.
Fixes #5738
> tpl/tplimpl: Fix template truth logic

- commands/list.go
Prints future dated posts as CSV, including the future date the post will be available from.
Prints like this:
```
$ hugo list future
episodes/19.md,2019-04-09T07:46:51+13:00
```
Things I'm not sure about:
* Should I somehow be writing the CSV through jww? I wasn't sure how to do that here.
* Do you want me to change the output format for the other list commands? Especially `expired`, that seems like a similar kind of case. Not sure what you'd want to do for `draft`, I suppose it could be useful to see the draft dates listed too (note that Hugo doesn't return future dated drafts when listing either drafts or future).
Fixes #5610
> List future dates in CSV format

- compare/compare.go
- hugolib/template_test.go
- metrics/metrics.go
- tpl/partials/init.go
- tpl/partials/partials.go
- tpl/template_info.go
- tpl/tplimpl/ace.go
- tpl/tplimpl/shortcodes.go
- tpl/tplimpl/template.go
- tpl/tplimpl/template_ast_transformers.go
- tpl/tplimpl/template_ast_transformers_test.go
This commit adds support for return values in partials.
This means that you can now do this and similar:
{{ $v := add . 42 }}
{{ return $v }}
Partials without a `return` statement will be rendered as before.
Fixes #5783
> Allow the partial template func to return any type

- docs/content/en/content-management/urls.md
- hugolib/alias.go
- hugolib/alias_test.go
- hugolib/page__meta.go
- hugolib/site_render.go
- hugolib/site_stats_test.go
- hugolib/site_url_test.go
> hugolib: Allow page-relative aliases

- hugolib/page_permalink_test.go
- hugolib/site_render.go
- resources/page/page_paths.go
Before this commit you would have to do this in multilingual setups:
```
---
title: "Custom!"
url: "/jp/custom/foo"
---
```
This commit allows for relative URLs, e.g:
```
---
title: "Custom!"
url: "custom/foo"
---
```
Which is obviously easier and more portable.
The meaning of relative may change to include more in the future (e.g. role based access).
Fixes #5704
> hugolib: Allow relative URLs in front matter

- helpers/content.go
- helpers/content_test.go
- hugolib/page__meta.go
- hugolib/page__per_output.go
- hugolib/page_test.go
- hugolib/rss_test.go
- hugolib/site_test.go
- tpl/transform/transform.go
Add the ability to have a `summary` page variable that overrides
the auto-generated summary.  Logic for obtaining summary becomes:
* if summary divider is present in content use the text above it
* if summary variables is present in page metadata use that
* auto-generate summary from first _x_ words of the content
Fixes #5800 
Tests have been added to ensure all three cases work as expected.  Note that in the tests the summary has markdown elements to ensure that processing occurs correctly; as such RST is explicitly excluded from the list of tested engines in the tests added in `hugolib/page_test.go`.
There is a discrepancy between the summary when auto-generated and when generated using the explicit delimiter; in the former case the output is plain and in the latter case it is wrapped …
> hugolib: Add parameter option for .Summary

- docs/content/en/content-management/front-matter.md
- docs/content/en/content-management/summaries.md
- docs/content/en/variables/page.md
Added documentation about the summary front matter variable as per #5806.
> doc: add information about summary front matter variable

- hugolib/page__meta.go
- hugolib/page_permalink_test.go
Will do this for one version only, as there may be situations where this is the correct thing.
Fixes #5818
> hugolib: Log warning on relative front matter url with lang

- docs/content/en/variables/page.md
The same fix as 3b86b4a9f5ce010c9714d813d5b8ecddda22c69f, applied to doc.
> docs: Remove the space in `. RelPermalink`

- hugolib/collections_test.go
- hugolib/site.go
- hugolib/taxonomy.go
- resources/page/weighted.go
We introduced a callback func() to get the owner Page in 0.55.0.
Sadly, `func` is  not a comparable type in Go.
This commit replaces the func with a struct pointer that wraps the Page.
Fixes #5850
> Fix WeightedPages in union etc.

- hugolib/hugo_sites.go
- hugolib/page.go
- hugolib/site.go
- hugolib/taxonomy.go
- hugolib/taxonomy_test.go
In Hugo 0.55 we connected the taxonomy nodes with their owning Page.
This failed if you had, say, a content file for a author that did not author anything in the site:
```
content/authors/silent-persin/_index.md
```
Fixes #5847
> hugolib: Fix panic for unused taxonomy content files

- hugolib/page.go
- hugolib/page__common.go
- hugolib/pagebundler_test.go
- hugolib/shortcode_test.go
- hugolib/site_render.go
The faulty logic published the bundled resources for the "first output" format.
This worked most of the time, but since the output formats list is sorted,
any output format only used for some of the pages (e.g. CSS) would not work properly.
Fixes #5858
> hugolib: Fix bundle resource publishing when multiple output formats

- tpl/template.go
- tpl/tplimpl/ace.go
- tpl/tplimpl/template.go
- tpl/tplimpl/templateProvider.go
- tpl/tplimpl/template_ast_transformers.go
- tpl/tplimpl/template_ast_transformers_test.go
- tpl/tplimpl/template_info_test.go
> tpl/tplimpl: Handle late transformation of templates

- hugolib/hugo_sites_rebuild_test.go
- hugolib/page__common.go
- hugolib/page__new.go
- hugolib/site.go
Which had some unpredictable behaviour when using `.Pages` on home page etc. that had a content page.
Fixes #5833
> hugolib: Fix Pages reinitialization on rebuilds

- hugolib/menu_test.go
- hugolib/site.go
- navigation/menu.go
- navigation/pagemenus.go
In Hugo `0.55` we introduced the `permalinkable` config attribute on Output Format, default enabled for `AMP` and `HTML`.
This meant that a Page could have different `RelPermalink` and `Permalink` depending on the rendering format.
The menu `URL` did not reflect that fact.
Fixes #5849
> Fix menu URL when multiple permalinkable output formats

- hugolib/site_output_test.go
- resources/page/page_paths.go
They were not correct for regular pages.
Fixes #5877
> Fix links for output formats for non-HTML outputs for regular pages

- hugolib/page__meta.go
- hugolib/page__new.go
- hugolib/page__paths.go
- hugolib/pagebundler_handlers.go
- hugolib/pagebundler_test.go
This fixes a bug introduced in Hugo 0.55.
Fixes #5882
> hugolib: No links for bundled pages

- i18n/i18n.go
- i18n/i18n_test.go
```bash
benchmark                                                    old ns/op     new ns/op     delta
BenchmarkI18nTranslate/all-present-4                         764           757           -0.92%
BenchmarkI18nTranslate/present-in-default-4                  2578          1457          -43.48%
BenchmarkI18nTranslate/present-in-current-4                  764           766           +0.26%
BenchmarkI18nTranslate/missing-4                             3362          1103          -67.19%
BenchmarkI18nTranslate/file-missing-4                        4646          3611          -22.28%
BenchmarkI18nTranslate/context-provided-4                    2013          2014          +0.05%
BenchmarkI18nTranslate/same-id-and-translation-4             1961          784           -60.02% …
```
> i18n: Avoid rebuilding the Translations map for every lookup

- hugolib/site_benchmark_new_test.go
- hugolib/testhelpers_test.go
- tpl/tplimpl/template.go
```bash
benchmark                                    old ns/op     new ns/op     delta
BenchmarkSiteNew/Bundle_with_image-4         14572242      14382188      -1.30%
BenchmarkSiteNew/Bundle_with_JSON_file-4     13683922      13738196      +0.40%
BenchmarkSiteNew/Multiple_languages-4        41912231      25192494      -39.89%
benchmark                                    old allocs     new allocs     delta
BenchmarkSiteNew/Bundle_with_image-4         57496          57493          -0.01%
BenchmarkSiteNew/Bundle_with_JSON_file-4     57492          57501          +0.02%
BenchmarkSiteNew/Multiple_languages-4        242422         118809         -50.99%
benchmark                                    old bytes     new bytes     delta
BenchmarkSiteNew/Bundle_with_image-4         3845077 …
```
> hugolib: Avoid recloning of shortcode templates

- go.mod
- go.sum
Hugo is currently using a version of blackfriday from Aug 4, 2018. I'm proposing it to be updated to v1.5.2, which was cut on Sept 23, 2018.
This is to pull in the recent fixes to fenced code blocks:
https://github.com/russross/blackfriday/releases/tag/v1.5.2
The mage tests come back clean. 
Thanks for considering!
> Update blackfriday to v1.5.2

- hugolib/site.go
- hugolib/site_sections_test.go
This was broken in Hugo 0.55.0.
Fixes #5883
> hugolib: Fix PrevInSection/NextInSection for nested sections

- hugolib/site_render.go
- hugolib/sitemap_test.go
- output/outputFormat.go
- output/outputFormat_test.go
In Hugo 0.55.0 we made AMP `permalinkable`. We also render the output formats in their natural sort order, meaning
`AMP` will be rendered before `HTML`. References in the sitemap would then point to the AMP version,
and this is normally not what you'd want.
This commit fixes that by making `HTML` by default sort before the others. If this is not you want, you can set `weight` on
the output format configuration.
Fixes #5910
> output: Fix permalink in sitemap etc. when multiple permalinkable output formats

- deploy/deploy.go
- go.mod
- go.sum
I think this is a better default since reading is cheaper than writing.
I could add a flag to disable this is you think it's a good idea.
> deploy: compute MD5 by reading if List didn't provide one

- commands/deploy.go
- commands/hugo.go
- deploy/cloudfront.go
- deploy/deploy.go
- deploy/deployConfig.go
- deploy/deployConfig_test.go
- go.mod
Fixes #5929.
* Adds a `invalidateCDN` boolean flag (defaults to true) that enables invalidation of a CloudFront CDN cache if any files changed during the "deploy".
* The CloudFront `DistributionID` is configured as part of the `target` in the config.
* Only CloudFront is supported for now, but other providers could be added.
* The invalidation is for the entire cache, not per-file. `s3deploy` supports a more complicated version which tries to invalidate individual files, but falls back to invalidating the entire cache if more than 8 files have changed. That added a lot of complexity in terms of keeping track of files changes, mapping paths, etc., and my guess is that a fairly high percentage of the time more than 8 files changed anyway, so I'd like to start with this.
> deploy: Support invalidating a CloudFront CDN cache

- deploy/deploy.go
- deploy/deployConfig.go
- deploy/deployConfig_test.go
- deploy/deploy_test.go
Fixes #5932.
Adds support for ordering of uploads, via a sequence of regular expressions configured in the `order` config under `deployments`. Uploads are sorted by path by default, but paths that match one of the `order` regexes are uploaded in that order.
I think this is similar to https://github.com/bep/s3deploy/pull/37, but (IMO) simpler.
> deploy: Support configuration of upload order

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/opengraph.html
- tpl/tplimpl/embedded/templates/shortcodes/vimeo_simple.html
The `safeHTMLAttr` function operates on a full attribute definition, not just within the attribute value.
Docs: https://gohugo.io/functions/safehtmlattr/
For `opengraph.html`, run the whole `content` HTML attribute through `safeHTMLAttr`. That will preserve `+` signs in formatted dates.
For `vimeo_simple.html`, `safeHTMLAttr` was in the context of an attribute value, thus having no effect. In this case we could replace it with `safeURL`, but since the code is coming from an API it is safer to just let Go's template engine sanitize the value as it already does with `provider_url`.
Fixes #5236 (no need to change Go upstream)
Related to #5246
> tpl: Fix internal templates usage of safeHTMLAttr

- Dockerfile
Switching the base image for the final build to alpine as it still
provides a minimal interface, but has a mechanism for easily including
relevant CA certificates.  This is currently pinned to a tagged version,
though since none of the underlying mechanisms are used this should
balance both remaining stable, supported for a period of time, and
providing usable functionality.
Resolves #5970
Affects #5056
> dockerfile:  Switch base image for final build

- commands/list.go
- commands/list_test.go
New:
- command `hugo list all`, return all posts meta in csv format
Refactoring:
- move common parts in commands/list.go to function `buildSites`
- change way to detect path to content
See #5904
> commands: Create new 'hugo list all' command

- tpl/collections/where.go
- tpl/collections/where_test.go
Hi. We just need check here if both values are numbers, convert them to float64, and then compare.
Fix #5685
> Fix #5685. Convert numeric values to float64 and compare them

- deploy/deploy.go
Sorry, missed this in the last PR.
> deploy: Remove TODO comment about subfolders, handled by GoCDK blob URLs

- hugolib/resource_chain_test.go
- resources/resource_factories/bundler/bundler.go
Adds a `\n;\n` between concatenated JavaScript files to ensure that the combined files are interpreted the same as if they were loaded separately.  There are a variety of ways that just straight concatenation can change the result but here are two examples:
<hr>
File A: `# A comment` 
File B: `console.log("Hello world");`
(In the real world, the most common time you'd hit this is pre-minified source files that end with a `#sourceMap=...` comment on their last line)
Before: 
```
```
Result: Nothing is printed because the entire combined file is a comment.
After: 
```
;
console.log("Hello world")
```
Result: Hello world is printed to the console.
<hr>
File A: `(function A() {})()`
File B: `(function B() {})()`
Before:
```
(function A() {})()(function B() {}())
```
Result: "undefined is not …
> Add safety barrier between concatenated javascript resources

- README.md
- docs/content/en/content-management/formats.md
- go.mod
- helpers/content.go
- hugolib/page_test.go
- parser/metadecoders/decoder.go
As the title says, this PR improves the Org mode support of hugo. For a basic overview of the changes, check out [this page](https://niklasfasching.github.io/go-org/go-org-vs-goorgeous) - it showcases the html output of `goorgeous` (left, currently included with hugo) and `go-org` (right, this PR) for the same input. The css is adapted to `go-org`, so open up dev tools for a more fair comparison.
For an overview of the open issues of `goorgeous` that are fixed in `go-org` take a look [here](https://niklasfasching.github.io/go-org/#misc.org)
If you want to try out any Org mode snippets, you can do so in your browser [here](https://niklasfasching.github.io/go-org/).
Also take a look at the [discussion](https://discourse.gohugo.io/t/improved-org-mode-support/15859/18) for more information.
I …
> Improve org mode support

- go.sum
- hugolib/paginator_test.go
- resources/page/pages.go
- resources/page/pages_test.go
- tpl/collections/sort.go
- tpl/collections/sort_test.go
The `sort` template func was producing a `[]page.Page` which did not work in `.Paginate`.
Fixes #6023
> tpl/collections: Fix slice type handling in sort

- commands/new_site.go
This PR makes a small change to the message printed when running `hugo new site`.
Some terminals (e.g. VS Code) include the comma in the URL when hyperlinking, resulting in a 404.
> Removed comma after URL in new site output

- hugolib/pagecollections.go
We occasionally see warnings when building our site:
```
WARN 2019/06/25 23:07:08 make non-relative ref/relref page reference(s) in page %q absolute, e.g. {{< ref "/blog/my-post.md" >}}
```
But the `%q` value is missing, making it difficult to track down the source of the warning.
`%q` was originally specified when this warning was added in #4974, but regressed with https://github.com/gohugoio/hugo/pull/5702/files#diff-9d95b9ca867c1a524fe3a51636c522c4L239
This change fixes the warning to include the source path. It will now output:
```
WARN 2019/06/25 23:07:31 make non-relative ref/relref page reference(s) in page "blog/my-post/index.md" absolute, e.g. {{< ref "/blog/my-post.md" >}}
```
> Include path to source page in non-relative ref/relref warning

- tpl/tplimpl/embedded/templates/pagination.html
When using a html link checker with Hugo, this template consistently causes errors, as it renders `href=""` attributes when next/previous is disabled.
This change makes it so that the `href` attribute is not rendered at all if `HasNext` is false - which is better semantically, and makes link checking far easier.
> Pagination - do not render href if no next item

- cache/filecache/filecache_test.go
- deps/deps.go
- helpers/path_test.go
- helpers/pathspec.go
- helpers/pathspec_test.go
- helpers/testhelpers_test.go
- helpers/url_test.go
- hugofs/decorators.go
- hugofs/fileinfo.go
- hugofs/nosymlink_fs.go
- hugofs/nosymlink_test.go
- hugofs/rootmapping_fs.go
- hugofs/walk.go
- hugolib/data/hugo.toml
- hugolib/filesystems/basefs.go
- hugolib/filesystems/basefs_test.go
- hugolib/hugo_modules_test.go
- hugolib/hugo_sites_build_test.go
- hugolib/pages_capture_test.go
- resources/page/testhelpers_test.go
- resources/testhelpers_test.go
- source/content_directory_test.go
- source/filesystem_test.go
- tpl/data/resources_test.go
This is in line with how it behaved before, but it was lifted a little for the project mount for Hugo Modules,
but that could create hard-to-detect loops.
> Block symlink dir traversal for /static

- common/maps/params.go
- common/maps/params_test.go
- hugolib/page_test.go
This error was introduced in 0.56 and has shown some site breakage in the wild.
Fixes #6121
> common/maps: Do not return error on params dot access on incompatible types

- go.mod
- go.sum
fixes superfluous whitespace around code blocks due to misuse of pre tag
> deps: Update go-org to v0.1.2

- tpl/tplimpl/embedded/templates/shortcodes/gist.html
Specify gists to always load over HTTPS by specifying the protocol.
> Always load GitHub Gists over HTTPS

- hugolib/page__per_output.go
- hugolib/taxonomy_test.go
We will need to revisit this with a proper spec, but this commit makes sure that draft/expiryDate etc. set in front matter on _index.md content files that should disable the page will:
* Not crash
* Make the rendered page not render any `.Content`.
Fixes #6222
Fixes #6210
> hugolib: Fix draft etc. handling of _index.md pages

- hugolib/shortcode.go
A panic occurred when the `nested` variable was nil.
Changed to check if the `nested` variable is nil.
Fixes #6075
> hugolib: Change to output non-panic error message if missing shortcode template

- resources/resource_transformers/postcss/postcss.go
This fixes a typo:
disrepency  > discrepancy
> Discrepancy typo fix in postcss.go

- hugolib/embedded_shortcodes_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/vimeo.html
- tpl/tplimpl/embedded/templates/shortcodes/youtube.html
Hello! This is my first PR here so I hope I'm doing everything correctly.
I noticed while investigating `youtube-nocookie` compatibility that there were a couple of shortcodes still defaulting to HTTP embeds on HTTP sites. With only YouTube and Vimeo remaining, as of this PR all built-in shortcodes would officially fetch embeds securely by default, as both services' docs dictate.
Vimeo was already mentioned in #6184 a few weeks ago but I believe this covers all the bases regarding `mage generate` and `mage check` (which took me quite a while to crack!)
Please let me know if there's anything I can fix and/or improve. Thanks! 😊
> tpl: Migrate last shortcodes (YouTube and Vimeo) to HTTPS embeds

- hugolib/config.toml
- hugolib/hugo_modules_test.go
- modules/client.go
- modules/collect.go
- modules/config.go
- modules/module.go
Now we only try to load modules via Go if there is one or more modules imported in project config.
Fixes #6299
> Make the "is this a Hugo Module" logic more lenient

- hugolib/resource_chain_test.go
- resources/resource_factories/bundler/bundler.go
- resources/resource_factories/bundler/bundler_test.go
In Hugo 0.58 we optimized the transformers that only adjusted metadata, e.g. the fingerprint.
This depended on the source readers implementing `io.ReadSeeker`.
The reader produced by `concat` did that, but the implementation was buggy.
This commit fixes that.
Fixes #6309
> Fix concat with fingerprint regression

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/instagram_simple.html
- tpl/tplimpl/embedded/templates/shortcodes/vimeo_simple.html
This could be a security and performance issue.
See https://developers.google.com/web/tools/lighthouse/audits/noopener
> tmp: add `rel="noopener"` for external links

- media/mediaType.go
- resources/image.go
- resources/image_test.go
- resources/images/config.go
- resources/images/image.go
- resources/resource.go
- resources/resource_metadata.go
The image format is defined as the image extension of the known formats.
All of `img.Resize "600x jpeg"`, `img.Resize "600x jpg"`, `img.Resize "600x png"` are valid
format definitions.
If the target format is defined in the operation definition string, then the converted image will be stored in this format.
Unknown extensions passed in the operation definition have not effect.
Tests were already failing (for me) with the `master` branch. I've added a partial fix for one of these, but haven't fully fixed that particular test. Tests are still failing, but not more than with `master`.
[Log of go test ./... on master](https://github.com/gohugoio/hugo/files/3637245/tests-master.txt)
See #6298
> Support target image format  for image transformations

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support.md
- .github/workflows/auto_close_support.yml
See https://discourse.gohugo.io/t/github-issue-template-to-reduce-support-issues/20873
The bug and proposal issue templates were not modified from the defaults provided by the Github template builder. Support requests that make it through with the support template will be given the label "Support" and automatically closed weekly by https://github.com/bdougie/close-issues-based-on-label
> [WIP] add issue templates and action to reduce support requests in issues

- hugolib/shortcode.go
- hugolib/shortcode_test.go
- parser/pageparser/item.go
- parser/pageparser/item_test.go
- parser/pageparser/pagelexer.go
- parser/pageparser/pagelexer_shortcode.go
- parser/pageparser/pageparser.go
- parser/pageparser/pageparser_intro_test.go
- parser/pageparser/pageparser_shortcode_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/twitter.html
- tpl/urls/urls.go
This means that you now can do:
{{< vidur 9KvBeKu false true 32 3.14 >}}
And the boolean and numeric values will be converted to `bool`, `int` and `float64`.
If you want these to be  strings, they must be quoted:
{{< vidur 9KvBeKu "false" "true" "32" "3.14" >}}
Fixes #6371
> Support typed bool, int and float in shortcode params

- resources/image_test.go
Fix filename mismatch errors on Debian auto-building machines
possibly due to different directory order on ext4 vs tmpfs file systems.
----
Filename mismatch error seen with TestImageOperationsGolden on Debian buildd machines and reproduced on Debian's amd64 porterbox barriere.debian.org:
image_test.go:518: filter all /a/gohugoio24_huc57dd738f4724f4b341121e66fd85555_267952_cfc2eacca4b2748852f953954207d615.png
quicktest.go:288: 
error:
values are not equal
got:
"gohugoio24_huc57dd738f4724f4b341121e66fd85555_267952_cfc2eacca4b2748852f953954207d615.png"
want:
"gohugoio8_hu7f72c00afdf7634587afaa5eff2a25b2_73538_200x100_resize_box_2.png"
stack:
/home/foka/hugo-0.58.3/obj-x86_64-linux-gnu/src/github.com/gohugoio/hugo/resources/image_test.go:547
c.Assert(fi1.Name(), qt.Equals, fi2.Name())
Full …
> resources: Ensure same dirinfos sort order in TestImageOperationsGolden

- go.mod
- go.sum
- helpers/content.go
- hugolib/page__per_output.go
see #6322 
The org mode renderer supports including other files [1]. To resolve relative
paths we need the path of the current file - either absolute or relative to the
directory hugo is run from. DocumentName is the path relative to the content
directory, not the base directory that hugo is run from - we could get the full
path by looking up the content directory from the config and merging both; or
we just make the absolute path of rendered files available in the
RenderingContext.
[1]: e.g. `#+INCLUDE: ./foo.py src python` includes `foo.py` as a python source
block.
> Update go-org & fix includes

- go.mod
- go.sum
- hugolib/resource_chain_test.go
- v2.5.1 removes import comments, solving a build error with Go 1.13
in GOPATH mode (used Debian packaging for example)
- v2.5.2 no longer converts polyline/rect/polygon/line to path
as it has been reported to break a SVG referenced by CSS,
see tdewolff/minify#260
The test case for Min SVG in TestResourceChains is updated accordingly.
Fixes pocc/tshark.dev#33
> deps: Update minify to v2.5.2

- hugolib/embedded_shortcodes_test.go
- hugolib/testhelpers_test.go
- tpl/data/data.go
- tpl/data/data_test.go
This broke for the Twitter simple shortcode now that Shortcodes accepts typed arguments.
Fixes #6382
> tpl: Make getJSON/getCVS accept non-string args

- tpl/collections/collections.go
Modified the messages functions after, first, and last threw on being passed invalid parameters (index or limit) to be more standardised and resemble what Go compiler would throw.
Fixes #6415
> tpl: Modify error messages of after, first, and last

- docs/content/en/content-management/shortcodes.md
- hugolib/embedded_shortcodes_test.go
- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/shortcodes/vimeo.html
Add an optional "title" attribute to the iframe in the vimeo shortcode. If one is not given, the title attribute will default to "vimeo video". It is imperative for iframes to have a non-empty "title" attribute in order to meet WCAG2.0 accessibility guidelines. https://www.w3.org/TR/WCAG20-TECHS/H64.
> Add optional "title" attribute to iframe in Vimeo shortcode

- commands/commandeer.go
As of now, if one attempts to run `hugo` in a directory without a config file, it will fail.
```
$ hugo
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
Run `hugo help new` for details.
```
This addresses #5896. It is worth noting that if the directory has a go.mod file, building will still continue, as it is still considered a config file. I'm not 100% on how to deal with this, as it seems that we still do want these to be considered config files for Hugo's module system. It's a small edge case, but this will catch _most_ cases.
> Do not attempt to build if there is no config file

- resources/image_test.go
Add exception for new test image in TestImageOperationsGolden due to "fused multiply and add" (FMA) instruction on s390x, ppc64* and arm64.
See #6439
---
(I was alerted by automated email telling me of snap build failure on those platforms and redirecting me to https://launchpad.net/~gohugoio/+snap/hugo-dev etc.)
> resources/images: Add exception for new test image

- go.mod
- go.sum
To fix our -race test under Go 1.14 (current tip or master)
See google/go-cmp#167
> Update past go-cmp's checkptr fix

- .travis.yml
- magefile.go
- Add arm64 support for Linux thanks to Travis CI’s new feature, see
https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support
- Force GO111MODULE=on
- Cache directories
- Switch to bionic (Ubuntu 18.04) environment
- Use "master" instead of "tip" to match the latest Travis CI docs
- ~~Use "x" in Go patch level: 1.12.x and 1.13.x~~
- Allow "mage -v check" to fail on non-AMD64 architectures
because "go test -race ./..." currently fails on arm64 and ppc64le.
> Update .travis.yml for arm64 support, etc.

- go.mod
- go.sum
to fix Java syntax highlighting
Fixes #6476
> deps: Update to Chroma v0.6.9 for Java lexer fix 

- .travis.yml
The default timeout of 15000 millisecond is too short
for go test -race on arm64.
See golang/go#35308
> travis: Increase timeout to 30000 for mage -v check

- docs/content/en/content-management/urls.md
- resources/page/permalinks.go
- resources/page/permalinks_test.go
In the vein of an [ancient TODO](https://github.com/gohugoio/hugo/commit/07978e4a4922bc21c230fee65052232b829bd1ab#diff-0688a3b65c7f5d01aa216f8d9b57fd00R111-R112) about supporting custom date formatting with strftime, this allows `:`-prefixed Go time format strings in permalink segments. This allows users to customize date-based permalinks any way they need to.
For example, with a date of 2019-11-09, the permalink `/:06/:1/:2` will render as `/19/11/9`.
See:
- [Discourse thread](https://discourse.gohugo.io/t/implementing-additional-date-formats-for-permalinks/17860)
- [Discussion of alternative approach](https://github.com/gohugoio/hugo/pull/6488)
> Support Go time format strings in permalinks

- commands/new_site.go
Many users seem to stumble over creating new sites in existing non-empty directories. And that `--force` is the necessary option. So I added *See --force* as a hint to the error.
Fixes #4825.
> commands: Add hint when dir not empty.

- commands/import_jekyll.go
- commands/import_jekyll_test.go
Prior refactor had eliminated writing FrontMatter for Jekyll imports. This
fixes that bug as well as adds a regression test.
Also removed unused site var, replaced some raw strings, and added regression
test for \r\n removal.
Fixes #5576
> commands: Fix jekyll metadata import on individual posts

- magefile.go
Darwin no longer supports 386 builds after Catalina. Also add
debugging output when running test suites from mage.
> mage: Fix mage check on darwin and add debugging output

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/opengraph.html
- tpl/tplimpl/embedded/templates/twitter_cards.html
Make `opengraph.html` image tag behave in the same way as `twitter_card.html`. Now it can pick an image like `*cover*` or `*thumbnail*` from page bundle, plus also respects `.Site.Params.images`
This is a copy of #5157 which I deleted accidentally while rebasing my branch to the latest master.
See this comment for additional info on how I tested it https://github.com/gohugoio/hugo/pull/5157#issuecomment-419701217
> Add support for featured and global image to OpenGraph template

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/schema.html
Make schema.html image tag behave in the same way as twitter_card.html. Now it can pick an image like *cover* or *thumbnail* from page bundle, plus also respects .Site.Params.images
Should nicely complement the #5378, as requested in https://github.com/gohugoio/hugo/issues/5078#issuecomment-434188426
> Add support for featured and global image to Schema template

- hugolib/pagebundler_test.go
- hugolib/pages_map.go
> Fix headless regression

- docs/content/en/content-management/image-processing/index.md
- docs/content/en/content-management/page-resources.md
- docs/data/docs.json
- hugolib/image_test.go
- media/mediaType.go
- resources/images/image.go
According to multiple sources, both official ([IANA] and [RFC2046]) and
otherwise (eg, [Mozilla] and [Wikipedia]), the official MIME type for
JPEG images is `image/jpeg`, not `image/jpg`.  Change Hugo to match.
[IANA]: https://www.iana.org/assignments/media-types/media-types.xhtml#image
[RFC2046]: https://tools.ietf.org/html/rfc2046
[Mozilla]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
[Wikipedia]: https://en.wikipedia.org/wiki/JPEG
> Fix incorrect MIME type from image/jpg to image/jpeg

- tpl/collections/merge.go
- tpl/collections/merge_test.go
* If the end result is maps.Params, we need to lower the keys
* Also make sure to handle nested maps of different type
Update #6633
> tpl/collections: Some more params merge adjustments

- go.mod
- go.sum
- export #+TITLE (front-matter title) as `<h1>` and demote all normal headlines
by 1 accordingly (i.e. a normal top level headline now becomes a `<h2>`
rather than a `<h1>`)
- preserve whitespace in paragraphs - this allows rendering meaningful
whitespace when wished for using e.g. css `white-space: pre;` (e.g. in verse
/ quote blocks). html ignores superfluous / duplicate whitespace so without css this does not change anything.
> deps: Update go-org

- Dockerfile
When building the extended version of Hugo using the Dockerfile and `--build-arg HUGO_BUILD_TAGS=extended`, the obtained Docker container is broken, because the source is built under alpine 3.11 and the compiled binary is copied to an image based on alpine 3.10. This problem was most likely introduced due to an update of the golang base image.
This commit changes the base image from alpine:3.10 to alpine:3.11, fixing extended version builds.
> Update alpine base image in Dockerfile to 3.11

- common/text/transform.go
- common/text/transform_test.go
- helpers/content.go
- helpers/path.go
- markup/blackfriday/convert.go
- markup/converter/converter.go
- markup/goldmark/autoid.go
- markup/goldmark/autoid_test.go
- markup/goldmark/convert.go
- markup/goldmark/convert_test.go
- markup/goldmark/goldmark_config/config.go
- tpl/urls/urls.go
You can turn off this behaviour:
```toml
[markup]
[markup.goldmark]
[markup.goldmark.parser]
autoHeadingIDAsciiOnly = true
```
Note that the `anchorize` now adapts its behaviour depending on the default Markdown handler.
Fixes #6616
> markup/goldmark: Make auto IDs GitHub compatible

- parser/pageparser/pagelexer_shortcode.go
- parser/pageparser/pageparser_shortcode_test.go
Fixes #6726 
This PR allows users to use raw string literals in shortcode params.
Examples for both named and positional params include:
```
{{< param `testparam` >}}
{{< param=`testparam` >}}
```
However, it does not support escaped backticks (eg {{< param \\\`testparam\\\` >}}), because it dosen't work on Go (unrecognized escape character error).  A new error is thrown for this as previously, it used to be handled either by the unrecognized unicode character error for the backtick or the unterminated quote error.
> Allow raw string literals in shortcode params

- parser/pageparser/pagelexer_shortcode.go
- parser/pageparser/pageparser_shortcode_test.go
Fixes #6766.
Previously, newline characters were not supported in param shortcode. This fixes it to make it in line with Go raw string behaviour.
> Add support for newline in raw string shortcode

- tpl/compare/compare.go
- tpl/compare/compare_test.go
This PR is trying to close #6619:
I adopted `&&` as the connective between logical values because of https://github.com/gohugoio/hugo/issues/6619#issuecomment-565811571:
`!(a==b || a==c)` is equilvalent to `a!=b && a!=c` so I understand `ne a b c` should be translated the same way
> Allow multiple arguments in ne/ge/gt/le/lt functions

- transform/livereloadinject/livereloadinject.go
- transform/livereloadinject/livereloadinject_test.go
This makes it work with Turbolinks.
Fixes #6821
> transform/livereloadinject: Inject livereload script right after head if possible

- commands/commands.go
- commands/commands_test.go
- commands/config.go
- commands/convert.go
- commands/deploy.go
- commands/hugo_test.go
- commands/list.go
- commands/list_test.go
- commands/new.go
- commands/new_content_test.go
- commands/new_site.go
- commands/new_theme.go
- commands/server_test.go
> commands: Fix config environment handling

- markup/highlight/highlight.go
- markup/highlight/highlight_test.go
* Use chroma.Coalesce
* for https://github.com/gohugoio/hugo/issues/6877
* This method was used in [Hugo < v0.60.0](https://github.com/gohugoio/hugo/blob/07a203406a1863ba7c48f9090de7c4587fae913d/helpers/pygments.go#L188) and are missing in >= v0.60.0
* Escape code strings if lexer is nil
* for https://github.com/gohugoio/hugo/issues/6856
Note: this fixation is only for `choma`'s highlight. 
We need more fixation of highlight function with `goldmark` because its highlight does not  work properly in CodeFences yet.
> markup/highlight: Fix chroma highlight

- common/hugo/version.go
- common/hugo/version_test.go
This should work for alpha/beta/rc releases.
Fixes #6910.
> Fix goMinorVersion on non-final Go releases.

- docs/content/en/functions/math.md
- tpl/math/init.go
- tpl/math/math.go
- tpl/math/math_test.go
I wanted to use math.Sqrt for working with areas and aspect ratios of images, so here it is.
I noticed that math.Log was already there, so I added it to the documentation.
> Added math.Sqrt (and docs for math.Log)

- tpl/resources/resources.go
I just added a check to see if the argument should be a ResourceTransformer is actually a map[string]interface, which would imply that the resource is missing, and put a more useful error message on that. Fixes #6942
> tpl: Change error message on missing resource

- tpl/data/data_test.go
- tpl/data/resources.go
Add url.QueryUnescape before reading file which allows files with unicode in their paths to be read.
Fixes #6996
> tpl: Fix error with unicode in file paths

- hugofs/filter_fs.go
While I was working on keeping track of build options in filterfs, I noticed an oddity that sometimes the filter function is passed the filepath, and sometimes it is passed the directory path.
This makes the arguments to applyFilters consistent (and then renames the argument to make it more clear).
> Pass directory name to filters in LstatIfPossible in the same way as Readdir

- common/herrors/error_locator.go
- common/herrors/error_locator_test.go
- common/herrors/file_error.go
- common/herrors/line_number_extractors.go
I probably found typos in comments.
- In license comment: `limitatio	ns` -> `limitations`
- In package comment: `Package errors` -> `Package herrors`
> common/herrors: Fix typos in comments

- docs/content/en/hosting-and-deployment/hosting-on-aws-amplify.md
AWS Amplify now supports a GUI method for using the latest `hugo` version. Please feel free to modify my wording here, etc.
> Update hosting-on-aws-amplify.md to use AWS Amplify GUI method

- go.mod
- go.sum
- tpl/transform/init.go
- tpl/transform/transform_test.go
Apparently, they flipped the :heart: back to the old one, so this is partially reverting #6392.
> Update to latest emoji package.

- commands/genchromastyles.go
- go.mod
- go.sum
Chroma was updated to include a new function to output all CSS
classes without skipping any considered redundant with the current
style.
This will modify the `hugo gen chromastyles` command to use this new
function by default, which avoids potential problems if the style is
later modified.
Also requires the updated Chroma (v0.7.2).
Resolves #7167
> Modify gen chromastyles to output all CSS classes

- go.mod
- go.sum
- markup/org/convert.go
- inline source blocks and exports
- result blocks and source block :exports parameter
- fix: html escaping in example blocks
- #+LINK based links
> deps: Update go-org to v1.1.0

- hugolib/hugo_sites.go
In `func add`, `m.mu.Unlock()` is forgot before panic.
This PR adds Unlock before panic to avoid possible deadlock.
> hugolib/hugo_sites: Add Unlock before panic

- tpl/tplimpl/template.go
In `func Lookup`,
`t.mu.RLock()` is followed by another `t.mu.RLock()`.
This will cause double-lock. There is no RUnlock for the RLock.
This PR changes `t.mu.RLock()` to `t.mu.RUnlock()`.
> tpl/tmplimpl/template: Change defer RLock to RUnlock

- hugolib/content_map_test.go
- hugolib/page__tree.go
Fix an issue that IsAncestor and IsDescendant always return false if the page is in subsection.
Related issue: https://github.com/gohugoio/hugo/issues/7178
If the page is in subsection, ref1 and ref2 values are as follows in `IsDescendant`.
```
ref1: /blog/subsection__hb_/page4__hl_
ref2: /blog
```
So, the following original code always return false since `ref2.key+cmBranchSeparator (/blog__hb_)` is not matched.
```go
cmBranchSeparator = "__hb_"
strings.HasPrefix(ref1.key, ref2.key+cmBranchSeparator), nil
```
We have to check `ref2.key + "/"`, too.
> Fix IsAncestor and IsDescendant under subsection

- hugolib/content_map_test.go
- hugolib/page__tree.go
IsAncestor and IsDescendant returned true if the same page is passed until the changes of https://github.com/gohugoio/hugo/pull/7097 .
```
{{ $blog.IsAncestor $blog }} -> true
```
Some themes (e.g., docsy) depend on this behavior.
This PR changes IsAncestor and IsDescendant to the old behavior.
> Fix IsAncestor and IsDescendant when the same page is passed

- lazy/init.go
Expand the text in the init timeout message to give the reader more hints as to what may be causing the issue.
The current error sent me on a wild goose chase trying to debug my shortcodes, but it turned out that the issue was just that I wasn't caching my resources/ directory on my build server. Once I found this blog post, I solved the issue in minutes:
https://www.henriksommerfeld.se/hugo-timeout-not-a-circular-loop-in-shortcode/
Googling the error message yields several additional posts from users who focus on loops in their shortcode when the problem seems to be overly-expensive builds.
> Add diagnostic hints to init timeout message

- tpl/collections/sort_test.go
- tpl/compare/compare.go
example use case: mark posts as `pinned: true` and be able to sort pages by that property without setting values to all unpinned posts  
sorted by the idea that true = 1 and false = 0  
so default ascending sort will put all false values first and all true values last
> Added support for sort by boolean

- tpl/tplimpl/embedded/templates.autogen.go
- tpl/tplimpl/embedded/templates/opengraph.html
This PR fixes a bug (?) where `.Date` was being used for `og:updated_time` instead of `.Lastmod`. Couldn't find an open issue for this. It was quicker to fix it than to open one.
.Lastmod is the time at which the website was most recently updated,
rather than .Date which is the time at which the website content file
was created.
> Use .Lastmod for og:updated_time

- deploy/deploy.go
- deploy/deploy_test.go
Deployments ignore directories with a leading `.`, but should not ignore
certain well known 'hidden' directories like `.well-known/`
Fixes #6691
> deploy: Do not suppress .well-known/ directory

- hugolib/content_render_hooks_test.go
- hugolib/page.go
- hugolib/page__per_output.go
- hugolib/site.go
- markup/converter/converter.go
- markup/converter/hooks/hooks.go
- markup/goldmark/render_hooks.go
This commit also
* Renames previous types to be non-specific. (e.g. hookedRenderer rather
than linkRenderer)
Resolves #6713
This was implemented much in the same way the current hooks are implemented, pulling in method definitions from [goldmark](https://github.com/yuin/goldmark). It still needs testing and documentation, but on my personal website I was able to successfully replace the `replaceRE` partial hack described in the issue above with a `render-heading.html` template similar to the one described.
> Add render template hooks for headings

- hugolib/site_test.go
- publisher/htmlElementsCollector.go
- publisher/htmlElementsCollector_test.go
> publisher: Fix tag collector for nested table elements

- docs/content/en/getting-started/installing.md
Fix a minor typo in install instructions for Linux.
> Fix typo in install instructions

- commands/commandeer.go
- commands/server.go
- config/commonConfig.go
- config/commonConfig_test.go
- docs/content/en/getting-started/configuration.md
> Add redirect support to the server

- tpl/tplimpl/embedded/templates/pagination.html
Fixes #7199.
Before:
```html
<ul class="pagination">
<li class="page-item">
<a href="/post/" class="page-link" aria-label="First"><span aria-hidden="true">&laquo;&laquo;</span></a>
</li>
<li class="page-item disabled">
<a  class="page-link" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
</li>
<li class="page-item active"><a class="page-link" href="/post/">1</a></li>
<li class="page-item"><a class="page-link" href="/post/pager/2/">2</a></li>
<li class="page-item"><a class="page-link" href="/post/pager/3/">3</a></li>
<li class="page-item disabled"><span aria-hidden="true">&nbsp;&hellip;&nbsp;</span></li>
<li class="page-item"><a class="page-link" href="/post/pager/10/">10</a></li>
<li class="page-item">
<a href="/post/pager/2/" class="page-link" aria-label="Next"><span …
```
> Beautify HTML generated by pagination template

- hugolib/alias.go
- hugolib/alias_test.go
- hugolib/site.go
- hugolib/site_render.go
- hugolib/testhelpers_test.go
- transform/urlreplacers/absurlreplacer.go
- transform/urlreplacers/absurlreplacer_test.go
This PR fixes alias' redirect URLs when using the `relativeURLs` setting. This applies to both aliases explicitly defined in the page front matter and aliases implicitly created for the default language (e.g. `/` -> `/en`).
Taking the language redirect as an example, when setting `relativeURLs` to `true`, currently, the redirect portion of `/index.html` file looks like this:
```
<meta http-equiv="refresh" content="0; url=/en" />
```
While the correct should be (the last `/` is not strictly necessary, but I added it to be consistent with other URLs generated by Hugo):
```
<meta http-equiv="refresh" content="0; url=./en/" />
```
Using the [example from Hugo's documentation](https://gohugo.io/content-management/urls/#example-aliases), it currently generates two "redirect" files like this:
* …
> Fix aliases with relativeURLs

- hugolib/alias_test.go
- hugolib/site_render.go
For the sake of completeness, I believe this fixes the aliases when using `uglyURLs` without any undesired side effects.
Currently, I get an error like this:
```
Error: Error building site: failed to render pages: open /some/path/public/posts/my-awesome-post.html: is a directory
```
Not sure if there's a better way handle those prefixes and suffixes in the test. In other languages, I'd probably use a lambda, but Go's anonymous functions seem syntactically a bit too heavy for this.
> Fix aliases with uglyURLs

- magefile.go
Expose the functionality of the hidden `hugo gen docshelper` command as
a mage target.
> Add genDocsHelper mage target

- common/collections/order.go
- hugolib/content_map.go
- hugolib/content_map_page.go
- hugolib/page.go
- hugolib/taxonomy_test.go
- resources/page/pages_sort.go
Preserve the order from front matter, which would be behaviour when doing this manually (before GetTerms).
Fixes #7213
> Fix order of GetTerms

- hugolib/alias_test.go
- hugolib/site_render.go
Currently, running the example from the alias unit test with `baseURL = "http://example.com/some/path"` generates a tree structure like this (where the path in the baseURL is prepended to the relative alias output path):
```
public/
├── blog/
│   └── page/
│       └── index.html
├── foo/
│   └── bar/
│       └── index.html
└── some/
└── path/
└── blog/
└── rel/
└── index.html
```
With this PR, it will look like this:
```
public/
├── blog/
│   ├── page/
│   │   └── index.html
│   └── rel/
│       └── index.html
└── foo/
└── bar/
└── index.html
```
Not sure if there's any special case where replacing `of.RelPermalink()` by `p.targetPaths().SubResourceBaseLink` could cause issues, but it worked correctly in all examples I tried.
> Fix aliases with path in baseURL

- hugolib/hugo_sites.go
- hugolib/hugo_sites_build.go
- hugolib/hugo_sites_build_test.go
- hugolib/hugo_sites_multihost_test.go
- hugolib/site.go
- hugolib/testhelpers_test.go
Before this change a robots.txt is created in every Site. So in public/robots.txt if there are no languages (was correct). But if there are multiple languages in every language directory, too (was wrong). If defaultContentLanguageInSubdir is true, no language is created into the root directory, so no robots.txt is in the root directory (was wrong). If multihosts are configured for each language, that is the only case where one robots.txt must be created in each language directory (was correct).
I've changed the behaviour, that only in the multihost case the robots.txt is created in the language directories. In any other case it is created in public/robots.txt. I've also added tests that files are not created in the wrong directories.
Fixes #5160
See also #4193
> Create robots.txt in the domain root directory

- README.md
The goal of this PR is to update installation instruction about `--tags extended` when `CGO_ENABLED=0` as it shows such no straightforward error:
```bash
$ go install --tags extended
../../go/gopath/pkg/mod/github.com/bep/golibsass@v0.6.0/libsass/transpiler.go:15:2: build constraints exclude all Go files in /home/mateusz/go/gopath/pkg/mod/github.com/bep/golibsass@v0.6.0/internal/libsass
```
This is because `CGO_ENABLED=0` on my linux machine (`go1.14.2 linux/adm64` - but previous versions of `go` and `hugo` had this problem as well)
I don't know if this is related to this issue as I haven't tested on ARM: https://github.com/gohugoio/hugo/issues/6991
> Updated installation instruction about Sass/SCSS support

- go.mod
- go.sum
- markup/org/convert_test.go
- Add support for #+MACRO
- fix a bug with #+LINK (edge case, should never happen anyways :TM:)
- Make title export optional (add export option)
- Remove cosmetic whitespace added by go-org (for easier visual
diffing) inside p tags (`<p>\nfoo\n</p>` => `<p>foo</p>`)
(should make `white-space: pre` on p look more in line with expectations)
- implement table separators via multiple tbodies (the html spec is ok with
that)
> deps: Update go-org to v1.2.0

- go.mod
- go.sum
- Add support for image links (i.e. link with image as description)
- Kinda breaking: Wrap headlines and headline+content in containers as emacs
Org mode does. Could break people's styles - I don't expect it, but who knows
what counts as sane when it comes to css.
Before:
```
<h2 id="headline-1">FOO</h2>
foo bar
```
After:
```
<div id="outline-container-headline-1" class="outline-2">
<h2 id="headline-1">FOO</h2>
<div id="outline-text-headline-1" class="outline-text-2">
foo bar
</div>
</div>
```
> deps: Update go-org to v1.3.0

- parser/metadecoders/decoder.go
- parser/metadecoders/decoder_test.go
When using Org mode with Hugo, it would be nice to have support for [Org timestamps](https://orgmode.org/manual/Timestamps.html) for the `DATE` header.
At the moment (hugo v0.72.0), `DATE` only supports Hugo's native syntax in Org files, therefore this is parsed correctly:
```
#+DATE: 2020-06-10
```
While this is not:
```
#+DATE: <2020-06-10 Wed>
```
Using the following template to format a page's `Date` attribute should produce the correct date:
```
{{ dateFormat "January 2, 2006" .Date }}
```
Output for `#+DATE: 2020-06-10`:
```
June 10, 2020
```
Output for `#+DATE: <2020-06-10 Wed>`:
```
January 1, 0001
```
Since Org mode defaults to the latter syntax, it would be great to have support for that in Hugo. Discussing this issue with @niklasfasching, he explained that this would fit better …
> Add support for native Org dates in frontmatter

- hugolib/hugo_sites.go
- hugolib/hugo_sites_rebuild_test.go
- hugolib/shortcode.go
- tpl/collections/apply_test.go
- tpl/template.go
- tpl/tplimpl/template.go
> Fix server reload when non-HTML shortcode changes
