go.mod
go.sum

looking forward to use the new Nord theme (included in this new version) on my site :)

feat: upgrade chroma

---

deploy/deploy.go

Fixes #8388.
The change is to check the error returned from `Delete` (if any) -- if it is `NotFound`, then log a `WARN` and continue instead of failing the deployment.

deploy: Don't treat a NotFound response for Delete as a fatal error.

---

tpl/tplimpl/embedded/templates.autogen.go
tpl/tplimpl/embedded/templates/opengraph.html
tpl/tplimpl/embedded/templates/twitter_cards.html

Remove .Site.Authors from embedded templates

---

tpl/strings/strings.go
tpl/strings/strings_test.go

Copies the implementation that already is part of .WordCount
This should handle the given test cases from #8479

tpl: Enhance countwords to handle special chars

---

hugolib/hugo_modules_test.go
modules/npm/package_builder.go

- Change SetEscapeHTML to false
- Change indent size from one whitespace to two whitespaces
- Add `scripts` field to test
Close #8512

Change SetEscapeHTML to false

---

docs/content/en/functions/querify.md

The querify function now accepts a slice per
<https://github.com/gohugoio/hugo/pull/8305>.

Update querify function description and examples

---

commands/hugo.go

Display version when building site

---

common/text/transform.go
publisher/htmlElementsCollector.go
publisher/htmlElementsCollector_test.go

publisher: Make the HTML element collector more robust

---

common/hugo/hugo.go
go.mod
go.sum

See https://github.com/sass/libsass/releases/tag/3.6.5

deps: Update to LibSASS 3.6.5

---

goreleaser.yml

See <https://spdx.org/licenses/>
Fixes #8555

Use SPDX license identifier

---

docs/content/en/functions/math.md
tpl/math/init.go
tpl/math/math.go
tpl/math/math_test.go

Add math.Max and math.Min

---

commands/static_syncer.go
common/loggers/ignorableLogger.go
common/loggers/loggers.go
deps/deps.go
docs/content/en/functions/errorf.md
helpers/general.go
hugolib/alias.go
hugolib/collections.go
hugolib/hugo_sites.go
hugolib/page__new.go
hugolib/site.go
hugolib/site_render.go
langs/i18n/i18n.go
resources/page/zero_file.autogen.go
tpl/collections/collections.go
tpl/data/resources_test.go
tpl/fmt/fmt.go
tpl/fmt/init.go
tpl/fmt/init_test.go

tpl/fmt: Add erroridf template func

---

.github/workflows/test.yml
config/services/servicesConfig.go
hugolib/embedded_shortcodes_test.go
resources/page/page_generate/generate_page_wrappers.go
tpl/tplimpl/embedded/templates.autogen.go
tpl/tplimpl/embedded/templates/shortcodes/instagram.html
tpl/tplimpl/embedded/templates/shortcodes/instagram_simple.html

Upgrade Instagram shortcode

---

.circleci/config.yml

Update to Go 1.16.5, Goreleaser 0.169.0

---

go.mod
go.sum

dep: Update to Goldmark v1.3.8

---

resources/image.go
resources/image_test.go
resources/images/smartcrop.go

resources/image: Fix fill with smartcrop

---

config/configLoader.go
hugolib/config.go
hugolib/config_test.go
modules/client.go
modules/collect.go
modules/module.go

Implement configuration in a directory for modules

---

common/maps/maps.go
common/maps/maps_test.go
common/maps/params.go
config/compositeConfig.go
config/configProvider.go
config/defaultConfigProvider.go
config/defaultConfigProvider_test.go
hugolib/config.go
hugolib/content_render_hooks_test.go

config: Fix merge of config with map[string]string values.

---

config/defaultConfigProvider.go
hugolib/config.go
hugolib/config_test.go
hugolib/language_test.go

Fix language menu config regression

---

common/maps/params.go
common/maps/params_test.go
config/defaultConfigProvider.go
config/defaultConfigProvider_test.go

Fix config handling with empty config entries after merge

---

hugolib/embedded_templates_test.go
tpl/tplimpl/embedded/templates.autogen.go
tpl/tplimpl/embedded/templates/opengraph.html
tpl/tplimpl/embedded/templates/schema.html

Fix date format in schema and opengraph templates

---

commands/commands.go
commands/hugo.go
commands/server.go
watcher/batcher.go
watcher/filenotify/filenotify.go
watcher/filenotify/fsnotify.go
watcher/filenotify/poller.go
watcher/filenotify/poller_test.go

Add polling as a fallback to native filesystem events in server watch

---

config/defaultConfigProvider.go
hugolib/cascade_test.go
hugolib/content_map_page.go
hugolib/page__meta.go
hugolib/site.go
resources/page/page_matcher.go

Add config.cascade

---

hugolib/resource_chain_test.go
minifiers/config.go
minifiers/minifiers_test.go
resources/resource_transformers/minifier/minify_test.go

minifiers: Make keepWhitespace = true default for HTML

---

common/maps/maps.go
common/maps/maps_test.go
hugolib/menu_test.go
hugolib/site.go
navigation/menu.go
navigation/pagemenus.go

Improve handling of <nil> Params

---

go.mod
go.sum

deps: Update github.com/tdewolff/minify/v2 v2.9.20 => v2.9.21

---

tpl/time/time_test.go

tpl/time: Adjust tests to handle matching local time zonesx

---

commands/genchromastyles.go
docs/content/en/content-management/formats.md
docs/content/en/content-management/shortcodes.md
docs/content/en/content-management/syntax-highlighting.md
docs/content/en/functions/highlight.md
docs/content/en/getting-started/installing.md
hugolib/config.go
hugolib/embedded_shortcodes_test.go
hugolib/shortcode_test.go
markup/blackfriday/renderer.go

Relates to #8912 (only addressed the ones that seemed less controversial for now)

highlight: Remove some pygments references

---

hugolib/resource_chain_test.go
resources/postpub/postpub.go

Prevent minifier from removing quoutes around post-processed attributes

---

.circleci/config.yml
.github/workflows/test.yml
htesting/test_helpers.go
htesting/test_helpers_test.go
modules/client.go
modules/collect.go
snap/snapcraft.yaml

Update to Go 1.17

---

go.mod
go.sum

deps: Update github.com/yuin/goldmark v1.4.0 => v1.4.1

---

common/htime/time.go
common/htime/time_test.go

common/htime: Fix time.Format with Go layouts

---

create/content_test.go
source/fileInfo.go

source: Make ContentBaseName() return the directory for branch bundles

---

go.mod
go.sum

deps: Upgrade github.com/yuin/goldmark v1.4.2 => v1.4.3

---

create/content_test.go
hugolib/content_factory_test.go
hugolib/filesystems/basefs.go

With theme and project with content directories and command on the form `hugo new posts/test.md`.
Fixes #9129

Fix path resolution in hugo new

---

go.mod
go.sum

deps: Upgrade github.com/yuin/goldmark v1.4.3 => v1.4.4

---

create/content.go
hugolib/content_factory.go
hugolib/filesystems/basefs.go

Improve error when we cannot determine content directory in "hugo new"

---

tpl/tplimpl/embedded/templates.autogen.go
tpl/tplimpl/embedded/templates/google_news.html

Add deprecation warning to google_news templates

---

deploy/deployConfig.go
deploy/deployConfig_test.go

Check for empty deployment targets and matchers

---

cache/filecache/filecache_config.go
cache/filecache/filecache_config_test.go
docs/content/en/getting-started/configuration.md
docs/content/en/hugo-pipes/introduction.md
resources/resource_factories/create/create.go

Make resources.Get use a file cache for remote resources

---

hugolib/hugo_modules_test.go
langs/i18n/translationProvider.go

Validate private use language tags

---

media/mediaType.go

Add rss suffix for application/rss+xml

---

docs/content/en/functions/highlight.md
tpl/transform/transform.go
tpl/transform/transform_test.go

Closes #9249
Fixes gohugoio/hugoDocs#63

tpl/transform: Optional options for highlight func

---

cache/filecache/filecache.go
cache/filecache/filecache_config.go
cache/filecache/filecache_test.go
hugolib/page.go
hugolib/resource_chain_test.go
resources/errorResource.go
resources/page/page_nop.go
resources/page/testhelpers_test.go
resources/resource.go
resources/resource/resourcetypes.go
resources/resource_factories/create/create.go
resources/transform.go
tpl/data/resources_test.go
tpl/resources/resources.go

- Make resource.Get return nil on 404 not found
- Allow user to handle/ignore errors in resources.Get

Misc resources.Get improvements/fixes

---

go.mod
go.sum

deps: Upgrade github.com/niklasfasching/go-org v1.5.0 => v1.6.0

---

create/content.go

create: Correctly pass newContentEditor flags

---

common/hugo/hugo.go
common/hugo/hugo_test.go
docs/content/en/functions/hugo.md
hugolib/hugo_smoke_test.go
hugolib/site.go
resources/page/site.go

Add hugo.Deps

---

markup/goldmark/render_hooks.go

Do not render hl_style as an HTML attribute

---

hugofs/walk.go
hugofs/walk_test.go
hugolib/filesystems/basefs_test.go
hugolib/hugo_modules_test.go

Fix duplicate mount sources

---

tpl/templates/integration_test.go
tpl/templates/templates.go

tpl/templates: Fix templates.Exist issue with base templates

---

media/mediaType.go

Add jsm and mjs extensions.
Closes #9483

Update the application/javascript media type

---

docs/content/en/content-management/front-matter.md
resources/page/page_matcher.go
resources/page/page_matcher_test.go

Fix validation of Page Kind in cascade target map

---

common/hugo/hugo.go

Add HUGO_ENV to the os/exec environment

---

commands/commands.go
commands/commands_test.go
commands/hugo.go
docs/content/en/commands/hugo.md
docs/content/en/commands/hugo_mod.md
docs/content/en/commands/hugo_new.md
docs/content/en/commands/hugo_server.md
tpl/template.go
tpl/template_info.go
tpl/tplimpl/integration_test.go
tpl/tplimpl/template.go
tpl/tplimpl/template_errors.go

Add --printUnusedTemplates

---

metrics/metrics.go
tpl/partials/integration_test.go
tpl/partials/partials.go

metrics: Add cached count tracking

---

go.mod
go.sum

deps: Update github.com/yuin/goldmark v1.4.4 => v1.4.7

---

go.mod
go.sum
tpl/lang/lang_test.go

deps: Update github.com/gohugoio/localescompressed v0.14.0 => v0.15.0

---

hugolib/page__common.go
hugolib/page__new.go
hugolib/page_test.go
resources/page/page.go
resources/page/page_nop.go
resources/page/testhelpers_test.go

Add page.Store

---

docs/layouts/_default/_markup/render-codeblock-mermaid.html
hugolib/page__per_output.go
markup/converter/hooks/hooks.go
markup/goldmark/codeblocks/integration_test.go
markup/goldmark/codeblocks/render.go
markup/highlight/highlight.go
tpl/diagrams/diagrams.go
tpl/tplimpl/embedded/templates/_default/_markup/render-codeblock-goat.html

- CodeblockContext method renames
- tpl/diagrams: Rename Body to Inner

Some renames

---

markup/goldmark/codeblocks/integration_test.go
markup/highlight/highlight.go
tpl/diagrams/diagrams.go
tpl/transform/transform.go
tpl/transform/transform_test.go

The final batch of codeblock adjustments

---

markup/highlight/config.go
tpl/transform/transform_test.go

tpl/transform: Fix it when template.HTML is passes as option to Hightlight

---

hugofs/fs.go
hugolib/filesystems/basefs.go
tpl/os/integration_test.go
tpl/os/os.go

tpl/os: Revert readDir in theme behaviour

---

minifiers/config.go
minifiers/minifiers_test.go
resources/resource_transformers/minifier/minify_test.go

minifiers: Make keepWhitespace = false default for HTML

---

hugolib/alias_test.go
hugolib/hugo_sites_build_test.go
hugolib/page_test.go
tpl/tplimpl/embedded/templates/alias.html

Add lang attribute to internal alias template

---

common/types/hstring/stringtypes.go
common/types/hstring/stringtypes_test.go
hugolib/page__per_output.go
markup/converter/hooks/hooks.go
markup/goldmark/integration_test.go
markup/goldmark/render_hooks.go
tpl/transform/transform.go

Fix potential infinite recursion in link render hooks

---

go.mod
go.sum
hugolib/integrationtest_builder.go
markup/goldmark/integration_test.go

deps: Fix Goldmark regression with HTML comments

---

commands/server.go
commands/server_test.go

Improve server startup/shutdown

---

create/content.go
hugolib/content_factory.go
hugolib/content_factory_test.go

Hi everyone!
I fixed  a few typos in `content_factory.go` and refactored any mentions.
I hope this kind of contribution is welcome.

Fix and refactor typos in content_factory.go

---

resources/resource_transformers/tocss/dartsass/client.go

dartsass: Improve error message when no read access

---

resources/images/config.go
resources/images/config_test.go

resources/images: Require width and height for Crop, Fill, and Fit

---

hugofs/fileinfo.go
hugofs/filter_fs.go
hugofs/language_composite_fs.go
hugofs/walk.go
hugolib/filesystems/basefs.go
hugolib/language_content_dir_test.go

Make sure file mounts higher up wins

---

docs/content/en/functions/hmac.md
tpl/crypto/crypto.go
tpl/crypto/crypto_test.go

tpl/crypto: Add optional encoding arg to hmac function

---

hugolib/hugo_sites.go
source/fileInfo.go

Deprecate .File.Extension

---

snap/snapcraft.yaml

Reference [this code ](https://forum.snapcraft.io/t/system-files-and-personal-files-request-for-onefetch/28963) to add plug, and maybe could resolve issue #6226.

Snap: Add {system,user}-gitconfig plugs to read gitconfig

---

hugolib/hugo_sites.go
hugolib/hugo_sites_build.go
hugolib/site.go
langs/language.go
resources/page/integration_test.go
resources/page/page_matcher_test.go
resources/page/pagegroup.go
resources/page/pages_sort_test.go
resources/page/site.go
resources/page/testhelpers_test.go
tpl/time/init.go
tpl/time/time.go
tpl/time/time_test.go

Localize all the GroupBy*Date methods

---

modules/client.go

modules/client: Vendor config directory if present

---

docs/data/docs.json
go.mod
go.sum
minifiers/config.go

Fixes #9713
Fixes #9740
Adds support for minify.tdewolff.svg.keepComments (bool)

deps: Update github.com/tdewolff/minify/v2 v2.10.0 => v2.11.0

---

hugolib/integrationtest_builder.go
resources/image_cache.go
resources/integration_test.go

Fix MediaType when reading images from cache

---

commands/commandeer.go
commands/commands_test.go
commands/server_test.go
hugofs/fs.go

Fix PostProcess regression for hugo server

---

compare/compare.go
hugolib/page__meta.go
hugolib/pages_language_merge_test.go
identity/identity.go
navigation/menu.go
resources/page/page.go
resources/page/pages.go
resources/resource/resources.go
resources/resource/resourcetypes.go
tpl/compare/compare.go
tpl/lang/lang.go

- Deprecate page.Author and page.Authors
- resources/page: Mark some more interface methods as internal
- tpl/lang: Handle nil values in lang.Merge
- Some godoc adjustments to make it easier to generate documentation stubs

Misc godoc related

---

go.mod
go.sum
hugolib/page_test.go
markup/goldmark/convert_test.go

Fixes #9054
Fixes #9756
Fixes #9757

deps: Update github.com/yuin/goldmark v1.4.11 => v1.4.12

---

.github/workflows/test.yml

Updated actions with permissions.
https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions

Updated actions with permissions

---

cache/filecache/filecache.go
commands/commandeer.go
commands/commands.go
commands/hugo.go
commands/hugo_test.go
commands/import_jekyll.go
commands/list.go
commands/list_test.go
commands/new_theme.go
commands/server.go
common/htime/time.go
common/loggers/loggers.go
go.mod
go.sum
hugofs/fileinfo.go
hugolib/content_factory.go
hugolib/page_test.go
hugolib/site.go
metrics/metrics.go
modules/collect.go
resources/resource/dates.go
tpl/collections/collections.go
tpl/partials/partials.go
tpl/time/init.go
tpl/time/time.go
tpl/tplimpl/template.go

Add `clock` cli flag

---

tpl/collections/integration_test.go
tpl/collections/sort.go

tpl/collections: Make sort stable

---

commands/commandeer.go
commands/server.go
config/configLoader.go
hugolib/config.go

Also fix the config error messages.
Fixes #9664

server: Fix SIGINT handling after loading bad configuration

---

commands/server.go
commands/server_test.go

As introduced in v0.99.0.
Fixes #9901

server: Fix multihost crash

---

helpers/general.go
resources/image.go
resources/resource.go
resources/resource/resourcetypes.go
resources/resource_factories/create/create.go
resources/transform.go
tpl/resources/integration_test.go
tpl/resources/resources.go

Implemented by most Resource objects, but not Page (for now).
Fixes #9313

Add resources.Copy

---

hugolib/content_map_page.go
hugolib/page__common.go
hugolib/page__content.go
hugolib/page__new.go
hugolib/page__per_output.go
hugolib/renderstring_test.go

Fix panic with markdownify/RenderString with shortcode on Page with no content file

---

docs/content/en/functions/path.Base.md
docs/content/en/functions/path.BaseName.md
docs/content/en/functions/path.Clean.md
docs/content/en/functions/path.Dir.md
docs/content/en/functions/path.Ext.md
docs/content/en/functions/path.Join.md
docs/content/en/functions/path.Split.md
tpl/path/path.go
tpl/path/path_test.go

tpl/path: Add path.BaseName function

---

config/security/securityonfig_test.go
go.mod
go.sum
tpl/transform/remarshal_test.go

deps: Update github.com/pelletier/go-toml/v2 v2.0.2 => v2.0.4

---

go.mod
go.sum

deps: Update github.com/tdewolff/minify/v2 v2.12.0 => v2.12.1

---

commands/new.go
create/content.go
create/content_test.go
hugolib/content_factory.go
hugolib/content_factory_test.go

Add `--force` to `hugo new`

---

commands/hugo.go
common/hugio/hasBytesWriter.go
common/hugio/hasBytesWriter_test.go
deps/deps.go
hugofs/hasbytes_fs.go
hugolib/hugo_sites_build.go
hugolib/resource_chain_test.go
hugolib/testhelpers_test.go
resources/transform_test.go

Support PostProcess for all file types

---

commands/commands_test.go
commands/server.go
commands/server_test.go

server: Fix redirects when file path contains bytes > 0x80

---

config/security/securityConfig.go
config/security/securityonfig_test.go
docs/data/docs.json

Allow proxy variables in subcommands

---

docs/content/en/content-management/image-processing/index.md
go.mod
go.sum
resources/errorResource.go
resources/image.go
resources/image_test.go
resources/images/color.go
resources/images/color_test.go
resources/images/image_resource.go
resources/transform.go

Which returns the most dominant colors of an image using a simple histogram method.
Fixes #10307

resources/images: Add image.Colors

---

commands/server.go
commands/server_test.go

commands: Fix 404 redirects Windows issue

---

commands/commandeer.go

Regression introduced in v0.104.1.

Fix htimes /: operation not permitted error on config changes

---

hugolib/page.go
hugolib/taxonomy_test.go

Fix taxonomy weight sort regression

---

README.md

I should have edited the README table of contents, when I made a change earlier.
Sorry for this double PR!

Editing the readme TOC for a change made earlier

---

tpl/resources/integration_test.go
tpl/resources/resources.go

tpl: resources.Get errors when given an empty string

---

commands/commands_test.go
commands/new_site.go

commands: Create assets directory with new site

---

tpl/collections/index.go
tpl/collections/index_test.go
tpl/diagrams/diagrams.go
tpl/diagrams/init.go
tpl/internal/templatefuncsRegistry.go

- tpl: Misco GoDoc improvements
- tpl/collections: Fix some index cases where the indices given is a slice and be more lenient with nil inputs

Misc improvements/fixes

---

hugolib/minify_publisher_test.go
tpl/tplimpl/embedded/templates/_default/sitemap.xml
tpl/tplimpl/embedded/templates/_default/sitemapindex.xml

tpl/tplimpl: Use https in sitemap templates

---

resources/resource_transformers/js/integration_test.go
resources/resource_transformers/js/options.go

This fixes the cases where
```js
import 'imp2/index.js';
import 'imp3/foo.js';
```
And these files lives in `assets` as:
```
imp2/index.ts
imp3/foo.ts
```
Fixes #10527

resources/js: Fix some import discrepancies between Hugo and ESBuild

---

tpl/openapi/openapi3/openapi3.go

To make it easier to document.

tpl/openapi3: Wrap *kopenapi3.T

---

cache/filecache/filecache_pruner.go
commands/hugo.go
commands/static_syncer.go
common/herrors/errors.go
common/herrors/errors_test.go
helpers/path.go
hugofs/decorators.go
hugofs/rootmapping_fs.go
hugofs/slice_fs.go
hugofs/walk.go
hugolib/codeowners.go
hugolib/filesystems/basefs.go
hugolib/page.go
hugolib/pages_capture.go
hugolib/site.go
magefile.go
modules/client.go
modules/collect.go
resources/resource_spec.go
tpl/tplimpl/template.go
watcher/filenotify/poller.go

Also consider wrapped errors when checking for file IsNotExist errors

---

parser/metadecoders/decoder.go
parser/metadecoders/decoder_test.go

- parser/metadecoders: Add empty /data JSON file as empty map
- parser/metadecoders: Simplify nil check in Unmarshal

Handle empty JSON

---

helpers/path.go
helpers/path_test.go

helpers: Allow at signs in UnicodeSanitize

---

tpl/resources/resources.go

tpl/resources: Fix data race in ToCSS

---

hugolib/minify_publisher_test.go
tpl/tplimpl/embedded/templates/_default/sitemap.xml
tpl/tplimpl/embedded/templates/_default/sitemapindex.xml

This reverts commit 3fd0b78498597ceb343b7fda2e9b652f3e957478.
See <https://github.com/gohugoio/hugo/issues/10515#issuecomment-1362287522>

Revert "tpl/tplimpl: Use https in sitemap templates"

---

hugolib/integration_test.go
hugolib/translations.go

hugolib: Exclude non-linkable pages from translations map

---

releaser/releaser.go

Hugo no longer uses the Goreleaser tool.

Remove reference to Goreleaser in code comment

---

hugolib/frontmatter_test.go
hugolib/page__meta.go

Preserve front matter slice value types (e.g. int)

---

tpl/internal/templatefuncsRegistry.go
tpl/strings/init.go
tpl/strings/regexp.go
tpl/strings/regexp_test.go

tpl/strings: Add findRESubmatch

---

resources/page/integration_test.go
resources/page/permalinks.go
resources/page/permalinks_test.go

Fix permalinks issue with repeated sections

---

go.mod
go.sum

deps: Upgrade github.com/alecthomas/chroma v2.4.0 => v2.5.0

---

go.mod
go.sum

deps: Upgrade github.com/yuin/goldmark v1.5.3 => v1.5.4

---

publisher/htmlElementsCollector.go
publisher/htmlElementsCollector_test.go

Most notably better handling self-closing elements
Closes #10698

Make the HTML collector parsing more robust

---

resources/page/pages_related.go

But only in the case where we know that we will need to access the Page fragments/tableofcontents.
In normal situations this will spread naturally across the CPU cores, but not in the situation where
`site.RegularPages.Related` gets called as part of e.g. the single template.
```bash
name            old time/op    new time/op    delta
RelatedSite-10    18.0ms ± 2%    11.9ms ± 1%  -34.17%  (p=0.029 n=4+4)
name            old alloc/op   new alloc/op   delta
RelatedSite-10    38.6MB ± 0%    38.6MB ± 0%     ~     (p=0.114 n=4+4)
name            old allocs/op  new allocs/op  delta
RelatedSite-10      117k ± 0%      117k ± 0%   +0.23%  (p=0.029 n=4+4)
```
See #10711

page: Add some concurrency to the building of the related page index

---

resources/resource_transformers/tocss/internal/sass/helpers.go

resources/sass: Remove debug statements

---

hugolib/shortcode.go
hugolib/shortcode_test.go

Add some shortcode testcases

---

docs/content/en/content-management/related.md
related/inverted_index.go
related/inverted_index_test.go
resources/page/pages_related.go

related: Add config option cardinalityThreshold

---

tpl/templates/integration_test.go
tpl/tplimpl/template_funcs.go

Fix "page" not defined

---

snap/snapcraft.yaml

snap: Fix dart-sass-embedded installation

---

deps/deps.go
langs/i18n/i18n.go
langs/i18n/i18n_test.go
langs/i18n/integration_test.go
resources/page/page.go
tpl/lang/lang.go

This is a workaround. We need to improve on this, but not today.
Fixes #10782

Page context handling in i18n

---

hugolib/page.go
hugolib/page__fragments_test.go
hugolib/page__output.go
hugolib/page__per_output.go
hugolib/shortcode_page.go
resources/page/page.go
resources/page/page_lazy_contentprovider.go
tpl/page/integration_test.go

Allow page.TableOfContents on self in shortcode

---

watcher/batcher.go

This PR refactors `watcher.New` function to use `time.NewTicker` instead of `time.Tick`. From the [docs](https://pkg.go.dev/time#Tick):
> Tick is a convenience wrapper for NewTicker providing access to the ticking channel only. While Tick is useful for clients that have no need to shut down the Ticker, be aware that without a way to shut it down the underlying Ticker cannot be recovered by the garbage collector; it "leaks".

watcher: use time.NewTicker to prevent leaks

---

hugolib/paginator_test.go
resources/page/pagegroup.go
resources/page/pagination.go

Don't fail when calling Paginate with an empty pages.PagesGroup

---

README.md
common/loggers/loggers.go
common/maps/params.go
hugolib/pagecollections.go
lazy/once.go
resources/page/page_paths.go
tpl/templates/integration_test.go
watcher/filenotify/poller.go

This PR corrects format issues reported by the [go report card](https://goreportcard.com/report/github.com/gohugoio/hugo).

Run gofmt -s on source files

---

hugolib/shortcode.go
hugolib/shortcode_test.go

Fix "unknown shortcode token" when calling shortcode within fenced code block

---

tpl/math/math.go
tpl/math/math_test.go

fix: math (must provide at least two values)

---

hugolib/page__fragments_test.go

Add test for ToC vs include

---

langs/i18n/integration_test.go
langs/i18n/translationProvider.go

Co-authored-by: 641bill <wo23636@126.com>
Fixes #9216

langs/i18n: Fallback to defaultContentLanguage instead of English

---

docs/content/en/functions/math.md
tpl/math/init.go
tpl/math/math.go
tpl/math/math_test.go

tpl: Add math.Abs

---

commands/commandeer.go
commands/hugobuilder.go
config/allconfig/load.go
modules/collect.go
testscripts/commands/hugo__flags.txt
testscripts/commands/hugo__publishdir_in_config.txt

To allow publishDir to be set in config file.

commands: Load config before creating the filesystem

---

go.mod
go.sum

deps: Update github.com/bep/golibsass v1.1.0 => v1.1.1

---

docs/content/en/functions/urls.JoinPath.md
tpl/urls/init.go
tpl/urls/urls.go
tpl/urls/urls_test.go

See https://pkg.go.dev/net/url#JoinPath
Closes #9694

tpl/urls: Add JoinPath template function

---

commands/commandeer.go
commands/hugobuilder.go
testscripts/commands/hugo_printpathwarnings.txt
testscripts/commands/hugo_printunusedtemplates.txt

And now with tests.
Updates #10953

Re-add --printUnusedTemplates and --printPathWarnings

---

commands/commandeer.go
commands/hugobuilder.go
commands/server.go

By wrapping all use of the shared config in a lock.
Updates #10953

commands: Fix data race

---

commands/hugobuilder.go
common/hugo/hugo.go
common/hugo/hugo_test.go
config/allconfig/configlanguage.go
config/configProvider.go
hugolib/config_test.go
hugolib/site_new.go
langs/i18n/i18n_test.go
resources/page/page_matcher_test.go
resources/page/site.go
tpl/cast/docshelper.go

Add hugo.WorkingDir

---

docs/content/en/content-management/shortcodes.md
tpl/tplimpl/embedded/templates/shortcodes/figure.html

to make it possible to e.g. to lazy load an figure/image

tpl/tplimpl: Add img loading attribute to figure shortcode 

---

hugolib/hugo_sites_build.go

Avoid writing to hugo_stats.json when there are no changes

---

commands/commandeer.go
commands/config.go
commands/new.go
testscripts/commands/config.txt

Add --format to hugo config

---

commands/commandeer.go
commands/server.go
hugolib/hugo_sites_build.go
hugolib/integrationtest_builder.go
hugolib/page.go
hugolib/page__per_output.go
hugolib/site.go
hugolib/site_new.go
hugolib/testhelpers_test.go
minifiers/config.go
testscripts/commands/hugo.txt

Fix regression with site.IsServer when not running a server

---

commands/hugobuilder.go
commands/server.go
testscripts/commands/hugo_configdev_env.txt
testscripts/commands/hugo_configdev_environment.txt
testscripts/commands/hugo_configprod.txt

Fix regression when loading config  -e is empty or HUGO_ENV or HUGO_ENVIRONMENT is set

---

langs/language.go
resources/page/pages_sort.go
resources/page/taxonomy.go
tpl/collections/sort.go

Fix potential deadlock in ByParam

---

tpl/tplimpl/embedded/templates/_default/rss.xml
tpl/tplimpl/embedded/templates/_default/sitemap.xml
tpl/tplimpl/embedded/templates/alias.html

If this is merged, I will update the documentation in the docs repo after release.

tpl/tplimpl: Use .Language.LanguageCode in built-in templates

---

.github/workflows/test.yml
magefile.go

github: Fix Windows build

---

commands/server.go
main_test.go
tpl/internal/templatefuncsRegistry.go

This PR does the same changes as in #10732

all: Replace deprecated ioutil with io and os

---

config/allconfig/allconfig.go
hugolib/config_test.go

Fixes #11089
~/d/g/g/hugo ❯❯❯ git resetf                   fix/myseryconfigissue-11089 ✭ ✱

Fix config merge regression with root slices (e.g. disableKinds)

---

hugolib/integrationtest_builder.go
resources/image_test.go
resources/images/image.go
resources/integration_test.go

Fix .Width and .Height for animated gifs

---

common/collections/append.go
common/collections/append_test.go
tpl/collections/integration_test.go

- tpl/collections: Fix append when appending a slice to a slice of slices
- common/collections: Always make a copy of the input slice in Append

Misc Append fixes

---

snap/snapcraft.yaml

Revert "snap: Transition base snap from core20 to core22 (#11101)"

---

go.mod
go.sum

deps: Update github.com/tdewolff/minify/v2 v2.12.5 => v2.12.7

---

.github/workflows/test.yml
commands/deploy_off.go
deploy/deployConfig.go

Fix broken nodeploy setup

---

commands/new.go
testscripts/commands/new.txt

commands: Enable format flag with hugo new site

---

docs/content/en/content-management/urls.md

docs: Update permalinks documentation

---

commands/new.go
testscripts/commands/new.txt

commands: fix help message for hugo new theme

---

common/collections/append.go
common/collections/append_test.go
tpl/collections/integration_test.go

fixes append regression to allow appending nil

---

config/allconfig/alldecoders.go
hugolib/config_test.go
tpl/collections/integration_test.go

Fix output formats and media type  per language config regression

---

config/commonConfig.go
hugolib/hugo_sites_build.go
hugolib/integrationtest_builder.go
hugolib/site_test.go
publisher/htmlElementsCollector.go
publisher/htmlElementsCollector_test.go
publisher/publisher.go

So you can do
```toml
[build.writeStats]
tags = true
classes = true
ids = false
```
Fixes #11191

Make build.writeStats a struct

---

.github/workflows/test.yml

To discover upstream issues before we release.

github: Build for Dragonfly in CI build

---

config/commonConfig.go
hugolib/hugo_sites_build.go
hugolib/site_test.go
publisher/htmlElementsCollector.go
publisher/htmlElementsCollector_test.go
publisher/publisher.go

Mostly to make it easier to toggle on/off this feature from the env.
See #11191

Rework the build.writeStats struct

---

docs/content/en/getting-started/configuration.md
helpers/general.go
helpers/general_test.go

Add titleCaseStyle none and firstupper

---

commands/hugobuilder.go
config/allconfig/configlanguage.go
config/configProvider.go
helpers/url_test.go
hugolib/config_test.go
hugolib/pagebundler_test.go
hugolib/paths/paths.go
hugolib/site.go
hugolib/site_new.go
hugolib/site_url_test.go
hugolib/sitemap_test.go
hugolib/testhelpers_test.go
main_test.go
modules/client.go
testscripts/commands/mod_vendor.txt

- Fix DefaultContentLanguageInSubdir with only 1 language
- Fix static content files multilingual root regression
- Fix hugo mod vendor for modules with hugo.toml

Misc fixes

---

config/allconfig/allconfig.go
hugolib/config_test.go
langs/config.go

Restore language.disabled config

---

docs/data/docs.json

Need to refresh security.exec.osenv

docs: Refresh docs.json

---

config/allconfig/allconfig.go

Will handle separately in current docs site.

config/allconfig: Update timeout description

---

tpl/collections/collections.go
tpl/collections/collections_test.go
tpl/collections/integration_test.go
tpl/collections/sort.go
tpl/collections/sort_test.go
tpl/collections/where.go
tpl/collections/where_test.go

tpl/collections: Fix WordCount (etc.) regression in Where, Sort, Delimit

---

common/herrors/errors.go
common/herrors/errors_test.go
config/commonConfig.go
resources/resource_transformers/babel/babel.go
resources/resource_transformers/postcss/integration_test.go
resources/resource_transformers/postcss/postcss.go
resources/transform.go

Improve error messages for PostCSS etc.

---

common/htime/integration_test.go
common/htime/time.go

common/htime: Fix localization of abbreviated month names

---

config/allconfig/allconfig.go
hugolib/config_test.go

Fix broken handling of legacy taxonomyTerm in disableKinds

---

snap/snapcraft.yaml

snap: Allow access to SSH keys and $HOME/.config/hugo

---

config/allconfig/load.go
hugolib/config_test.go

Fix multiple languages in HUGO_DISABLELANGUAGES

---

commands/server.go

This PR does the same changes as in #10732

commands: Replace deprecated ioutil with os

---

docs/content/en/functions/where.md

docs: Update where function operators

---

hugolib/integrationtest_builder.go
resources/image_cache.go
resources/integration_test.go
resources/resource.go

Fix so temporary images do not get published

---

go.mod
go.sum
markup/highlight/integration_test.go

deps: Fix Chroma dependency version

---

config/allconfig/load.go
testscripts/commands/server__watch_moduleconfig.txt

Fix module config watch regression

---

.github/ISSUE_TEMPLATE/bug_report.md

One more attempt to discourage use of issue queue for questions and troubleshooting.

Update GitHub issue template

---

helpers/path.go

testing: Write test caches to /tmp

---

Dockerfile

- `golang:1.21-alpine`
- `alpine:3.18`

Dockerfile: update Docker images

---

hugolib/page.go
hugolib/page_test.go

Fix .RawContent for empty content pages

---

hugolib/page.go
hugolib/pagecollections_test.go

Fix RegularPagesRecursive for the home page

---

cache/filecache/filecache.go
cache/filecache/filecache_pruner.go
testscripts/commands/new_content.txt

Delay the creation of cache directories until they're used

---

commands/server.go

With dozens of different languages, it is nice to see which port maps to which language in local development.

Print language code after web server address info

---

main_test.go

Fix tests for Go 1.21.1

---

tpl/tplimpl/embedded/templates/google_analytics_async.html

google_analytics_async.html: Add deprecation warning

---

tpl/collections/collections.go
tpl/collections/integration_test.go

tpl/collections: Fix and deprecate echoParams

---

resources/resource_transformers/integrity/integrity.go
resources/resource_transformers/integrity/integrity_test.go

resources/integrity: Return string instead of template.HTMLAttr

---

common/hugo/hugo.go
common/hugo/hugo_test.go
docs/content/en/functions/hugo.md
docs/content/en/variables/site.md
hugolib/site_new.go
resources/page/page_matcher_test.go
resources/page/site.go

And deprecate site.IsServer.
Closes #11510

common/hugo: Add hugo.IsServer and hugo.IsDevelopment

---

commands/hugo_windows.go

commands: Update message displayed when running CLI from GUI

---

hugolib/page.go
hugolib/shortcode.go
parser/pageparser/item.go
parser/pageparser/itemtype_string.go

Remove rest of the now unused emoji code

---

hugolib/page_test.go
tpl/collections/collections.go
tpl/collections/collections_test.go

tpl/collections: Make delimit return a string

---

docs/content/en/functions/images/index.md
resources/images/color.go
resources/images/filters.go
resources/images/padding.go

This addresses the primary use case described in https://github.com/gohugoio/hugo/issues/11599.

resources/images: Create padding image filter

---

tpl/urls/urls.go

tpl/urls: Return strings from URL functions

---

commands/new.go
docs/content/en/commands/hugo_new_content.md

commands/new: Remove format flag from new content cmd

---

hugolib/site_new.go
resources/page/pagination.go
resources/page/pagination_test.go
resources/page/site.go

Make site.BaseURL and $pager.URL a string

---

helpers/content.go
helpers/content_test.go
tpl/transform/integration_test.go

helpers: Fix TrimShortHTML used by markdownify and RenderString

---

markup/goldmark/render_hooks.go

markup/goldmark: Sync image render hook code with Goldmark

---

navigation/menu.go
navigation/pagemenus.go

- MenuEntry.IsEqual
- MenuEntry.IsSameResource
Closes #11670

navigation: Unexport menu entry methods

---

tpl/tplimpl/embedded/templates/disqus.html
tpl/tplimpl/embedded/templates/google_analytics.html
tpl/tplimpl/embedded/templates/google_analytics_async.html
tpl/tplimpl/embedded/templates/shortcodes/gist.html

Closes #6379
This has no effect on minification. See https://github.com/gohugoio/hugo/issues/6379#issuecomment-705646726.

tpl/tplimpl: Remove superfluous type attr on script elements

---

tpl/fmt/fmt.go
tpl/fmt/integration_test.go

tpl/fmt: Print suppression help with erroridf

---

markup/goldmark/toc.go
markup/tableofcontents/integration_test.go
markup/tableofcontents/tableofcontents.go

markup: Add Level to Heading struct

---

docs/content/en/functions/math/Rand.md
docs/content/en/getting-started/glossary.md
tpl/math/init.go
tpl/math/math.go
tpl/tplimpl/template_funcs_test.go

tpl/math: Add math.Rand template function

---

hugolib/page__output.go
hugolib/paginator_test.go
resources/page/pagination.go

Improve error message when attempting to paginate from a single page template

---

common/paths/pathparser.go
config/allconfig/allconfig.go
hugofs/component_fs.go
hugolib/content_map.go
hugolib/disableKinds_test.go
hugolib/page__new.go
hugolib/pagebundler_test.go

Fix disabled languages regression

---

commands/commandeer.go
commands/hugobuilder.go
commands/server.go
hugolib/hugo_sites_build.go
hugolib/rebuild_test.go
resources/resource.go
resources/resource_spec.go

* Add --pprof flag to server to enable profile debugging.
* Don't cache the resource content, it seem to eat memory on bigger sites.
* Keep --printMemoryUsag running in server
Fixes #11974

Misc resource fixes/improvements

---

hugolib/datafiles_test.go
hugolib/hugo_sites.go
hugolib/page_test.go
source/fileInfo.go

Preserve file/dir name case when loading data

---

resources/page/site.go

resources/page: Formally deprecate .Site.LastChange

---

cache/dynacache/dynacache.go
commands/hugobuilder.go
common/collections/stack.go
config/allconfig/allconfig.go
config/allconfig/configlanguage.go
config/configProvider.go
hugolib/content_map_page.go
hugolib/hugo_sites.go
hugolib/hugo_sites_build.go

Also fix a logical flaw in the cache resizer that made it too aggressive. After this I haven't been able to reproduce #11988, but I need to look closer.
Closes #11973
Updates #11988

Handle resource changes when the resources is already evicted from cache

---

commands/commandeer.go
commands/hugobuilder.go
commands/server.go
testscripts/commands/server.txt
testscripts/commands/server__edit_config.txt
testscripts/commands/server__edit_content.txt
testscripts/commands/server__multihost.txt
testscripts/commands/server__watch_hugo_stats.txt
testscripts/commands/server__watch_moduleconfig.txt
testscripts/commands/server_disablelivereload.txt
testscripts/commands/server_disablelivereload__config.txt
testscripts/commands/server_render_static_to_disk.txt
testscripts/commands/server_render_to_memory.txt

commands: Make the server flag --renderToDisk into --renderToMemory (note)

---

hugolib/content_map_page.go
hugolib/taxonomy_test.go

Fix site.Taxonomies for taxonomies with space in name

---

common/paths/pathparser.go
hugolib/content_map_page.go
hugolib/hugo_sites_build.go
hugolib/pages_capture.go
hugolib/rebuild_test.go

Fix rebuild of changed bundled content files

---

hugolib/content_map_page.go
hugolib/page__new.go
hugolib/taxonomy_test.go

Fix taxonomy term with backing file regression

---

markup/goldmark/toc_integration_test.go

- Change copyright date
- Change name of site configuration file
- Reference issue numbers in failing tests

markup/goldmark: Update TOC test

---

common/paths/pathparser.go
common/paths/pathparser_test.go
config/allconfig/allconfig.go
config/allconfig/configlanguage.go
config/configProvider.go
hugofs/component_fs.go
hugolib/content_map.go
hugolib/content_map_page.go
hugolib/page.go
hugolib/page__new.go
hugolib/page__output.go
hugolib/rebuild_test.go
identity/finder.go
identity/identity.go
resources/resource.go
resources/resource_cache.go
resources/resource_factories/bundler/bundler.go
resources/resource_factories/create/create.go

Fix rebuild with resources.Concat

---

hugolib/content_map_page.go
hugolib/hugo_sites_build.go
hugolib/rebuild_test.go
resources/resource/resourcetypes.go

Fix rebuild regression on non-default content language edits

---

hugolib/hugo_sites_build.go

Fix server panic on i18n file change

---

hugolib/content_map_test.go
hugolib/page__data.go
hugolib/taxonomy_test.go

Don't use the same value in .Data.Term.Title as in .Title

---

commands/list.go
testscripts/commands/list.txt

commands: Fix --clock with the list command

---

hugolib/content_map_page.go
hugolib/taxonomy_test.go

Fix handling of build options for term pages

---

hugolib/robotstxt_test.go
output/layouts/layout.go

Fix robots.txt using the built-in template regression

---

hugolib/content_map_page.go
hugolib/rebuild_test.go

Fix rebuilding of pages without default content language

---

tpl/tplimpl/embedded/templates/_default/_markup/render-link.html
tpl/tplimpl/render_hook_integration_test.go

tpl/tplimpl: Resolve fragments in link render hook

---

hugolib/pages_capture.go
hugolib/rebuild_test.go

Fix rebuild when adding a bundle with space in name

---

hugolib/sitemap_test.go
output/layouts/layout.go

Sitemap should not use list.xml

---

modules/client.go
testscripts/commands/mod_get_u.txt

Related topic: https://discourse.gohugo.io/t/theme-error-with-hugo-mod-u/48410

fix(commands/mod): ignore invalid module path

---

common/paths/pathparser.go
hugolib/pagecollections.go

```
name                             old time/op    new time/op    delta
GetPage-10                          413ns ± 0%     287ns ± 1%  -30.47%  (p=0.029 n=4+4)
GetPageRegular/From_root-10         757ns ± 1%     706ns ± 1%   -6.75%  (p=0.029 n=4+4)
GetPageRegular/Page_relative-10     838ns ± 1%     786ns ± 1%   -6.16%  (p=0.029 n=4+4)
name                             old alloc/op   new alloc/op   delta
GetPage-10                           312B ± 0%       24B ± 0%  -92.31%  (p=0.029 n=4+4)
GetPageRegular/From_root-10          328B ± 0%      200B ± 0%  -39.02%  (p=0.029 n=4+4)
GetPageRegular/Page_relative-10      360B ± 0%      232B ± 0%  -35.56%  (p=0.029 n=4+4)
name                             old allocs/op  new allocs/op  delta
GetPage-10                           8.00 ± 0%      2.00 ± …
```

Speed up GetPage

---

hugofs/rootmapping_fs.go
hugolib/filesystems/basefs.go
hugolib/filesystems/basefs_test.go
resources/resource_transformers/tocss/dartsass/transform.go
resources/resource_transformers/tocss/scss/tocss.go

tocss: Fix the import resolving from absolute to relative assets paths

---

hugolib/config_test.go
hugolib/content_map.go

Fix panic for disableKinds page for content resources

---

hugolib/content_map_page.go
hugolib/taxonomy_test.go

Fix term template lookup when its backed by a content file

---

hugolib/hugo_sites_multihost_test.go
resources/image_cache.go

Fix multihost processed image not copied to non-default content languages

---

hugofs/fileinfo.go
hugofs/rootmapping_fs.go
hugofs/rootmapping_fs_test.go
hugolib/filesystems/basefs.go
hugolib/filesystems/basefs_test.go
hugolib/integrationtest_builder.go

Fix single mount rename panic

---

hugolib/content_map_page.go
hugolib/pagecollections_test.go

Fix .Page.Pages with similary named sections

---

resources/page/taxonomy.go
resources/page/taxonomy_integration_test.go

resources/page: Make Taxonomy.Get and Taxonomy.Count case-insensitive

---

hugofs/rootmapping_fs.go
hugolib/filesystems/basefs_test.go

hugofs: Fix vertical mount merge issue

---

resources/images/text.go

resources/images: Retain newlines with text overlays

---

snap/snapcraft.yaml

snap: Transition to from core20 to core22

---

commands/server.go
common/hugo/hugo.go
common/hugo/hugo_integration_test.go
common/hugo/hugo_test.go
config/allconfig/allconfig.go
config/allconfig/configlanguage.go
config/configProvider.go
hugolib/config_test.go
hugolib/content_map_page.go
hugolib/filesystems/basefs_test.go
hugolib/hugo_sites.go
hugolib/hugo_sites_multihost_test.go
hugolib/site.go
hugolib/site_new.go
hugolib/site_render.go
modules/config.go
resources/page/page_matcher_test.go
resources/page/site.go

hugo.IsMultiHost => hugo.IsMultihost
hugo.IsMultiLingual => hugo.IsMultilingual
Closes #12232

common/hugo: Rename IsMultiHost and IsMultiLingual

---

hugolib/mount_filters_test.go
resources/resource/resources.go
resources/resource_factories/create/create.go
tpl/resources/resources_integration_test.go

Fix Name for nested resourced fetched in resources.ByName and similar

---

resources/page/pagemeta/page_frontmatter.go
resources/page/pagemeta/pagemeta_integration_test.go

Fix front matter date location when value gets inherited from other dates

---

hugolib/hugo_sites_build.go
hugolib/rebuild_test.go

Fix panic when changing archetype files when servere is running

---

hugolib/page_test.go
tpl/tplimpl/embedded/templates/shortcodes/figure.html

tpl/tplimpl: Modify figure shortcode to look for page resource

---

go.mod
go.sum
testscripts/commands/gen.txt

build(deps): bump chroma github.com/alecthomas/chroma/v2 to v2.13.0

---

.circleci/config.yml
scripts/fork_go_templates/main.go
tpl/internal/go_templates/fmtsort/sort_test.go
tpl/internal/go_templates/htmltemplate/js.go
tpl/internal/go_templates/htmltemplate/js_test.go
tpl/internal/go_templates/testenv/exec.go
tpl/internal/go_templates/testenv/testenv_notunix.go
tpl/internal/go_templates/testenv/testenv_test.go
tpl/internal/go_templates/testenv/testenv_unix.go
tpl/internal/go_templates/texttemplate/parse/node.go

Upgrade to Go 1.22.1

---

common/types/types.go
hugolib/page.go
tpl/collections/collections.go
tpl/collections/collections_integration_test.go
tpl/collections/reflect_helpers.go

Fix intersect and similar for term entry page collections

---

hugolib/content_map_page.go
hugolib/page_test.go

Fix translationKey handling for term pages

---

hugolib/site.go
hugolib/sitemap_test.go

Fixes #12266
This is a follow-up to https://github.com/gohugoio/hugo/pull/11245.

hugolib: Fix sitemap index with monolingual site

---

hugolib/page__tree.go
hugolib/site_sections_test.go

Fix .Parent when there are overlapping regular pages inbetween

---

hugolib/content_map_page.go
hugolib/hugo_sites_build.go
hugolib/site_output_test.go

Fix regression for outputs defined in front matter for term pages

---

hugolib/content_map_page.go
hugolib/hugo_sites_build.go
hugolib/page.go
hugolib/rebuild_test.go

Fix rebuild when changing mixed case named templates

---

markup/asciidocext/convert_test.go
markup/asciidocext/internal/converter.go

markup/asciidocext: Add Level to Heading struct

---

resources/resource_factories/create/create.go
resources/resources_integration_test.go

resources: Use different cache key when copying resources

---

hugolib/embedded_templates_test.go
tpl/tplimpl/embedded/templates/opengraph.html
tpl/tplimpl/embedded/templates/twitter_cards.html

tpl/tplimpl: Remove trailing slash from void elements

---

hugolib/content_map_page.go
hugolib/pagebundler_test.go

Fix resource bundling for overlapping page.md vs page.txt

---

tpl/strings/strings.go
tpl/strings/strings_test.go

tpl/strings: Create strings.Diff template function

---

tpl/lang/lang.go
tpl/urls/urls.go

I guess some errors are mistakenly discarded in https://github.com/gohugoio/hugo/issues/2354.
I didn't add any tests because I cannot find tests even for similar methods so maybe you consider such tests are too much. Ask me write ones if you consider they are necessary. To write test, I need your instructions, say, where to write test, how big (integrated) should they be, how much should tests cover and so on.

errors: Return error from cast.ToStringE() consistently

---

hugolib/embedded_shortcodes_test.go
tpl/tplimpl/embedded/templates/shortcodes/youtube.html

Changes:
- Add query string params for controls, loop, mute, start, and end
- Add iframe loading attribute
- Obtain default iframe title from YouTube oEmbed API
- Fix autoplay feature
- Improve readability
Closes #3694
Closes #9213
Closes #10520
Closes #10575
Closes #10576

tpl/tplimpl: Improve youtube shortcode

---

hugolib/menu_test.go
hugolib/site.go

Fix sectionPagesMenu for pages in root level

---

cache/dynacache/dynacache.go
docs/data/docs.yaml
hugolib/content_map_page.go
markup/internal/attributes/attributes.go
tpl/urls/urls.go

The the word "the" is repeated in a few files.
Remove the duplicates

all: fix duplicate duplicate words

---

resources/page/taxonomy.go
resources/page/taxonomy_integration_test.go

resources/page: Add taxonomies Page method

---

.github/workflows/test-dart-sass-v1.yml
.github/workflows/test.yml

- **github: Format GitHub actions files**
- **github: Update actions**

Misc GitHub

---

helpers/content.go
helpers/content_test.go
hugolib/page__content.go
hugolib/page__per_output.go
tpl/transform/transform.go

helpers: Fix TrimShortHTML when used with AsciiDoc content

---

hugolib/hugo_sites_build.go
hugolib/integrationtest_builder.go
hugolib/rebuild_test.go
hugolib/site.go

 Fix server rebuilds when adding a content file on Linux

---

commands/gen.go

commands: Provide examples for chromastyles flags

---

commands/gen.go
docs/content/en/commands/hugo_gen_chromastyles.md

For symmetry, also rename --linesStyle to --lineNumbersInlineStyle.
Closes #12393

commands: Add gen chromastyles --lineNumbersTableStyle flag

---

cache/dynacache/dynacache.go
cache/dynacache/dynacache_test.go
commands/commandeer.go
hugolib/content_map_page.go
hugolib/hugo_sites_build.go
resources/resource_transformers/tocss/scss/scss_integration_test.go

Fix partial rebuilds for SCSS fetched with GetMatch and similar

---

hugolib/menu_test.go
hugolib/site.go

Only add root sections to the section pages menu

---

modules/collect.go

modules: Fix potential infinite loop in module collection

---

SECURITY.md

The security model was moved in https://github.com/gohugoio/hugoDocs/pull/2495

SECURITY.md: Update link to security model

---

LICENSE

Use Apache License without modification

---

hugolib/content_map_page.go
hugolib/rebuild_test.go
hugolib/site_benchmark_new_test.go

Make sure replaced pages gets marked as stale

---

commands/commandeer.go
commands/hugobuilder.go
hugolib/hugo_sites_build.go

commands: Print "Webserver is ..." right before "Total ..."

---

tpl/tplimpl/embedded/templates/opengraph.html
tpl/tplimpl/tplimpl_integration_test.go

tpl/tplimpl: Improve locale value in opengraph.html

---

create/skeletons/theme/layouts/_default/baseof.html

create/skeletons: Remove superfluous language code fallback

---

tpl/tplimpl/embedded/templates/schema.html
tpl/tplimpl/tplimpl_integration_test.go

tpl/tplimpl: Plainify title and description in schema.html

---

hugolib/content_map.go
hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go

Also warn about duplicate content paths with --printPathWarnings

---

hugolib/content_map_page.go
hugolib/content_map_test.go

hugolib: Allow override of sitemap file name

---

metrics/metrics.go

A minor change about beatifying metrics output.

metrics: increase maximum length of cumulative duration to 15

---

hugolib/pages_language_merge_test.go
resources/page/site.go
resources/page/site_integration_test.go

resources/page: Deprecate .Sites.First in favor of .Sites.Default

---

hugolib/content_map_page.go
hugolib/pagecollections_test.go

content adapter: Fix site.GetPage using the base part of the path

---

go.mod
go.sum

Addresses https://discourse.gohugo.io/t/50419

deps: Upgrade github.com/yuin/goldmark v1.7.2 => v1.7.4

---

create/skeletons/theme/hugo.toml

Region subtag should be in ALLCAPS

create/skeletons: Fix languageCode region subtag

---

commands/hugobuilder.go

And improve the logging for live reload.
Closes #12643

commands: Simplify the browser live reload logic

---

resources/images/images_integration_test.go
tpl/compare/compare.go
tpl/compare/compare_test.go

Fix compare of uints and ints in eq, gt etc.

---

internal/warpc/katex.go
tpl/transform/transform.go
tpl/transform/transform_integration_test.go

And fix the options handling.
Closes #12745
Fixes #12746

Add some more KaTeX options

---

markup/goldmark/blockquotes/blockquotes.go
markup/goldmark/blockquotes/blockquotes_integration_test.go

Fix nilpointer regression with empty blockquotes

---

.github/workflows/image.yml

I'm just adding the branch to the filter list here ... I have tested these variations fine on https://github.com/bep/githubactionstest ... and I don't see why it does not work in this repo... Maybe a ... glitch?
See #12753

github: Adjust image workflow

---

tpl/transform/transform_integration_test.go

tpl/transform: Don't run ToMath tests in parallel

---

config/allconfig/allconfig.go
config/allconfig/alldecoders.go
config/commonConfig.go
docs/data/docs.yaml
hugolib/site.go
resources/page/pages_prev_next_integration_test.go

Add config options page.nextPrevSortOrder/nextPrevInSectionSortOrder

---

.circleci/config.yml
releaser/releaser.go

releaser: Rework the run conditions

---

hugolib/content_map_page.go
resources/resource/resourcetypes.go

Fix missing method NameNormalized panic

---

common/hugo/hugo.go
go.mod
go.sum

deps: Upgrade github.com/bep/golibsass v1.1.1 => v1.2.0

---

tpl/resources/resources.go

tpl/resources: Improve resources.Concat error message

---

hugolib/page__per_output.go
hugolib/site.go
markup/converter/hooks/hooks.go
markup/goldmark/blockquotes/blockquotes.go
markup/goldmark/codeblocks/render.go
markup/goldmark/convert.go
markup/goldmark/convert_test.go
markup/goldmark/internal/render/context.go
markup/goldmark/passthrough/passthrough.go
markup/goldmark/render_hooks.go
markup/goldmark/tables/tables.go
markup/goldmark/tables/tables_integration_test.go
tpl/tplimpl/embedded/templates/_default/_markup/render-table.html

Add Markdown render hooks for tables

---

hugolib/page__content.go
hugolib/page_test.go
hugolib/securitypolicies_test.go
hugolib/site_stats_test.go
hugolib/site_test.go
markup/goldmark/blockquotes/blockquotes.go
markup/goldmark/blockquotes/blockquotes_integration_test.go
markup/goldmark/blockquotes/blockquotes_test.go
resources/page/page_markup_integration_test.go

- **Make ContentWithoutSummary return Content when summary is fetched from front matter**
- **Fix stray end p tag in Obsidian callout titles**

Misc 0.134 fixes

---

resources/resource_transformers/tocss/dartsass/dartsass_integration_test.go
resources/resource_transformers/tocss/dartsass/transform.go

dartsass: Resolve directory paths to directory index files

---

resources/resource_transformers/tocss/dartsass/dartsass_integration_test.go
resources/resource_transformers/tocss/dartsass/transform.go
resources/resource_transformers/tocss/scss/scss_integration_test.go
resources/resource_transformers/tocss/scss/tocss.go

libsass: Resolve directory paths to directory index files

---

commands/hugobuilder.go

This should fix https://github.com/gohugoio/hugo/issues/12677, see https://github.com/gohugoio/hugo/issues/12677#issuecomment-2308489571 by @jmooring

Add exclusion for helix .bck files

---

tpl/compare/compare.go
tpl/compare/compare_test.go

tpl/compare: Use any data type for compare.Conditional condition

---

commands/commandeer.go
commands/commands.go
docs/content/en/commands/hugo_build.md
testscripts/commands/gen.txt
testscripts/commands/hugo_build.txt

Closes https://github.com/gohugoio/hugo/issues/11391

commands: Add "hugo build" as an alias for "hugo"

---

resources/page/pagemeta/page_frontmatter.go
resources/page/pagemeta/pagemeta_integration_test.go

resources/page: Treat null dates as zero dates

---

create/skeletons/site/archetypes/default.md
create/skeletons/skeletons.go

create/skeletons: Honor --format flag when creating default archetype

---

config/allconfig/allconfig_integration_test.go
config/allconfig/alldecoders.go

fix https://github.com/gohugoio/hugo/issues/12926

fixed #12926 uglyurls parse to map[string]bool

---

create/skeletons/skeletons.go
testscripts/commands/new.txt

create/skeletons: Add delimiters to archetype front matter

---

tpl/strings/strings.go
tpl/strings/strings_test.go

tpl/strings: Add TrimSpace function

---

tpl/transform/transform_integration_test.go
tpl/transform/unmarshal.go

tpl/transform: Revert unmarshal whitespace removal

---

commands/commandeer.go
commands/hugobuilder.go
commands/server.go
hugolib/hugo_sites.go
hugolib/hugo_sites_build.go
hugolib/integrationtest_builder.go
hugolib/page__new.go
hugolib/site.go
testscripts/commands/server__error_recovery_edit_config.txt
testscripts/commands/server__error_recovery_edit_content.txt
tpl/template.go
tpl/tplimpl/template.go

Also clean up the error handlingin the commands package.
Fixes #11378

hugolib: Fix stuck server errors on front matter errors

---

common/constants/constants.go
markup/goldmark/goldmark_integration_test.go
markup/goldmark/hugocontext/hugocontext.go

markup/goldmark: Add warning (using Warnidf) on Goldmark <!-- raw HTML omitted -->

---

markup/goldmark/hugocontext/hugocontext.go

markup/goldmark: Only log Raw HTML omitted WARN on block entering

---

hugofs/rootmapping_fs.go
hugolib/filesystems/basefs_test.go

Do not watch directories with no mounted files in it

---

common/maps/scratch.go
hugolib/page.go
hugolib/page__common.go
hugolib/page__new.go
hugolib/page_test.go
resources/page/page.go

Alias Page.Scratch to Page.Store

---

common/maps/cache.go
hugolib/content_map_page.go
hugolib/content_map_test.go
lazy/init.go
lazy/once.go

Regression introduced in Hugo `v0.137.0`.
Fixes #13019

Fix concurrent map read and map write in short page lookups

---

markup/goldmark/goldmark_integration_test.go
markup/goldmark/hugocontext/hugocontext.go

markup/goldmark: Improve the raw HTML omitted warning

---

common/hugo/hugo.go
common/maps/scratch.go
hugolib/page_test.go
hugolib/shortcode.go
hugolib/site.go
resources/page/page.go
resources/page/site.go

Add site.Store and hugo.Store and Shortcode.Store

---

go.mod
go.sum
markup/goldmark/convert.go
markup/goldmark/internal/render/context.go
markup/goldmark/render_hooks.go

deps: Upgrade github.com/yuin/goldmark v1.7.4 => v1.7.8

---

commands/server.go

commands: Add -O flag to server to open browser

---

hugolib/rendershortcodes_test.go
markup/goldmark/goldmark_integration_test.go
markup/goldmark/hugocontext/hugocontext.go

Fix extra newline/paragraphs issue with .RenderShortcodes

---

hugolib/content_map_page.go
hugolib/page__new.go
hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go

Make sure term is always set

---

go.mod
go.sum
minifiers/minifiers_test.go

- **minifiers: Add failing test for upstream bug**
- **Revert "build(deps): bump github.com/tdewolff/minify/v2 from 2.20.37 to 2.21.1"**

Fix minify

---

hugolib/page__content.go
hugolib/rebuild_test.go
identity/finder.go
tpl/template.go

Fix server edits of resources included in shortcode/hooks

---

go.mod
go.sum

See https://github.com/bep/godartsass/issues/31 for some context.

deps: Upgrade github.com/bep/godartsass/v2 v2.3.1 => v2.3.2

---

markup/goldmark/blockquotes/blockquotes.go
markup/goldmark/blockquotes/blockquotes_integration_test.go

markup/goldmark: Fix blockquote render hook text parsing

---

resources/resource_transformers/tocss/dartsass/dartsass_integration_test.go
resources/resource_transformers/tocss/dartsass/transform.go
resources/resource_transformers/tocss/scss/scss_integration_test.go
resources/resource_transformers/tocss/scss/tocss.go

Fix Sass imports of on the form index.{scss,sass}

---

config/allconfig/allconfig.go
hugolib/config_test.go
hugolib/site_render.go

Add config option disableDefaultLanguageRedirect

---

internal/js/esbuild/options.go
internal/js/esbuild/options_test.go

js/esbuild: Add platform option

---

internal/js/esbuild/batch.go

We already do this for scripts e.g. inside a group.
This makes sure that group A's entry points gets added before B's, which can be an important property, see https://github.com/evanw/esbuild/issues/399#issuecomment-1458680887

js/esbuild: Build groups in order of their ID

---

tpl/collections/collections.go
tpl/collections/collections_test.go
tpl/collections/querify.go
tpl/collections/querify_test.go

tpl/collections: Allow querify to accept a map argument

---

tpl/tplimpl/embedded/templates/shortcodes/youtube.html

Pass a map instead of a slice to the collections.Querify function.

tpl/tplimpl: Update youtube shortcode

---

hugolib/hugo_sites_build.go
internal/js/esbuild/batch.go
internal/js/esbuild/batch_integration_test.go

Ranging over a nil slice in Go works great, but is a hassle onced passed to JS.

Misc JS adjustments

---

parser/pageparser/pagelexer_intro.go
parser/pageparser/pagelexer_intro_test.go

parser/pageparser: Fix Org Mode summary delimiter assignment

---

deps/deps.go
hugolib/paths/paths.go
hugolib/site.go
internal/js/api.go
internal/js/esbuild/batch.go
internal/js/esbuild/batch_integration_test.go
resources/resource.go
tpl/js/js.go

Note that this is an unreleased feature.
Fixes #13151

js: Fix js.Batch for multihost setups

---

hugolib/menu_test.go
hugolib/site.go

hugolib: Fix fallbacks for menu entry Name and Title

---

common/loggers/logger.go

common/loggers: Write PrintTimerIfDelayed output to stdErr

---

config/allconfig/allconfig.go
config/allconfig/allconfig_integration_test.go

config/allconfig: Fix slice of language configs

---

hugolib/404_test.go
hugolib/content_map_page.go

Fix server refresh on 404 template changes

---

docs/content/en/functions/images/QR.md
tpl/images/images.go
tpl/images/images_integration_test.go
tpl/tplimpl/embedded/templates/shortcodes/qr.html
tpl/tplimpl/tplimpl_integration_test.go

tpl/images: Change signature of images.QR to images.QR TEXT OPTIONS

---

hugolib/hugo_sites_build.go
tpl/templates/defer_integration_test.go

templates: Fix handling of multiple defers in the same template

---

hugolib/content_map_page.go
hugolib/content_map_test.go

Fix branch resource overlapping bundle path

---

common/types/types.go
hugolib/hugo_sites_build.go
tpl/transform/transform.go
tpl/transform/transform_integration_test.go

Adjust error handling in ToMath vs try  (note)

---

config/allconfig/allconfig.go
config/privacy/privacyConfig.go
config/privacy/privacyConfig_test.go
config/services/servicesConfig.go
config/services/servicesConfig_test.go
hugolib/testhelpers_test.go
tpl/tplimpl/embedded/templates/shortcodes/twitter.html
tpl/tplimpl/embedded/templates/shortcodes/x.html
tpl/tplimpl/embedded/templates/shortcodes/x_simple.html
tpl/tplimpl/template.go
tpl/tplimpl/tplimpl_integration_test.go

tpl/tplimpl: Deprecate twitter shortcode in favor of x shortcode

---

common/hashing/hashing.go
common/maps/ordered.go
common/maps/ordered_test.go
config/allconfig/allconfig.go
hugolib/cascade_test.go
hugolib/content_map_page.go
hugolib/page__meta.go
resources/page/page_matcher.go
resources/page/page_matcher_test.go
resources/page/pagemeta/page_frontmatter.go

Make cascade front matter order deterministic

---

hugolib/cascade_test.go
hugolib/content_map_page.go

Fix cascade with overlapping sections

---

markup/goldmark/blockquotes/blockquotes.go
markup/goldmark/blockquotes/blockquotes_integration_test.go

markup/goldmark: Trim space from blockquote render hook text

---

hugolib/hugo_sites_build.go

Fix TailwindCSS related server rebuild issue

---

common/maps/maps_test.go
common/maps/params.go
resources/page/pagemeta/page_frontmatter.go

Fix data race in pages from data

---

common/hugo/hugo.go
common/hugo/hugo_test.go
tpl/debug/debug.go

common/hugo: Adjust deprecation timing and message

---

hugolib/rss_test.go
transform/urlreplacers/absurl.go
transform/urlreplacers/absurlreplacer.go

Fix RSS with baseURL with subrid when render hooks is enabled

---

hugolib/shortcode.go
hugolib/shortcode_test.go

Fix shortcode name in error message on self-closing shortcodes with no .Inner

---

hugolib/hugo_sites_build.go

Move "print unused templates" after renderDeferred

---

commands/gen.go
testscripts/commands/gen.txt

commands: Validate style argument passed to gen chromastyles

---

docs/data/docs.yaml
helpers/docshelper.go

helpers: Add Chroma styles to docs.yaml

---

commands/hugobuilder.go

To prevent ghost rebuilds (from VSCode and possibly others).
Fixes #13373

commands: Move the CHMOD event filter up

---

docs/content/en/functions/js/_common/options.md
internal/js/esbuild/options.go
internal/js/esbuild/options_test.go

js/esbuild: Add drop option

---

hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go
resources/page/pagemeta/page_frontmatter.go

Support menus as maps in content adapters

---

hugolib/page.go
hugolib/page__common.go
hugolib/page__meta.go
hugolib/page__new.go
hugolib/pagesfromdata/pagesfromgotmpl_integration_test.go
related/inverted_index.go
related/inverted_index_test.go
resources/page/page.go

Fix some related content issues with content adapters

---

go.mod
go.sum
main_test.go

deps: Upgrade github.com/rogpeppe/go-internal v1.13.1 => v1.14.1

---

commands/gen.go
testscripts/commands/gen.txt

commands: Add --omitEmpty flag to gen chromastyles

---

tpl/tplimpl/embedded/templates/shortcodes/vimeo.html
tpl/tplimpl/shortcodes_integration_test.go

tpl/tplimpl: Add loading attribute to Vimeo shortcode

---

go.mod
go.sum

deps: Upgrade golang.org/x/mod v0.23.0 => v0.24.0

---

tpl/tplimpl/embedded/templates/shortcodes/vimeo.html
tpl/tplimpl/embedded/templates/shortcodes/youtube.html
tpl/tplimpl/shortcodes_integration_test.go

tpl/tplimpl: Fix full screen option in vimeo and youtube shortcodes

---

tpl/tplimpl/embedded/templates/_partials/pagination.html

Updated to match new embedded template path.

tpl/tplimpl: Update embedded pagination template

---

tpl/tplimpl/templatestore.go
tpl/tplimpl/templatestore_integration_test.go

tpl: Skip dot and temp files inside /layouts

---

tpl/templates/templates_integration_test.go
tpl/tplimpl/templatedescriptor.go
tpl/tplimpl/templates.go
tpl/tplimpl/templatestore.go
tpl/tplimpl/templatestore_integration_test.go

- **tpl: Fix some baseof lookup issues**
- **tpl: Resolve layouts/all.html for all html output formats**
- **tpl: Fix legacy section mappings**

tpl: Misc fixes

---

tpl/tplimpl/templatedescriptor.go
tpl/tplimpl/templatedescriptor_test.go
tpl/tplimpl/templatestore.go
tpl/tplimpl/templatestore_integration_test.go

tpl: Fix codeblock hook resolve issue

---

tpl/tplimpl/templatedescriptor.go
tpl/tplimpl/templatestore_integration_test.go

tpl: Fix when layout specified in front matter and no match is found

---

tpl/math/init.go
tpl/math/math.go
tpl/math/math_test.go

tpl/math: Add MaxInt64 function

---

resources/resource_factories/create/remote.go

Fix file caching for 404 responses in resources.GetRemote
